### ISSUE TITLE
[Azure:ResourceGroup] Fix ResourceGroup Creation Error and enhance Management it

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1008]
**[배경]**
- Spider REST API를 통한 사용에서, 
- Azure의 경우 Region 정보를 등록할 때 location과 함께 ResourceGroup을 함께 등록합니다. 
  ```shell
    curl -X POST http://$RESTSERVER:1024/spider/region -H 'Content-Type: application/json' -d \
        '{
                "RegionName":"azure-no-rs",
                "ProviderName":"AZURE",
                "KeyValueInfoList": [{"Key":"location", "Value":"northeurope"}, {"Key":"ResourceGroup", "Value":"cb-no-group"}]
        }'
  ```

<br>

- 이때, ResourceGroup은 이미 존재할수도 있고, 존재하지 않을 수 도 있습니다.
- 존재하지 않을 경우는 AzureDriver.ConnectCloud() 호출 시점에 체크하여 자동 생성이 되는 로직입니다.
  - https://github.com/cloud-barista/cb-spider/blob/a7979fab08d9c5bcfdcde92c89d6aa0f3b60f42d/cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go#L73

<br>

**[Issue-1]**
- 그런데, 현재 다음 코드 영역에서, 
  - https://github.com/cloud-barista/cb-spider/blob/a7979fab08d9c5bcfdcde92c89d6aa0f3b60f42d/cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go#L223

- `resourceClient.Get(ctx, region.ResourceGroup)` 호출시,
  - 존재하지 않는 ResourceGroup의 경우 에러를 반환하고 있으며, 
  - 현재, 에러 발생시 `nil`을 반환함으로 아래 부분에 있는 생성 코드가 예상과 달리 skip되고 있습니다. 
    ```
    "resources.GroupsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceGroupNotFound\" Message=\"Resource group 'NOGRP' could not be found.\""
    ```

- 이에, 다음 적용 검토해주시기 바랍니다.
- `resourceClient.Get()` 에러 반환시, 
  - 존재하지 않는 리소스 그룹일 경우, 리소스 그룹 생성
  - 다른 오류일 경우, 오류 반환

<br>

**[Issue-2]**
- 현재 자동 생성 되는 로직만 있고, 자동 삭제되는 로직이 없습니다.
  - 현재, Tumblebug 시험 환경에는 ResourceGroup이 750여개~~
- 다음처럼 자동 삭제 되는  로직 추가를 고려해주시기 바랍니다. 
  - 다음 3종 자원들의 경우는 대상 자원 삭제 후 현재 `리소스 그룹`에 자원이 없는 경우에는 현재 `리소스 그룹` 삭제
    - 로직 추가 대상 자원: VPC, KeyPair, Disk
    - 현재, 3종 외 타 자원들은 VPC가 존재해야 생성되는 자원으로 `리소스 그룹` 삭제 조건과 항상 무관

- 추신: 
  - 현재 로직은 빈번하게 check하는 비효율적인 방법일 수 있습니다만, 
  - 타 CSP들 과는 달리, Azure만의 상황이라서 일단 드라이버 수준에서 지원해보고자 합니다. 
 
cf) @seokho-son @sykim-etri

**Comment by powerkimhub** [comment]
- 아, 기존에는 자동 생성이 잘되었었으며, 
- 대략, 다음 시점 이후에 잠재적으로 오류가 내재되어 왔었던 것 같습니다.
- https://github.com/cloud-barista/cb-spider/commit/77032ba511ce5d0f8834011f3d34293415832ef8#diff-abc30a2d450e3b4ec145cd44b6eabf8970e21bc0c93c0bec3ee0afe0160516ebL154

**Comment by seokho-son** [comment]
@powerkimhub  bug fix 반영 일정 문의 드립니다.

**Comment by ish-hcc** [comment]
Fixed in https://github.com/cloud-barista/cb-spider/pull/1120
