### ISSUE TITLE
Enhancement for regionzone API request body

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#1017]
**What would you like to be enhanced**

- regionzone API 의 request body를 ConnectionName이 아니라, 조회에 필수적인 CredentialName 만 입력 받도록 개선

**Why is this needed**

- regionzone API 는 특정 CSP의 리전/존 정보를 조회하는 API 이며, 현재 API의 실행을 위해서는 "ConnectionName" 을 입력값으로 받고 있음. 
  - ConnectionConfig에는 RegionName 이 포함되어 있으므로, regionzone API 활용 전에 이미 Region 정보가 등록되어 있다고 가정해야 함. 그래서 현재는 적어도 CSP당 1개 이상의 Region을 미리 등록 필요.
  - 그러나, regionzone 를 CB-TB 등에서 Region 자동 등록에 활용하기 위해서는, 기존에 등록된 Region 정보는 없다고 가정해야 함.

**Proposed solution**
- regionzone API 의 request body를 ConnectionName이 아니라, 조회에 필수적인 CredentialName 만 입력 받도록 개선

**Comment by powerkimhub** [comment]
- Connection 설정 전에 사용할 수 있는 CredentialName 기반 API를 추가하도록 하지요. 
  - Connection 설정 이후에는 Connection 기반 사용도 가능하도록 현재 API 유지

**Comment by powerkimhub** [comment]
- Completed via https://github.com/cloud-barista/cb-spider/commit/3f6221123247bf9de5d9d32de748a83b37271014
- Since [CB-Spider v0.8.5](https://github.com/cloud-barista/cb-spider/releases/tag/v0.8.5)
- ref) [Region/Zone Rest API Guide](https://github.com/cloud-barista/cb-spider/wiki/REST-API-Region-Zone-Information-Guide)
- ex)
  ```
  curl -sX GET "http://localhost:1024/spider/preconfig/regionzone?DriverName=aws-driver01&CredentialName=aws-credential01" | json_pp
  ```
  ```
  {
     "regionzone" : [
        {
           "DisplayName" : "ap-northeast-2",
           "KeyValueList" : [],
           "Name" : "ap-northeast-2",
           "ZoneList" : [
              {
                 "DisplayName" : "ap-northeast-2a",
                 "KeyValueList" : null,
                 "Name" : "ap-northeast-2a",
                 "Status" : "Available"
              },
              {
                 "DisplayName" : "ap-northeast-2b",
                 "KeyValueList" : null,
                 "Name" : "ap-northeast-2b",
                 "Status" : "Available"
              },
              {
                 "DisplayName" : "ap-northeast-2c",
                 "KeyValueList" : null,
                 "Name" : "ap-northeast-2c",
                 "Status" : "Available"
              },
              {
  --More--
  ```

**Comment by seokho-son** [comment]
@powerkimhub 반영 감사합니다. 변경 사항에 대해서 의견이 있어서, 이슈를 다시 오픈하였습니다.

http://localhost:1024/spider/preconfig/regionzone?**DriverName=aws-driver01**&CredentialName=aws-credential01

-DriverName=aws-driver01 쿼리파람은 사용자 입장에서는 값을 찾고 입력하기 번거로운 정보인 것 같습니다. 사용자 입력에서는 제외하고, 필요하다면 내부적으로 처리하도록 하는 것이 가능할지 문의 드립니다.

**Comment by powerkimhub** [comment]
@seokho-son 

- 현재 정보 구조에서는 불가능 합니다. 
- CredentialName으로 얻을 수 있는 정보는 아래와 같고, 
- Provider Name만으로는 Driver가 여러개 일 수 있으므로, 
  - DriverName을 알수 없는 구조입니다. 

Credential Name | Provider Name | Credential Info  
-- | -- | --
