### ISSUE TITLE
[NCPVPC:VM] Ambiguous Error Message Returned When VM Creation Fails

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1022]
* 대상 Region/Zone: NCPVPC: JPN / JPN-4
* 대상 VM 이미지

  * ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/63fe5bb8-b220-417d-adc9-2da1c8ad6560)

<br>

* **실수로, 없는 VM Spec으로 요청시,** 
* 적합하지 않은 오류 메시지를 제공하고 있습니다. 

* 요청 인자 및 오류 메시지
```
[오후 1:50:42] curl -sX POST http://localhost:1024/spider/vm -H 'Content-Type: application/json' -d '{ "ConnectionName" : "ncpvpc-japan4-config", "ReqInfo" : { "Name" : "vm-01", "ImageType" : "PublicImage",                                "ImageName" : "SW.VSVR.OS.LNX64.UBNTU.SVR1804.B050", "VMSpecName" : "t2.micro", "VPCName" : "vpc-01", "SubnetName" : "subnet-01",                                 "SecurityGroupNames" : ["sg-01"], "DataDiskNames" : [], "KeyPairName" : "keypair-01",                                 "VMUserId" : "Administrator", "VMUserPasswd" : "xxxxxxx" }}'
[오후 1:50:45]    ==> {"message":"Failed to Delete the Cloud-Init Script with the initScriptNo : [4378], [Failed to Delete any Cloud-Init Script!!]"}
```

----

**[VM Spec 설정 추가 등 적합한 인자로 호출]**

* Region/Zone: NCPVPC: JPN / JPN-4
* VM 이미지: SW.VSVR.OS.LNX64.UBNTU.SVR2004.B050
* VM Spec: SVR.VSVR.HICPU.C002.M004.NET.SSD.B050.G002
 
<br>

* 다음처럼 VM이 잘 만들어진 후에 

```
pc/resources.(*NcpVpcVMHandler).GetVMStatus() - VM Status of [20598932] : [Creating]
pc/resources.(*NcpVpcVMHandler).GetVMStatus() - VM Status of [20598932] : [Booting]
pc/resources.(*NcpVpcVMHandler).GetVMStatus() - VM Status of [20598932] : [Creating]
pc/resources.(*NcpVpcVMHandler).GetVMStatus() - VM Status of [20598932] : [Running]
```

<br>

### 동일한 오류 발생
* Cloud-Init 스크립트 삭제시 오류가 생기는 듯합니다. 
* Meta-DB의 RDB 교체 영향 등인지 확인이 필요해 보입니다. 

```
[CB-SPIDER].[INFO]: 2024-01-24 05:13:54 VMHandler.go:1349, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/ncpvpc/resources.(*NcpVpcVMHandler).DeleteInitScript() - NCPVPC Cloud driver: called DeleteInitScript()!!
[CB-SPIDER].[ERROR]: 2024-01-24 05:13:55 VMHandler.go:1367, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/ncpvpc/resources.(*NcpVpcVMHandler).DeleteInitScript() - Failed to Delete any Cloud-Init Script!!
```

- 결과적으로 CSP에는 VM이 만들어지고, 
- Spider에는 VM이 등록되지 않은 상태인 dangling 상태로 존재

<br>

![image](https://github.com/cloud-barista/cb-spider/assets/46367962/756a2c48-7610-4675-843c-caf36afe0e7d)

**Comment by innodreamer** [comment]
@powerkimhub 
VM 생성 완료 후 NCP VPC platform 내부적으로 생성했던 cloud-init script를 삭제하고 script 삭제가 성공했어도 성공 여부를 체크하는 과정에서 error가 발생했습니다.
전에는 이 부분에서 error가 발생하지 않았었는데 NCP VPC에서 response 값이 변경된거 같네요.

따라서, Script 삭제 성공 여부를 체크하는 코드를 보완했습니다.

(참고) NCP VPC의 경우는 타 cloud service와 다르게 cloud-init script를 적용하기 위해서는 cloud-init script NCP VPC platform 내부적으로 생성하고 그 script의 ID 값을 이용해서 적용합니다.
따라서, 드라이버 내부적으로 VM 생성 초기에 cloud-init script를 생성하고, VM 생성 완료 후 그 script를 삭제하고 있습니다.
