### ISSUE TITLE
When creating Windows VM using NCP Classic Driver, error occurs under VM NAME length constraints

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#1041]
**What happened**
:  CB-Spider로 NCP Classic 연동 driver를 이용해 'Windows server' VM 생성시, 아래와 같이 VM Name 길이 제약 조건으로 오류 발생

```
[CLOUD-BARISTA].[ERROR]: 2024-02-05 22:28:56 VMManager.go:499, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.StartVM() - Failed to Create NCP VM instance. :  Status: 400 Bad Request, Body: {
  "responseError": {
    "returnCode": "905",
    "returnMessage": "Please check your input value : [oh-test-w-cn0e55ci1q9o41dkp6qg]. Length constraints: Minimum length of 3. Maximum length of 15. location : serverName"
  }
} 
```

**What you expected to happen**
: Spider에서 관리하는 NameID를 생성할때 NCP Classic의 경우 15자까지만 사용해야함.
 (Windows VM 경우만 따로 지정할 수 있을지 모르겠습니다.)

**How to reproduce it (as minimally and precisely as possible)**
: CB-Spider로 NCP Classic 연동 driver를 이용해 'Windows' VM 생성
  - Image : SPSW0WINNTEN0016A (Windows Server 2016 (64-bit) English Edition)
  - VMSpec : SPSVRSSD00000005A (상기 Win server와 호환)

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by innodreamer** [comment]
NCP VPC 연동 driver를 이용해서 windows server VM 생성시에도 spider에서 유사한 오류가 발생합니다.

```
[CLOUD-BARISTA].[ERROR]: 2024-02-06 01:32:23 VMHandler.go:249, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/ncpvpc/resources.(*NcpVpcVMHandler).StartVM() - Failed to Create VM instance : [Status: 400 Bad Request, Body: {
  "responseError": {
    "returnCode": "1100013",
    "returnMessage": "Windows server names are limited to up to 15 bytes because of NetBIOS."
  }
}] 
```

**Comment by powerkimhub** [comment]
**[현황분석]**
- NCP, NCPVPC의 경우 다음과 같이 사용자가 입력한 VM Name을 Server Name으로 설정되고,
- Server Name은 다시 Windows의 hostname으로 사용 될 수 있어서, 
- Windows NetBIOS hostname 15자 제한을 걸고 있는 걸로 보입니다. 
- 아래 그림에서 처럼, console에서는 hostname으로 사용안 하도록 설정할 수 있지만, 여전히 15자 제약은 풀리지는 않습니다.
  - hostname 설정 해지 API도 없는 듯

<br>

![image](https://github.com/cloud-barista/cb-spider/assets/46367962/f1917efd-4165-44d9-8340-63abd7f911da)

<br>

**[서버 적용 완료]**
- 반영 참고: https://github.com/cloud-barista/cb-spider/commit/f7ac78b6ed7af4096811096f9d7a4590330de89d
- #### 단, 다음 https://github.com/cloud-barista/cb-spider/issues/1045 해결 후 정상 동작 됨

<br>

**[Test 환경]** 
- #1045 적용 가정하에 시험한 결과임
- 다음 환경에서 실험 완료 **(Image ID, Spec ID 참고)**
- 엄청 오래 걸림(Console에서 해도 오려 걸림)

```
  * windows: 
	- VM Image: disk 100G 이미지 조건, KR-1 Zone에서 SPSW0WINNTEN0016A (disk 100G)
	- VM Spec: disk 100G 스펙 조건, KR-1 Zone에서 SPSVRSTAND000004A (2cpu, 4GB,100GB)
```

**Comment by powerkimhub** [comment]
- Completed in https://github.com/cloud-barista/cb-spider/pull/1088
