### ISSUE TITLE
[NHN/NCP Classic] Implement ImageHandler.CheckWindowsImage()

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1045]
- 구현이 안되어 있으면, 
- 일부 기능에서 정상 동작하지 않을 수 있습니다.

**Comment by innodreamer** [comment]
일단 간단히 확인했을때, NCP Classic의 경우는 MyImageHandler에 CheckWindowsImage()를 구현해놓고 사용하고 있습니다.
(그걸로 PublicImage, MyImage 경우 모두 WindowsImage 여부 판단)

- NCP VMHandler 내에서 적용한 예
isPublicWindowsImage, err := myImageHandler.CheckWindowsImage(vmReqInfo.ImageIID)
isMyWindowsImage, err := myImageHandler.CheckWindowsImage(vmReqInfo.ImageIID)

**Comment by powerkimhub** [comment]
- 해당 함수는 아래와 같이 서버에서 호출 되고 있습니다. 

https://github.com/cloud-barista/cb-spider/blob/fe7bac19943eded37f43a24a9f36f0b77034a81c/api-runtime/common-runtime/VMManager.go#L645

**Comment by innodreamer** [comment]
@powerkimhub 아, 그러면 그 위치에도 구현해놓도록 하겠습니다.

**Comment by powerkimhub** [comment]
- Completed in https://github.com/cloud-barista/cb-spider/pull/1069
- Completed in https://github.com/cloud-barista/cb-spider/pull/1088
