### ISSUE TITLE
[NCP 등] local Function Naming Convention

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1046]
- 다음과 같이 Driver 내부에서만 사용되는 함수 종류는 첫글자를 대문자로 수정이 필요합니다.
- 전체 반영 필요
  ```
  func (vmHandler *NcpVMHandler) GetVmIdByName(vmNameID string) (string, error) {
  ```

**Comment by innodreamer** [comment]
@powerkimhub 첫자가 대문자가 아닌 소문자로 수정해야한다는 의미이시죠?

**Comment by powerkimhub** [comment]
- 넵, 
- 첫자가 대문자이면, 불필요하게 외부에 노출 되어 보안 등의 이슈...

**Comment by innodreamer** [comment]
@powerkimhub 네... 저 맨 위의 멘트가 혼동이 될 수 있을거 같아 재질문했습니다.
꼭 적용이 필요하다면 국내 CSP 외 타 드라이버도 적용이 필요할 거 같습니다.
