### ISSUE TITLE
[NHN/KT] define idmaxlength

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1048]
- 아래와 같이 idmaxlength가 정의 되지 않은 상태입니다.
- 잠재적인 id length 오류 발생 가능성이 존재합니다. 

https://github.com/cloud-barista/cb-spider/blob/5deaa7cbf5c47f272dc80d509ff4922ccf244c83/cloud-driver-libs/cloudos_meta.yaml#L108

**Comment by innodreamer** [comment]
- Update KT Cloud cloudOS-Meta info.
  - https://github.com/cloud-barista/cb-spider/pull/1085/commits/4c39d152c8b38124b358c045f21f23bbb1963b79

**Comment by innodreamer** [comment]
- Update NHN Cloud cloudOS-Meta info
  - https://github.com/cloud-barista/cb-spider/pull/1108/commits/7a2c9e1a9dada17fd43c6a358c5f8b4abe56e003
