### ISSUE TITLE
[KT/RegionZone] RegionZone Fetch Error

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1052]
- ListRegionZone: Pass

  ```
  curl -sX GET "http://localhost:1024/spider/regionzone?ConnectionName=ktcloud-korea-seoul1-config" | json_pp
  ```
  ```
  {
     "regionzone" : [
        {
        .... 중간 생략 ...
        {
           "DisplayName" : "서울",
           "KeyValueList" : [],
           "Name" : "KOR-Seoul",
           "ZoneList" : [
              {
                 "DisplayName" : "KOR-Seoul M",
                 "KeyValueList" : null,
                 "Name" : "95e2f517-d64a-4866-8585-5177c256f7c7",
                 "Status" : "Available"
              },
              {
                 "DisplayName" : "KOR-Seoul M2",
                 "KeyValueList" : null,
                 "Name" : "d7d0177e-6cda-404a-a46f-a5b356d2874e",
                 "Status" : "Available"
              }
           ]
        }
     ]
  }
  ```

- GetRegionZone(`KOR-Seoul`): Fail
  - 위 목록에서 얻은 `KOR-Seoul` 리전에 대한 RegionZone 정보 요청시 다음과 같은 오류가 발생합니다. 
  ```
  curl -sX GET "http://localhost:1024/spider/regionzone/KOR-Seoul?ConnectionName=ktcloud-korea-seoul1-config" | json_pp
  ```
  ```
  {
     "message" : "Failed to Get Valid RegionCode : The RegionCode are Not Exist!! "
  }
  ```

- ListOrgZone(): Fail
  - 모든 Zone 원본 정보 목록 요청시 다음과 같은 오류가 발생합니다. 
  ```
  curl -sX GET "http://localhost:1024/spider/orgzone?ConnectionName=ktcloud-korea-seoul1-config" | json_pp
  ```
  ```
  {
     "message" : "Failed to Get Valid RegionCode : The RegionCode are Not Exist!! "
  }
  ```

- Region Zone 관련 API 규격 등은 다음을 참고해주시기 바랍니다. 
  - [REST API Region Zone Information Guide](https://github.com/cloud-barista/cb-spider/wiki/REST-API-Region-Zone-Information-Guide)

**Comment by innodreamer** [comment]
@powerkimhub 제가 좀전에 테스트해보니 정상작으로 나오는데 어떤 상황으로 저런 오류가 나오는지 모르겠네요.
``
~/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/test/region-zone-test]# ./11.ktcloud-region-zone-test.sh 
#### Region-Zone Test Process - Start ###

### Region/Zone : List
{
   "regionzone" : [
      {
         "DisplayName" : "김해",
         "KeyValueList" : [],
         "Name" : "KOR-HA",
         "ZoneList" : [
            {
               "DisplayName" : "KOR-HA",
               "KeyValueList" : null,
               "Name" : "dfd6f03d-dae5-458e-a2ea-cb6a55d0d994",
               "Status" : "Available"
            }
         ]
      },
      {
         "DisplayName" : "천안",
         "KeyValueList" : [],
         "Name" : "KOR-Central",
         "ZoneList" : [
            {
               "DisplayName" : "KOR-Central A",
               "KeyValueList" : null,
               "Name" : "eceb5d65-6571-4696-875f-5a17949f3317",
               "Status" : "Available"
            },
            {
               "DisplayName" : "KOR-Central B",
               "KeyValueList" : null,
               "Name" : "9845bd17-d438-4bde-816d-1b12f37d5080",
               "Status" : "Available"
            }
         ]
      },
      {
         "DisplayName" : "서울",
         "KeyValueList" : [],
         "Name" : "KOR-Seoul",
         "ZoneList" : [
            {
               "DisplayName" : "KOR-Seoul M",
               "KeyValueList" : null,
               "Name" : "95e2f517-d64a-4866-8585-5177c256f7c7",
               "Status" : "Available"
            },
            {
               "DisplayName" : "KOR-Seoul M2",
               "KeyValueList" : null,
               "Name" : "d7d0177e-6cda-404a-a46f-a5b356d2874e",
               "Status" : "Available"
            }
         ]
      }
   ]
}
# start: 1708404429.105539407
# finish: 1708404429.791158219
# diff(sec): .685618812

### Region/Zone : Get
{"Name":"KOR-Seoul","DisplayName":"서울","ZoneList":[{"Name":"95e2f517-d64a-4866-8585-5177c256f7c7","DisplayName":"KOR-Seoul M","Status":"Available","KeyValueList":null},{"Name":"d7d0177e-6cda-404a-a46f-a5b356d2874e","DisplayName":"KOR-Seoul M2","Status":"Available","KeyValueList":null}],"KeyValueList":[]}

### ORG Region : List
{
   "RegionList" : [
      {
         "RegionCode" : "KOR-Seoul",
         "RegionName" : "서울"
      },
      {
         "RegionCode" : "KOR-Central",
         "RegionName" : "천안"
      },
      {
         "RegionCode" : "KOR-HA",
         "RegionName" : "김해"
      }
   ]
}

### ORG Zone : List
{
   "ZoneList" : [
      {
         "allocationstate" : "Enabled",
         "dhcpprovider" : "VirtualRouter",
         "id" : "95e2f517-d64a-4866-8585-5177c256f7c7",
         "localstorageenabled" : false,
         "name" : "KOR-Seoul M",
         "networktype" : "Advanced",
         "securitygroupsenabled" : false,
         "tags" : []
      },
      {
         "allocationstate" : "Enabled",
         "dhcpprovider" : "VirtualRouter",
         "id" : "d7d0177e-6cda-404a-a46f-a5b356d2874e",
         "localstorageenabled" : false,
         "name" : "KOR-Seoul M2",
         "networktype" : "Advanced",
         "securitygroupsenabled" : false,
         "tags" : []
      }
   ]
}
#### Region-Zone Test Process- Finished ##
``

**Comment by innodreamer** [comment]
@powerkimhub 참고로, 위에서 사용한 테스트 스크립트는 아래와 같습니다.
```
#!/bin/bash
echo "#### Region-Zone Test Process - Start ###"

sleep 1 
echo -e "\n### Region/Zone : List"
start=`date +%s.%N`
curl -sX GET http://localhost:1024/spider/regionzone -H 'Content-Type: application/json' -d '{"ConnectionName": "'${CONN_CONFIG}'"}' | json_pp
finish=`date +%s.%N`
diff=$( echo "$finish - $start" | bc -l )
echo '# start:' $start
echo '# finish:' $finish
echo '# diff(sec):' $diff

sleep 2 
echo -e "\n### Region/Zone : Get"
curl -sX GET http://localhost:1024/spider/regionzone/${REGION_NAME} -H 'Content-Type: application/json' -d '{"ConnectionName": "'${CONN_CONFIG}'"}'

sleep 2 
echo -e "\n### ORG Region : List"
curl -sX GET http://localhost:1024/spider/orgregion -H 'Content-Type: application/json' -d '{"ConnectionName": "'${CONN_CONFIG}'"}' | json_pp

sleep 2
echo -e "\n### ORG Zone : List"
curl -sX GET http://localhost:1024/spider/orgzone -H 'Content-Type: application/json' -d '{"ConnectionName": "'${CONN_CONFIG}'"}' | json_pp

echo "#### Region-Zone Test Process- Finished ###"
```

**Comment by powerkimhub** [comment]
- 최신 버전에서 현황입니다.
- 다음 위치의 스크립트에서도,
  - cb-spider/api-runtime/rest-runtime/test/region-zone-test/11.ktcloud-region-zone-test.sh
- 위에 공유해주신 스크립트로 대체해서 실행해도
- 현재 다음과 같은 오류가 발생하고 있습니다.  

```
ubuntu@powerkim-develop:region-zone-test# ./11.ktcloud-region-zone-test.sh
#### Region-Zone Test Process - Start ###

### Region/Zone : List
{
   "regionzone" : [
      {
         "DisplayName" : "김해",
         "KeyValueList" : [],
         "Name" : "KOR-HA",

        ... 중략 ...

}
# start: 1708409397.261068521
# finish: 1708409397.832398307
# diff(sec): .571329786

### Region/Zone : Get
{"message":"Failed to Get Valid RegionCode : The RegionCode are Not Exist!! "}

### ORG Region : List
{
   "RegionList" : [
      {
         "RegionCode" : "KOR-Seoul",
         "RegionName" : "서울"
      },
      {
         "RegionCode" : "KOR-Central",
         "RegionName" : "천안"
      },
      {
         "RegionCode" : "KOR-HA",
         "RegionName" : "김해"
      }
   ]
}

### ORG Zone : List
{
   "message" : "Failed to Get Valid RegionCode : The RegionCode are Not Exist!! "
}
#### Region-Zone Test Process- Finished ###
```

- #### 다음 Region 정보 등록시 Region Name 설정 부분과 API 인자의 Region Name 정보 확인 부탁 드립니다. 

- Region 등록시 Region 이름이 다음처럼 변경이 된 것 같습니다.
  - 과거(언젠가 복사해서 제가 사용하던 Region 등록 스크립트): `KOR-Central`
  ```
  curl -X POST http://$RESTSERVER:1024/spider/region -H 'Content-Type: application/json' -d '{"RegionName":"ktcloud-korea-cheonan1","ProviderName":"KTCLOUD", "KeyValueInfoList": [{"Key":"Region", "Value":"KOR-Central"}, {"Key":"Zone", "Value":"eceb5d65-6571-4696-875f-5a17949f3317"}]}'
  ```
  - 현재(~/test/connect-config/11.ktcloud-conn-config.sh): `KOR-Cheonan(KOR-Central-A)`
  ```
  curl -X POST http://$RESTSERVER:1024/spider/region -H 'Content-Type: application/json' -d '{"RegionName":"ktcloud-korea-cheonan1","ProviderName":"KTCLOUD", "KeyValueInfoList": [{"Key":"Region", "Value":"KOR-Cheonan(KOR-Central-A)"}, {"Key":"Zone", "Value":"eceb5d65-6571-4696-875f-5a17949f3317"}]}'
  ```

<br>

- but, 현재 test script Region Name 환경 변수 설정(11.ktcloud-region-zone-test.sh): `KOR-Central`
  ```
  export CONN_CONFIG=ktcloud-korea-cheonan1-config
  export REGION_NAME=KOR-Central
  ```

**Comment by innodreamer** [comment]
@powerkimhub ~/test/connect-config/11.ktcloud-conn-config.sh script를 spider에 있는 최종본으로 사용하시기 바랍니다.

현재 github 코드를 web으로본 코드를 캡춰해서 공유해드리고, AdminWeb에서 조회한 Region/Zone 정보를 공유해드립니다.
![image](https://github.com/cloud-barista/cb-spider/assets/51111668/ce8d1946-17bd-48d2-a55f-63423b7369a4)
 
![image](https://github.com/cloud-barista/cb-spider/assets/51111668/ac61e831-1488-4cfd-97cc-cbbb096f6128)

**Comment by powerkimhub** [comment]
@innodreamer 

- 최신 connect-config로 시험하니 잘 실행되네요. 
- JSON 출력 포맷을 위해서 다음처럼 json_pp 파이프라인만 추가해두었습니다.
- https://github.com/cloud-barista/cb-spider/commit/8f06e04add2fe0179faaf4ad4de528329f6f917c
