### ISSUE TITLE
Add Korean checker workflow

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-spider#1064]
**What would you like to be added**
: I'd like to add **a workflow to check if Korean is included in each PR**.

**Why is this needed**
: In recent PRs, it has often been found that it is necessary to modify Korean to English.
: This workflow can automate Korean language checks during reviews, which are trivial but need attention.
: Finally, we can focus on the feature review.

**The workflow tested**
- The workflow: [korean-checker.yaml](https://github.com/yunkon-kim/test-on-github-actions/blob/main/.github/workflows/korean-checker.yaml)
- An example PR: https://github.com/yunkon-kim/test-on-github-actions/pull/140

Please feel free to tell me if you have any comments or concerns :-)

**Comment by powerkimhub** [comment]
- Great suggestion!
- It should boost productivity.

**Comment by powerkimhub** [comment]
@yunkon-kim 

- 다음 상황 확인 부탁 드립니다.
- https://github.com/cloud-barista/cb-spider/actions/runs/7898820615/job/21556993182

**Comment by powerkimhub** [comment]
> @yunkon-kim
> 
> * 다음 상황 확인 부탁 드립니다.
> * https://github.com/cloud-barista/cb-spider/actions/runs/7898820615/job/21556993182

 - new issue opened via https://github.com/cloud-barista/cb-spider/issues/1070
