### ISSUE TITLE
Issue on `korean-checker.yaml` workflow

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-spider#1070]
**What happened**
: Fail to comment PR on `korean-checker.yaml` workflow

**What you expected to happen**
: It seems to be an issue with access permissions to add comments.

Ref. #1069

GitHub Actions execution result
https://github.com/cloud-barista/cb-spider/actions/runs/7898820615/job/21556993182?pr=1069

**Comment by yunkon-kim** [comment]
Ref. #1080

GitHub Actions execution result
https://github.com/cloud-barista/cb-spider/actions/runs/7954682728/job/21712490486?pr=1080

**Comment by powerkimhub** [comment]
- Good, thanks ~

**Comment by yunkon-kim** [comment]
Finally confirmed leaving a comment when a PR contains Korean text (#1097)
