### ISSUE TITLE
[NHN:VPC] Check Latest Version

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1099]
- cf) https://github.com/cloud-barista/cb-spider/pull/1098
---

<br>

- 두번째 VPC를 생성 요청하면, Server에서 다음과 같은 오류를 반환합니다. 
  ```
  {"message":"vpc-nhncloud-korea-pangyo-config can have only 1 VPC, but already have a VPC vpc-01"}
  ```
- Driver Capability 설정 때문입니다. 
- 다음 설정을 `false`로 설정 부탁드립니다. 

https://github.com/cloud-barista/cb-spider/blob/b09b937f912a364e013932530aec00cb10222dfe/cloud-control-manager/cloud-driver/drivers/nhncloud/NHNCloudDriver.go#L51

<br>

- 추가로, AddSubnet/RemoveSubnet API는 
- CSP가 제공하지 않는 기능인지, 추가 계획 중이신건지 문의 드립니다.

**Comment by powerkimhub** [comment]
@innodreamer 

- 추가로 국내 드라이버들의 다음 설정들도 부탁 드립니다. 
  - DriverCapabilityInfo.RegionZoneHandler
  - DriverCapabilityInfo.PriceInfoHandler

**Comment by innodreamer** [comment]
@powerkimhub NHN Cloud drvCapabilityInfo.SINGLE_VPC 정보를 'false'로 보완했습니다.

  (추가로, 아래의 정보 기입 완료)
  drvCapabilityInfo.RegionZoneHandler = true
  drvCapabilityInfo.PriceInfoHandler = false

  - https://github.com/cloud-barista/cb-spider/pull/1108/commits/c44e3c6ebcdf1f73f16fb9c404c9a3a21dd6287c

**Comment by innodreamer** [comment]
@powerkimhub NHN Cloud VPC/Subnet 관련하여 신규 지원 API에 따라 VPCHandler에 AddSubnet(), RemoveSubne(), DeleteVPC() 기능까지 모두 완료되었습니다.
  - Related issue) https://github.com/cloud-barista/cb-spider/issues/1059
