### ISSUE TITLE
 [NHN:Subnet] Review deleteSubnet, addSubnet(), and removeSubnet()

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1106]
**[NHN VPC Create/Delete Pseudo Code 현황]**
- CreateVPC()
  - GetVPC() 호출; 제약 사항으로 존재만 확인
  - createSubnet() 호출: 여러개 subnet 추가 가능
    - 참고
      https://github.com/cloud-barista/cb-spider/blob/e5f096da3d9f233136e5ac1e0ccc0a1bcc3d91eb/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go#L107

- DeleteVPC()
  - GetVPC() 호출; GetVPC()만 실행/확인하고 있음, 

<br>

**[확인/점검 필요 사항]**

- CreateVPC()와 페어링을 위해서 DeleteVPC()에서는 deleteSubnet()이 불필요한지 재확인 부탁드립니다. 
  - subnet이 생성만 되고, 삭제는 안되고 있는 지 확인이 필요해 보입니다. 
  - deleteSubnet()의 경우, 
    - 다음 sdk를 활용하여 실제 subnet 삭제 가능한지도 확인 부탁드립니다.
    - 참고
      https://github.com/cloud-barista/nhncloud-sdk-go/blob/393c599a4b76b6fe572e270cc7f7c429aaf7afba/openstack/networking/v2/subnets/requests.go#L175

- 또한, AddSubnet(), RemoveSubnet()의 경우에는
  - 위의 createSubnet(), deleteSubnet 기능과 유사해보입니다.
  - 혹시, 추가 가능한지 재확인 부탁드립니다.

**Comment by innodreamer** [comment]
@powerkimhub 
지난 유사한 issue에 아직 개발이 진행중이고 완료되지 않은 상태라고 comment 남긴적 있습니다.
참고) https://github.com/cloud-barista/cb-spider/issues/1099#issuecomment-1968909417

**Comment by powerkimhub** [comment]
@innodreamer 

- 아, 그러네요^^
- close 하겠습니다.

**Comment by innodreamer** [comment]
- https://github.com/cloud-barista/cb-spider/pull/1108
