### ISSUE TITLE
[NHN Cloud] The Internet Gateway connection is required to the Routing Table of newly Created VPC

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#1109]
이제 NHN Cloud의 VPC/Subnet Handler 기능 관련하여 신규로 추가된 REST API를 적용하여 VPC/Subnet 추가 및 삭제가 가능해진 상태이다.
이렇게 update된 기능을 이용해 신규로 추가한 VPC를 기반으로 현재의 VMHandler를 이용해 VM을 생성하면 VM이 생성된 뒤 public IP를 할당하는 과정에서 아래와 같은 error가 발생한다.

```
[NHN Cloud Client].[ERROR]: 2024-03-06 18:11:54 VMHandler.go:791, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudVMHandler).associatePublicIP() - Failed to AssociateInstance the Public IP!! : [Bad request with: [POST https://kr1-api-instance-infrastructure.nhncloudservice.com/v2/a77e25da7cc04a388716a7dc10dc9340/servers/6878eb1c-34fe-46b3-a284-d7e47a49dce3/action], error message: {"badRequest": {"message": "Unable to associate floating IP 180.210.83.106 to fixed IP 172.16.0.45 for instance 6878eb1c-34fe-46b3-a284-d7e47a49dce3. Error: External network a858742a-245b-41d3-9a05-617e1b069eb9 is not reachable from subnet 566a2f4d-6171-4b7f-8d42-fe1f47f91d86.  Therefore, cannot associate Port 8a86bc2a-2f35-4ce9-8fda-96191027a275 with a Floating IP.\nNeutron server returns request_ids: ['req-239b7feb-1bbb-44eb-8da4-5dd2467a04cf']", "code": 400}}]  
```

이 error의 원인은 신규로 생성된 VPC에 해당하는 (default) Routing Table에 Internet Geteway가 연결되지 않은 상태이기 때문이다.
참고로, 전에는 API를 이용해 VPC/Subnet을 추가할 수 없는 상태여서, API로는 'Default Network'라는 이름의 단일 VPC만 사용 가능할 때는 console에서 그 단일 VPC에 해당하는 Routing Table에 Internet Geteway를 연결해놓고 사용한 상태였고, API로 그 VPC만 사용하게 되니 이런 error가 발생하지 않았다.

Ref)
  - https://docs.nhncloud.com/ko/Network/Floating%20IP/ko/overview/
  - https://docs.nhncloud.com/ko/Network/Internet%20Gateway/ko/overview/

![image](https://github.com/cloud-barista/cb-spider/assets/51111668/b0a76833-8e09-44b0-8a25-7115a5516cfc)
(신규 VPC에 해당하는 Routing Table에 Internet Geteway를 연결하고, VM public IP를 생성한 상태)

이러한 error를 발생하지 않게 하기 위해 신규 생성한 VPC에 해당하는 Routing Table에 Internet Geteway를 연결하는 기능을 추가해야한다. (가능한한 console이 아닌 API를 통해 연결해야함.)

**Comment by innodreamer** [comment]
일단 신규로 지원하는 VPC/Subnet 관련 API를 확인해보면 Routing Table에 Internet Geteway를 연결하는 기능은 지원한다.
 - Ref) https://docs.nhncloud.com/ko/Network/VPC/ko/public-api/#_38

그러나, Internet Gateway를 추가/조회/삭제가 가능해야 사용하지 않는 Internet Gateway를 연결할 수 있는데, 그러한 기능은 API는 아직 찾을 수 없어 고객센터에 문의가 필요하다.
(참고, NHN Cloud에서 Internet Gateway는 VPC와 같이 default로 3개까지만 생성 가능)

**Comment by innodreamer** [comment]
NHN 고객센터에 문의한 결과, Internet Gateway를 추가/조회/삭제 기능의 API는 아직 공식적으로 지원하지 않아 그 기능은 console을 통해서 해야하고 그와 관련된 사항을 향후 업데이트하겠다는 답변을 받았음.

따라서, 현재 상황으로는 아래와 같이 console에서의 작업이 필요한 상태임.
1) Cloud-Barista를 이용해서 VPC를 신규로 생성
2) Console에서 Internet Gateway를 생성하고 그 신규 VPC에 해당하는 기본 Routing Table에 연결

(참고)
  - 다른 Routing Table에 연결된 Internet Gateway는 연결할 수 없음.
  - 기본 Routing Table을 이용해도 되니 Routing Table을 추가로 생성할 필요는 없음

- Console상의 관련 메뉴
  - Internet Gateway 생성시
    - Console > Network > Internet Gateway : 
  - Internet Gateway 연결시
    - Console > Network > Routing > 인터넷 게이트웨이 연결 :

그리고, 추가적으로 확인한 사항으로서, VPC와 Internet Gateway 생성/사용이 3개로 제한되어 있는 상황이어서 쿼터를 증가시킬 수 있는지 문의해서 받은 답변으로서 project별로 증가가 가능하다고 함.

**Comment by innodreamer** [comment]
NHN Cloud에 요청하여 VPC 및 Internet Gateway 사용 쿼터를 project당 5개로 증가 시켰음.

**Comment by innodreamer** [comment]
위와 관련하여, Cloud-Barisita를 이용해 NHN Cloud VM을 생성할때, 실제 VM이 생성되기 전에, 사용자가 지정한 VPC에 해당하는 Routing Table이 Internet Gateway에 연결된 상태인지 체크되도록 업데이트함.
 - PR : https://github.com/cloud-barista/cb-spider/pull/1110

**Comment by powerkimhub** [comment]
- NHN가 IG(Internet Gateway) 제어 API 제공 시점까지 다음처럼 Register/UnRegister VPC로 활용
- https://github.com/cloud-barista/cb-spider/issues/1196#issuecomment-2117713927
