### ISSUE TITLE
Can we provide a VM with a GPU in GCP ?

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#1124]
- 현재 CB-Spider에서 GCP의 경우 GPU가 포함된 VM을 생성할 수 있는 방법이 있는지 문의드립니다.

**Comment by powerkimhub** [comment]
[현황]
  - 현재 Spider 버전은 다음 오류가 발생합니다.
    ```
    {"message":"googleapi: Error 400: Instances with guest accelerators do not support live migration., badRequest"}
    ```
[계획]
  - 신규 이슈 오픈해서 해결 예정입니다.

**Comment by seokho-son** [comment]
@powerkimhub 확인 감사합니다.

**Comment by powerkimhub** [comment]
@seokho-son 

- 다음 이슈를 참고하여 GPU-VM 배포를 활용해보시기 바랍니다. 
- https://github.com/cloud-barista/cb-spider/issues/1125
