### ISSUE TITLE
[NHN Cloud] Support Windows VM Login with 'cb-user' account using cloud-init

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#1136]
**What would you like to be enhanced**
- 아래와 같은 이유들로 NHN Cloud VM의 guest OS중 Windows OS는 타 CSP의 Windows OS 경우와는 다르게 예외적으로 'cb-user' 계정으로 login 가능하도록 드라이버를 통해 계정 생성 필요함.

**Why is this needed**
- NHN Cloud VM의 Windows OS는 기본적으로 Administrator 계정의 초기 login 비밀번호를 확인할 때, console에서 VM 생성시 지정한 keypair(private key)를 이용해서 확인하는 방법을 지원하고 있음.
- 그러나 위의 방법은 사용자가 Cloud-Barista를 이용해서 VM을 생성한 후 NHN Cloud console에 접속해서 VM Admin 비밀번호를 확인해야하는 번거로움이 있음.
- 또한, NHN Cloud의 VM Windows OS 경우는 cloud-init 으로 'Administrator' PW를 변경할 수는 없고 다른 이름의 계정은 생성 가능함. 

**Proposed solution**
- 적용 방법은 타 CSP의 경우와 유사하게 사용자가 Cloud-Barista를 이용해서 VM을 생성할때 드라이버 내부적으로 Windows image 여부를 판별하여 Windows image인 경우는 windows VM에 해당하는 cloud-init script가 실행되도록함.
- 단, NHN Cloud의 경우는 cloud-init 으로 'Administrator' PW를 변경할 수는 없으므로 예외적으로 'cb-user' 계정으로 사용자 계정을 생성하고 admin group에 포함시킴.

**Comment by powerkimhub** [comment]
- Related Issue: https://github.com/cloud-barista/cb-spider/issues/805
