### ISSUE TITLE
[Server:PMKS:AWS] Cannot fetch Cluster Info after deleting NodeGroup 

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1142]
cc) @sykim-etri 

- AdminWeb에서 AWS Cluster의 NodeGroup 삭제 직후 Get Cluster시 다음 오류 발생
- Asnyc 호출에 의한 meta 정보 불일치 문제로 예상
- ※ 10분 정도 후에 CSP에서 NodeGroup이 삭제 되고 나면, Get Cluster가 정상 동작

```
[오전 12:30:52] curl -sX GET http://localhost:1024/spider/cluster -H 'Content-Type: application/json' -d '{"ConnectionName": "aws-config01"}'
[오전 12:30:52]    ==> {"message":"aws-config01, spider-cluster-01, economy-co5tk53p70iv25uho6ig: does not exist!"}
```

**Comment by powerkimhub** [comment]
@sykim-etri 

- 혹시, 전에 유사 이슈 있었다면 현 이슈에 매달아 주시기 바랍니다.

**Comment by sykim-etri** [comment]
노드그룹 삭제 후 클러스터 정보 조회시 에러가 발생하는 [이슈](https://github.com/cloud-barista/cb-spider/issues/1012)가 있었으나 발생 원인은 상이할 것으로 예상됩니다.

**Comment by powerkimhub** [comment]
- 감사합니다.

**Comment by powerkimhub** [comment]
- Fixed in https://github.com/cloud-barista/cb-spider/commit/99bfb598ef60e5786b77f78755e5f2d3d4bdf76b
