### ISSUE TITLE
[Azure:Zone] Disk cannot be attached to a VM in Zone 2 and MyImage ...

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1153]
- #### 다음 Zone 개념 추가 PR을 반영한 버전의 시험 결과가 아래와 같습니다. 
  - https://github.com/cloud-barista/cb-spider/pull/1152

- #### 아래 시험 결과 중 `Fail` 부분(disk attach, vm creation with MyImage) 확인 부탁 드립니다. 

---

- Region 등록: `northeurope`, `Zone 2`
  - 참고: 최신 Spider 서버에서 `location`을 `Region`으로 변경 => `Region` Key로 등록
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/0d233930-2e20-450d-a7a2-cdaca8a6e35b)

- Connection 등록
  - 위 등록한 Region 정보를 이용한 Connection 등록
  - 이하 자원 제어 시험에 활용

<br>

- VPC/Subnet, SG, Key 등 생성: OK

<br>

- VM 생성: OK (`Zone 2`에 잘 생성됨)
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/add5636a-68c9-4c95-8f23-6cdd7e3004b6)

<br>
<br>

- Disk 생성: OK (azure console에서 zone 정보 확인 못함)
- 생성한 Disk를 **vm1에 Attach: Fail**
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/65f449fb-872f-4fd3-83cd-b40e9ce13055)

<br>

-  - 현재 다음과 같은 Zone mismatch 오류 발생

<br>

  ```
  [오후 8:15:25] PUT> http://localhost:1024/spider/disk/spider-disk-01/attach -H 'Content-Type: application/json' -d '{ "ConnectionName": "azure-region-zone-01", "ReqInfo": { "VMName" : "vm-01" } }'
  [오후 8:15:31]    ==> {"message":"Failed to AttachDisk. err = compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"BadRequest\" Message=\"Disk /subscriptions/a20fed83-96bd-4480-92a9-140b8e3b7c3a/resourceGroups/NORTHEUROPE/providers/Microsoft.Compute/disks/spider-disk-01-cobs9tjp70ijpqlmm430 cannot be attached to the VM because it is not in zone '2'.\""}  
  ``` 

<br>
<br>

- NLB 생성: OK
  - vm2 추가 생성 후 NLB 생성
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/8fb365cd-0426-4a11-9e6e-515cf9e0ffdf)
- NLB 호출/Forwarding: OK
  ```
  nc -v 52.169.217.148 22
  Connection to 52.169.217.148 22 port [tcp/ssh] succeeded!
  ```

<br>
<br>

- MyImage 생성(Snapshot): OK
  - 참고: Azure의 경우 Snaphot 시 대상 VM은 generalized 됨(사용 불가, `suspended`: 정상)

<br>

- **MyImage를 이용한 VM 생성: Fail**
  - 이 오류는 현재 상태에서는 Spider 서버 오류인지, Driver 오류인지 파악 하기가 쉽지 않네요. 
  - Driver 수준에서 시험 선행 부탁 드립니다.

**Comment by powerkimhub** [comment]
cc: @ish-hcc @seokho-son 

- 추가 시험
  - AZ가 존재하지 않는 Region(location) `koreasouth` 대상으로 Zone 설정 효과 시험 
- Region 설정
  - Zone 구분이 없지만, 
  - 다음처럼 `Zone 1`로 설정(설정은 하지만, 무의미 할 것으로 판단)
  - ※ 현재는 Zone Key가 없으면 Region 등록시 Spider 서버에서 validation 에러 처리됨
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/a1d2b692-ee0b-4d8c-8649-ca19c8e194a5)

<br>

- VM 생성: azure console에서도 Zone 정보를 제공하지 않음을 확인
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/2e53669c-8190-4684-a59b-07a3dd8fb401)

<br>

- 이 경우 `Zone` 구분이 없기 때문에 예상대로 **disk attach도 성공함**


---

- Zone을 2로 설정 후 동일한 시험
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/b5b03ed1-0166-4f53-85c6-3f3e214dc094)
- 결과는 Zone 1과 동일

[고찰]
- Zone을 제공하지 않는 location(koreasouth 등)의 경우 
- 현재 사용자의 Zone 설정과 무관하게(Zone 지원 여부 확인하지 않고) Region 수준에서 자원이 잘 제어됨

[계획]
- 조만간, Zone-Level Control이 마무리 되면, VM과 Disk 정보에 `Zone` 정보를 제공할 것이며,
- 사용자는 이 정보를 확인하여 VM이나 Disk가 Region에 binding된 건지(자원 정보에 Zone 정보가 없을 경우) Zone에 binding 된 것인지 판단 가능하므로, 
- 현재는, 특별히 이슈가 되지 않는 한 현 상태로 유지

**Comment by ish-hcc** [comment]
@powerkimhub
상세한 리뷰 감사합니다. MyImage 부분은 테스트 해보니 다른 CSP 에서도 동일한 문제가 발생하는거 같습니다.

이 부분에서 DiskType 은 default 인데 diskSize 정보가 없어서 발생하는 문제로 보입니다.
https://github.com/cloud-barista/cb-spider/blob/master/api-runtime/common-runtime/VMManager.go#L630

### 테스트 진행 사항
- Azure에서 MyImage로 VM 생성시 reqInfo
&{{vm-02 } MyImage {spider-myimage-01 spider-myimage-01} {vpc-01 } {subnet-01 } [{sg-01 }] Standard_B1ls {keypair-01 } default  [] Administrator cloudbarista123^ false}
- Azure에서 PublicImage로 VM 생성시 reqInfo
&{{vm-01 } PublicImage {Canonical:UbuntuServer:18.04-LTS:latest Canonical:UbuntuServer:18.04-LTS:latest} {vpc-01 } {subnet-01 } [{sg-01 }] Standard_B1ls {keypair-01 } default  [] Administrator cloudbarista123^ false}

- IBM에서 MyImage로 VM 생성시 reqInfo
&{{vm-03 } MyImage {spider-myimage-01 spider-myimage-01} {vpc-01 } {subnet-01 } [{sg-01 }] bx2-2x8 {keypair-01 } default  [] Administrator cloudbarista123^ false}

**Comment by ish-hcc** [comment]
Disk Zone 관련 수정 완료
https://github.com/cloud-barista/cb-spider/pull/1164

**Comment by powerkimhub** [comment]
> @powerkimhub 상세한 리뷰 감사합니다. MyImage 부분은 테스트 해보니 다른 CSP 에서도 동일한 문제가 발생하는거 같습니다.

<br> 

- 관련 시험 및 현황 공유 캄사 드립니다. 
- 이 에러는 그 사이 다른 사유로 AdminWeb 파트 수정 사항이 있었는데, 
- 의도치 않게 MyImage 기반 VM 생성에 영향을 주었네요. 
- 이 이슈는 서버 파트에서 patch하도록 하겠습니다.

**Comment by ish-hcc** [comment]
@powerkimhub 넵 알겠습니다 감사합니다!

**Comment by powerkimhub** [comment]
- Disk Attach Error fixed via [#1164](https://github.com/cloud-barista/cb-spider/pull/1164)
- VM Creation Error with MyImage fixed via https://github.com/cloud-barista/cb-spider/commit/975bb16ce2646e44f409767b4858e99c88e329bc
