### ISSUE TITLE
[Bug] Need to update initClientOpts() function in client.go related to endpoint

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#1161]
@sykim-etri 전에 올려주신 이 PR (https://github.com/cloud-barista/nhncloud-sdk-go/pull/37) 관련하여, NHN cloud driver를 전체적으로 다시 테스트해봤습니다.

관련하여 driver에서 보완되어야할 부분은 제가 update했는데, go SDK에 대해서는 아래의 사항을 좀 보완해주시기 바랍니다.

[ 오류 내용 ]
AdminWeb 기준으로 VPC 생성 테스트시, KR1 / KR2 region에 해당하는 connection config에서는 VPC가 정상적으로 생성되는데,
JPN region에서는 VPC 생성시 아래와 같은 오류가 발생합니다.

```
[CLOUD-BARISTA].[INFO]: 2024-04-15 19:47:39 client.go:370, github.com/cloud-barista/nhncloud-sdk-go/openstack.initClientOpts() - 
 
[CLOUD-BARISTA].[INFO]: 2024-04-15 19:47:39 client.go:362, github.com/cloud-barista/nhncloud-sdk-go/openstack.initClientOpts() - err=No suitable endpoint could be found in the service catalog.
 
[CLOUD-BARISTA].[ERROR]: 2024-04-15 19:47:39 VPC-SubnetManager.go:335, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateVPC() - No suitable endpoint could be found in the service catalog. 
```

./cloud-barista/nhncloud-sdk-go/openstack/client.go 파일에서 관련 부분을 좀 보완하셔야할거 같습니다.

**Comment by sykim-etri** [comment]
@innodreamer

**Comment by sykim-etri** [comment]
@innodreamer , @powerkimhub 
상기와 같이 리전별로 제공하는 서비스가 다를 경우 대응할 좋은 방안이 있을까요?
cloud-driver-libs/cloudos_meta.yaml 방식이 유효할지 검토가 필요할 것 같습니다.

당장은 코드 상에서 리전값에 따라 분기하여 처리할 예정입니다.

**Comment by innodreamer** [comment]
@sykim-etri (@powerkimhub)
최신 Spider 코드로 실행해도 아직 JPN region에서 VPC 생성시 저 맨 위에 명시한 error가 발생합니다.

코드를 수정하신 뒤에는 항상 제시된 error가 다시 발생하지 않는지 테스트를 해주시기 바랍니다.

**Comment by powerkimhub** [comment]
@innodreamer 

<br>

- 최신 소스에서 다음 Region/Zone에서 VPC 생성이 잘 되고 있습니다. 
- 재확인 부탁 드립니다. 
  ```
  Region:JP1, Zone:jp-pub-a,
  ```
- Create VPC 결과
```
[오후 5:38:49] curl -sX POST http://localhost:1024/spider/vpc -H 'Content-Type: application/json' -d '{ "ConnectionName" : "nhncloud-japan-tokyo-config", "ReqInfo" : { "Name" : "vpc-01", "IPv4_CIDR" : "10.0.0.0/16", "SubnetInfoList" : [ { "Name": "subnet-01", "Zone": "jp-pub-a", "IPv4_CIDR": "10.0.8.0/22"} ] }}'
[오후 5:38:53]    ==> {"IId":{"NameId":"vpc-01","SystemId":"d7173b3c-9c99-4be9-9aa4-9d1321d16262"},"IPv4_CIDR":"10.0.0.0/16","SubnetInfoList":[{"IId":{"NameId":"subnet-01","SystemId":"1084a732-79e9-4fba-8893-e50d67828413"},"Zone":"","IPv4_CIDR":"10.0.8.0/22","KeyValueList":[{"Key":"VPCId","Value":"d7173b3c-9c99-4be9-9aa4-9d1321d16262"},{"Key":"RouterExternal","Value":"No"},{"Key":"CreatedTime","Value":"2024-04-17 08:38:54"}]}],"KeyValueList":[{"Key":"Status","Value":"available"},{"Key":"RouterExternal","Value":"No"},{"Key":"CreatedTime","Value":"2024-04-17 08:38:51"}]}

```

**Comment by powerkimhub** [comment]
@innodreamer 

- NHN go SDK를 별도로 받지는 않고, 
- Spider mod에 따라 받아 지는 환경으로 시험한 결과입니다.

**Comment by sykim-etri** [comment]
@innodreamer 

기존 생성된 MCIR(VPC, SecurityGroup, Spec 등)을 삭제하려고 하니 유사한 에러가 발생하고 있습니다.
아마도 현재 NHN Cloud쪽 이슈가 있는 것으로 생각됩니다.

**Comment by innodreamer** [comment]
@sykim-etri (@powerkimhub)
오류 원인을 찾아서 PR 올렸습니다.

@sykim-etri 님이 NhnCloudDriver.go code를 update하실 때 실수로 NhnCloudDriver-lib.go는 update하지 않으셔서 오류가 발생한거 같습니다.
따라서, 아래와 같이 향후에는 이런 문제가 없도록 NhnCloudDriver.go가 그대로 반영되도록 보완했습니다.
 - Related PR : https://github.com/cloud-barista/cb-spider/pull/1166

**Comment by innodreamer** [comment]
저는 plug-in mode(dynamic mode)로 사용하고 있어서 이런 오류를 발견했네요.
향후 타 국내 CSP driver들도 이렇게 update할 예정입니다.

본 issue를 close합니다.
