### ISSUE TITLE
Are the spec lists the same for all regions on Alibaba?

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#1181]
CB-Tumblebug에서는 모든 리전의 vm spec 리스트를 조회합니다. 
관련하여, Alibaba의 경우 vm spec 리스트를 제공하는데 부하가 큰 것으로 보여서, 아래와 같이 질문 드립니다.

Alibaba의 경우, 
- 리전(존)별로 CSP의 vm spec 리스트 조회시, 모두 동일한 값을 리턴하는 것으로 보이는데 맞나요? (모든 리전의 결과가 1483개)
- 그렇다면, 그 이유가 Alibaba의 경우 VM spec list가 리전과 무관하게 동일하여, Alibaba가 리전별로 VM spec을 조회하는 별도의 방법을 제공하지 않아서 그런 것일까요?

```
12:48AM INF core/mcir/common.go:1453 > [alibaba-ap-southeast-5-ap-southeast-5a] #Spec: 1483
12:48AM INF core/mcir/common.go:1453 > [alibaba-cn-heyuan-cn-heyuan-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-us-west-1-us-west-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-wulanchabu-cn-wulanchabu-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-huhehaote-cn-huhehaote-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-qingdao-cn-qingdao-b] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-eu-west-1-eu-west-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-southeast-7-ap-southeast-7a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-nanjing-cn-nanjing-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-chengdu-cn-chengdu-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-wuhan-lr-cn-wuhan-lr-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-southeast-2-ap-southeast-2a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-northeast-2-ap-northeast-2a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-shenzhen-cn-shenzhen-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-south-1-ap-south-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-shanghai-cn-shanghai-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-me-east-1-me-east-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-southeast-6-ap-southeast-6a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-zhangjiakou-cn-zhangjiakou-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-hongkong-cn-hongkong-b] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-guangzhou-cn-guangzhou-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-me-central-1-me-central-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-hangzhou-cn-hangzhou-b] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-us-east-1-us-east-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-southeast-1-ap-southeast-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-eu-central-1-eu-central-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-fuzhou-cn-fuzhou-a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-northeast-1-ap-northeast-1a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-ap-southeast-3-ap-southeast-3a] #Spec: 1483
12:49AM INF core/mcir/common.go:1453 > [alibaba-cn-beijing-cn-beijing-a] #Spec: 1483
```

**Comment by seokho-son** [comment]
@powerkimhub 어느분께 여쭤보면 되는지 문의드립니다.

**Comment by raccoon-mh** [comment]
@seokho-son @powerkimhub 
늦게 확인드려 죄송합니다.

Alibaba cloud 의 경우 스펙 조회에 있어 리전별로 다른결과를 제공하지 않습니다.

https://api.alibabacloud.com/api/Ecs/2014-05-26/DescribeInstanceTypes?sdkStyle=old&tab=DEBUG
위 API debug 콘솔에서 확인해보시면 모든 리전에서 같은결과 반환하는 것을 확인해 보실 수 있습니다. 

DescribeInstanceTypes 작업은 인스턴스 유형의 사양 및 성능 정보만 쿼리하는 데 사용됩니다

https://api.alibabacloud.com/document/Ecs/2014-05-26/DescribeInstanceTypes
위 API 문서에 따르면 DescribeInstanceTypes 가 아닌 특정 리전에서만 사용가능한 인스턴스는 DescribeAvailableResource 를 통해 조회 할 수 있다고 하고 있습니다.  

https://www.alibabacloud.com/help/en/ecs/developer-reference/api-ecs-2014-05-26-describeavailableresource
DescribeAvailableResource 는 다음 목표를 갖고 있습니다.
Queries the availability of resources in a zone. You can call this operation before you create or modify instances to ensure that sufficient resources are available.

DescribeAvailableResource 조회시 다음과 같은 결과를 얻을 수 있습니다.

 - "RegionId": "cn-beijing" CALL
```
// "RegionId": "cn-beijing" CALL
{
  "RequestId": "************",
  "AvailableZones": {
    "AvailableZone": [
      {
        "Status": "Available",
        "StatusCategory": "WithStock",
        "ZoneId": "cn-beijing-f",
        "AvailableResources": {
          "AvailableResource": [
            {
              "Type": "InstanceType",
              "SupportedResources": {
                "SupportedResource": [
                  {
                    "Status": "Available",
                    "StatusCategory": "WithStock",
                    "Value": "ecs.g7nex.xlarge"
                  },
                  {
                    "Status": "SoldOut",
                    "StatusCategory": "WithoutStock",
                    "Value": "ecs.gn7i-c8g1.2xlarge"
                  },
                  {
                    "Status": "Available",
                    "StatusCategory": "WithStock",
                    "Value": "ecs.hfg7.2xlarge"
                  },
		....
                ]
              }
            }
          ]
        },
        "RegionId": "cn-beijing"
      }
    ]
  }
}
```

 - "RegionId": "eu-west-1" CALL
```
// "RegionId": "eu-west-1" CALL
{
  "RequestId": "*********",
  "AvailableZones": {
    "AvailableZone": [
      {
        "Status": "Available",
        "StatusCategory": "WithStock",
        "ZoneId": "eu-west-1b",
        "AvailableResources": {
          "AvailableResource": [
            {
              "Type": "InstanceType",
              "SupportedResources": {
                "SupportedResource": [
                  {
                    "Status": "Available",
                    "StatusCategory": "WithStock",
                    "Value": "ecs.g6e.13xlarge"
                  },
                  {
                    "Status": "Available",
                    "StatusCategory": "WithStock",
                    "Value": "ecs.g5ne.large"
                  },
		....
                ]
              }
            }
          ]
        },
        "RegionId": "eu-west-1"
      }
    ]
  }
}

```
기존 스펙에 대한 상세를 제공하는 DescribeInstanceTypes 에서는 아래와 같은 정보를 반환하지만 특정 리전의 결과가 궁금한 경 우, 위 DescribeAvailableResource 가 적합할 수 있을 것 같습니다. 
```
...
{
        "NvmeSupport": "unsupported",
        "PrimaryEniQueueNumber": 1,
        "TotalEniQueueQuantity": 1,
        "EniTrunkSupported": false,
        "InstanceTypeFamily": "ecs.t1",
        "EriQuantity": 0,
        "SecondaryEniQueueNumber": 1,
        "PhysicalProcessorModel": "",
        "LocalStorageCategory": "",
        "GPUSpec": "",
        "CpuArchitecture": "X86",
        "InstanceTypeId": "ecs.t1.xsmall",
        "SupportedBootModes": {
          "SupportedBootMode": [
            "BIOS"
          ]
        },
        "MemorySize": 0.5,
        "EniIpv6AddressQuantity": 0,
        "EniTotalQuantity": 1,
        "CpuCoreCount": 1,
        "InstanceCategory": "",
        "EniQuantity": 1,
        "GPUAmount": 0,
        "DiskQuantity": 17,
        "CpuSpeedFrequency": 0,
        "InstanceFamilyLevel": "EntryLevel",
        "CpuTurboFrequency": 0,
        "EniPrivateIpAddressQuantity": 1
      },
...
```

결론은 현재 Alibaba vmspec 의 경우 DescribeInstanceTypes 를 사용하여 상세한 정보를 모든 리전에서 제공하고 있습니다. 리전 별 특정 리전에서만 사용가능한 리소스에 대한 조회가 필요할 경우 DescribeAvailableResource 를 사용해야 합니다.

의견 부탁드립니다.

**Comment by powerkimhub** [comment]
@raccoon-mh (@seokho-son )

<br>

- 분석 캄사 드립니다. 
- 공유 해주신 내용을 토대로 보완 정리한 내용이 다음과 같습니다. 
 
<br>

### * Alibaba VM Instance Type 정보 제공 현황

<br>

<p align="center">
<img width=650 src="https://github.com/cloud-barista/cb-spider/assets/46367962/4cbbea14-1255-41e6-a0c7-b86bd856747e">

<br>

**[DescribeInstanceTypes API]**
- Region에 상관 없이 Alibaba가 제공하는 Instance Type의 전체 목록을 제공
- 입력으로 사용되는 Region은 API를 호출할 endpoint 위치 용도로 추정됨(어떤 리전에 물어봐도 목록은 동일함)
- 2024/05/24 현재 전체 Instance Type 목록 수: 1490개

<br>

**[DescribeAvailableResource API]**
- 특정 Region이 제공하는 Instnace Type 목록 및 각 Instance Type 의 현재 가용 여부(Available | SoldOut) 제공
  - Region내 Zone별로 제공하는 Instance Type 목록을 제공하며, Zone별로 제공 목록이 다름
  - 제공 목록에는 현재 `SoldOut` 상태인 InstnanceType도 존재하므로,  
  - 제공 받은 모든 목록으로 VM을 생성할 수 있는 것은 아님.
- ※ 참고: API는 다음 인자 설정으로 특정 Region의 Instance Type 목록 확인이 가능함
  - RegionId 인자: 필수 입력
  - DestinationResource 인자: 몇가지 type 입력 가능함, 현재는 'InstanceType`을 입력

- 2024/05/24 현재 제공 목록 개수 차이 예시(Region별 편차가 큼)
  - Beijing Region의 경우: Zone 구분 없이 Region에서 제공하는 모든 Instance Type 종류가 **701개** 정도
  - London Region의 경우: Zone 구분 없이 Region에서 제공하는 모든 Instance Type 종류가 **191개** 정도

<br>

### * CB-Spider에서 Alibaba VM Spec 목록 제공 방법 재고
- Spider VM Spec 목록을 `DescribeAvailableResource API` 기반으로 
  - 현재 사용 가능한 VM Spec 만을 제공하는 것으로 개선을 고려해보았으나,
- 일단, `현상 유지`를 제안 드립니다. 

**[사유]**
- `DescribeAvailableResource API` 제공 정보는 Zone 수준임
- 현재 Spider의 Connection이 Zone 수준까지 포함하고 있지만, 
- Zone-based Control 대상인 VM의 경우 사용자가 Region 내 다른 Zone을 지정할 수 있으며,
- 이 경우 대상 Zone의 Connection 등록이 없다면, VM Spec 정보를 확인할 수 없음
- 또한, 타 CSP 등 전반적으로 현재 제공하는 Image, VM Spec 목록을 제공하는 Spider API는 
  - 대상 Region에서의 가용한 Image, Spec을 보장하기 보다는 전체 목록을 제공하는 컨셉임.
- 대상 Region에서 가용한 Image 및 Spec 정보를 제공이 필요하다고 하면, 
  - 향후, 별도의 API를 추가하는 것이 좋을 듯합니다.

**Comment by powerkimhub** [comment]
※ 참고: 관련 API 결과 원문
- [DescribeInstanceType-Beijing](https://gist.github.com/powerkimhub/e5b6bf722b7175c349c32591e18acdc1) - 모든 Region 동일
- [DescribeAvailableResource-Beijing](https://gist.github.com/powerkimhub/0ebb1bd57ec90c38556260371e6e4249)
- [DescribeAvailableResource-London](https://gist.github.com/powerkimhub/3a0bfe4e97d4c20debfedabc913adb93)

**Comment by seokho-son** [comment]
@powerkimhub 안녕하세요. 손석호 입니다. CB-Spider 입장에서의 정리 감사합니다.

CB-TB 가 현재 CB-SP의 해당 API를 사용하고 있는 주요 이유는 사실 리전(또는 존)별로 가용한 실제 Spec 리스트를 확인하기 위해서 입니다. 그래서, DescribeInstanceTypes 보다도 DescribeAvailableResource 가 더 유용한 상황입니다.
처음 @raccoon-mh 께서 1차 정리해주셨을 때, DescribeAvailableResource API와 DescribeInstanceTypes API (또는 개별 InstanceType 조회 API 병렬 수행) 활용하여, CB-SP 기존 출력 포맷과 같은 형태로 출력되도록 하는 것을 제안 드릴까 했었습니다. 작업량과 시스템 부하에 큰 이슈가 없다면 말이죠.

상기 정리해주신 방안도 현황상 타당해보입니다. 다만, 현재 CB-TB에서 해당 API를 활용하는 방식과는 다소 차이가 있어서,
- 특정 Region 및 AZ에서 가용한 Image 및 Spec 정보를 제공(당연히 다른 리소스도 포함되면 좋습니다)이 필요하므로, 별도의 API 제공을 요청 드립니다.

**Comment by powerkimhub** [comment]
@seokho-son 

- 모든 CSP가 제공할 수는 없겠지만, 
- 가능한 CSP 한정으로라도 AvailableResource 관련 API 추진을 스케줄링해보겠습니다.

**Comment by powerkimhub** [comment]
- cf) https://github.com/cloud-barista/cb-spider/issues/1205
