### ISSUE TITLE
Use identical key for the credentials of all CSPs

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#1183]
**What would you like to be enhanced**

현재 CSP credential 등록을 위해서, Key 명칭을 별도로 지정하여 validation 하고 있음.
- https://github.com/cloud-barista/cb-spider/blob/master/cloud-driver-libs/cloudos_meta.yaml#L11
- https://github.com/cloud-barista/cb-spider/blob/master/cloud-driver-libs/cloudos_meta.yaml#L23
- ...

각 키를 CSP 콘솔/UI/API 상에서 사용하는 key와 가급적 동일한 스트링으로 처리하도록 개선 제안. 
- CSP가 대소문자를 구분하지 않는 경우에는, SP에서도 대소문자 구분 없이 validation
- 대소문자 구분도 가급적 CSP 방식 준수 (관련 없는 경우 모두 소문자)

예를 들면,
[AWS] ClientId / ClientSecret --> 
(CSP 키) `aws_access_key_id` / `aws_secret_access_key`

[GCP] PrivateKey / ProjectID / ClientEmail -->
(CSP 키) 
project_id=""
client_id=""
client_email=""
private_key_id=""
private_key=""

[Azure] (CSP 키) 
clientId=""
clientSecret=""
tenantId=""
subscriptionId=""

**Why is this needed**

현재 각 CSP별로 조금씩 다른 credential key 명칭을 사용 중.

현재는 CSP가 직접 사용하는 Key 명칭과 차이가 있어서, 사용자 경험을 저하시키는 경향이 있음. (credential 생성 및 등록시, CSP 콘솔/UI 상의 명칭과 다르므로 사용자는 이를 파악하기가 어려움)

CB-TB에서는 credentials를 역으로 기존 명칭으로 변경하여 TF와 같은 외부 솔루션에서도 활용할 수 있는 크레덴셜 생성 도구를 일부 지원하고 있으나, 다소 소모적인 작업. (exportCredentials.sh)

**Comment by seokho-son** [comment]
CB-SP에 반영되는 경우, CB-TB에도 이어서 반영 예정. (cc @yunkon-kim)

**Comment by powerkimhub** [comment]
@seokho-son 

- 좋은 제안입니다. 

<br>

**[Plan]**
- (1) cloudos_meta.yaml: `credential_csp_format` Key 추가
- (2) Server:  
  - (a) input 값 validation을 `credential` | `credential_csp_format` 로 체크
  - (b) input 값 format이 `credential_csp_format` 형식일 경우, `credential` 형식으로 Key 값 변경
- (3) 이후 기존 Key로 동일하게 처리

**Comment by powerkimhub** [comment]
@MZC-CSC @dev4unet @dogfootman @raccoon-mh @mzc-ljhoon @dev-hippo-an @SungWoongz @CliffSynn @inno-cloudbarista @ish-hcc @ @innodreamer

<br>

- CSP별 다음 예시처럼 추가 부탁 드립니다. 
  - https://github.com/cloud-barista/cb-spider/blob/53be17adca2d6a3362f34cedb32c67b52bc48a99/cloud-driver-libs/cloudos_meta.yaml#L12

---

**[Driver 반영 현황]**
- [x] AWS
- [x] Azure
- [x] GCP
- [ ] Alibaba
- [ ] Tencent
- [ ] IBM VPC
- [ ] OpenStack
- [ ] NHN
- [ ] NCP Classic
- [ ] NCP VPC
- [ ] KT Classic
- [ ] KT VPC

**Comment by seokho-son** [comment]
@powerkimhub 새로운 형태의 변수를 추가하시기 보다는, 이번 기회에 기존 키 명칭을 변경해버리면 어떨까요? 향후에도 다른 CSP 드라이버가 추가되거나 변경될 때도 CSP포멧만 준용하는 것이 (코드 유지보수 차원에서) 유리할 것 같습니다. 

credential: aws_access_key_id / aws_secret_access_key

**Comment by powerkimhub** [comment]
@seokho-son 

- 사용자는 적용 후엔 CSP 포맷만 입력하시면 됩니다.  
- 향후, 신규 CSP 추가 시는 `credential`에 CSP 포맷 한가지 형태만 유지할 예정입니다. 
- 기존 포맷은 deprecated 전에 기존 사용자들을 위한 하위 호환성 제공(backward compatibility) 측면입니다. 
- 또한, CSP포맷 전격 교체는 작업 범위가 전체 드라이버이어서 일단 후순위로  별도 스케줄링이 필요한 작업입니다.

**Comment by powerkimhub** [comment]
- NCP Classic/NCP VPC 반영: https://github.com/cloud-barista/cb-spider/commit/72902a6307b0840ab6a97bef2d8a69b7fee2437a

**Comment by powerkimhub** [comment]
- 나머지 반영: https://github.com/cloud-barista/cb-spider/commit/e373af3a4ce10311a569f52c1b6c720028d4fe67, https://github.com/cloud-barista/cb-spider/commit/e13c50554a4b39c8842be6e4f3139f46b4f4b6b5

**Comment by powerkimhub** [comment]
@seokho-son (@innodreamer @yunkon-kim )

<br>

- [v0.9.1](https://github.com/cloud-barista/cb-spider/releases/tag/v0.9.1)부터 지원 합니다. (기존 Key도 활용 가능)
  - 세부 내용: Release Note 참고
- API 활용 예시(AWS)
    ```
    curl -sX POST http://localhost:1024/spider/credential \
    -H 'Content-Type: application/json' \
    -d '{        
        "CredentialName": "aws-credential01",
        "ProviderName": "AWS",
        "KeyValueInfoList": [
            {
                "Key": "aws_access_key_id",
                "Value": "AKIAR4XXXXX"
            },
            {
                "Key": "aws_secret_access_key",
                "Value": "QOumDIA4XXXXXXXX"
            }
        ]
    }'
    ```

### * CSP별 활용 가능한 Credential Key 확인 방법

**[AWS]**
  ```
  curl -sX GET http://localhost:1024/spider/cloudos/metainfo/aws -H 'Content-Type: application/json' |json_pp |more
  {
     "Credential" : [                       <========= Type-1
        "ClientId",
        "ClientSecret"
     ],
     "CredentialCSP" : [                <========= Type-2
        "aws_access_key_id",
        "aws_secret_access_key"
     ],
     "DefaultRegionToQuery" : [
        "ap-northeast-2",
        "ap-northeast-2a"
     ],
     ... 중략 ...
  ```

**[Alibaba]**
  ```
   curl -sX GET http://localhost:1024/spider/cloudos/metainfo/alibaba -H 'Content-Type:
   application/json' |json_pp |more
  {
     "Credential" : [                  <========== Type-1
        "ClientId",
        "ClientSecret"
     ],
     "CredentialCSP" : [           <========== Type-2
        "AccessKeyId",
        "AccessKeySecret"
     ],
     ... 중략 ...
  ```
