### ISSUE TITLE
[Tumblebug 요청] Spec 정보 제공 기능 추가

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#121]
VM 최적 배치 판단 등을 위한 Spec(or Flavor) 정보 제공 필요.

<개략일정>
    (1) Common Driver Interface 추가 - 1/09(목)
    (2) 각 Driver 추가 개발/시험
    (3) REST Interface 추가 개발/시험
    (4) 배포

**Comment by seokho-son** [comment]
@powerkimhub 가능하다면 각 connectionConfig(클라우드의 특정 리젼 또는 az 단위)에서 사용될 수 있는 모든 spec list 정보 조회 기능이 있으면 좋겠습니다.

**Comment by powerkimhub** [comment]
@seokho-son 고려하겠습니다.

**Comment by powerkimhub** [comment]
부득이 일정을 아래와 같이 순연합니다. 

<개략일정>
(1) Common Driver Interface 추가 - 1/15(수)
(2) 각 Driver 추가 개발/시험
(3) REST Interface 추가 개발/시험
(4) 배포

**Comment by powerkimhub** [comment]
[(CB-Spider)-드라이버공통인터페이스-VMSpec(안)-2020.01.17.pptx](https://github.com/cloud-barista/cb-spider/files/4075829/CB-Spider.-.-VMSpec.-2020.01.17.pptx)

각 클라우드 드라이버 리더분들께서는, 
첨부를 참고하시어 다음 사항을 진행해주시기 바랍니다. 

  (1) 담당 클라우드 관련 내용 검증 및 추가 (~1/22)
  (2) 담당 드라이버 VMSpec 인터페이스 추가 개발/시험 (~1/31)

@dev4unet @jazmandorf @hyokyungk @Jin-Whee-Park

**Comment by powerkimhub** [comment]
- (3)  REST API 추가 개발 후 시험 결과가 다음과 같습니다. 
[vmspec-test현황-2020.03.10.pdf](https://github.com/cloud-barista/cb-spider/files/4312644/vmspec-test.-2020.03.10.pdf)

- 각 드라이버 담당분들께서는 붉은색 font를 확인하시어 반영/시험 부탁드립니다. 
-- xxxorgspec API 관련 format 오류는  \" 등 문자열 포멧 확인 부탁드립니다. 
- GCP/Alibaba도 환경상의 문제로 REST API 시험 전이지만, 동일 증상이 의심 되는 부분은 사전 반영 부탁드립니다. 

@dev4unet @jazmandorf @hyokyungk @Jin-Whee-Park 
cf) @seokho-son @jihoon-seo

**Comment by powerkimhub** [comment]
@dev4unet @jazmandorf @hyokyungk
확인 및 수정 요청드립니다. 

**#AWS: 시험 성공**

**#GCP: 정보 출력 char encoding(?) 오류**
  - ListOrgVMSpec() 및 GetOrgVMSpec(): 정상 출력
  - ListVMSpec() 및 GetVMSpec(): 비정상 출력

```
$curl -sX GET http://localhost:1024/spider/vmspec/asia-east1/n2-highcpu-80 -H 'Content-Type: application/json' -d '{ "ConnectionName": "gcp-taiwan-config" }' | json_pp
{
   "Mem" : "▒▒",
   "VCpu" : {
      "Clock" : "",
      "Count" : "P"
   },
   "Name" : "n2-highcpu-80",
   "Gpu" : [
      {
         "Mfr" : "",
         "Count" : "",
         "Model" : "",
         "Mem" : ""
      }
   ],
   "KeyValueList" : null,
   "Region" : "asia-east1"
}

```

**#Azure/Cloudit/OpenStack: Region 정보 출력 오류**
  - Azure: 반환 정보 중 Region 정보가 Resource Group 이름으로 설정됨
  - Cloudit: 반환 정보 중 Region 정보가 Empty임
  - OpenStack: 반환 정보 중 Region 정보가 Empty임

**#Alibaba: 시험전임**

**#참고: 시험 스크립트 예시**

```
<Azure인 경우>
curl -sX GET http://localhost:1024/spider/vmspec/northeurope -H 'Content-Type: application/json' -d '{ "ConnectionName": "azure-northeu-config" }' | json_pp
curl -sX GET http://localhost:1024/spider/vmspec/northeurope/Standard_H16mr_Promo -H 'Content-Type: application/json' -d '{ "ConnectionName": "azure-northeu-config" }' | json_pp
# CSP original 정보
curl -sX GET http://localhost:1024/spider/vmorgspec/northeurope -H 'Content-Type: application/json' -d '{ "ConnectionName": "azure-northeu-config" }' | json_pp
curl -sX GET http://localhost:1024/spider/vmorgspec/northeurope/Standard_H16mr_Promo -H 'Content-Type: application/json' -d '{ "ConnectionName": "azure-northeu-config" }' | json_pp
```

cf) @seokho-son @jihoon-seo @Jin-Whee-Park

**Comment by powerkimhub** [comment]
completed!!
