### ISSUE TITLE
[Spider server] Abnormal Error messages occur when Disk Detech with NCP VPC driver

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#1228]
**What happened**
: NCP VPC driver를 이용해서 disk volume을 생성 후, 특정 VM에 attach 할때는 문제 없으나 attach된 disk를 detech 할때 Spider server에서 아래와 같은 오류 메시지가 발생함. 
참고로, 그런 경우 NCP VPC driver에서는 오류 메시지 출력되지 않음.

해당 VM은 정상적으로 running 되고 있는 상태인데 VM Status가 running 상태가 아니라고 오류 메시지 출력됨.
(Spider server에서 NCP VPC VMHandler의 GetVM()을 call 하고 그런 결과가 나오는 것 같음)

```
[CLOUD-BARISTA].[ERROR]: 2024-07-05 16:58:57 VMManager.go:1058, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.getVMInfo() - The VM status is 'Creating' or 'Booting', so wait for the VM creation before inquiring the info. : 25365298 
[CLOUD-BARISTA].[ERROR]: 2024-07-05 16:58:57 VMManager.go:1044, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.ListVM() - ncpvpc-kr-KR-1:VM:oh-vm-01 # The VM status is 'Creating' or 'Booting', so wait for the VM creation before inquiring the info. : 25365298 
```

**What you expected to happen**
: Spider server에서 위의 오류 메시지가 출력되지 않아야함.

**How to reproduce it (as minimally and precisely as possible)**
: Spider AdminWeb에서 NCP VPC driver를 이용해 아래의 image/spec으로 VM 생성 후, disk volume을 생성해서 attach 하고 detach함.
 - Zone : KR1
 - VMImage : SW.VSVR.OS.LNX64.UBNTU.SVR2004.B050
 - VMSpec : SVR.VSVR.HICPU.C004.M008.NET.SSD.B050.G002

(참고) NCP VPC에서는 disk volume 생성 과정에서 detach 과정이 한번 생김. 
(생성 후 available한 상태로 놓기 위해)

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by powerkimhub** [comment]
@innodreamer 

<br>

**[요약]**
- Detach 진행되는 동안 GetVM()이 실행되며 이 부분 점검이 필요한 것 같습니다. 

<br>

**[세부]**
- 해당 오류 메시지를 Throw하는 위치를 보면, 다음과 같습니다. (339line)
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/9f524c81-b2f0-4c5f-947b-f6a8c711677b)
- 이때 사용되는 상태 정보는 326line에서 얻은 VM 상태입니다. 

- GetVMStatus() 끝 부분에서는 ConvertVMStatusString()이 호출됩니다. 
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/70320689-99ba-4b80-beda-39ba39ef6bbe)
- Detach 동작은 VM의 `setting up` 상태일 것 같고, 이 경우에도 위 코드블록 779line과 같이 `Creating` 상태를 반환하게 되는 것 같습니다. (코드로 추정했을 때)
- 이 VM상태 반환은 이슈로 발췌해주신 오류 메시지 반환으로 이어지고 있는 상황입니다. 
- detach 중인 VM의 `setting up` 상태는 `Creating`이나 `Booting` 상태와 달리 VM 정보를 제공해줄 수 있을 것 같습니다. 
- 점검 부탁 드립니다.

<br>

**[추가로]**
- 현재 ListVM()에서 다음 910line을 보면, VM별로 상태를 2차 조회하고 있습니다. 
  - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/1e80042a-6dd5-4ec4-b811-a9d687e0f9c5)
- 907line의 vm 정보에는 vm struct으로만 추정해보면, 
  - VM 상태 정보(ServerInstanceStatusName)가 이미 포함되어 있을 수도 있겠습니다. 
  - Request Filter 조건에 따라 상태 정보가 비어 있을 수도 있겠습니다. 
  - 혹시라도, 상태를 다시 fetch 하지 않고, 이 정보를 직접 활용할 수 있는 지 점검 부탁 드립니다.

**Comment by innodreamer** [comment]
@powerkimhub 위의 GetVM() 실행시의 VM Status 값 적용과 연관된 비정상적 error message 발생 issue 관련하여 NCP Classic/VPC VMHandler를 보완/테스트 후 PR 올렸습니다.

그리고, ListVM() 실행시 VM Status를 2차 적용하는 이유는 NCP에서 받아온 VM list에 대해 1차적으로 VM Status를 확인하여 VM 상세 정보 수집시 문제가 발생하지 않는 status인 것만 GetVM()을 하여 상세 정보를 append 해나가기 위한 것입니다.
위와 관련하여서도 처리 과정을 좀더 명확하게 처리하기 위해 ListVM() 부분 코드도 보완해서 함께 PR 올렸습니다.
