### ISSUE TITLE
Alibaba Spec list error issue

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#1273]
Alibaba

/vmspec 으로 spec 리스트 조회시, 하기 적절하지 않은 오류 메시지 대량 발생하는 문제가 있습니다.
(cb-spider:0.9.0)

- 실제 기능 오류라면 개선이 필요하고, 
- 아니라면 에러 메시지를 적절하게 정리해주시면 좋을 것 같습니다. 

cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil> 
cb-spider     | [CB-SPIDER].[ERROR]: 2024-08-01 10:18:58 VMSpecHandler.go:74, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.ExtractVMSpecInfo() - <nil>

**Comment by seokho-son** [comment]
@powerkimhub 현황 문의드립니다. :) 
혹시 차기 릴리스에 포함이 가능할까요?

**Comment by powerkimhub** [comment]
@seokho-son 

- 가능합니다. 
- Fixed in https://github.com/cloud-barista/cb-spider/commit/e71b66272055b9f866376f19a49aedfd149b0367
