### ISSUE TITLE
Target date for cb-spider v0.9.2 ?

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#1282]
현재 cb-spider 일부 기능에 오류가 있어서,

cb-tb에서는 v0.9.1, latest 활용을 잠시 멈추고, v0.9.0을 활용하는 것이 좋다고 알려주셨습니다.

현재 cb-spider, cb-tb 양쪽을 동시 수정 개발하고 있는 경우(k8s, net 등)이 있는 것으로 보여서,

---

cb-spider가 (오류 해결되신 버전) v0.9.2 프리릴리스를 찍어주시면,

cb-tb에서 빠르게 연동 테스트를 진행해야 하는 상황인 것 같습니다.

---

이에

대략적인 cb-spider v0.9.2 프리릴리스 시점을 문의 드립니다.

**Comment by powerkimhub** [comment]
- 8/23 예정입니다.
