### ISSUE TITLE
[TEST] Tagging to Resource Test 

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1289]
- 시험 가이드 및 결과 현황 장소를 참고하시기 바랍니다. 
  - [Driver별 Tag 시험 현황](https://docs.google.com/spreadsheets/d/1IallXfsNLAfdWWFv7gMObjF_VwZPC96C/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

**Comment by innodreamer** [comment]
@powerkimhub

**Comment by innodreamer** [comment]
@powerkimhub 
KT Cloud Classic(G1/G2 platform)의 다른 자원들에 대해서는 Find 기능을 포함하여 tagging 기능 개발이 완료되었습니다.

다만, KT Cloud Classic NLB의 경우, 아래 link에서와 같이 별도의 tag 생성/삭제 (조회는 미지원) 기능의 API를 지원하는데,
Key/Value 형식으로 tag를 생성하는 기능은 아니고 NLB 정보 조회시 'tag'라는 parameter에 단일 string으로 정보가 제공되어 tagging 기능이라기보다 description과 유사한 기능을 제공합니다.

- NLB API 가이드 : https://cloud.kt.com/docs/open-api-guide/g/network/load-balancer

이러한 경우, NLB에 대한 tagging 기능도 KT Cloud Classic tagging 기능에 통합시켜서 개발해야지, 아니면 NLB의 경우의 제외시켜야할지 판단해주시기 바랍니다.

**Comment by powerkimhub** [comment]
@innodreamer 

<br>

- KT Classic NLB Tagging 지원 여부 => 제외하는 것이 좋을 것 같습니다.
- 사유: 공유 해주신 API에 따르면, 
  - Key/Value Tagging 보다는 단일 Name Tag 기능이며(Name Tag 유무 판단 용),
  - Key/Value Tagging 위해서는 매순간 파싱과 문자열 붙여 넣기 등 오류 발생률이 증가할 듯 합니다. 
- 현황판에는 반영하였습니다. 
  - https://docs.google.com/spreadsheets/d/1dtx-bfEuNGiCF9x8VL9pRCitKWnR14AN/edit?gid=920972581#gid=920972581

**Comment by SungWoongz** [comment]
@powerkimhub 
AWS, ALIBABA, GCP, TENCENT 테스트 완료 되었습니다.

**Comment by powerkimhub** [comment]
@SungWoongz 

- 캄사합니다.

**Comment by SungWoongz** [comment]
@powerkimhub 
- alibaba, tencent NLB 태그 테스트 완료되었습니다.

- 관련 PR 링크 드립니다.
  - https://github.com/cloud-barista/cb-spider/pull/1341

**Comment by powerkimhub** [comment]
- released via [v0.9.6](https://github.com/cloud-barista/cb-spider/releases/tag/v0.9.6)
