### ISSUE TITLE
[Alibaba] The VPC resource type is independent of the ECS resource type.

### ISSUE THREAD

**Issue by SungWoongz** [cloud-barista/cb-spider#1293]
@powerkimhub
 - VPC 리소스 타입이 ECS 리소스 타입에서 떨어져 나왔습니다.
 - 따라서 Tag 테스트 전 코드 수정이 필요할 것 같습니다.
 - 수정 후 PR 하겠습니다.

**Comment by powerkimhub** [comment]
- 넵.

**Comment by SungWoongz** [comment]
![image](https://github.com/user-attachments/assets/66a7e4e0-b43d-48cf-8164-542fe36482b2)

- 티켓 문의 결과 현재 존재하는 VPC에 Tag 추가하는 API가 없다고 합니다.
- subnet에 Tag 추가하는 API또한 존재하지 않는 것으로 확인 되었습니다.

**Comment by powerkimhub** [comment]
@SungWoongz 

- 현황 파악/공유 캄사드립니다. 
- 최종적으로 다음처럼 정리하면 되겠지요?
  - VPC/Subnet 생성시 Tagging 가능
  - 생성 후에 Tag 추가는 현재 불가

**Comment by SungWoongz** [comment]
@powerkimhub 
- 네 맞습니다!

**Comment by powerkimhub** [comment]
@SungWoongz 

- 다음과 같이 정리했습니다.
  - https://docs.google.com/spreadsheets/d/1dtx-bfEuNGiCF9x8VL9pRCitKWnR14AN/edit?gid=920972581#gid=920972581
  - https://docs.google.com/spreadsheets/d/1IallXfsNLAfdWWFv7gMObjF_VwZPC96C/edit?gid=920972581#gid=920972581
- 시험은 가능한 범위에서 진행 부탁드립니다.

**Comment by SungWoongz** [comment]
@powerkimhub 
- 네 알겠습니다.
- 감사합니다 !
