### ISSUE TITLE
[NCPVPC:Disk] Incorrect Zone-based Control for Disk

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1298]
- Zone-based Control 시험에서 
  - 참고: https://docs.google.com/spreadsheets/d/1U_xZA9MkV6zrLyPDSw2WlbJ03jFcvGNp5zPrJ_hkSoc/edit?gid=0#gid=0
- <Case-1> Default Zone 시험: **Fail**

<br>

**[증상]**
- Connection : KR / KR-1 zone
- Subnet 생성을 default Zone(KR-1)로 생성: **Pass**
- VM 생성을 위에서 생성한 subnet(KR-1) 설정으로 생성: **Pass**
- Disk 생성을 default Zone(KR-1)로 생성: **Issu** (점검 필요)
  - Zone 정보가 올라오고 있지 않음 
  - ![image](https://github.com/user-attachments/assets/08b6ddc9-49ab-4630-88aa-a8b2c9b27a36)

**Comment by innodreamer** [comment]
@powerkimhub 위의 issue에 언급된대로 Disk info에 Zone 정보가 나타나도록 보완하고,
VPCHandler, VMHander를 추가 보완 후 아래의 테스트를 완료했습니다. 참고하십시오.

	- Subnet
		- Default zone info 제시 확인 완료
		- KR-2 connection에서 KR-1 subnet 생성 테스트 완료
	- S/G
		- KR-2 connection에서 KR-1 subnet 가진 VPC 기준 S/G 생성 테스트 완료
	- VM
		- Default zone info 제시 확인 완료
		- KR-2 connection에서 KR-1 VM 생성 테스트 완료
	- Disk
		- Default zone info 제시 확인 완료
		- KR-2 connection에서 KR-1 Disk 생성 테스트 완료
		- KR-2 connection에서 KR-1 Disk에 KR-1 VM attach/detach 테스트 완료
	- MyImage
		- KR-2 connection에서 KR-1 VM snapshot 테스트 완료
