### ISSUE TITLE
[Tencent] Unable to Retrieve VM List When Creating myImage Resource in adminWeb2

### ISSUE THREAD

**Issue by SungWoongz** [cloud-barista/cb-spider#1305]
@powerkimhub 

- AdminWeb2에서 + 버튼으로 MyImage 생성 시 Source VM 목록이 불러와 지지 않습니다. 
- 해당 오류 사진들 첨부합니다.

![image](https://github.com/user-attachments/assets/9b6a5141-4899-4438-94ca-9fbd1dd5d808)

**Comment by SungWoongz** [comment]
@powerkimhub 
- spider pull 후 다시 시도해도 
- 위와 같은 이슈가 존재합니다
- 확인 부탁 드립니다.

**Comment by SungWoongz** [comment]
@powerkimhub 

- alibaba도 같은 이슈가 있습니다.
- 확인 부탁드립니다.

![image](https://github.com/user-attachments/assets/be6ead68-f097-49f1-a31a-e75d1e6eba67)

**Comment by powerkimhub** [comment]
@SungWoongz 

<br>

**[증상]**
- MyImage를 생성 후에 삭제하고 나서,
- MyImage 페이지를 클릭하면, 다음과 같은 오류 메시지가 발생합니다.
  ```
  [CB-SPIDER].[ERROR]: 2024-08-30 21:24:09 MyImageHandler.go:150, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.AlibabaMyImageHandler.GetMyImage() - no result with request image IID(NameId/SystemId) : alibaba-beijing-myimage-4mc-cr8raajp70ivma2c87ug/m-2zegm0f3mw8xx52w20j7
  [HISCALL].[211.175.140.123] 2024-08-30 21:24:09 (Friday) github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/alibaba/resources.LoggingError():92 - "CloudOS" : "ALIBABA", "RegionZone" : "cn-beijing", "ResourceType" : "MYIMAGE", "ResourceName" : "alibaba-beijing-myimage-4mc-cr8raajp70ivma2c87ug", "CloudOSAPI" : "GetMyImage()", "ElapsedTime" : "0.7629", "ErrorMSG" : "no result with request image IID(NameId/SystemId) : alibaba-beijing-myimage-4mc-cr8raajp70ivma2c87ug/m-2zegm0f3mw8xx52w20j7"
  [CB-SPIDER].[ERROR]: 2024-08-30 21:24:09 MyImageManager.go:310, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.ListMyImage() - no result with request image IID(NameId/SystemId) : alibaba-beijing-myimage-4mc-cr8raajp70ivma2c87ug/m-2zegm0f3mw8xx52w20j7
  ```

<br>

**[분석]**
- 이 오류는 MyImage 삭제시 제대로 삭제가 안되어 그 영향으로 발생하는 오류로 보입니다. 
- DeleteMyImage() 코드 블록에서, 
  - IsNil() 함수는 `ecs.Image` struct에 대해서 호출이 되며, 이 경우 nil pointer 오류가 발생하고 있습니다.
  - 확인 부탁드립니다.
  - https://github.com/cloud-barista/cb-spider/blob/86a9f987df14c1a43854056a746eeb12d4c6d50f/cloud-control-manager/cloud-driver/drivers/alibaba/resources/MyImageHandler.go#L226

**Comment by SungWoongz** [comment]
@powerkimhub 
- CommonManager.go

- checkNotFoundError 함수에서 strings.Contains(msg, "noresult") 한 줄 추가가 필요해 보입니다.

- spider를 통해서 리소스 생성 후 해당 리소스를 csp 콘솔에서 삭제 했을 때
- spider의 getList()를 spider의 IID를 갖고 csp를 호출하는데
- csp에 해당 리소스가 없으면 "no result with request image IID(NameId/SystemId) alibaba-beijing-myimage-4mc-cr8raajp70ivma2c87ug/m-2zegm0f3mw8xx52w20j7"와 같은 오류를 내려주는데
- 해당 오류 메시지를 처리하는 부분이 없어서 err를 리턴하며 모든 리소스들이 보이지 않기 때문입니다. 
```
func checkNotFoundError(err error) bool {
	msg := err.Error()
	msg = strings.ReplaceAll(msg, " ", "")
	msg = strings.ToLower(msg)

	return strings.Contains(msg, "does not exist") || strings.Contains(msg, "notfound") ||
		strings.Contains(msg, "notexist") || strings.Contains(msg, "failedtofind") || strings.Contains(msg, "failedtogetthevm")
}
```

- 괜찮으시다면
- sourceVM의 systemID를 포함하도록 수정했고 PR올릴 때 checkNotFoundError도 같이 수정해서 PR을 올릴까요 ?

**Comment by powerkimhub** [comment]
@SungWoongz 

- 아 넵.
- 캄사합니다~
