### ISSUE TITLE
Is this a bug or intended in the Add Subnet API response?

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-spider#1310]
Subnet 추가 과정에서 응답 값이 예상과 달라서 문의를 드립니다. 

(테스트 환경)
: Tumblebug 0.9.8, Spider 0.9.2
: aws, ap-northeast-2

(시나리오)
: Subnet을 1개를 갖는 VPC를 정상적으로 생성한 후,
: Subnet을 추가하는 과정에서 응답이 예상과 다른 상황입니다.

API 상으로 보면,
`POST /vpc/{VPCName}/subnet` API를 통해 서브넷을 추가 했을 때, 
Response Body는 SubnetInfo로 되어있으나, value에는 VPC의 정보들이 들어 있는 것으로 보입니다.

**Comment by powerkimhub** [comment]
@yunkon-kim 

- 아 swag 정의가 잘못되었네요.
- 추가된 subnet까지 포함한 vpc 정보 반환이 맞습니다.
- 놓친 부분이네요. 👍

**Comment by yunkon-kim** [comment]
@powerkimhub  감사합니다!

API를 호출한 쪽에서는 응답 받은 VPCInfo.SubnetInfoList를 순차 탐색해서 요청한 Subnet 정보를 찾아야 하는 상황인가 보네요.

일단 API 응답에 맞춰 적용하겠습니다.

**Comment by powerkimhub** [comment]
- Fixed in https://github.com/cloud-barista/cb-spider/commit/ad6d3990d8f93f37339d19e7ce80cd61887cbd4d
