### ISSUE TITLE
[AWS:MyImage] Access Nil Pointer

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1314]
**[이슈 현황]**
- MyImage를 생성 후 생성한 MyImage에 대해 바로 Delete를 요청하면
 - 몇 분 동안은 Nil Pointer 접근 오류가 발생합니다. 
 - 이 경우 적절한 에러 반환 처리가 필요할 듯 합니다.
 - 점검 부탁 드립니다.

<br>

**[이슈 분석]**
- 아래 그림에서와 같이 
- blockDevice.Ebs는 nil이 아니지만, blockDevice.Ebs.SnapshotId가 nil인 기간이 존재합니다. 
- ![image](https://github.com/user-attachments/assets/5fe2c854-cc4b-4f30-a358-d642485c68ef)

**Comment by dev4unet** [comment]
아직 SnapshotId가 할당되지 않은 경우 에러를 발생하도록 했으며 spider의 adminweb2에서 에러 메시지가 출력되는 것을 확인했습니다.

이번에 빌드할 때 보니 make에 swag가 들어갔는데 [Quick Start Guide](https://github.com/cloud-barista/cb-spider/wiki/Quick-Start-Guide) 문서에는 swag 바이너리 파일 설치 관련 부분이 없어서 에러가 발생하는 사용자가 있을 듯 싶습니다.^^

**Comment by powerkimhub** [comment]
@dev4unet 

- 캄사합니다. 
- Start Guide 보완하겠습니다~
