### ISSUE TITLE
[API:Cluster] Remove Namespace Functionality and API from Cluster Management

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1319]
@seokho-son @sykim-etri (@MZC-CSC )

<br>

- 다음 변경 사항이 Tumblebug K8S-Cluster 통합 작업에 이슈가 없을 지 확인 부탁 드립니다. 

<br>

**[개요]**

- Cluster의 경우 CB-Tumblebug(TB)를 통과하지 않고 WebTool에서 직접 연동 가능한 기능을 제공하고 있음
  - TB는 NameSpace 하위에 자원을 관리하고 있음
  - WebTool에서 TB를 통해서 생성한 자원을 활용하여 동일한 Namespace에 Cluster 관리가 가능하도록 
  - Spider에서 TB의 NameSpace 관리를 인지하도록 제공하는 기능이 포함되어 있음
- TB를 통한 Cluster 제공이 추진 중에 있으므로 더이상 Namespace 개념을 유지할 필요가 없어 제거가 필요함

<br>

**[API 변경 요약]**
- NameSpace 관련 기능/코드 제거
  - NameSpace 입력 인자 및 관련 처리 제거
  - WebTool 전용 API 제거
    ```
    curl --location 'localhost:1024/spider/nscluster' \
    --data '{
        "_NameSpace": "pmks-test",
        "ConnectionNames": [
            "tencent-seoul1-config"
        ]
    }'
    ```

- 일관성 위해 반환 정보를 기존 자원(VPC 등)들과 동일한 포맷으로 정정
  - 즉, 반환 정보에서 Connection 정보 제거
  - AS-IS
    ```
    {
      "Connection": "tencent-seoul1-config",
      "ClusterInfo": {
        "IId": {
          "NameId": "myk8scluser-01",
          "SystemId": "cls-ma2cu9n3"
        },
    ... 중략 ...
    ```
  - TO-BE
    ```
    {
        "IId": {
          "NameId": "myk8scluser-01",
          "SystemId": "cls-ma2cu9n3"
        },
    ... 중략 ...
    ```

**Comment by seokho-son** [comment]
제 관점에서는 특별히 문제 없어 보입니다. :)
@sykim-etri 께서 최종확인해 주시면 될 것 같습니다.

**Comment by sykim-etri** [comment]
특별한 이슈는 없습니다.
완료 후 안내주시면 반영하도록 하겠습니다.

**Comment by powerkimhub** [comment]
- 넵, 캄사합니다.

**Comment by sykim-etri** [comment]
https://github.com/cloud-barista/cb-spider/releases/tag/v0.9.4
