### ISSUE TITLE
[GCP:Cluster] when calling SetNodeGroupAutoscaling(off -> on), how do we handle it?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-spider#1329]
[(PMKS) 개발,시험,이슈현황](https://docs.google.com/spreadsheets/d/1mPmfnfmyszYimVzplZMzsqO3WsBmOdes) 내 GCP 행의 기타 이슈에 아래와 같은 내용이 있으며, 현재 시험 결과도 동일하게 off->on으로 변경시 min: 0, max: 0으로 이전 사용값으로 변하지는 않습니다.
```
* AutoScaling 설정변경 (현재설정으로는 끄기만 가능)
  on -> off : SetNodeGroupAutoScaling 으로 설정가능
  off -> on : max, min 값 필요
```

어떻게 처리하는 것이 좋을 지에 대한 의견 부탁드립니다.

**Comment by sykim-etri** [comment]
고려할 수 있는 방법으로는 keypair 저장 방식과 유사하게, nodepool의 autoscaling 관련 정보를 저장해 두는 방법이 있겠습니다.

**Comment by powerkimhub** [comment]
@sykim-etri 

<br>

- 관련하여, 호출되는 Driver API는 다음과 같습니다. 
  ```
  SetNodeGroupAutoScaling(clusterIID IID, nodeGroupIID IID, on bool) (bool, error)
  ```
- 이 API가 호출되면, 
  - Driver에서 `nodeGroupIID`를 이용하여 설정에 필요한 
  - `MinNodeSize`, `MaxNodeSize`를 획득해서 실행 가능한지 점검 부탁드립니다. 

- 참고: NodeGroupInfo
  ```
  type NodeGroupInfo struct {

          ... 중략 ...

          // Scaling config.
          OnAutoScaling   bool `json:"OnAutoScaling" validate:"required" example:"true"`
          DesiredNodeSize int  `json:"DesiredNodeSize" validate:"required" example:"2"`
          MinNodeSize     int  `json:"MinNodeSize" validate:"required" example:"1"`
          MaxNodeSize     int  `json:"MaxNodeSize" validate:"required" example:"3"`
  
          ... 중략 ...

  }
  ```

**Comment by sykim-etri** [comment]
SetNodeGroupAutoScaling(false) 호출하면 GCP에서는 MinNodeSize, MaxNodeSize 값을 관리하지 않은 것으로 보입니다.
더불어 SetNodeGroupAutoScaling(true) 호출시 MinNodeSize와 MaxNodeSize 값이 설정되어 있지 않아도 에러를 리턴하지는 않고 MinNodeSize와 MaxNodeSize 값을 각각 0으로 관리하고 있습니다.

또한 CreateCluster()나 AddNodeGroup()시 MinNodeSize와 MaxNodeSize를 설정하지 않은 경우도 각각 0으로 관리하고 있습니다. 이때 실제 생성되는 노드 수는 DesiredNodeSize만큼은 생성되었습니다.

**Comment by sykim-etri** [comment]
임시 대응책으로 SetNodeGroupAutoScaling(true) 호출시 실제 ON으로 변경한 후 false 및 에러(ChangeNodeGroupAutoscaleSize로 설정값을 변경하도록 안내)를 리턴하는 방법도 있을 것으로 생각됩니다.

**Comment by powerkimhub** [comment]
- Completed in [#1330](https://github.com/cloud-barista/cb-spider/pull/1330)
