### ISSUE TITLE
I got an error with 'database is locked'

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-spider#1335]
CB-TB를 통해 동시에 여러 개의 자원 생성을 진행하는 중이었으며, sshkey 생성할 때 아래와 같은 에러가 발생하였습니다.
어떤 이슈가 있는 것일까요?
@powerkimhub 

```
[CB-SPIDER].[ERROR]: 2024-09-20 16:48:51 common.go:116, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/common.AddKey() - database is locked                           
[CB-SPIDER].[ERROR]: 2024-09-20 16:48:51 KeyPairHandler.go:91, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/gcp/resources.(*GCPKeyPairHandler).CreateKey() - database is locked                                                                                                                                                                          
[CB-SPIDER].[ERROR]: 2024-09-20 16:48:51 KeyPairManager.go:208, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateKey() - database is locked
[CB-SPIDER].[INFO]: 2024-09-20 16:48:51 ConnectionConfigInfoManager.go:102, github.com/cloud-barista/cb-spider/cloud-info-manager/connection-config-info-manager.GetConnectionConfig() - call GetConnectionConfig()                                                                                                                                                                       
```

**Comment by sykim-etri** [comment]
해당 sshkey의 생성을 다시 요청하면 정상 생성되었습니다.

**Comment by powerkimhub** [comment]
@sykim-etri 

<br>

- sqlite 단점이 동시성에 약하다는 것입니다.(다음 링크에서 `단점` 검색)
  - https://github.com/cloud-barista/cb-spider/issues/888
- 그래서, 옮겨 타기 전에 동시성 시험을 어느 정도 해본 후에 도입했는데(위 링크에서 '동시성테스트' 검색)
  - 동시 접근에 따른 locking가 생겼네요. 
- 일단, busywait(timeout:5sec)로 설정을 변경했습니다. 
  - 활용해보시기 바랍니다.
  - https://github.com/cloud-barista/cb-spider/commit/13dc937226acd37833de781f184f2de88731069e 가 반영된 최신 소스
  - docker 사용하시려면, 다음 action 완료 후 [edge](https://hub.docker.com/r/cloudbaristaorg/cb-spider/tags) 사용
    - https://github.com/cloud-barista/cb-spider/actions/runs/10958505286

**Comment by powerkimhub** [comment]
@sykim-etri 

<br>

- 관련 증상이 사라졌는지요?

**Comment by sykim-etri** [comment]
@powerkimhub 동일한 시험 환경에서 해당 이슈가 발생하지는 않는 것을 확인하였습니다.

**Comment by powerkimhub** [comment]
@sykim-etri 

<br>

- 현황 확인/공유 감사합니다. 
- 일단, close 하겠습니다. 
- 혹시, 재발하면 reopen 해주시길.
