### ISSUE TITLE
[Tencent:Cluster] I got an error that "SecurityGroup is invalid"

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-spider#1343]
**What happened**
SecurityGroup 생성에 문제가 없었으며, 클러스터 생성까지 진행되었으나 GetCluster() 호출시 아래와 같은 에러가 발생합니다.

```
cb-spider          | [CB-SPIDER].[ERROR]: 2024-09-27 04:49:11 ClusterHandler.go:566, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterAccessInfo() - Failed to Create Cluster Endpoint:  [TencentCloudSDKError] Code=InvalidParameter, Message=SecurityGroup is invalid, RequestId=722d74a2-63af-47d7-a9e4-c66aeca602cf 
cb-spider          | [CB-SPIDER].[ERROR]: 2024-09-27 04:49:11 ClusterHandler.go:457, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo() - Failed to Create Cluster Endpoint:  [TencentCloudSDKError] Code=InvalidParameter, Message=SecurityGroup is invalid, RequestId=722d74a2-63af-47d7-a9e4-c66aeca602cf
cb-spider          | [CB-SPIDER].[ERROR]: 2024-09-27 04:49:11 ClusterHandler.go:150, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster() - Failed to Get ClusterInfo :  Failed to Create Cluster Endpoint:  [TencentCloudSDKError] Code=InvalidParameter, Message=SecurityGroup is invalid, RequestId=722d74a2-63af-47d7-a9e4-c66aeca602cf 
cb-spider          | [HISCALL].[211.175.140.137] 2024-09-27 04:49:11 (Friday) github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster():152 - "CloudOS" : "TENCENT", "RegionZone" : "ap-seoul", "ResourceType" : "CLUSTER", "ResourceName" : "crr3elccpuq181c8i9d0", "CloudOSAPI" : "GetCluster()", "ElapsedTime" : "1.8629", "ErrorMSG" : "Failed to Get ClusterInfo :  Failed to Create Cluster Endpoint:  [TencentCloudSDKError] Code=InvalidParameter, Message=SecurityGroup is invalid, RequestId=722d74a2-63af-47d7-a9e4-c66aeca602cf"
cb-spider          | [CB-SPIDER].[ERROR]: 2024-09-27 04:49:11 ClusterManager.go:817, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster() - Failed to Get ClusterInfo :  Failed to Create Cluster Endpoint:  [TencentCloudSDKError] Code=InvalidParameter, Message=SecurityGroup is invalid, RequestId=722d74a2-63af-47d7-a9e4-c66aeca602cf 
```

**Environment**
- CB-TB v0.9.12
- CB-SP v0.9.3

**Comment by powerkimhub** [comment]
@sykim-etri (@MZC-CSC )

<br>

- 재현 시험 결과 상기 오류는 권한 오류로 생각 되며, 
- 권한 부여시 해결되었습니다. 
  - 세부 내용 아래 재현 및 Granting 가이드 참고
- @sykim-etri 다음 엑셀 현황에서 `Role 추가 필요시 추가 가이드`에 권한 설정 내용 간단히 정리/추가 부탁 드립니다. 
  - [(PMKS) 개발,시험,이슈현황](https://docs.google.com/spreadsheets/d/1mPmfnfmyszYimVzplZMzsqO3WsBmOdes/edit?gid=1299745060#gid=1299745060)
  - 현 이슈가 해결되시면 `close` 부탁 드리며, 
  - 다른 이슈가 남아 있다면 공유 부탁 드립니다. 

<br>


**[최초 실행: Granting 이전] Cluster 생성 안됨(SecurityGroup is invalid 오류)**
- Granting 방법: 하단 참고
```
[CB-SPIDER].[ERROR]: 2024-09-30 10:14:22 ClusterHandler.go:567, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterAccessInfo() - Failed to Create Cluster Endpoint:  [TencentCloudSDKError] Code=InvalidParameter, Message=SecurityGroup is invalid, RequestId=be67c0f4-dd14-4d00-902d-4af6bbdc4a0f 
```

<br> 

**[Granting 이후] Cluster 생성되며, Cluster 및 NodeGroup 준비 상태에서 접근 시 오류 반환**
- 이슈 [1352](https://github.com/cloud-barista/cb-spider/issues/1352)에서 관련 commit으로 처리하였습니다. 
- 예시: NodeGroup 없이 Access Endpoint 접근 시 에러 메시지
  ```
  [CB-SPIDER].[ERROR]: 2024-09-30 10:31:19 ClusterHandler.go:560, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterAccessInfo() - cls-c7tl9xd7[TencentCloudSDKError] Code=ResourceUnavailable.ClusterState, Message=CLUSTER_STATE_ERROR(cluster without worker Node is not allowed to enable extranet access  endpoint, please add Nodes.), RequestId=bd48280c-f20d-4fd3-8320-18f3acc9d4cb 
  ```

<br>

**[Granting 가이드-Console 기반]**
1. Tencent Console: TKE 메뉴 접근시 다음과 같은 Granting 메시지가 뜨고, Granting 설정
  ![image](https://github.com/user-attachments/assets/c63cd813-292d-4dd6-abe0-3212c5373226)

2. 상기 Granting 완료로 Cluster 생성 후 Spider에서 AddNodeGroup 시도 시에는 다음과 같은 에러 메시지 출력
- AS_QCRole 설정 필요 
  ![image](https://github.com/user-attachments/assets/2a2d1f4d-c9fd-4c6e-9e87-2db68c54fa16)

3. 다음 Tencent Autoscaling Console link로 처음 접속하면,
- https://console.tencentcloud.com/autoscaling 
- 다음과 같은 Granting 메시지가 뜨고, Granting 설정
  ![image](https://github.com/user-attachments/assets/14ec8ef8-5896-4a1a-b611-5d54c186b102)
  - click하면. - AS_QCRole 설정 됨
    ![image](https://github.com/user-attachments/assets/604318ce-9da4-4400-8b7b-d43822f213cd)
- 이후 NodeGroup 추가하면 성공.

**Comment by sykim-etri** [comment]
>   * [(PMKS) 개발,시험,이슈현황](https://docs.google.com/spreadsheets/d/1mPmfnfmyszYimVzplZMzsqO3WsBmOdes/edit?gid=1299745060#gid=1299745060)

개별 계정으로 접근시 이미 해당 권한이 허용된 상태(root 계정 단위의 권한 관리 추정)라 기존 가이드를 안내하는 것으로 업데이트하였습니다.
