### ISSUE TITLE
[Azure:Cluster] Unable to Retrieve Azure NodeGroup VM Info due to ResourceGroup and Path Differences

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1353]
@ish-hcc (@sykim-etri )

**[현황]**
- 최신 AdminWeb을 기준으로
- 다음과 같이 NodeGroup을 선택한 후,
  ![image](https://github.com/user-attachments/assets/0ba4492d-ac2d-4ed0-b159-5626a575656c)

<br>

- NodeGroup을 구성하는 특정 Node를 클릭하면, 
  ![image](https://github.com/user-attachments/assets/f0b5196a-3394-49ba-89d4-18b76cfacf71)

<br>

- 다음과 같은 Node 정보를 제공하고 있습니다. 
  ![image](https://github.com/user-attachments/assets/e73db682-5468-482d-97bc-f93a1fc6ed62)

<br>

- Azure의 경우에는 다음과 같이 오류가 발생하고 Node 정보를 제공 할 수 없습니다. 
  ![image](https://github.com/user-attachments/assets/397881dd-999c-4f3d-a3a1-0075af7ede46)

<br>

**[이슈]**
- 상기 Node(VM) 정보는 다음 API를 이용하여 정보를 제공하고 있습니다. 
  - https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml#/%5BVM%20Management%5D/get-csp-vm

  - 즉, SystemId를 이용한 VM 정보 획득

<br>

- 그런데, Azure Kubernetes Cluster의 경우에는 
- Azure에서 별도의 ResourceGroup을 생성해서 Computing 자원을 제공하고 있습니다.
- 참고: Azure Driver 내부에서 별도로 생성된 ResourceGroup 이름을 얻는 부분
  - In ClusterHandler.go
    ```
    func getclusterNodeResourceGroup(clusterName string, resourceGroup string, regionString string) string {
	    return fmt.Sprintf("CB_%s_%s_%s", resourceGroup, clusterName, regionString)
    }
    ```

- 그래서, NodeGroup을 구성하는 Node의 SystemId를 보면, 다음과 같이 Cluster와 **ResourceGroup이 다릅**니다. 
  - Cluster SystemId 예시
    ```
    /subscriptions/a20fed83-xxxx-xxxxresourcegroups/northeurope/providers/Microsoft.ContainerService/managedClusters/azure-northeu-cluster-mfj-crr919bp70irobps45m0
    ```
  - NodeGroup VM SystemId 예시
    ```
    /subscriptions/a20fed83-xxxx-xxxx/resourceGroups/CB_northeurope_azure-northeu-cluster-mfj-crr919bp70irobps45m0_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodegroupm9a-29768530-vmss/virtualMachines/1
    ```

- 추가로 **resource path**가 vm(`../virtualMachines/...`)과는 달리 `.../virtualMachineScaleSets.../`입니다. 
  - normal VM SystemId 예시
    ```
    /subscriptions/a20fed83-xxxx-xxxx/resourceGroups/northeurope/providers/Microsoft.Compute/virtualMachines/azure-northeu-vm-iw6-crrpajrp70igkt1h3l1g
    ```

================

**[이슈 요약]**
- 결과적으로 다음과 같은 차이로 인하여,
  - (1) ResourceGroup 차이
  - (2) resource path vm과의 차이

- 다음과 같이 Spider API를 사용하여 VM 정보를 제공할 수 없습니다. 
  - [normal VM] OK
    curl -X 'GET' 'http://localhost:1024/spider/cspvm//subscriptions/a20fed83-xxxx-xxxx/resourceGroups/**northeurope**/providers/Microsoft.Compute/virtualMachines/azure-northeu-vm-iw6-crrpajrp70igkt1h3l1g?ConnectionName=azure-northeu-config' -H 'accept: application/json'

  - [NodeGroup VM] Fail
    curl -X 'GET' 'http://localhost:1024/spider/cspvm//subscriptions/a20fed83-xxxx-xxxx/resourceGroups/CB_northeurope_azure-northeu-cluster-mfj-crr919bp70irobps45m0_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodegroupm9a-29768530-vmss/virtualMachines/1?ConnectionName=azure-northeu-config' -H 'accept: application/json'

**[제안]**
- (1) ResourceGroup 차이 관련
  - Azure가 자동으로 별도의 ResouceGroup을 생성해서 컴퓨팅 자원을 활용하는데, 
  - 혹시, 현재 사용하는 ResourceGroup과 동일한 ResourceGroup에서 
    - Copmputing 자원을 관리하도록 설정 가능한지 확인 부탁 드립니다. 
  - 가능하다면, 동일 ResourceGroup에서 자컴퓨팅 자원 관리하도록 수정
  - 사유: ResourceGroup이 다르면 VM 정보 등 접근할 때 ResourceGroup간 접근 권한이 필요합니다. 

- (2) resource path vm과의 차이 관련
  - virtualMachineScaleSets에 포함된 VM의 정보를 제공할 수 있는 방법을 확인 부탁 드립니다. 
  - (1순위) 현재 Driver VMHandler.Get()을 이용한 제공 방법
    - 타 ResourceGroup 접근 권한 부여하면 해결될지도 확인은 필요해 보입니다.
    - 예를 들면, NodeGroup에 포함된 VM이 `.../virtualMachineScaleSets/...` path 외에도 VM path를 갖는 SystemId가 있다면 이를 이용한 방법 등 
  - (2순위) 별도 API를 이용한 제공 방법 
    - 현재 Driver에 없는 별도 API로만 제공 가능하다면 
    - 일단, 관련 Azure API 공유 부탁 드립니다. 
    - Spider Server에서 어떤식으로 연동할지 고민부터 한후에 
    - 개발에 들어가는 것이 두번일을 안할 것 같습니다.

**Comment by powerkimhub** [comment]
@ish-hcc 

<br>

- PR([#1326](https://github.com/cloud-barista/cb-spider/pull/1362)] 캄사합니다. 
- 시험 결과가 아래와 같습니다. 
- 확인 부탁드립니다. 

---

**[Normal VM: Get Info Test]** 
 - 정상

<br>

**[Cluster NodeGroup VM: Get Info Test]**
  - 다음 값들이 empty이지만, 이 값들은 NodeGroup VM 특성상 정상으로 생각됩니다.
    - PrivateIP만 혹시 제공 가능한지 점검 부탁드립니다. 
    ```
    AccessPoint, PrivateIP, PublicIP
    ```
  - StartTime: 점검 부탁드립니다. 
    <img width="565" alt="image" src="https://github.com/user-attachments/assets/cbf378d4-ff87-4629-bb54-0a7dfd7b4d25">

  - 참고: curl로 확인 방법
    ```
    curl -sX 'GET'   'http://localhost:1024/spider/cspvm//subscriptions/a20fed83-xxx-xxx/resourceGroups/CB_northeurope_azure-northeu-cluster-mfj-crr919bp70irobps45m0_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodegroupm9a-29768530-vmss/virtualMachines/1?ConnectionName=azure-northeu-config'   -H 'accept: application/json' |json_pp |grep StartTime
       "StartTime" : "0001-01-01T00:00:00Z",
    ```

**Comment by ish-hcc** [comment]
@powerkimhub
말씀해 주신 사항들이 모두 scale set vm 쪽에 정보가 없습니다
azure에서 공용 IP 하나만 쿠버네티스 리소스에서 확인됩니다
start time도 실제 vm에만 항목이 존재하는 것으로 보입니다

**Comment by powerkimhub** [comment]
@ish-hcc 

<br>

- 넵, 확인 감사드립니다. 
- Cluster 운영 측면에서는 필수가 아닌 부가 정보들이므로 큰 이슈는 없어 보입니다. 
- close하도록 하겠습니다.

**Comment by ish-hcc** [comment]
@powerkimhub 
넵 확인해주셔서 감사합니다!
