### ISSUE TITLE
[Azure:SSHKey] Change SSHKey ResourceCategory from AzureNetworkCategory to AzureComputeCategory

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1355]
@ish-hcc 

<br>

**[현황/이슈]**
- SSHKey 생성시에 SSHKey SystemId는 `AzureComputeCategory`로 생성되며, 다음 예시와 같은 SystemId를 서버가 받고 있습니다.
  - ex) /subscriptions/a20fed83-xxx-xxx/resourceGroups/NORTHEUROPE/providers/Microsoft.**Compute**/sshPublicKeys/azure-northeu-keypair-kny-crpdhd3p70it0u9n9nig

- 그런데, VM 및 Cluster에서는 SSHKey의 SystemId를 `AzureNetworkCategory`로 다음과 같은 SystemId로 핸들링하고 있습니다. 
  - ex) /subscriptions/a20fed83-xxx-xxx/resourceGroups/northeurope/providers/Microsoft.**Network**/sshPublicKeys/azure-northeu-keypair-kny-crpdhd3p70it0u9n9nig

- 이로 인해, VM이나 Cluster 정보 조회시 활용한 SSHKey 정보 검색시 SSHKey의 SystemId가 달라서,SSHKey를 찾지 못하는 현상이 발생합니다. 

- 지금까지, 문제가 드러나지 않은 이유는 지금까지는 맨뒤 ID(Spider 서버에서는 Short ID라 칭함)로만 검색을 했었기 때문입니다. 
- 현재는, [다른 이슈](https://github.com/cloud-barista/cb-spider/issues/993) 해결을 위해서 전체 ID를 비교 검색해야 하는 상황입니다. 

<br>

**[반영/검토]**

- Hotfix로 @powerkimhub 이 반영하였습니다. 

- 다음 commit을 참고하시어, 혹시 다른 부분에 영향이 있을 지 검토/확인 부탁드립니다. 
  - 또한, 기존에 되던 기능이 안될 경우 다음 commit을 의심해 봐주시기 바랍니다. 
  - 큰 이슈가 없어 보이신다면 현 이슈를 close 해주시기 바랍니다. 
  - https://github.com/cloud-barista/cb-spider/commit/df6ae5036c8e1b04dd8f75df2171c1d97d0e5d34

**Comment by ish-hcc** [comment]
@powerkimhub 소스상으로 확인해 봤을때 영향은 없어 보입니다. 확인해 주셔서 감사합니다.
