### ISSUE TITLE
[Need to fix] REST API result format is different from the JSON Standard & CB-Tumblebug.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#136]
@seokho-son  @jihoon-seo @zephy-mzc 
This change affects CB-Tumblebug and CB-WebTool.

- example of correction
```
<AS-IS> 
    null 

<TO-BE> 
  {  "driver": [] }

<AS-IS> 
[
        {
            "DriverLibFileName": "aws-driver-v1.0.so",
            "DriverName": "aws-driver01",
            "ProviderName": "AWS"
        }
]

<TO-BE>
{
  "driver": [
        {
            "DriverLibFileName": "aws-driver-v1.0.so",
            "DriverName": "aws-driver01",
            "ProviderName": "AWS"
        }
  ]
}
```

**Comment by jihoon-seo** [comment]
관련 함수
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L53
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L148
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L242
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L336
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L430
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L524
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L618
- https://github.com/cloud-barista/cb-spider/blob/31e1be44c2926fe42f101e1c67e3d4225a5360ed/api-runtime/rest-runtime/CCMRest.go#L685
(더 있을 수 있음)

**Comment by powerkimhub** [comment]
- You can get the previous interface version.
  $ git clone --branch v0.1.1 https://github.com/cloud-barista/cb-spider.git

**Comment by powerkimhub** [comment]
completed.

- Now you can get list like this.
```
$ curl -sX GET http://localhost:1024/spider/vmstatus?connection_name=aws-ohio-config |json_pp
{
   "vmstatus" : [
      {
         "VmStatus" : "Suspended",
         "VmId" : "i-0bdc15983e803e7a8",
         "VmName" : "backup"
      },
      {
         "VmId" : "i-03488fbc4001f7476",
         "VmStatus" : "Suspended",
         "VmName" : "spider1"
      },
      {
         "VmName" : "Park_node1",
         "VmStatus" : "Suspended",
         "VmId" : "i-0d582231c5d2d4642"
      },
      {
         "VmName" : "Park_node2",
         "VmId" : "i-0db92d5774cac2547",
         "VmStatus" : "Suspended"
      },
      {
         "VmName" : "Park_master",
         "VmStatus" : "Suspended",
         "VmId" : "i-089c919eb7bc35eea"
      }
   ]
}
```
ref) https://github.com/cloud-barista/cb-spider/commit/3d09601939344683ddcfd82609179b25c29e45a5
