### ISSUE TITLE
[Metadata: Region/Zone] Enhance Supported Region and Zone Info

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#1389]
* [Metadata 개선 일정](https://docs.google.com/spreadsheets/d/1h7Iz1oLVBHRsMDXev9Oia_tZZIfRYb0a_yaJ3N7WmJY/edit?usp=sharing)
* [Region/Zone 개선 방안 및 가이드](https://docs.google.com/presentation/d/1pe8SG-e6OJjMjGv2rhq6zmUFUApzsFl6/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)
* 관련 문의/이슈 있으시면 남겨 주시기 바랍니다.

**Comment by MZC-CSC** [comment]
질문있습니다.

중국의 경우
  ap-chengdu: China, Chengdu 가
  
해당 사이트에서는 지역구, 성, 시에서 시단위로 표시되는 것 같습니다.     
Chengdu Shi의 Sichuan 으로 나오는데 
[China], Sichuan

1. China, Chengdu
2. China, Sichuan

어떤것으로 할까요?
조회 결과인 2번으로 할까요?

**Comment by MZC-CSC** [comment]
Hong Kong으로 검색되는데 Country 없이 조회된 그대로 쓰면 될까요? 아니면 china를 추가할까요?

1. Hong Kong
2. China, Hong Kong

**Comment by MZC-CSC** [comment]
Singapore 의 경우 Country, city 가 아닌 1개 값만 나옵니다.

1. Singapore   ( 조회결과)
2. Singapore, Singapore

2번으로 할까요?

**Comment by powerkimhub** [comment]
@MZC-CSC @ish-hcc @innodreamer 

- 음.. 역시 뭐하나 만만치 않네요. 게다가 Ohio가 city가 아니고, 주였네요. 

<br>

**[DisplayName Format]**
- DisplayName 규격을 다음처럼 개정하도록하겠습니다. 
- COUNTRY, REGION/CITY
  - COUNTRY: 필수
  - REGION/CITY: 둘중 최소 하나 입력 필수, 둘다 입력도 가능
    - REGION 정의: COUNTRY와 CITY 사이의 행정구역
      - ex: Province, State, Prefecture, Territory, … 
    - CITY: 대상 Zone의 실제 데이터센터 위치가 공식적으로 City까지 확인이 될때 City까지 입력
- 위와 같은 포멧으로 작성시에 Country, Region, City에 사용될 명칭을 다음 Site에서 참조
  - https://www.geonames.org
  - 단, 검색 결과 중 다음처럼 삭제 가능한 행정구역 접미사 삭제
    -  예시: `Jeonju-si`에서 ‘-si’ 제거

<br>

**[예시]**
- `China, Hong Kong`
- `Singapore, Singapore`
- `China, Sichuan/Chengdu` # Chengdu가 Region Name에 포함되어 있으므로 데이터센터 위치 정확하므로 입력

<br>

- Region DisplayName
  ```
  South Korea, Seoul
  South Korea, Busan
  South Korea, Jeju-do
  South Korea, Jeollabuk-do
  ```

- Zone DisplayName
  ```
  South Korea, Seoul
  South Korea, Busan
  South Korea, Jeju-do
  South Korea, Jeollabuk-do/Jeonju     # Jeonju-si에서 ‘-si’ 제거, 전주 Zone이 존재한다는 가정
  ```

<br>

- 일단, 위와 같은 형태로 일괄 작업 후에 
- 사용해보면서 이슈 발생시에 보완해가도록 하겠습니다.

**Comment by powerkimhub** [comment]
- 위 변경 내용 다음 가이드에 반영
- [Region/Zone 개선 방안 및 가이드](https://docs.google.com/presentation/d/1pe8SG-e6OJjMjGv2rhq6zmUFUApzsFl6/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

**Comment by powerkimhub** [comment]
@MZC-CSC @ish-hcc @innodreamer

<br>

- Server 및 AdminWeb 반영 완료하였습니다. 
- 과정에서 각 CSP들의 Yaml 포맷 보완되었습니다. 
- 전반적으로 점검을 한 상태이지만, 
- 각 담당 CSP별로 이상이 없는 지 확인 부탁 드립니다. 
- Spider Pre-Release Tag는 특별한 수요가 없으면, 
  - Spec Info, Image Info, Price Info 등 개선 후 찍을 계획입니다. 
- 이하, 개선 내용 참고하시기 바랍니다. 

---

### [Before]
- 이슈: Region 및 Zone 지역 이름(DisplayName)이 일관성이 없음

![image](https://github.com/user-attachments/assets/f660e001-2493-4f5a-954f-82ed680c82e9)


### [After]
- 추상화된 일관된 지역 이름 형식으로 제공 (추상화 포맷/규칙 [참고](https://docs.google.com/presentation/d/1pe8SG-e6OJjMjGv2rhq6zmUFUApzsFl6/edit#slide=id.p3))
- CSP가 제공하는 지역 이름(CSPDisplayName) 정보 추가 제공
- Rest API: 호출은 전과 동일하며, 제공 결과만 보완됨
![image](https://github.com/user-attachments/assets/5fab3ee7-df44-4e7e-a093-3d81831b4e78)

<br>

### [현재 적용 완료 CSP]

| CSP Name       | File Name                   |
|----------------|-----------------------------|
| AWS            | aws_region_meta.yaml        |
| Azure          | azure_region_meta.yaml      |
| GCP            | gcp_region_meta.yaml        |
| Alibaba        | alibaba_region_meta.yaml    |
| Tencent        | tencent_region_meta.yaml    |
| IBM            | ibm_region_meta.yaml        |
| OpenStack      | openstack_region_meta.yaml  |
| NHN Cloud      | nhncloud_region_meta.yaml   |

<br>

### [적용 방법]
- `cb-spider/cloud-driver-libs/region/*`에 대상 csp용 yaml 추가
  - (1) CSP yaml 파일 존재 시에 yaml 내용 적용하여 제공
  - (2) 파일 없을 시에 기존 내용으로 제공됨
- **※ 아직 제공 전인 CSP 드라이버의 빠른 반영을 희망합니다~**

<br>

**Comment by powerkimhub** [comment]
- https://github.com/cloud-barista/cb-spider/commit/068af1624b170eb15891dc745394213ffb3b92fc
- https://github.com/cloud-barista/cb-spider/commit/bf87ab376795756a82d19696f8e468d6facff67d
