### ISSUE TITLE
Suggestion: Add `/spider/` prefix for REST APIs

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#139]
As-Is:
- /publicip
- /vnetwork
- /vm
- ...

---

To-Be:
- /spider/publicip
- /spider/vnetwork
- /spider/vm
- ...

---

[사유]
- API-GW 에서 지금은 각 API (/publicip, /vnetwork, /vm, ...) 별로 rule 을 적고 있습니다.
- 향후 http://api-gw:8000/spider/* 로 오는 모든 요청을 http://cb-spider:1024/* 로 보내고 싶습니다.
- 예를 들어 API-GW 테스트 시 Spider 에 API 요청할 때 1) Spider 로 직접 보내기, 2) API-GW 로 보내기 를 계속 왔다갔다 해야 하는데, 이 때 Spider API 도 /spider/ (또는 /cb-spider/) 로 시작하도록 통일되어 있으면, 테스트도 편리하고, 향후에도 편리할 것으로 예상됩니다.

---

- 영향: Spider API 를 이용하는 Tumblebug, Dragonfly, Webtool 등도 Spider API 변경에 대한 대응이 필요합니다.
- 기타: Tumblebug, Dragonfly, Webtool 등도 모두 이런 스타일로 갔으면 좋겠습니다.

**Comment by jihoon-seo** [comment]
관련 파일
- https://github.com/cloud-barista/cb-spider/blob/master/api-runtime/rest-runtime/CBSpiderRuntime.go
(더 있을 수도 있음)

**Comment by powerkimhub** [comment]
- You can get the previous interface version.
  $ git clone --branch v0.1.1 https://github.com/cloud-barista/cb-spider.git

**Comment by powerkimhub** [comment]
completed.
- Now you can use like this.
  $ curl -sX GET http://localhost:1024/spider/driver

ref) https://github.com/cloud-barista/cb-spider/commit/3f55a947559ddb63685cb61f5ec31c7e1a6db9b2
ref) https://github.com/cloud-barista/cb-spider/commit/246b1693096bf6e7d018826826bde9e6e773a892
