### ISSUE TITLE
Suggestion: `connection_name` - in query string vs. in JSON body

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#140]
- 현재 Spider: `{{spider_ip}}:{{spider_port}}/keypair?connection_name={{connection_name}}`
위와 같이, URL 뒤에 query param 으로 명시
- 현재 Tumblebug: `{{tb_ip}}:{{tb_port}}/ns/{{ns_id}}/resources/publicIp`
위와 같이 API Call 할 때, JSON body 에
```JSON
{
  "connectionName": "{{connection_name}}",
  "cspPublicIpName": "jhseo-test"
}
```
위와 같이 명시

---

- 통일을 시켜야 한다는 것은 아니지만, Spider 에서도 아래 방법으로 connection_name 을 명시받는 것은 어떤지 하여 이슈로 작성해 봅니다.
- 만약 바꾼다면, Spider 를 이용하는 TB, Dragonfly, Webtool 등도 Spider 변경에 대한 대응이 필요합니다. 이를 고려하면, 바꾸지 않는 것이 나을 수도 있습니다.

**Comment by powerkimhub** [comment]
@jihoon-seo 
Query Param도 간단한 정보를 넘기는 사용되는 표준 방법으로 생각됩니다. 
일관성 유지 외에 보안 상의 문제라던지 추가 이슈가 없다면, 
프레임워크별로 해도 될듯합니다. 

1주일 정도 오픈 뒤에 추가 comment가 안 붙으면 close하도록 하겠습니다.

**Comment by seokho-son** [comment]
@powerkimhub 
resource를 식별하고 싶으면 Path Variable을 사용하고, 
정렬이나 필터링을 한다면 Query Parameter를 사용하는 것이 Best Practice 라고 알려져 있는 것 같습니다. ex: "GET /cars/honda/civic/coupe/{resource}/{filter=xxxxxx}"
https://ryan-han.com/post/translated/pathvariable_queryparam/

개인적으로는 개별 프레임워크들이 개발은 독립적으로 진행될 수 있지만, API의 경우 사용자의 입장에서 공통된 방식을 사용하면 좋을 것 같긴합니다. API를 사용하는 개발자 입장에서는 API 패턴에 일관성이 있어야 API를 활용한 개발이 편리하지 않나 싶습니다. 참고하시기 바랍니다.

**Comment by powerkimhub** [comment]
@jihoon-seo @seokho-son 많은 사람들이 그리 쓴다면, 
이번 REST API 수정 작업시에 함께 수정하도록 하지요. 

- **connection_name=xxx**을 body로 집어 넣으면 될 듯한데,
- 혹시, 다른 수정사항도 보이는게 있나요?

**Comment by powerkimhub** [comment]
completed.
Now you can use it like this.
  - Before: `{{spider_ip}}:{{spider_port}}/keypair?connection_name={{connection_name}}`
  - Now: 
      ` curl -sX POST http://localhost:1024/spider/securitygroup -H 'Content-Type: application/json' -d '{ "ConnectionName": "aws-ohio-config",
        "ReqInfo": { "Name": "security01-powerkim", "SecurityRules": [ {"FromPort": "1", "ToPort" : "65535", "IPProtocol" : "tcp", "Direction" : "inbound"} ] } }' `

ref) more examples: https://github.com/cloud-barista/cb-spider/tree/master/api-runtime/rest-runtime/test/aws-shooter-name
ref) https://github.com/cloud-barista/cb-spider/commit/a2d31c7531b7543faa06baf72ca9bf7ae53e0445
