### ISSUE TITLE
How to register driver library & information into container spider?

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#145]
issued by @jihoon-seo

**Comment by powerkimhub** [comment]
@jihoon-seo 
 - spider container가 stateless가 가능하려면, 
   driver lib 파일을 저장할 수 있는 shareable persistent storage가 필요한데, 
 - 현재 Cloud-Barista 운영 환경에는 etcd 밖에 없네요. 
   - but, etcd에는 파일을 저장할 수 없습니다. 
   - 이를 시도했던 사람도 있지만(https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fxetorthio%2Fetcd-fs&sa=D&sntz=1&usg=AFQjCNEr6u1BFiHkLqdd0bqJmKCXNf7hBw), 바람직한 방법은 아니어 보입니다. 
 - nfs-pod 등을 이용하여 PV(persistent Volume) 구성 및 활용 방법도 있겠지만, 
 - 제가 아는 가장 빠른 방법은 nfs를 구성하고, spider container에서 mount하는 방법이 있겠습니다. 
 - 아래 방법으로 **시험 후 결과 공유** 부탁드립니다. 

**<시험방법>**
  * ref) https://github.com/powerkimhub/ease/tree/master/easy-NFS
```
    (1) NFS Server 설치: install-nfs-server.sh
           -  운영하는 etcd 서버 등 ubuntu 서버에 설치
    (2) 등록하고자 하는 driver library 파일을 아래 위치에 복사
           - /nfs/cloud-driver-lib
    (3) NFS Client 설치 및 mount: install-nfs-client.sh
           - spider container 또는 이미지 스크립트에 반영
    (4) driver 등록 시험
```

**Comment by jihoon-seo** [comment]
Spider 를 컨테이너로 실행하는 경우
컨테이너 이미지 안에 드라이버 파일들이 내장되어 있습니다.

```
root@d511380a2895:~/go/src/github.com/cloud-barista/cb-spider/cloud-driver-libs# ls -alh
total 186M
drwxr-xr-x 2 root root 4.0K May  8 11:07 .
drwxr-xr-x 1 root root 4.0K May 12 06:06 ..
-rw-r--r-- 1 root root   39 Mar 13 01:34 README.md
-rwxr-xr-x 1 root root  66M Apr 17 06:51 alibaba-driver-v1.0.so
-rwxr-xr-x 1 root root  38M May  8 11:05 aws-driver-v1.0.so
-rwxr-xr-x 1 root root  20M May  8 11:06 azure-driver-v1.0.so
-rwxr-xr-x 1 root root  14M Apr 17 06:51 cloudit-driver-v1.0.so
-rwxr-xr-x 1 root root  34M May  8 11:06 gcp-driver-v1.0.so
-rwxr-xr-x 1 root root  15M May  8 11:06 openstack-driver-v1.0.so
```

그런데 Spider 의 초기 meta_db 에는 driver들에 대한 정보가 등록되어 있지 않습니다.

물론 driver 정보를 등록할 때 `DriverName` 과 `ProviderName` 을 지정해 줘야 하기 때문에
사용자가 직접 등록하는 것이 타당하기는 합니다.

```JSON
{
    "DriverName": "gcp-driver01",
    "ProviderName": "GCP",
    "DriverLibFileName": "gcp-driver-v1.0.so"
}
```

하지만 `DriverLibFileName` 란에 들어갈 값 (파일명) 은
1. 소스코드를 받아서 설치 및 실행하는 사람은
`cb-spider/cloud-driver-libs` 에 들어가서
어떤 드라이버 파일들이 있는지를 확인해야 알 수 있고
2. 컨테이너로 실행하는 사람은
어쩌면 컨테이너에 접속하여 (`docker exec` / `docker-compose exec`)
`~/go/src/github.com/cloud-barista/cb-spider/cloud-driver-libs` 안에 어떤 드라이버 파일들이 있는지 확인해 봐야 할 수도 있습니다.

다른 방법으로는
Spider GitHub repo README 등에
드라이버 파일명 목록을 기재해 놓는 방법 등이 있겠습니다.

**Comment by powerkimhub** [comment]
@jihoon-seo 
고려해보겠습니다. 
시간은 좀 걸릴거에요.

**Comment by powerkimhub** [comment]
@jihoon-seo 

- Cloud Driver 등록시 `DriverLibFileName` 입력 정보 지원 관련: Guide 추가로 보완하였습니다. 
  - [기능 및 사용법: (1) Cloud Driver 정보 등록 및 관리](https://github.com/cloud-barista/cb-spider/wiki/features-and-usages#1-cloud-driver-%EC%A0%95%EB%B3%B4-%EB%93%B1%EB%A1%9D-%EB%B0%8F-%EA%B4%80%EB%A6%AC)
  - [제공하는 CloudOS 목록: Cloud Driver lib. 컴럼 추가](https://github.com/cloud-barista/cb-spider/wiki/Supported-CloudOS)

- Spider Container 실행 모드의 경우 Cloud Driver Library 신규 추가 방법
  - 이슈분리: https://github.com/cloud-barista/cb-spider/issues/467
