### ISSUE TITLE
Bug: AWS 에 Name: (null) 인 EIP 가 있을 때, Spider 에서 GET PublicIP list 하면 아무것도 안 뜸

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#147]
![EIP](https://user-images.githubusercontent.com/46767780/77275474-bce5f680-6cfb-11ea-852e-49a0aca14fdf.png)

---

Request:
GET `{{spider_ip}}:{{spider_port}}/spider/publicip`

---

Response:
```JSON
{
    "publicip": []
}
```

**Comment by powerkimhub** [comment]
@jihoon-seo 
https://github.com/cloud-barista/cb-spider/issues/146 문제의 후속 영향으로 보입니다.
https://github.com/cloud-barista/cb-spider/issues/146 이슈로 통합합니다.
