### ISSUE TITLE
Issue: AWS vnetwork 생성 시, 1) 사용자가 지정한 이름, 2) AWS에 기록되는 이름, 3) 사용자에게 리턴되는 이름이 다름

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#148]
Request:
POST `{{spider_ip}}:{{spider_port}}/spider/vnetwork`
```JSON
{
    "ConnectionName": "aws-us-east-1-config",
    "ReqInfo": {
    	"Name": "jhseo-test"
    }
}
```

---

AWS Console:
![vnet1](https://user-images.githubusercontent.com/46767780/77489025-44597400-6e7a-11ea-9e4a-23c9ec9cfae8.png)
![vnet2](https://user-images.githubusercontent.com/46767780/77489031-4a4f5500-6e7a-11ea-8b01-4d8058deb260.png)

---

Response:
```JSON
{
    "Id": "subnet-01b0dadd2ab683d79",
    "Name": "jhseo-test",
    "AddressPrefix": "192.168.0.0/16",
    "Status": "pending",
    "KeyValueList": [
        {
            "Key": "VpcId",
            "Value": "vpc-017466936a5667f1c"
        },
        {
            "Key": "MapPublicIpOnLaunch",
            "Value": "false"
        },
        {
            "Key": "AvailableIpAddressCount",
            "Value": "65531"
        },
        {
            "Key": "AvailabilityZone",
            "Value": "us-east-1e"
        }
    ]
}
```

---

FYI:
이를 GET, DELETE 하려면
`{{spider_ip}}:{{spider_port}}/spider/vnetwork/CB-VNet` 으로 하면 안 되고
`{{spider_ip}}:{{spider_port}}/spider/vnetwork/jhseo-test` 로 해야 합니다.

**Comment by powerkimhub** [comment]
@jihoon-seo 
현 이슈는 리모델링 대상에 포함되어 있습니다. 
리모델링 작업이 시간이 좀 걸릴 듯하니, 
현 이슈도 오픈해두고, 리모델링 완료 시점에 재확인해보도록 하지요. 

**AS-IS: 부연 설명**
  - 현재 버전은 입력 이름이 subnet 이름입니다. 
  - 실제 VNet인 AWS의 VPC는 내부에서 생성하며, AWS는 사용자가 ID를 관리할 수 없어, 
     label로 CB-VNet으로 부여한 상태입니다. 
  - 삭제시에는 입력 이름인 subnet 이름으로 삭제 요청하면 되고, 마지막 subnet이 삭제되면 VNet(CB-VNet)도 삭제되는 방식입니다. 
  - 이는 다른 CSP들의 VPC or VNet과의 통합 과정의 어려움을 피하기 위한 마감 시간을 고려한 트릭이며, 
  - 이번 리모델링 작업 후에는 해소될 예정입니다.

**Comment by jihoon-seo** [comment]
리모델링으로 해소된 것으로 보입니다.
