### ISSUE TITLE
Bug: AWS VPC 만들 때 IID.NameId 가 제대로 전달되지 않았는데도 AWS 에 VPC 가 생성됨

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#182]
FYI - 올바른 요청
```JSON
{
    "ConnectionName": "'${CONN_CONFIG}'",
    "ReqInfo": {
        "Name": "VPC-01",
        "IPv4_CIDR": "192.168.0.0/16",
        "SubnetInfoList": [
            {
                "Name": "Subnet-01",
                "IPv4_CIDR": "192.168.1.0/24"
            }
        ]
    }
}
```

---

제가 Spider 에 날린 요청 (잘못된 요청입니다):
```JSON
{
  "ConnectionName": "aws-us-east-1-config",
  "ReqInfo": {
    "IId": {
      "NameId": "VPC-01",
      "SystemId": "VPC-01"
    },
    "IPv4_CIDR": "192.168.0.0/16",
    "SubnetInfoList": [
      {
        "IId": {
          "NameId": "",
          "SystemId": ""
        },
        "IPv4_CIDR": "192.168.1.0/24",
        "KeyValueList": null
      }
    ]
  }
}
```

---

제가 예상한 결과:
Spider 가
"ReqInfo.Name 이 비어 있습니다" 라고 에러를 출력하고
AWS VPC 를 생성하지 않음

---

현재 동작:
Spider 가
**Name (Label) 없는 AWS VPC 를 생성하고**
HTTP 500 에러를 리턴함

```JSON
{
    "time": "2020-04-29T17:56:08.300475343+09:00",
    "id": "",
    "remote_ip": "127.0.0.1",
    "host": "localhost:1024",
    "method": "POST",
    "uri": "/spider/vpc",
    "user_agent": "Go-http-client/1.1",
    "status": 500,
    "error": "",
    "latency": 5574431517,
    "latency_human": "5.574431517s",
    "bytes_in": 365,
    "bytes_out": 36
}
```

**Comment by jihoon-seo** [comment]
6/5 현재 같은 문제가 있습니다.

제안: API call 의 JSON body 내 필수 field 들의 유효성 검사 로직 추가

[예]
- ConnectionName
- ReqInfo
  - Name
  - IPv4_CIDR
  - SubnetInfoList
    - Name
    - IPv4_CIDR

---

이번 기회에

1. CB 모든 API/함수에 인풋 데이터의 유효성 검사 로직 추가
2. API 스펙 정의 및 발표 (예: 필수 field 가 어떤 것들인지)

를 하는 방법도 있는데
공수는 좀 있을 것 같습니다.

**Comment by powerkimhub** [comment]
@jihoon-seo 

- Common Validator 개발 및 적용
- 관련 내용 참고
  - https://github.com/cloud-barista/cb-spider/issues/394#issuecomment-963167074

- **[Issue TEST]**
  - ![image](https://user-images.githubusercontent.com/46367962/140770264-a984b539-0a08-4822-a96d-6eb1dd29d37f.png)

- **[Result Message]**
  - ![image](https://user-images.githubusercontent.com/46367962/140770618-4d1a4e93-f15f-4017-8d0b-8d7ba27e4819.png)
