### ISSUE TITLE
[Feature req.] Spider 메타정보만 삭제하는 기능

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#183]
용도
- 자원/VM 등을 CSP 에서는 그대로 두고, Spider 메타정보에서만 삭제하고 싶을 때
- CSP 에서 이미 지워진 자원/VM 등을 Spider 메타정보에서도 삭제하고 싶을 때

**Comment by powerkimhub** [comment]
@jihoon-seo Thanks for the good suggestions.

**Comment by powerkimhub** [comment]
아래 이슈로 통합.
- https://github.com/cloud-barista/cb-spider/issues/228
