### ISSUE TITLE
AWS Region 생성시 Region에 대한 Key 명칭 대소문자 구분 이슈

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#189]
Bug 리포트 입니다.

Region 생성시 Region에 대한 Key Value를 입력하는데,
AWS 의 경우, Key를 소문자 "region"으로 했을 때, AWS의 Endpoint를 못찾는 문제가 발생합니다.
테스트해보니, "Region" 으로 하면 문제 없습니다.
(@powerkimhub 해당 사항을 공시하시거나, 대소문자 구분을 하지 않도록 수정하는 것이 좋을 것 같습니다.)

[버그 상황 예시]
```
curl -sX POST http://$RESTSERVER:1024/spider/region -H 'Content-Type: application/json' -d \
    '{
        "ProviderName" : 
        "KeyValueInfoList" : [
            {
                "Key" : "region"
                "Value" : "us-east-1"
            }
        ],
        "RegionName" : 
    }' | json_pp

```

[에러메시지: VPC 생성시]
```
## 1. VPC: Create

{
   "message" : "{\"message\":\"InvalidEndpointURL: invalid endpoint uri\\ncaused by: parse https://ec2.Not set.amazonaws.com/: invalid character \\\" \\\" in host name\"}\n"
}

```

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo 
- 정리가 될때까지, 다음 위치의 예시 활용바랍니다. 

#aws
cb-spider/api-runtime/rest-runtime/test/aws-shooter-name/cim-insert-test.sh

#azure
cb-spider/api-runtime/rest-runtime/test/azure-shooter/cim-insert-test.sh

#gcp
cb-spider/api-runtime/rest-runtime/test/gcp-shooter/cim-insert-test.sh

#alibaba
cb-spider/api-runtime/rest-runtime/test/alibaba-shooter/cim-insert-test.sh

#cloudit
cb-spider/api-runtime/rest-runtime/test/cloudit-shooter/cim-insert-test.sh

#openstack
cb-spider/api-runtime/rest-runtime/test/openstack-shooter-name/cim-insert-test.sh

#docker
cb-spider/api-runtime/rest-runtime/test/docker/cim-insert-test.sh

#cloudtwin
cb-spider/api-runtime/rest-runtime/test/cloudtwin-shooter/cim-insert-test.sh

**Comment by powerkimhub** [comment]
https://github.com/cloud-barista/cb-spider/issues/248

**Comment by powerkimhub** [comment]
- fix it with https://github.com/cloud-barista/cb-spider/issues/414#issuecomment-968860618
