### ISSUE TITLE
[XXXDriver.go & XXXDriver-lib.go 공존 이슈]

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#193]
- AS-IS: XXXDriver.go build 시 번거로움

**Comment by jihoon-seo** [comment]
2020-05-19 현재

[XXXDriver.go 삭제 완료됨]
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/alibaba (`AlibabaDriver.go.del` 로 남아 있음)
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/docker
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/gcp
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/openstack

[XXXDriver.go 남아 있음]
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/aws
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/azure
- https://github.com/cloud-barista/cb-spider/tree/master/cloud-control-manager/cloud-driver/drivers/cloudit

**Comment by powerkimhub** [comment]
@jihoon-seo 현황 정보 감사. 
급한 불 꺼지면, 근본적인 문제를 해결 에정입니다. 
순번타는 중^^

**Comment by powerkimhub** [comment]
@jihoon-seo 반영 완료하였습니다. ( @hyokyungk @dev4unet @jazmandorf )

- XXXDriver-lib.go와 build_driver_lib.sh를 {driver}-plugin/* 이동
