### ISSUE TITLE
securityGroup 상세 firewall 룰 처리 이슈

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#197]
Spider를 통해 securityGroup 생성시 상세 firewall 룰 입력 방식 공유가 필요.

[예시]
```
curl -sX POST http://localhost:1323/tumblebug/ns/$NS_ID/resources/securityGroup -H 'Content-Type: application/json' -d \
	'{
		"name": "SG-'$CSP'-'$POSTFIX'",
		"connectionName": "'${CONN_CONFIG[INDEX]}'",
		"vNetId": "VPC-'$CSP'-'$POSTFIX'",
		"description": "jhseo test description",
		    "firewallRules": [
			    {
				    "FromPort": "1",
				    "ToPort": "65535",
				    "IPProtocol": "tcp",
				    "Direction": "inbound"
			    }
		    ]
	    }' | json_pp #|| return 1
```

"FromPort": "1",
"ToPort": "65535",
"IPProtocol": "tcp",
"Direction": "inbound"

각 Key의 Value로 입력할 수 있는 정보 공유가 필요하며,
특히 IPProtocol 중 icmp (ping 등을 처리하기 위한) 를 추가하기 위한 예시가 필요합니다.

또한 CSP 간에 일관성 있는 키워드를 사용하도록 확인 및 처리가 필요합니다.

**Comment by seokho-son** [comment]
ref @jihoon-seo @powerkimhub

**Comment by powerkimhub** [comment]
by @dev4unet 

## [AWS] ##
```
                      {
                            FromPort:   "-1",
                            ToPort:     "-1",
                            IPProtocol: "icmp",
                            Direction:  "inbound",
                        },
```
(ref) https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html
https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html#security-group-rules

## [ALIBABA] ##
```
                      {
                            FromPort:   "-1",
                            ToPort:     "-1",
                            IPProtocol: "icmp",
                            Direction:  "inbound",
                        },
```
(ref) https://www.alibabacloud.com/help/doc-detail/25471.htm?spm=a2c63.p38356.879954.8.44fa4839CwvQSP#concept-sm5-2wz-xdb

**Comment by powerkimhub** [comment]
by @dev4unet

[GCP]  AWS, Alibaba와 동일한 인자 패턴으로 변환 추진
  - 변환 기준: -1 => Null, From과 To 모두 -1 => All

(ref) https://cloud.google.com/vpc/docs/firewalls?hl=ko&_ga=2.238147008.-1577666838.1589162755#protocols_and_ports

**Comment by powerkimhub** [comment]
by @hyokyungk 

## 현황(Azure/OpenStack/Cloudit)
[Azure]
[]irs.SecurityRuleInfo{
	{
		FromPort:   "*",
		ToPort:     "*",
		IPProtocol: "ICMP",
		Direction:  "inbound",
	},
}
[OpenStack]
[]irs.SecurityRuleInfo{
	{
		IPProtocol: "ICMP",
		Direction:  "inbound",
	},
}
[Cloudit] ICMP 프로토콜 기본 활성화 (별도 설정 불필요/비지원)

## 추진
[Azure/OpenStack] 다음 입력 값으로 가능하도록 드라이버 변경 추진
[Cloudit] 추후 정리

```
                     {
                            FromPort:   "-1",
                            ToPort:     "-1",
                            IPProtocol: "icmp",
                            Direction:  "inbound",
                        },
```

**Comment by seokho-son** [comment]
@powerkimhub SG그룹 관련 Azure 시험 오류 리포트 @jihoon-seo 

[Input example] call to azure. // tumblebug API이지만, fiewallRules 는 그대로 전달합니다.
```
curl -sX POST http://localhost:1323/tumblebug/ns/$NS_ID/resources/securityGroup -H 'Content-Type: application/json' -d \
	'{
		"name": "SG-'$CSP'-'$POSTFIX'",
		"connectionName": "'${CONN_CONFIG[INDEX]}'",
		"vNetId": "VPC-'$CSP'-'$POSTFIX'",
		"description": "jhseo test description",
		    "firewallRules": [
			    {
				    "FromPort": "1",
				    "ToPort": "65535",
				    "IPProtocol": "tcp",
				    "Direction": "inbound"
			    },
				{
				    "FromPort": "-1",
				    "ToPort": "-1",
				    "IPProtocol": "icmp",
				    "Direction": "inbound"
			    }
		    ]
	    }' | json_pp #|| return 1

```

[Output for Azure test]
```
{
   "message" : "{\"message\":\"network.SecurityGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\\\"SecurityRuleInvalidPortRange\\\" Message=\\\"Security rule has invalid Port range. Value provided: -1. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.\\\" Details=[]\"}\n"
}

```

**Comment by powerkimhub** [comment]
완료.

ref) https://github.com/cloud-barista/cb-spider/commit/47689b4c9aa1000d20d0fe0afbaa7645256a34b5
