### ISSUE TITLE
Info: rackspace/gophercloud 관련

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#201]
현재 [go.mod](https://github.com/cloud-barista/cb-spider/blob/master/go.mod) 에는 이렇게 되어 있습니다.
```
github.com/rackspace/gophercloud v1.0.1-0.20161013120614-60916741c8ec
```

---

`go.mod` 파일을 업데이트 하기 위해
`cb-spider` 디렉토리에서 `go mod tidy` 명령을 내리면
다음과 같이 변경됩니다.

```
github.com/rackspace/gophercloud v1.0.0
```

https://github.com/rackspace/gophercloud 에 가서 확인해 보면
`master` 브랜치에는
이 이슈를 작성하는 현재 2,156 개의 커밋이 있는데
`v1.0.0` 태그는 1,144 번째 커밋에 찍혔습니다. 너무 오래되었습니다.

---

해결책:
https://github.com/rackspace/gophercloud/commits/master 에서
travis-ci 테스트를 패스한 가장 마지막 commit 의 commit ID 를 복사하고
(예: `60916741c8ec228e035f8229aee85452840e2c0d`)

`cb-spider` 디렉토리에서 다음의 명령을 내립니다.
`go get -u -v github.com/rackspace/gophercloud@60916741c8ec228e035f8229aee85452840e2c0d`

---

다시 `go.mod` 파일을 확인해 보면 다음과 같습니다.
```
github.com/rackspace/gophercloud v1.0.1-0.20161013120614-60916741c8ec
```

**Comment by powerkimhub** [comment]
@jihoon-seo 
감사합니다. 
추후 참고하도록 할께요.

**Comment by inno-cloudbarista** [comment]
@powerkimhub @jihoon-seo 

https://github.com/inno-cloudbarista/cb-spider/tree/feature/openstack-gophercloud
해당 브랜치에 gophercloud 신규 라이브러리를 적용을 진행하고, 테스트를 진행 중입니다.
기본 리소스에 대한 모든 CRUD 통합 테스트를 진행 후에 PR 요청을 드리도록 하겠습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- PR을 적용 후에도 빌드 방법이 동일한지요?
- 즉, go.mod 파일 수정만으로 대상 gophercloud 버전의 다운로드가 가능한지요?
- 아니면, go get-u -v ~ 등 뭔가 별도 수행해야 하나요?
- 후자이면, 현재 반영을 고려해볼 필요가 있겠습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 

- 빌드 방법은 동일합니다.
- go.mod 파일에 새로운 gophercloud 모듈을 추가하면 자동으로 go.sum 파일에 해당 모듈에 대한 체크썸 정보가 등록되는 형태입니다.

go.mod 파일 (수정사항)
```
github.com/gophercloud/gophercloud v0.17.0
```

go.sum 파일 (수정사항)
```
github.com/gophercloud/gophercloud v0.17.0 h1:BgVw0saxyeHWH5us/SQe1ltp0GRnytjmOLXDA8pO77E=
github.com/gophercloud/gophercloud v0.17.0/go.mod h1:wRtmUelyIIv3CSSDI47aUwbs075O6i+LY+pXsKCBsb4=
```

**Comment by powerkimhub** [comment]
Changed the Go SDK of OpenStack with `github.com/gophercloud/gophercloud`
- https://github.com/cloud-barista/cb-spider/pull/368
- https://github.com/cloud-barista/cb-spider/pull/370
