### ISSUE TITLE
새로운 gophercloud 패키지 이용

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#215]
@hyokyungk 
현재 `go.mod` 를 보면 `github.com/rackspace/gophercloud` 패키지를 사용하는 것으로 되어 있습니다.
그런데 https://github.com/rackspace/gophercloud/issues/592 이슈를 보면
저것 대신 `github.com/gophercloud/gophercloud` 를 사용하도록 권장하고 있습니다.
어떻게 생각하시나요..?

**Comment by powerkimhub** [comment]
@hyokyungk (ref: @jihoon-seo )
- 반영 하시기게 되면 카푸치노 행사를 고려하여 스케줄링 해주시기 바랍니다. 
- 동작에 문제가 없다면, 행사 이후로...

**Comment by hyokyungk** [comment]
@jihoon-seo 

gophercloud/gophercloud 라이브러리 대신 rackspace/gophercloud 라이브러리를 선택한 이유는
gophercloud에서 제공하지 않는 다양한 리소스까지 rackspace/gophercloud API를 통해 핸들링이 가능하다고 판단해서였습니다.

gophercloud의 extension 라이브러리를 타고가다보면 결국 rackplace/gophercloud 라이브러리를 사용하도록 되어있는 구조입니다.
(http://gophercloud.io/docs/compute/ 문서의 extension 링크를 참고 부탁드려요.)

해당 부분은 gophercloud/gophercloud를 통해서 핸들링 할 수 있는 리소스 범위와 rackplace/gophercloud를 통해 핸들링할 수 있는 리소스 범위,
그리고 현재 개발되어있는 부분을 모두 지원하는지 까지 판단을 해봐야 할 것 같습니다.

대부분은 호환이 되고 일치할 것이라고 생각하지만, 100%라고 보장할 순 없을 것 같아요

해당 부분은 카푸치노 버전 이후 다시 재검토 후 의견 공유드리도록 하겠습니다.
