### ISSUE TITLE
[VMSpecHandler] 메모리 정보 불일치

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#220]
@dev4unet @jazmandorf @hyokyungk 

<VMSpecHandler Interface> 관련 확인 부탁 드립니다.
- VMSpeccInfo.Mem 값의 경우 단위가 CSP별로 섞여 올라오고 있습니다. 
- 단위를 **Megabyte, 상수 값** 통일 부탁 드립니다. 
- 숫자 규모로 파악된 현황: 
       > AWS/GCP/Azure/OpenStack => Mega
       > Alibaba/Cloudit => Giga
- CSP별 확인 및 Mega로 반영 부탁 드립니다. 
- **Alibaba: 시급성 - 상**

<참고>
```
type VMSpecInfo struct {
        Region string
        Name   string
        VCpu   VCpuInfo
        Mem    string
        Gpu    []GpuInfo

        KeyValueList []KeyValue
}

```

**Comment by jihoon-seo** [comment]
모든 CSP 드라이버에 대해 처리가 완료되었으면
이 이슈는 close 해도 될 것 같습니다.
