### ISSUE TITLE
[Suggestion] Change User API Docs with Swagger.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#275]
- cf) https://github.com/cloud-barista/cb-tumblebug/pull/215

**Comment by powerkimhub** [comment]
- option info) https://github.com/cloud-barista/cb-tumblebug/issues/190

**Comment by powerkimhub** [comment]
- cf) https://github.com/cloud-barista/cb-tumblebug/discussions/414#discussioncomment-546987

**Comment by powerkimhub** [comment]
- cf) https://cloud-barista.slack.com/archives/CJQ7575PU/p1619747581050800?thread_ts=1618881200.048600&cid=CJQ7575PU
- cf) https://github.com/cloud-barista/cb-tumblebug/pull/485

**Comment by powerkimhub** [comment]
- cf) swaggo: https://github.com/cloud-barista/cb-tumblebug/pull/189

**Comment by powerkimhub** [comment]
- cf) ladybug: https://github.com/cloud-barista/cb-ladybug/issues/42

**Comment by powerkimhub** [comment]
- cf) https://github.com/cloud-barista/cb-spider/issues/393

**Comment by powerkimhub** [comment]
- Added pilot codes : https://github.com/cloud-barista/cb-spider/pull/418

**Comment by powerkimhub** [comment]
- Thanks @jihoon-seo

**Comment by jihoon-seo** [comment]
Related PR: Add another Swagger pilot codes #420

**Comment by powerkimhub** [comment]
- cf) https://github.com/swaggo/swag
- cf) `OpenAPI 스펙 버전: 2.0을 최대한 준수 (3.1을 아직 지원하지 않는 외부 도구들이 많음을 고려)` from M-CMP

**Comment by powerkimhub** [comment]
- cf) https://github.com/cloud-barista/cm-data-mold/pull/35

**Comment by powerkimhub** [comment]
- Supported since [v0.9.4](https://github.com/cloud-barista/cb-spider/releases/tag/v0.9.4)
