### ISSUE TITLE
[Suggestion] Remove return value for cloud credential from API

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#280]
현재 curl -H "${AUTH}" -sX POST http://$SpiderServer/spider/credential 등을 통해

Cloud 의 credential 를 생성하면

처리 결과로 다시 credential 정보를 리턴하고 있습니다. (CredentialKey 및 CredentialVal 쌍)

해당 값은 사람이 바로 읽을 수 없도록 기본적인 인코딩 해주셨으나,

Credential 값의 보안적 중요도를 생각했을때 값 (특히, CredentialVal) 자체를 리턴하지 않는 것이 바람직할 것 같습니다.

API 를 통한 credential 조회시에도 마찬가지로 적용하는 것이 좋아 보입니다.

**Comment by powerkimhub** [comment]
@seokho-son 조만간 반영하도록 하지요.

**Comment by powerkimhub** [comment]
- Completed via 
  - https://github.com/cloud-barista/cb-spider/commit/493011a49d6db39f9043c82f3c72fc3521fed7fa
  - https://github.com/cloud-barista/cb-spider/commit/5f1520783aff13fc81323dc0f429cba489b7faff

- Credential 관련 Create/List/Get API 반환 정보에서 credential 정보 대신 다음 메시지를 출력
  - 'Hidden for security.'
  - AWS 예시) 
  ```
  ClientId:Hidden for security., 
  ClientSecret:Hidden for security.
  ```

**Comment by powerkimhub** [comment]
[FYI] Admin Web page
![image](https://user-images.githubusercontent.com/46367962/150933752-760124cf-95c9-4ddf-b630-58855163c272.png)
