### ISSUE TITLE
Minor changes needed in drivers/docker/resources/VMHandler.go

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#322]
https://github.com/cloud-barista/cb-spider/blob/d5f6e12cfad9c636a3ed38e9311f98910de39099/cloud-control-manager/cloud-driver/drivers/docker/resources/VMHandler.go#L273-L274

`return` 문 2개 중 하나를 지우면 될 것 같습니다.

---

**Comment by powerkimhub** [comment]
Thanks.
Completed. 
cf) https://github.com/cloud-barista/cb-spider/commit/56fab5e5cb41757250c2843703d24e446750187d
