### ISSUE TITLE
[Cloud-Twin] Integration test of Tumblebug & Dragonfly

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#334]
### [Abbr]
- CT: Cloud-Twin
- SP: CB-Spider
- TB: CB-Tumblebug
- DF: CB-Dragonfly

### Test Items
- Provisioning the Dragonfly Agent to a Virtual VM with Tumblebug
- Checking the installed Dragonfly-Agent status
- Fetching gathered monitoring data from Dragonfly

### Test Plan
- Single Cloud-Twin Test: TB/DF - SP - CT
- Multiple Cloud-Twin Test: TB/DF - SP - CT*n
  - if fail: DF - (TB - SP - CT)*n

### Issue
- port mapping between virtual VM's 22 ports(SSH) and real VM's generated ports
- We want to see the virtual VM's SSH Port(22) like real world.

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo @innodreamer @hyokyungk 

>### Issue
>- port mapping between virtual VM's 22 ports(SSH) and real VM's generated ports
>- We want to see the virtual VM's SSH Port(22) like real world.

### TO-BE
- User gets a SSH Port Number from VMInfo and tries connect to the VM with it.

### Handling SSH Port Number in Spider
- Add SSH Port Number in the VMInfo Structure returned by CreateVM/GetVM/ListVM  Call
- VMInfo - KeyValueList - "ssh_port"
```
    {
       "vm" : [
          {
             "IId" : {
                "SystemId" : "a2f03758-3b89-4101-8345-a0caf23915e5",
                "NameId" : "cloudtwin-cloud-5-config-vm-01"
             },
   
      ...

             "KeyValueList" : [
                {
                   "Key" : "ssh_port",
                   "Value" : "31368"
                }
             ],

      ...

```

- Cloud-Twin VM:  generated Port Number
- Other CSPs VM: default 22( fixed)

**Comment by jihoon-seo** [comment]
현재 CB-Spider 에서 리턴하는 `VMInfo` struct 가 다음과 같습니다.

```Go
type SpiderVMInfo struct { // Spider
	VMSpecName   string //  instance type or flavour, etc... ex) t2.micro or f1.micro
	VMUserId     string // ex) user1
	VMUserPasswd string

	IId               common.IID // {NameId, SystemId}
	ImageIId          common.IID
	VpcIID            common.IID
	SubnetIID         common.IID   // AWS, ex) subnet-8c4a53e4
	SecurityGroupIIds []common.IID // AWS, ex) sg-0b7452563e1121bb6
	KeyPairIId        common.IID
	StartTime         time.Time  // Timezone: based on cloud-barista server location.
	Region            RegionInfo //  ex) {us-east1, us-east1-c} or {ap-northeast-2}
	NetworkInterface  string     // ex) eth0
	PublicIP          string
	PublicDNS         string
	PrivateIP         string
	PrivateDNS        string
	VMBootDisk        string // ex) /dev/sda1
	VMBlockDisk       string // ex)
	KeyValueList      []common.KeyValue
}
```

---

[제안 (안)]
Spider, Tumblebug 등에서 각 VM / CM (container machine) 에 대해
`AccessPoint` 와 같은 필드를 이용하는 것은 어떨까요?

예:

1. 22번 포트를 사용하는 VM/CM

```JSON
    {
       "vm" : [
          {
             "IId" : {
                "SystemId" : "a2f03758-3b89-4101-8345-a0caf23915e5",
                "NameId" : "cloudtwin-cloud-5-config-vm-01"
             },
   
      ...

             "AccessPoint" : "123.123.123.123:22"

      ...
}
```

2. 31368번 포트를 사용하는 CM (또는 VM)

```JSON
    {
       "vm" : [
          {
             "IId" : {
                "SystemId" : "a2f03758-3b89-4101-8345-a0caf23915e5",
                "NameId" : "cloudtwin-cloud-5-config-vm-01"
             },
   
      ...

             "AccessPoint" : "123.123.123.123:31368"

      ...
}
```

이렇게 하면, 포트 번호가 22번이든 31368번이든
일관적인 표기, 관리, 활용 등을 할 수 있을 것으로 예상됩니다.

---

`AccessPoint` 는 `PublicIP` 와 포트번호 정보를 포함하므로
`PublicIP` 필드를 `AccessPoint` 필드로 대체하는 방안도 있지만,

struct/API 변경에 따른 다른 프레임워크와의 호환성 문제,
기존까지 공개해 왔던 API 의 중대 변화 등을 고려하면
`PublicIP` 필드는 그대로 두고 `AccessPoint` 필드를 추가하여 활용하는 방안도 있겠습니다.

**Comment by powerkimhub** [comment]
@jihoon-seo 의견 감사합니다. 깔끔하네요^^ 

- 일이 약간 커지겠지만, 수용하겠습니다. 

@dev4unet @hyokyungk @innodreamer 
- 현재는 Server layer에서 일괄 반영 및 제공하도록하겠습니다. 
- 향후, 실제 CSP 기반의 VM들에서도 SSH Port 변경 수요가 생긴다면, 
  그때는 Driver Layer에서 작업이 생길수도 있겠습니다.(참고만 해주세요)

**Comment by powerkimhub** [comment]
### [Develop Guide]

- 반영 작업: VMInfo에 AccessPoint 추가
- 대상 기능: StartVM/ListVM/GetVM

1. Common Driver interface 수정
2. Cloud-Twin: Driver 수정
3. Real CSP: Server-Common-runtime 반영
4. REST API 및 API Docs 반영
5. gRPC 및 Go API 반영 
6. 타 프레임워크 전파: @cloud-barista/cb-tumblebug-maintainer  @cloud-barista/cb-dragonfly-maintainer

**Comment by jihoon-seo** [comment]
제가 예시로 `AccessPoint` 라는 단어를 쓰기는 했으나,
더 적합하고 더 널리 쓰이고 있는 다른 단어가 있을 수도 있습니다.
실제 반영 작업이 시작되기 전에, 발견이 되면 좋을 것 같습니다.. :)

**Comment by powerkimhub** [comment]
## [참고]

### Issue
Cloud-Twin이 제공하는 vVM(virtual VM=Pod-Container)의 경우 
컨테이너 특성상 Dragonfly-Agent 설치 이슈(systemd 등 사용 불가) 존재

### Solution
- Kubernetes privileged mode로 vVM Dockerfile 수정 및 Pod 실행 
- ref) https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privileged

### 대상 OS
- 1차 Ubuntu 18.04.5 LTS
- 향후 필요시 CentOS 추가

**Comment by powerkimhub** [comment]
## [추진 이슈]

### Issue
- vVM 및 VM default SHELL 선택 필요
- 참고: https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1616392263005000 
 
### Solution
- 현재는 bash(/bin/bash)를 기본 환경으로 추진
- 타 shell은 향후 수요가 있을 경우 고민

**Comment by powerkimhub** [comment]
## [추진 이슈] 

### Issue (reported by @Jin-Whee-Park )
- Container(vVM), chroot 환경, golden image 환경등에서 Service start & stop 금지 정책으로 service start 불가
- 참고: http://jpetazzo.github.io/2013/10/06/policy-rc-d-do-not-start-services-automatically/ 
 
### Solution
- /usr/sbin/policy-rc.d 설정 값 수정 (101 => 0)
- 참고: https://stackoverflow.com/a/48782486

**Comment by powerkimhub** [comment]
## 진행현황

> ### [Develop Guide]
> 
> - ~~반영 작업: VMInfo에 AccessPoint 추가~~
> - ~~대상 기능: StartVM/ListVM/GetVM~~
> 
> 1. ~~Common Driver interface 수정~~
> 2. Cloud-Twin: Driver 수정 (#WIP @powerkimhub )
> 3. ~~Real CSP: Server-Common-runtime 반영~~
> 4. ~~REST API~~ 및 API Docs 반영
> 5. gRPC 및 Go API 반영 : (#TODO  @jmleefree CLI 확인도 부탁합니다.)
> 6. 타 프레임워크 전파: @cloud-barista/cb-tumblebug-maintainer  @cloud-barista/cb-dragonfly-maintainer 


## <REST API 시험 방법>
1. Latest version Spider 서버 가동
2. AdminWeb 이용한 Mock Driver 기반 VM 추가 
3. VM 중 SSHAccessPoint 정보 확인: **"SSHAccessPoint" : "4.3.2.1:22"** 

    - REST API  경우 예시

```
$ curl -sX GET http://3.36.93.11:1024/spider/vm -H 'Content-Type: application/json' -d '{ "ConnectionName": "mock-mock-default--connection-config-01"}' |json_pp
{
   "vm" : [
      {
         "PublicIP" : "4.3.2.1",
         "NetworkInterface" : "vm-01_mockni",
         "VMUserPasswd" : "",
         "VMBlockDisk" : "/dev/sda1",
         "PrivateIP" : "1.2.3.4",
         "SecurityGroupIIds" : [
            {
               "NameId" : "sg-01",
               "SystemId" : "vpc-01-delimiter-sg-01"
            }
         ],
         "IId" : {
            "SystemId" : "vm-01",
            "NameId" : "vm-01"
         },
         "SubnetIID" : {
            "SystemId" : "subnet-01",
            "NameId" : "subnet-01"
         },
         "Region" : {
            "Region" : "default",
            "Zone" : ""
         },
         "VpcIID" : {
            "NameId" : "vpc-01",
            "SystemId" : "vpc-01"
         },
         "PublicDNS" : "vm-01..spider.barista.com",
         "ImageIId" : {
            "SystemId" : "mock-vmimage-01",
            "NameId" : "mock-vmimage-01"
         },
         "PrivateDNS" : "vm-01..spider.barista.com",
         "KeyValueList" : null,
         "SSHAccessPoint" : "4.3.2.1:22",
         "VMSpecName" : "mock-vmspec-01",
         "KeyPairIId" : {
            "NameId" : "keypair-01",
            "SystemId" : "keypair-01"
         },
         "VMBootDisk" : "/dev/sda1",
         "VMUserId" : "ec2-user",
         "StartTime" : "2021-03-24T07:06:00.356370607Z"
      }
   ]
}
```

**Comment by powerkimhub** [comment]
- completed.
