### ISSUE TITLE
How to lookup GCP VM image info?

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#339]
요약: GCP 의 `cspImageId` 가 URL 형식이라서 발생하는 현상으로 추정

CC @seokho-son 

Spider 에

[요청]
`GET http://cb-spider:1024/spider/vmimage/https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024`
```JSON
{
  "ConnectionName": "gcp-asia-east1"
}
```

이렇게 요청하면
Spider 에서 404 Not Found 를 리턴합니다.

[응답]
```JSON
{
  "time": "2021-04-05T18:29:16.639955477+09:00",
  "id": "",
  "remote_ip": "127.0.0.1",
  "host": "localhost:1024",
  "method": "GET",
  "uri": "/spider/vmimage/https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024",
  "user_agent": "go-resty/2.4.0 (https://github.com/go-resty/resty)",
  "status": 404,
  "error": "code=404, message=Not Found",
  "latency": 36655,
  "latency_human": "36.655µs",
  "bytes_in": 35,
  "bytes_out": 24
}
```

---

[참고]

Tumblebug 에도 LookupImage 함수를 만들었었습니다. (호출되면 Spider 에 Lookup 요청 보냄)

그런데, Tumblebug 도 동일 현상이 있었습니다. (Tumblebug 이 Spider 를 호출하지 않고 바로 404 Not Found 를 리턴)

[요청]
`GET http://$TumblebugServer/tumblebug/lookupImage/https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024`
```JSON
{
  "connectionName": "gcp-asia-east1"
}
```

[응답]
```JSON
{
  "message": "Not Found"
}
```

그래서, `cspImageId` 를 
GET 요청의 URL 이 아니라
JSON 바디에 넣는 것으로 바꾸니

[요청]
`GET http://$TumblebugServer/tumblebug/lookupImage`
```JSON
{
  "connectionName": "gcp-asia-east1",
  "cspImageId": "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024"
}
```

이 현상이 사라졌습니다. (Tumblebug 이 404 에러를 리턴하지 않고, Spider 를 호출함. 하지만 Spider 가 404 를 리턴함)

**Comment by jihoon-seo** [comment]
현재 상황에서는, string encoding 을 해서 Spider 에 요청하면 된다고 합니다. :)

**Comment by powerkimhub** [comment]
@jihoon-seo @seokho-son 

### 현재 시점의 제안 방법: 
- user input: escape encoding( '/' => '%2F', ' ' => '%20 등') 후 넘김
- FW server: path 전달 받은 후 escape decoding 처리

### 사유 (현재 기준)

[1] GetImage REST API의 이미지 이름을 JSON Body로 옮기려고 생각해 보니,
- Spider의 경우 다른 모든 자원들의 GetXXX 형식(url 형식, '/vpc/:Name') 규칙과 다르게 됩니다. 
- JSON Body로 변경하려면, 추후 시간을 갖고 일괄 변경해야 하겠습니다. 
- 현재 시점에서 이 상황은 피하고자 합니다.  

### 부연 설명

[1] REST 호출시 escape 처리는 일반적일 수 있을 것 같습니다. 
- 대부분 end user가 사용하기 보다는 개발자에 의해 개발되는 도구에 의해 사용되므로. encoding을 해서 넘김.
  - 참고: https://www.werockyourweb.com/url-escape-characters/
- REST path 및 pathparam으로 전달되는 값들 중 사용자가 escape char를 포함 시키는 상황에서는, 동일 문제가 발생할수 있음.

[2] echo에서 escape 처리는 사용자에게 맡기는 정책인 듯.
  - https://github.com/labstack/echo/issues/878 (현재 소스도 같은 정책)

**Comment by powerkimhub** [comment]
- For your convenience: https://www.url-encode-decode.com/
