### ISSUE TITLE
Deny long resource name string from GCP API

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#341]
**What happened**
: 리소스 명칭 길이에 의한 GCP API 거절

**What you expected to happen**
: 가이드가 필요함.. `delimiter` 삭제 가능?

**How to reproduce it (as minimally and precisely as possible)**
: CB-TB로 VM을 자동 생성하다보면, VM의 명칭이 Key이므로 어느정도 길어질 수 있음. CSP 리전 명칭등을 키에 활용하면, 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3' 와 같은 수준으로 명칭이 길어짊 수 있으며, 이 경우 GCP 는 오류를 리턴함.

**Anything else we need to know?**
: 
```
[CB-SPIDER].[ERROR]: 2021-04-06 01:01:17 SecurityHandler.go:153, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/gcp/resources.(*GCPSecurityHandler).CreateSecurity() - googleapi: Error 400: Invalid value for field 'resource.name': 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
More details:
Reason: invalid, Message: Invalid value for field 'resource.name': 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
Reason: invalid, Message: Invalid value for field 'resource.targetTags[0]': 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
 
[CB-SPIDER].[ERROR]: 2021-04-06 01:01:17 CCMCommon.go:823, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateSecurity() - googleapi: Error 400: Invalid value for field 'resource.name': 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
More details:
Reason: invalid, Message: Invalid value for field 'resource.name': 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
Reason: invalid, Message: Invalid value for field 'resource.targetTags[0]': 'gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
```

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by seokho-son** [comment]
gcp-australia-southeast1-gcp3-delimiter-gcp-australia-southeast1-gcp3 는 69개 ~
제한은 60개 ?

**Comment by powerkimhub** [comment]
@seokho-son 

> : 가이드가 필요함.. delimiter 삭제 가능?

- '-delimiter-': 삭제 불가. 
- GCP Resource Naming Guide: 1~63 영문, 대문자 사용불가, '-' 끝 불가 등
  - ref) https://cloud.google.com/compute/docs/naming-resources
  - 추후, CB-Spider Resource Naming Guide 제공 예정.

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo 

- 현재, SG Name의 경우 부득이 Spider 내부에서 `{VPC Name}-delimiter-{SG Name}`와 같이 관리되며,
- 이로인하여, SG Name의 경우 `63-{VPC Name}`이 최대 가능 char 수로, 이는 개선이 필요한 사항이네요.
- 향후, 개선 방안을 마련해보록 하지요.

**Comment by powerkimhub** [comment]
- Tagging before ID enhancement (cf. [v0.4.7](https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.7) )

**Comment by powerkimhub** [comment]
cf. https://github.com/cloud-barista/cb-tumblebug/discussions/554

**Comment by powerkimhub** [comment]
- solved it through https://github.com/cloud-barista/cb-spider/commit/92a4a66b75fe6a6c356224eefaf0d7dd90813156
