### ISSUE TITLE
API for get region mismatch

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#346]
**What happened**
: 
GET Get Cloud Region. 
localhost:1024/spider/region/{{region_name}}

Spider API 문서의 예시에는 아래와 같은 리턴 바디 예시가 있음.
```
{
  "RegionName": "aws-ohio",
  "ProviderName": "AWS",
  "KeyValueInfoList": [
    {
      "Key": "region",
      "Value": "us-east-2"
    }
  ]
}
```
**What you expected to happen**
: 
텀블벅에서 "Key": "region"
을 예상하고 String 비교를 하였으나, Spider는 API 문서 예시와 다르게 대문자를 포함하여 리턴함
"Key": "Region"

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 
API 문서 또는 코드 수정을 통해 일관성을 제공할 필요가 있음. 또는 대소문자에 대한 처리 가이드 필요.

**Any other context**
:

**Comment by powerkimhub** [comment]
- 유사이슈: https://github.com/cloud-barista/cb-spider/issues/189

### [Plan]
- Structure로 Abstraction 시도
- Structure로 통일 불가시, keyValue 활용하는 Driver 내 Syntax check 기능 추가

**Comment by powerkimhub** [comment]
- fix it with https://github.com/cloud-barista/cb-spider/issues/414#issuecomment-968860618
- fix API documents: 
  - https://documenter.getpostman.com/view/9027676/UV5ZBcCw#69405edb-282e-44f7-8df2-bd03a0864c98
