### ISSUE TITLE
[Configure rootfs size when creating a VM?]

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#348]
- ref) https://github.com/cloud-barista/cb-tumblebug/discussions/457

**Comment by powerkimhub** [comment]
### [Goal]
- VM 생성 요청시 rootfs volume Size 변경 기능 추가

### [Plan]
- Check rootfs resize capability of all CSPs 
- If All CSPs are capable, Add size attribute into ReqInfo Structure.
- Task Scope: API, API Runtime, All Drivers, CLI, AdminWeb, ...

**Comment by powerkimhub** [comment]
- 설계 및 개발 가이드 참고
  - [(CB-Spider) VM Root Disk 설정 제공 방안 공유(안)-2021.11.04.pptx](https://github.com/cloud-barista/cb-spider/files/7509505/CB-Spider.VM.Root.Disk.-2021.11.04.pptx)

**Comment by powerkimhub** [comment]
@dev4unet @hyokyungk @inno-cloudbarista @innodreamer 

### [적용대상 및 현황]

|CSP|Status|
|:----|:----:|
|1.  AWS |          진행중 * |
|2. Azure |         진행중(Size제외) *  |
|3. GCP |            완료 |
|4. Alibaba |       완료 |
|5. Tencent |      완료 |
|7. OpenStack | 진행중(Type제외) * |

---

|CSP|Status|
|:----|:----:|
|6. IBM |             적용불가 |
|8. Cloudit |         적용불가 |
|9. NCP |            적용불가 |
|10. KT |             적용불가 |

**Comment by powerkimhub** [comment]
**[GCP/Alibaba/Tencent 적용]**
- https://github.com/cloud-barista/cb-spider/pull/518

<br>

@inno-cloudbarista @hyokyungk (@dev4unet , @innodreamer)
- PR내 구현 조건, 시험 항목 등 참고하시면,
- 일관성 있고 좋을 거 같습니다.

**Comment by powerkimhub** [comment]
**[AWS 적용 / Tencent 개선]**
- https://github.com/cloud-barista/cb-spider/pull/523

**Comment by powerkimhub** [comment]
[issue]
- AWS/GCP/Alibaba/Tencent: return VMInfo에 관련 설정 필요
  - https://github.com/cloud-barista/cb-spider/pull/523#issuecomment-965318564

<br>

- AWS: 현재 규격으로 제공되지 않는 Disk Type 존재
  - https://github.com/cloud-barista/cb-spider/pull/523#issuecomment-965363272

<br>

- Azure: 제공 지역 및 IOPS 제한 등
  - https://github.com/cloud-barista/cb-spider/pull/529#issue-1051678985

<br>

- Azure: 확인 사항
  -  PR 버전에서 reqInfo.RootDiskType = ""인 경우, 기존 버전과 동일하게 CSP 기본 disk type으로 처리되는지요?(@inno-cloudbarista )
  - 변경 전 API를 사용한 많은 시험 프로그램들의 경우 별도 설정 없이 호출되며, 이경우 호환성 제공을 위해서 입니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

관련하여, 추가 질의 드립니다. 

- disk type을 꼭 설정해야 하는 것이 아니라면, 
- 설정을 하지 않으면, CSP가 default로 PremiumSSD로 설정해준다면, 
- "" 요청시 bypass하는 것이 좋을 것 같습니다. 
  - 사유: 향후 Azure에서 default type을 다르게 변경 가능성이 있음
- 항상 설정해줘야 한다면 현재처럼 두시면 되겠습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
넵 알겠습니다. 해당 사항 코드에 반영하겠습니다.

**Comment by powerkimhub** [comment]
[Azure 적용]
- https://github.com/cloud-barista/cb-spider/pull/529

**Comment by powerkimhub** [comment]
- Thanks, @innodreamer 

- [OpenStack 적용]
  - https://github.com/cloud-barista/cb-spider/pull/535

- [OpenStack Root Disk Size 설정 방식]
  - Size 조절시 Volume Creation 옵션으로만 가능
  - Volume 생성 후 Root Disk로 마운트
  - Spec에 기술된 내용은 적용되지 않음

  - ![image](https://user-images.githubusercontent.com/46367962/142332531-897673f5-7ebc-41b2-9cb3-5b42c3550360.png)

- [Volume Creation 여부에 따른 VM 생성 시간 차이] 
  - 단, Farm 환경에 따라 생성 시간 차이가 큼(1분 미만 vs 2~4분)
  - ![image](https://user-images.githubusercontent.com/46367962/142332641-20aa0cb7-ee1e-4eaa-a3ca-328e155dc649.png)
