### ISSUE TITLE
How to trace API changes ans share it to other fws

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#350]
CB-Spider 
https://github.com/cloud-barista/cb-spider/releases/tag/v0.3.7

적용 및 CB-TB 연동 후, CB-TB가 정상적으로 동작하지 않는 문제가 있어서, 
추적하다 보니 Spider에서 API (리턴 키/값 ?)에 변경이 있었던 것 같습니다. (아마, https://github.com/cloud-barista/cb-spider/commit/cffd019344faf4a97f3b8e3816b74df766452edc 커밋)

Region 관련해서 API 리턴 값에 변경이 있는지요?

혹시 API(리턴구조) 등이 변경되고 있다면, 타 FW에 영향이 있으므로
프리릴리스시 (또는 상시) API 변경 사항에 대한 공유가 필요할 것 같습니다.

**Comment by powerkimhub** [comment]
@seokho-son 

> Region 관련해서 API 리턴 값에 변경이 있는지요?

- 근래 API 변경은 없었습니다.
- 오류가 발생했다면, 재현 방법이나 오류메시지, 로그 등을 공유해주시면 확인해보도록 하지요.

- 혹시, TB에서 다음 utility를 사용한다면, path 변경이 영향을 주었을 수도 있겠네요. 
  - 만약, 이 utility를 사용한다면, 향후에는 변경시에 현황을 공유드리지요. 
  - [before] utils/import-info
  - [current] utils/import-drv-region-info
    - ref) https://github.com/cloud-barista/cb-spider/commit/746153edb9c34f8c987922a30b1a0f07a618d4f9

> 혹시 API(리턴구조) 등이 변경되고 있다면, 타 FW에 영향이 있으므로
> 프리릴리스시 (또는 상시) API 변경 사항에 대한 공유가 필요할 것 같습니다.

- API뿐만아니라, 주요 수정 관련 issue 등록시에는 영향받는 FW 멤버들의 name tagging 또는 필요시 slack 공지 등을 통해 사전 공유 중입니다.

**Comment by seokho-son** [comment]
변경된 사항이 없다면, 아마도 버전을 변경해가며 생긴 알 수 없는? 오류인 것 같습니다.
정확한 문제를 파악하지는 못하고, TB에서 이런저런 보완 장치를 하여 문제가 발생하지 않도록 처리해두었습니다. 
감사합니다.
해당 이슈는 Spider API 변경에 의한 이슈가 아니므로, 그리고 변경 사항을 잘 공유해주고 계시므로
Close 하겠습니다.
