### ISSUE TITLE
[Security Group] No Source Address configuration makes security rules to VMs

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#355]
**What would you like to be enhanced**
- Access control of Security Group about VM

**Why is this needed**
- issued by @cloud-barista/cb-tumblebug-maintainer 
- Can  not setup accessible source or destination address to the VMs

**Proposed solution**
- Add source or destination address CIDR features to Security Rules.

**Comment by powerkimhub** [comment]
### [Plan]
- Add a address CIDR attributes of SecurityRules in SecurityHandler
- Task Scope: Driver Common Interface, All Drivers, API, CLI, AdminWeb, ...

**Comment by powerkimhub** [comment]
@dev4unet @hyokyungk @innodreamer @jmleefree 

### 개요
- 부득이 전체 port 개방으로 VM 운영 중 이상한 process가 실행된 사례가 있음
- 24H, WIP 환경 등에서 개방된 API를 통한 무차별 공격 가능성에 불안함
- 해결 방안 중 하나는 Inbound source로 허용 IP 및 대역을 설정하는 것임.
- 그러나, 현재 Spider는 source 설정을 제공하지 않음.
 
- 이에 시급히 Inbonud의 source, Outbound의 destination 정보 설정을 제공하고자 합니다. 
- 대상: 전체 Cloud Driver
- 설정 정보: IP CIDR Block
- 설정 값 예시)
  - IPv4 설정: 0.0.0.0/0, 0.0.0.0/8, 0.0.0.0/16, 0.0.0.0/24, 0.0.0.0/32
  - IPv6 설정: ::/0, ::/8, ::/16, ::/24, ::/32

--- 
### 개발 가이드

- SecurityHandler.go의 SecurityRuleInfo 구조체를 다음과 같이 개선하였습니다.
- 추가되는 API는 없습니다. 
- Inbound Source 및 Outbound Destination에 대한 CIDR 설정을 내려 보내주시기 바랍니다. 
- 각 Cloud Driver SecurityHandler 반영 부탁드립니다.


### [AS-IS]

  ```
  type SecurityRuleInfo struct {
            FromPort   string
            ToPort     string
            IPProtocol string
            Direction  string
            CIDR  string
  }
  ```

### [TO-BE]

  ```
  type SecurityRuleInfo struct {
            FromPort   string
            ToPort     string
            IPProtocol string
            Direction  string
            CIDR  string
  }
  ```

## working process
~~1. add to driver interface~~
2. add to all drivers
3. add to common service function
4. add to REST API and WebAdmin Tool
5. add to gRPC API
6. add to CLI
7. test

--------------

### =============== 현황 분석: AWS / Azure / GCP / Alibaba, 그 외 CSP 분석 생략
## AWS ##
- Inboud source 설정 선택: CIDR 블록, 보안그룹 ID, 접두사 목록
- Outboud destination 설정 선택: CIDR 블록, 보안그룹 ID, 접두사 목록
- Ref) https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html 

![image](https://user-images.githubusercontent.com/46367962/118506612-6ee64a80-b768-11eb-8fb6-43e3983b65a2.png)

 - 참고: Console
 
![image](https://user-images.githubusercontent.com/46367962/118506869-a94fe780-b768-11eb-9551-ce13757bb395.png)

![image](https://user-images.githubusercontent.com/46367962/118506883-ac4ad800-b768-11eb-8bbc-eceaf48cff22.png)


  
## Azure ##
- Inboud, Outboud 둘다 Source, Destination을 설정

![image](https://user-images.githubusercontent.com/46367962/118506957-bc62b780-b768-11eb-9f47-985ca116c192.png)

- Inbound Source 설정 선택: CIDR 블록, Service Tag, Application security group
 
![image](https://user-images.githubusercontent.com/46367962/118507012-cc7a9700-b768-11eb-97c7-bbebd47e85fa.png) 

![image](https://user-images.githubusercontent.com/46367962/118507029-d1d7e180-b768-11eb-9d00-d151e9283738.png)

![image](https://user-images.githubusercontent.com/46367962/118507048-d603ff00-b768-11eb-9c1b-99ae7866d8b6.png)

![image](https://user-images.githubusercontent.com/46367962/118507067-da301c80-b768-11eb-8587-d9bc222db409.png)

- Inbound Destination 설정 선택: CIDR, virtualNetwork, Application security group

![image](https://user-images.githubusercontent.com/46367962/118507269-09df2480-b769-11eb-8319-473edc08b487.png)

![image](https://user-images.githubusercontent.com/46367962/118507280-0cda1500-b769-11eb-92eb-9c6426bce1d3.png)

![image](https://user-images.githubusercontent.com/46367962/118507292-0fd50580-b769-11eb-889a-b810ca042d05.png)

![image](https://user-images.githubusercontent.com/46367962/118507308-12cff600-b769-11eb-9464-de236810a00e.png)

- Outbound Source 설정 선택: CIDR, virtualNetwork, Application security group
- Outboud Destination 설정 선택: CIDR, Service Tab, Application security group



## GCP ##
- Inboud source 설정 선택: CIDR 블록, 소스 태그
- Outboud: destination 설정 선택: CIDR 블록
- Inbound Source

![image](https://user-images.githubusercontent.com/46367962/118507434-3004c480-b769-11eb-9262-edc9af58b102.png)

![image](https://user-images.githubusercontent.com/46367962/118507449-3430e200-b769-11eb-9c8a-cff312b5c88d.png)

![image](https://user-images.githubusercontent.com/46367962/118507458-372bd280-b769-11eb-91c1-4abaf83faa69.png)

- Outbound Destination

![image](https://user-images.githubusercontent.com/46367962/118507505-41e66780-b769-11eb-920c-c3268a9ef7bb.png)

![image](https://user-images.githubusercontent.com/46367962/118507518-46128500-b769-11eb-9f78-eef51c8dd950.png)

 
## Alibaba ##
- Inboud source 설정 선택: CIDR 블록, Security Groups
- Outboud destination 설정 성택: CIDR 블록, Security Groups
- Inbound Source

![image](https://user-images.githubusercontent.com/46367962/118507581-53c80a80-b769-11eb-843d-9dfada885b55.png)

- Outbound Destination

![image](https://user-images.githubusercontent.com/46367962/118507626-5f1b3600-b769-11eb-94e0-5613673d0453.png)

**Comment by powerkimhub** [comment]
- 이미지가 잘 안보이는 게 있네요. 
- 원본을 첨부하오니 필요시 참고하시기 바랍니다. 
 
[CSP별-SG설정정보-2021.04.22.docx](https://github.com/cloud-barista/cb-spider/files/6494737/CSP.-SG.-2021.04.22.docx)

**Comment by powerkimhub** [comment]
ref) https://github.com/cloud-barista/cb-spider/pull/372

## working process
~~1. add to driver interface~~
2. add to all drivers
~~3. add to common service function~~
~~4. add to REST API and WebAdmin Tool~~
~~5. add to gRPC API~~
~~6. add to CLI~~
7. test 
  - Mock Driver: Pass
--------------

**Comment by innodreamer** [comment]
NCP driver에도 CIDR filed가 반영되었습니다.
 : https://github.com/cloud-barista/ncp/pull/29

**Comment by powerkimhub** [comment]
### v0.3.14 시험 결과 참고

- AWS, GCP, Azure, Alibaba, OpenStack 시험 완료
- https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-v0.3.14-test-for-WIP-Integration

**Comment by powerkimhub** [comment]
- GCP 이슈 참고: https://github.com/cloud-barista/cb-spider/pull/384

**Comment by powerkimhub** [comment]
- CloudIt fixed: https://github.com/cloud-barista/cb-spider/commit/8a9cb540823ae656d8afa51e7249c5a921756e76
- All Drivers Completed
