### ISSUE TITLE
CallLog: Need to check the elapsed time of the CSP Call

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#359]
**What happened**
- CSP 자원 제어 API 호출에 소요되는 시간 측정 구간이 CSP  마다 상이함.(특히 VM)

**What you expected to happen**
- CSP 자원 제어에 소요되는 시간 측정 구간이 의미상 동일해야 함. 

**Proposed solution**
- 측정 대상 자원: 
  - 공통자원: VPC/Subnet, Security Group, VM KeyPair, VM, VM Image, VM Spec 
  - 추가자원: StartVM()시에 필요한 다른 자원 제어 시에 추가로 호출하는 자원 호출 정보 추가 가능
- 측정 방법
  - 단일 자원에 대한 단일 API 호출 시간
  - VM의 경우 이슈가 존재할 수 있음.

**Comment by powerkimhub** [comment]
### [현황 분석 및 이슈]

#### [드라이버별 확인 사항]  @dev4unet @hyokyungk @innodreamer 
- StartVM() CallLog elapsed time 구간 확인
  - Azure VM의 경우 'WaitForCompletionRef' 호출을 포함하여 측정하고 있음. 
    - 그외 CSP는 API 호출 시간만 측정하고 있음.
  - CSP별 제공하는 WaitFor() 종류 함수 동작 확인 필요:
    - VM의 상태가 'running'일때까지 기다리는 건지?
    - VM에 요청한 API 동작만 완료될때까지 기다리는 건지?

- VM외에 다른 자원도 elapsed time도 드라이버별로 재점검 필요

#### AWS 참고
- HisCall StartVM 측정 구간

```
        runResult, err := vmHandler.Client.RunInstances(input)
        callLogInfo.ElapsedTime = call.Elapsed(callLogStart)
        cblogger.Info(runResult)

        ...

        WaitForRun(vmHandler.Client, newVmId)
        ...

func WaitForRun(svc *ec2.EC2, instanceID string) {
        cblogger.Infof("EC2 ID : [%s]", instanceID)

        input := &ec2.DescribeInstancesInput{
                InstanceIds: []*string{
                        aws.String(instanceID),
                },
        }
        err := svc.WaitUntilInstanceRunning(input)
        if err != nil {
                cblogger.Errorf("failed to wait until instances exist: %v", err)
        }
        cblogger.Info("=========WaitForRun() 醫~E猷~L")
}

```

#### GCP 참고
- HisCall StartVM 측정 구간

```
        callLogStart := call.Start()
        op, err1 := vmHandler.Client.Instances.Insert(projectID, zone, instance).Do()
        callLogInfo.ElapsedTime = call.Elapsed(callLogStart)

        ...

        vmStatus, _ := vmHandler.WaitForRun(irs.IID{NameId: vmName, SystemId: vmName})  //  until "Running" status

```
- 이슈:  WaitForRun()를 통해서 'Running' status까지 기다려야 하는 이유 확인 필요
  - 과정에서 에러 핸들링이 어렵고, loss가 발생하고 있음. 
  - 관련 이슈: https://github.com/cloud-barista/cb-spider/issues/340
  - 아래 그림 GCP Starting 상태처럼, 'Provisioning staging' 등 현재 상태를 반환하면 문제가 있었는지 확인 필요

#### Azure 참고
- HisCall StartVM 측정 구간

```
        start := call.Start()
        future, err := vmHandler.Client.CreateOrUpdate(vmHandler.Ctx, vmHandler.Region.ResourceGroup, vmReqInfo.IId.NameId, vmOpts)
        if err != nil {
                LoggingError(hiscallInfo, err)
                return irs.VMInfo{}, err
        }
        err = future.WaitForCompletionRef(vmHandler.Ctx, vmHandler.Client.Client)
        if err != nil {
                LoggingError(hiscallInfo, err)
                return irs.VMInfo{}, err
        }
        LoggingInfo(hiscallInfo, start)

```

#### Alibaba 참고
- 이슈: HisCall VPCHandler만 처리하고 있음.
- 이슈: EC2 문자열 제거 필요


#### OpenStack 참고
- HisCall StartVM 측정 구간

```
        start := call.Start()
        server, err := servers.Create(vmHandler.Client, createOpts).Extract()
        if err != nil {
                LoggingError(hiscallInfo, err)
                return irs.VMInfo{}, err
        }
        LoggingInfo(hiscallInfo, start)

```

#### CloudtIt 참고
- HisCall StartVM 측정 구간

```
        start := call.Start()
        creatingVm, err := server.Start(vmHandler.Client, &requestOpts)
        if err != nil {
                LoggingError(hiscallInfo, err)
                return irs.VMInfo{}, err
        }
        LoggingInfo(hiscallInfo, start)

```

#### NCP 드라이버 단에서 자체 확인

----------

# ---------------------- 참고
![image](https://user-images.githubusercontent.com/46367962/117630488-32d64700-b1b6-11eb-97bc-fc432119ae35.png)

**Comment by dev4unet** [comment]
@powerkimhub 
AWS / GCP / Alibaba의 경우 이전에 문의 했을 때 각 메소드별로 내부에서 처리하는 로직들이 상이하고 호출되는 API들이 많은데 모든 API마다 호출해야 할 지 함수 시작전과 종료에서 호출해야 할지 문의 했었습니다.
당시에 메인 함수의 용도에 맞는 API 하나에 대해서만 호출하는 것으로 하고 향후 개선하는 것으로 얘기가 되어서 해당 함수명 이름에 맞는 API하나의 호출만 체크하고 있습니다.
예를 들어, **VM생성의 경우 VM생성 함수 호출전에 체크를 시작해서 API 호출이 끝나면 체크를 종료합니다.**
그 뒤의 런닝 상태까지 대기 하거나 다른 API 호출 등은 체크하고 있지 않고 있습니다.

[런닝 상태를 체크하는 이유]
VM이 런닝되지 않으면 VM의 정보를 조회할 수 없기 때문에 그렇습니다.
VM 생성 후 VM의 id만 리턴하는 것이 아닌 VM생성 요청 후 VM정보 조회에 필요한 정보를 리턴하도록 되어 있기 때문에 VM 상태를 체크해야 하는데 VM이 런닝되기전에 정보 조회 요청이 들어가면 에러가 발생합니다.
그래서 VM의 상태가 완전히 구동될 때까지 대기 후 VM의 정보를 조회해서 리턴 값을 처리하고 있습니다.
	vmInfo, errVmInfo := vmHandler.GetVM(irs.IID{NameId: vmName, SystemId: vmName})

**Comment by powerkimhub** [comment]
@dev4unet 

- 현황 공유 감사드립니다. 

- StartVM() Interface 반환 값을 아이디와 상태 정보만 반환했었어야 하는데... 라고 후회 중입니다. 
  - 현재는 StartVM()이 복잡해질 수 밖에 없네요.
  - 사용자가 이런식으로 쓰면, 됐을 텐데요
    - result=StartVM() -> Loop: if(GetStatus(result.vmid)!='running') -> GetVM(result.vmid)
  - 현재는 TB에서 사용 중이어서  바꾸기가 부담스러운 상황이네요.
- 일단, CSP별 현황 파악되시면 정보 공유 부탁드립니다. 
- 전체 현황 파악 후에 방안을 마련 해보도록하겠습니다.

**Comment by powerkimhub** [comment]
@dev4unet 

- 넵, 감사합니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 

Azure, OpenStack, Cloudit 드라이버의 StartVM() elapsed time 관련 내부 로직을 전리해 공유드립니다.
간단하게 요약하자면 OpenStack, Cloudit 모두 VM 생성 요청을 기준으로만 elapsed time 측정하며,
VM 프로비저닝 후 후처리 작업 (Public IP 연동, ssh user 생성 등)을 위해서 VM이 active 상태가 될 때까지 별도의 대기 로직이 주가되어 있는 상태입니다.

[Azure]
* elapsed time에 API 호출 응답 시간 및 VM 프로비저닝 시간까지 대기
* WaitForCompletionRef 함수를 통해 VM 생성이 완료되기까지 대기
* elapsed time에 API 호출 시간을 포함해 VM 생성 완료 시간까지 포함

[OpenStack]
* elapsed time에 API 호출 응답 시간만 포함
* OpenStack의 경우  servers.Create() 함수는 API 동작만 완료될 때 까지 대기
* OpenStack에서 Public IP 할당을 위해서 VM이 Active 상태(Running 상태와 동일)가 될 때까지 대기
* VM 생성 후 Public IP 할당
* VM 프로비저닝 관련 후처리 작업(Public IP 할당) 후 VM 정보를 조회해서 리턴

[Cloudit]
* elapsed time에 API 호출 응답 시간만 포함
* Cloudit의 경우 server.Start() 함수는 API 동작만 완료될 때 까지 대기
* VM 생성 후 상세 VM 정보 조회를 하기 위해서는 VM 프로비저닝이 완료될 떄까지 대기 필요
* VM 생성 API 후 Private IP가 할당될 때까지 for 루프를 통해 체크
* VM 프로비저닝 완료 시 VM 정보를 조회해서 리턴

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 확인 후 방안 마련하도록 하겠습니다. 
- 감사합니다.

**Comment by powerkimhub** [comment]
@dev4unet  @hyokyungk @inno-cloudbarista @innodreamer 

다음과 같이 2가지로 분리하여 마무리 하도록 하겠습니다. 
(PR도 분리해서 추진해주시기 바랍니다. )
(대상 및  반영 시기 확인 해주시기 바랍니다.)

### 1. CallLog 처리
- **대상: Alibaba, Azure 수정 필요,** 
- 다음 링크 참고, 수정 완료 후 링크에 반영
  - https://github.com/cloud-barista/cb-spider/wiki/What-happens-when-call-StartVM()-for-each-Cloud-Driver
- **반영 시기: ASAP( ~5/14)**

### 2. Waiting Loop 유무 및 개선
- 현재처럼 유지: 반환 되는 VM 정보를 TB에서 잘 활용중이라고 합니다. 
- 에러 처리 개선, 에러 메시지 제공 개선 등은 필요
  - **대상:  Alibaba, Cloudit, GCP, OpenStack 등 자체 Waing Loop 사용 Driver**
  - https://github.com/cloud-barista/cb-spider/issues/340 참고
  - **반영 시기: 5/21(금)**
- 향후, Waiting Loop 파트 제거 필요시 비동기 API 추가 예정입니다.
  - 예시) CreateVM(vmReqInfo VMReqInfo) (VMStatusInfo, error)
  - 반영시기: 행사 이후 미정(못할수도...)

**Comment by innodreamer** [comment]
@powerkimhub NCP driver의 경우, StartVM() 실행시, 구동되는 과정에서 WaitToGetInfo() 라는 function을 이용해서 VM status가 "Creating" / "Booting" 일때는 계속 기다리다 "Running" 상태일때 GetVM()으로 VM info를 가져옵니다.

참고로, VM termination 시에는 TerminateVM()이 실행된 후 "Suspended" / "Terminating" 상태가 완전히 끝날때까지 기다렸다가 (termination이 완료되면) VM에 mapping 되어 있던 public IP를 반납합니다. Waiting이 없이 반납하면 때때로 error가 발생되어서요.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 

Azure 드라이버 수정사항을 적용해 PR 요청을 올렸으니, 확인 부탁드리겠습니다.
https://github.com/cloud-barista/cb-spider/pull/366

**Comment by powerkimhub** [comment]
@inno-cloudbarista

- 수고많으셨습니다.

**Comment by powerkimhub** [comment]
@dev4unet  @hyokyungk @inno-cloudbarista @innodreamer 

### 1. CallLog 처리
- 링크 업그레이드:  https://github.com/cloud-barista/cb-spider/wiki/StartVM-and-TerminateVM-Main-Flow-of-Cloud-Drivers
- StartVM flow를 좀더 구체화 하고, TerminateVM flow를 추가하였습니다. (issued by @inno-cloudbarista)
- Alibaba, CloudIt, OpenStack 수정 필요합니다.  (링크 Etc 참고)
- **반영 시기: ASAP( ~5/14)**

과정에서, @powerkimhub이 다음 내용을 소스 반영하였습니다. 
문제가 없는 지 검토부탁드립니다. 

- AWS: TerminateVM
  - SystemID를 얻기위한 GetVM() 삭제하고 입력 인자로 설정
- Azure: TerminateVM
  - Calllog EndTime 위치 수정

### 2. Waiting Loop 유무 및 개선
- 현 이슈에서는 다루지 않고, 아래 이슈에서 향후 개선
  - https://github.com/cloud-barista/cb-spider/issues/340

**Comment by powerkimhub** [comment]
Fixed it.
- Azure: https://github.com/cloud-barista/cb-spider/pull/366
- OpenStack: https://github.com/cloud-barista/cb-spider/pull/368
- CloudIt: https://github.com/cloud-barista/cb-spider/pull/369
- cf) https://github.com/cloud-barista/cb-spider/wiki/StartVM-and-TerminateVM-Main-Flow-of-Cloud-Drivers
