### ISSUE TITLE
[AdminWeb] no server address set in Container Env.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#363]
**What happened**
- AdminWeb에서 사용하는 Spider Server 주소 설정이 안되어 있음.
-  ref) https://github.com/cloud-barista/cb-larva/issues/89#issuecomment-837901268

**What you expected to happen**
: 

**Environment**
- server in Container environment

**Comment by jihoon-seo** [comment]
I am working on this. 😊
