### ISSUE TITLE
Check for duplicated server.Get() calls

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#371]
**What would you like to be enhanced**
- StartVM() 성능 개선을 위해서 불필요한 server.Get(vm) 호출인지 확인 필요 

**Why is this needed**
- StartVM() 성능 개선 

**Proposed solution**
- 중복 호출이라면 불필요한 server.Get(vm) 삭제

-------
### 세부설명

아래 CloudIt:StartVM()에서,
145line에 도달했을 경우에 121 line for loop의 마지막 123 line: server.Get() 호출의 반환 정보와
145 line 호출로 얻은 정보가 같을 것 같습니다. 

```
121         for {
122                 // Check VM Deploy Status
123                 vmInfo, err := server.Get(vmHandler.Client, creatingVm.ID, &requestOpts)
124                 if err != nil {
125                         LoggingError(hiscallInfo, err)
126                         return irs.VMInfo{}, err
127                 }
128
129                 if vmInfo.PrivateIp != "" && getVmStatus(vmInfo.State) == irs.Running {
130                         ok, err := vmHandler.AssociatePublicIP(creatingVm.Name, vmInfo.PrivateIp)
131                         if !ok {
132                                 LoggingError(hiscallInfo, err)
133                                 return irs.VMInfo{}, err
134                         }
135                         break
136                 }
137                 time.Sleep(1 * time.Second)
138                 curRetryCnt++
139                 if curRetryCnt > maxRetryCnt {
140                         cblogger.Errorf(fmt.Sprintf("failed to start vm, exceeded maximum retry count %d", maxRetryCnt))
141                         return irs.VMInfo{}, errors.New(fmt.Sprintf("failed to start vm, exceeded maximum retry count %d", maxRetryCnt)    )
142                 }
143         }
144
145         vm, err := server.Get(vmHandler.Client, creatingVm.ID, &requestOpts)

```

**Comment by inno-cloudbarista** [comment]
@powerkimhub 

순서 상으로는 VM이 프로비저닝이 완료되어 Running 상태에 도달했을 때 순서는 아래와 같습니다.

(1) vmInfo, err := server.Get(vmHandler.Client, creatingVm.ID, &requestOpts)

(2) ok, err := vmHandler.AssociatePublicIP(creatingVm.Name, vmInfo.PrivateIp)
  > VM 상태에 새롭게 PublicIP가 자동으로 할당됨
  > (1)번에서 가져온 vmInfo 정보 (+신규 Public IP 정보)
  
(3) vm, err := server.Get(vmHandler.Client, creatingVm.ID, &requestOpts)
  > (2)번에서 추가된 Public IP 정보를 포함한 VM 정보 다시 조회

PublicIP를 할당하기 위해서 for loop 를 벗어나 한번 더 VM 정보를 조회하는 로직이니,
중복 로직과는 별도의 로직이라서 삭제 시 Public IP 정보가 누락되어 표현될 것 같습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 아, 그러네요. 
- 꼭, 있어야 하겠네요. 
- 상세 설명  감사드립니다~ 👍
