### ISSUE TITLE
[Need to enhance Security Group source filter of GCP]

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#382]
**What would you like to be enhanced**
- GCP 제공 특성상 Security Group Source 설정 관련 이슈가 있음.

**Why is this needed**
- 잠재적인 오류 상황이 존재함

**Proposed solution**
- 잠재적인 오류 상황 해결.

**Relational info**
- https://github.com/cloud-barista/cb-spider/pull/381
- https://cloud-barista.slack.com/archives/DLW5NFRV3/p1621931328010900
- https://cloud-barista.slack.com/archives/DLW5NFRV3/p1621931380011300
- https://cloud-barista.slack.com/archives/DLW5NFRV3/p1621931599014000

**Comment by jihoon-seo** [comment]
왜인지, Slack 링크들이 안 들어가지네요..
![image](https://user-images.githubusercontent.com/46767780/119635080-4b995a80-be4e-11eb-808a-d23a8a484e79.png)

**Comment by powerkimhub** [comment]
@jihoon-seo 

- 혹시, slack이 안깔린 환경인가요?
- 음.. 왜그럴까...

**Comment by powerkimhub** [comment]
@jihoon-seo 

- 이런, 개톡이였네요^^
- 다른 방법으로 공유하겠습니다

**Comment by powerkimhub** [comment]
- GCP 이슈 참고: https://github.com/cloud-barista/cb-spider/pull/384

**Comment by powerkimhub** [comment]
- 추가 이슈: https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1624515176154500
  -[GCP] VM 생성시 SG 2개 설정의 경우 오류 발생

**Comment by powerkimhub** [comment]
> * 추가 이슈: https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1624515176154500
>   -[GCP] VM 생성시 SG 2개 설정의 경우 오류 발생

- Security Group 입력 값 오류임
  - 기존: "m-gcp-sg001-in,m-gcp-sg001-out"
  - 교정: "m-gcp-sg001-in", "m-gcp-sg001-out"

**Comment by powerkimhub** [comment]
- 다음 이슈로 reopen
  - https://github.com/cloud-barista/cb-spider/issues/595
