### ISSUE TITLE
"CIDR block is malformed" when creating AWS SG

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#386]
**What happened**
: 
Tumblebug 을 통해서 아래와 같이 SG 생성 시도를 했습니다.
```JSON
                                "firewallRules": [
                                        {
                                                "FromPort": "1",
                                                "ToPort": "65535",
                                                "IPProtocol": "tcp",
                                                "Direction": "inbound"
                                        },
                                        {
                                                "FromPort": "1",
                                                "ToPort": "65535",
                                                "IPProtocol": "udp",
                                                "Direction": "inbound"
                                        },
                                        {
                                                "FromPort": "-1",
                                                "ToPort": "-1",
                                                "IPProtocol": "icmp",
                                                "Direction": "inbound"
                                        }
                                ]
```

그랬더니, 이러한 에러 메시지가 떴습니다. (AWS => Spider => Tumblebug)
```
InvalidParameterValue: CIDR block is malformed\\n\\tstatus code: 400, request id: e038d6d7-0bd6-438d-8f2a-3606ed71bd7f
```

AWS 콘솔에 가서 확인해 보면
SG 는 만들어졌는데
인바운드 규칙에는 아무 것도 등록되어 있지 않습니다.
![image](https://user-images.githubusercontent.com/46767780/119771124-25c89000-bef8-11eb-8592-91dabadd81bc.png)

Spider AdminWeb 에서 확인해 보면
Spider meta DB 에는 등록되지 않았습니다.
![image](https://user-images.githubusercontent.com/46767780/119771180-3d077d80-bef8-11eb-9d88-261085dd999c.png)
![image](https://user-images.githubusercontent.com/46767780/119771206-47c21280-bef8-11eb-9ecc-5d035c0ccc97.png)

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by jihoon-seo** [comment]
Tumblebug 에서 CIDR 을 명시하지 않아서 발생한 오류입니다.

다만, (Tumblebug 또는 사용자가) Spider 에 올바르지 않은 (예: CIDR 을 명시하지 않은) 요청을 하면
CSP 에 SG 를 만들지 말고
Spider 단에서 오류를 반환하는 것이 더 좋아 보입니다. 😊

**Comment by powerkimhub** [comment]
@jihoon-seo 

- 아직 gcp가 반영이 안된 상태이어서 별도 공지 하지 않은 상태입니다. 
- 공지 후 시험 진행해보시기 바랍니다.
- 하위 호환성을 위해서 'CIDR' 별도 입력 없으면(예전처럼) default '0.0.0.0/0'으로 설정 예정입니다. 
- 활용에 참고하시기 바랍니다.

**Comment by powerkimhub** [comment]
- CIDR 입력 없는 경우 default 설정 0.0.0.0/0으로 설정하도록 반영되었습니다. 
- 시험 시나리오 및 결과 참고하시기 바랍니다. 
  - https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-v0.3.14-test-for-WIP-Integration
