### ISSUE TITLE
register a name with whitespace, but can't delete it.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#394]
**What happened**
- Name으로 whitespace가 입력되어 delete가 되지 않는 증상
- 사례) credential 정보 삭제 불가 이슈: https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1622683877061800 

**What you expected to happen**
- 입력 정보에 대한 trim 수행으로 문제 예방

**Comment by seokho-son** [comment]
@powerkimhub trim 보다는 허용하지 않도록 처리하는 것이 어떨까요

**Comment by powerkimhub** [comment]
@seokho-son 

- Thanks.
- 웹도구 입력시 모르고 space가 따라 들어오는 경우이며, 이는 사용자의 의도가 아니라 조작 실수라고 생각됩니다. 
   - 의도: "crdential-01"
   - 실수: "credential-01        "
- 이런 종류의 실수는 의도대로 공백을 제거 후 처리해주는 것도 나쁘지 않아 보입니다. 
- 입력되는 모든 정보에 대해 공백을 제거해서 일관성만 유지해준다면, 다른 문제는 없어 보입니다. 
- 어떤 종류의 whitespace까지 trim 처리를 해줄 것인지는 구현 시에 고민 예정입니다.
  - 아마도: '\t', '\n', '\v', '\f', '\r', ' '
- 관련 예시:
  - 브라우져 입력창에 test             와 같이 공백을 추가해서 입력해도 공백이 없는 test로 찾아줌.

**Comment by seokho-son** [comment]
실수: "credential-01 " 로 입력을 했는데, 
내부적으로 정상 처리되도록 하는 경우,

사용자가 오타를 인지하지 못하고, 계속 "credential-01 " 로 조회하려고 할 수도 있을 것 같습니다. 
(CB-TB의 경우는 조금 다른 것이.. name으로 생성 요청을 하지만, id를 생성하여 오브젝트에 할당하고, 이후 오브젝트 조작을 위해서는 id만 사용하도록 합니다.)

**Comment by powerkimhub** [comment]
@seokho-son 

- Name 뿐만 아니라 value에도 값으 뒤에 space는 일반적이진 않는 사용입니다. 
- 다음 사례를 봐도, 입력 값에 space가 포함되어 있는 지를 모르고 있는 상태입니다. 
  - https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1622683877061800 
- 일단, spider에서는 생성 요청시의 name 키의 양끝 공백 문자열은 trim 처리로 추진해보겠습니다.

**Comment by powerkimhub** [comment]
- string type 적용 : 입력 인자가 문자열인 경우 emptiness와 TrimSpace처리
  - https://github.com/cloud-barista/cb-spider/commit/8a085947a952db835cb378dbfa4fc5fbf83f5de5
