### ISSUE TITLE
Time to revisit VPC and VNet, ...

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#401]
### [They call it]

- AWS: VPC 
- AZURE: VNET
- Alibaba: VPC
- GCP: VPC Network 
- Openstack: Virtual Network

**Comment by inno-cloudbarista** [comment]
1.  VPC Service 출시 시기
  - 2019년 06월 vpc gen 1 출시 (2021년 02월 서비스 종료)
  - 2019년 10월 vpc gen 2 출시 

2. IBM의 VPC Service 계획

3. Classic 대비 VPC 제공 리전

 - VPC 제공 리전: vpc의 리전은 7개
	dallas, Frankfurt, london, osaka, sydney, tokyo, toronto, washington

 - Classic 제공 리전: 46개
		- NA-West : 
                                sanjose 3개
		- NA-South :
				dallas6개, mexico 1개
		- NA-East : 
				montreal 1개, toronto3개, washington 4개
		- South America:
				sao paulo 3개,
		- Europe: 
				london 4개, Frankfurt3개, amsterdam 2개, paris 1개, milan 1개
		- Asia-Perdific:
				chennai 1개, hongkong 1개, osaka 3개, seoul 1개, singafore 1개, sydney 4개, tokyo 3개 

4. VLan vs VPC 사용 비용
 - VPC : VPC 당 사용료는 없지만, virtaulServer당 floating ip 1달러
 - Vlan: 처음 생성되는 VLAN 사용시 사용료 없음. 그러나 사용자가 VLAN 생성시 25달러과금 인스턴스당 public IP비용 없음

5. SDK 이슈
  - VPC gen2 : 1.0 에서 0.7로 롤백하는 이슈 (https://github.com/IBM/vpc-go-sdk#using-the-sdk)
  - Classic Infra https://github.com/softlayer/softlayer-go/issues 
 
@powerkimhub

**Comment by powerkimhub** [comment]
by @dev4unet 

### [About GCP VPC]
- VPC 관리 모드
  - Global 관리: Region 구분 없는 전역에 생성 및 관리
  - Custom 관리: Region 별로 VPC 생성 및 관리

- Handling in Spider
  - VPC 초기 제어 방법
    - 그 시절 Go API로는  Global 방법만 가능(포탈은 Custom도 가능)
    => Global로 생성 및 관리하고, Region을 태깅 하여 구분했었음

  - VPC 현재 제어 방법
    - 클래식(?) 서비스 종료 시점 쯤 Go API에서도 Custom 방식 제공
    => 멀티 리전 생성 옵션 해제 및 Custom 방식으로 VPC 및 Subnet 생성 및 관리

- VPC CIDR 관련
  - VPC 생성시 CIDR 제공하지 않음.
  - Subnet CIDR만 제공

**Comment by powerkimhub** [comment]
- AWS / GCP / Alibaba / Tencent: 현재 VPC 기반 서비스 제공

**Comment by powerkimhub** [comment]
@hyokyungk  ( @dev4unet @innodreamer )

```
VPC 이슈 관련하여, 
제공해주신 자료 및 추가 분석을 통하여 2차례 정도의 내부 협의 회의를 진행하였습니다.
협의 결과 및 분석 자료를 공유드리오니 참고해주시기 바랍니다. 
```

### [이슈 및 협의 결과]
- [이슈] IBM Cloud Driver 구현 모델: Classic or VPC ?
  - VPC 기반 구현 선추진 ( @hyokyungk : 추가 이슈 발생 시 공유해주시면 감사하겠습니다. )
  - VPC 기반 구현 완료 후 Classic 추진 여부 재점검

- [이슈] Network 자원 용어: VPC vs VNet ?
  - CB-Spider 계층: VPC 명칭 사용
  - Tumblebug 이상 계층: TB 계층에서의 자원 관리 형상 등 추가 세미나 및 협의 후 결정

### [참고: VPC 분석 및 협의 자료]
- VPC 개요 및 세부 분석 자료는 다음을 참고하시기 바랍니다.
- [(CB-Spider)VPC-vs-VNet-2021.07.19.pptx](https://github.com/cloud-barista/cb-spider/files/6840352/CB-Spider.VPC-vs-VNet-2021.07.19.pptx)
- 급하시면, 54-59page 위주로 참고하시면 되겠습니다.
