### ISSUE TITLE
[Driver Interface] Confused XXXVMSpec() usage with unuseful region arg.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#417]
**What would you like to be enhanced**

- 예를 들면, 다음과 같이 ListVMSpec(Region string)에 넘겨지는 Region 인자 값이,
- CSP에 따라 region 값일 수도 있고, zone 값이어야 하 수도 있음.
    ```
        // Region: AWS=Region, GCP,Tencent=Zone, Azure=Location
        ListVMSpec(Region string) ([]*VMSpecInfo, error)
    ```

<br>

- 사실, driver의 VMSpecHandler는 이미 RegionInfo를 매달고 있으므로, 
- CSP마다 사용하는 필요한 정보를(filter 값을, region | zone)  알아서 선택적으로 활용할 수 있음.(사례: GCP)

- related Interface

  ```
  VMSpecHandler.go:       ListVMSpec(Region string) ([]*VMSpecInfo, error)
  VMSpecHandler.go:       GetVMSpec(Region string, Name string) (VMSpecInfo, error)
  VMSpecHandler.go:       ListOrgVMSpec(Region string) (string, error) 
  VMSpecHandler.go:       GetOrgVMSpec(Region string, Name string) (string, error)
  ```

**Comment by powerkimhub** [comment]
cf) https://github.com/cloud-barista/cb-spider/pull/415

**Comment by powerkimhub** [comment]
@dev4unet @hyokyungk @inno-cloudbarista @innodreamer 

**[대상]**
- 모든 드라이버

**[Plan]**
- 다음 인터페이스를 
```
VMSpecHandler.go:       ListVMSpec(Region string) ([]*VMSpecInfo, error)
VMSpecHandler.go:       GetVMSpec(Region string, Name string) (VMSpecInfo, error)
VMSpecHandler.go:       ListOrgVMSpec(Region string) (string, error) 
VMSpecHandler.go:       GetOrgVMSpec(Region string, Name string) (string, error)
```

- 다음처럼 변경 예정입니다.(Region input 인자 삭제)
```
VMSpecHandler.go:       ListVMSpec() ([]*VMSpecInfo, error)
VMSpecHandler.go:       GetVMSpec(Name string) (VMSpecInfo, error)
VMSpecHandler.go:       ListOrgVMSpec() (string, error) 
VMSpecHandler.go:       GetOrgVMSpec(Name string) (string, error)
```

- 반영 작업 동안 build 오류 예방을 위해서 다음 순으로 진행하고자 합니다. 
  - (1) 모든 driver에서 Region input 인자 사용 부분을 connection에 매달린 정보 활용하도록 수정
  - (2) 이후 Driver common interface 수정 및 드라이버 일괄 적용

- Driver별로 추진 부탁 드립니다. 
- 1차 목표는 11/9일 입니다.
- 이미 반영이 된 Driver는 현황 파악 위해 댓글 부탁 드립니다.

**Comment by innodreamer** [comment]
일단 국내 driver에서의 현황을 말씀드리면 아래와 같습니다.
- NCP : 두가지 방식을 혼용해서 사용
- NCP VPC : 두가지 방식을 혼용해서 사용
- KT Cloud : ListVMSpec(), GetVMSpec()에는 보완 완료됨. ListOrgVMSpec(), GetOrgVMSpec()은 보완되지 않음.

11/8(월)까지 적용 완료 예정입니다.

**Comment by dev4unet** [comment]
@powerkimhub 
Tencent는 파라메터 정보를 이용하지 않기에 수정  사항 없으며 AWS / Alibaba / GCP는 수정해서 PR 했습니다.

**AWS** - Zone기반
- API는 Zone기반으로 구현되어 있으며 일부 로그 등에 사용된 파라메터의 Region 이용 부분을 세션의 Region으로 대체

**Alibaba**
- 파라메터의 Region 대신 세션의 Region으로 대체

**GCP** - Zone기반
- GetVMSpec()의 리턴 값에 사용된 파라메터의 Region 값 대신 세션의 Region 값으로 대체

**Tencent** - Zone 기반
- 이미 Zone기반으로 구현되어 있어서 변동 사항 없음

**Comment by powerkimhub** [comment]
### [적용 현황]
1.  AWS:          반영완료
2. *Azure:         반영예정
3. GCP:            반영완료
4. Alibaba:       반영완료
5. Tencent:       확인완료
6. IBM:             확인완료
7. *OpenStack: 반영예정
8. *Cloudit:         반영예정
9. *NCP:            반영예정
10. KT:             확인완료

**Comment by powerkimhub** [comment]
- Azure/OpenStack/Clooudit: https://github.com/cloud-barista/cb-spider/pull/510

**Comment by innodreamer** [comment]
@powerkimhub KT Cloud driver에서 반영되었습니다.

https://github.com/cloud-barista/ktcloud/pull/37

**Comment by innodreamer** [comment]
@powerkimhub NCP driver에서 반영 완료되었습니다.
https://github.com/cloud-barista/ncp/pull/41

KT Cloud와 NCP driver에서 해당 region parameter가 포함된 상태로 call하는 부분이 있어서 common interface가 변경된 후 자체적으로 다시 한번 보완하겠습니다.

**Comment by powerkimhub** [comment]
@dev4unet @inno-cloudbarista @innodreamer 

- 최종 반영 및 시험 완료하였습니다. 
  - https://github.com/cloud-barista/cb-spider/commit/67d9ce5196961b5578e66806b15f63e0e9931b7f

- 샘플링 테스트 완료: Mock, AWS, GCP, Azure, Alibaba, OpenStack
