### ISSUE TITLE
Bug: GET aws publicip with invalid `eipalloc` ID returns an empty JSON object, not an error message

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#43]
HTTP req:
GET `{{spider_ip}}:{{spider_port}}/publicip/{{spider_publicipId}}?connection_name={{connection_name}}` with invalid `{{spider_publicipId}}`
(e.g. `{{spider_publicipId}}` that does not exist)

---

HTTP res:
Expected:
```JSON
{
    "message": "InvalidPublicIP.NotFound: The public IP 'eipalloc-081849160f2b98917' does not exist\n\tstatus code: 400, request id: 1a4b8bf9-2079-4c82-b549-64991b8afd4d"
}
```

What actually got:
```JSON
{
    "Name": "",
    "PublicIP": "",
    "OwnedVMID": "",
    "Status": "",
    "KeyValueList": null
}
```

**Comment by powerkimhub** [comment]
Thanks for your patch!!
https://github.com/cloud-barista/cb-spider/pull/44
