### ISSUE TITLE
After StartVM(), User want to immediately log in to the VM with cb-user@ssh

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#436]
**What would you like to be enhanced**

```
급하신 분들은 맨 아래 결론 부분을 바로 참고해주시기 바랍니다^^
```

###  [StartVM() Return 상태 점검 필요]
  - StartVM()이 return을 한 시점에 **SSH Daemon이 서비스 준비가 안되어 있는 경우**가 발생할 수 있음.
  - 이는 다음과 같은 유사 이슈들을 발생시키고 있음. 
    - https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1624579894163800?thread_ts=1624517128.159600&cid=CLFCLNFTJ
    - https://github.com/cloud-barista/cb-ladybug/issues/75 (Agent 설치 안하는 경우임)
      - Tumblebug Agent 설치 시에는: n번 가능 상태를 체크하여 기다린 후 ssh 가능해지면 설치를 시작하고 있음.

### [현재 Spider 및 CSP들의 Ideal한 사용 방법]
  - StartVM() Return: Creating 상태 또는 Running 상태 등을 유동적으로 반환 
  - User는 GetStatus()를 반복 사용하여 Running 상태일 때를 기다렸다가 사용 시작
    - Running 상태일 때는 대상 VM에 ssh 접속이 가능해야 함. 
    - 기타: 현재는 Running 상태일 때도  ssh 접속을 보장할 수는 없음.

### [사용자가 원하는 방법]
  - StartVM() Return: 대상 VM에 바로 ssh 접속 가능
  - StartVM()이 Sync Call임으로 인해서 사용자들은 묵시적으로 VM을 바로 사용 가능할 거라고 생각할 수 있음.
    - 이로 인하여, 계속 오류 보고가 발생하고 있음.

### [결론 및 전체 Driver 점검 요청]
  - 사용자들이 주로 생각하는 방법을 수용하도록 하겠습니다. 
    - 추가적으로 일부 CSP들의 경우 `cb-user` 계정 삽입을 위해서 이미 ssh login 상태를 StartVM() 내부에서 기다리고 있습니다. 
  - 전체 Driver 확인 및 반영 부탁 드립니다. 

  - StartVM() Call이 error 없이 Return을 했다면,
    - 그 즉시, `ssh cb-user@vm`  명령 또는 접속이 가능해야 함.
    - 같은 방법을 사용하실 필요는 없지만, 참고하시라고 사례 링크합니다. 
      - 참고: [CloudIt  사례](https://github.com/cloud-barista/cb-spider/blob/09e8cd80a43b2a27180f20cefc9d8f9d764543e4/cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go#L197)

  - 이로인하여  StartVM() 호출 시간이 더 길어질 수는 있겠습니다. 
     - 이 부분은 다음 이슈를 참고해 주시기 바랍니다. 
       - https://github.com/cloud-barista/cb-spider/issues/429

**Comment by seokho-son** [comment]
@powerkimhub 
`Running 상태일 때는 대상 VM에 ssh 접속이 가능해야 함.` 
이것을 Spider에서 제공해주셔야 하는지 저는 확신이 없습니다.

레이어상 서비스 관리를 하는 CB-TB에서 처리하는게 적합해보인다는 생각입니다.
(처리하더라도 VM의 running 상태의 의미를 바꾸기보단.. 다른 flag를 제공하는 것이 좋을 듯하고요. 예를 들면, Dragonfly Agent 설치 완료 flag를 따로 가지고 있습니다.)

다만 `일부 CSP들의 경우 cb-user 계정 삽입을 위해서 이미 ssh login 상태를 StartVM() 내부에서 기다리고 있습니다.` 의 경우는  CloudInit에 해당하므로 Spider가 생각하는 Running 조건에 포함하는 것이 나을 것 같네요.

**Comment by powerkimhub** [comment]
@seokho-son 

- Agent 설치 없이 제공되는 VM에 대해서도 SSH 접속이 가능한 상태를 제공 예정인가요?
  - 사례 참고: https://github.com/cloud-barista/cb-ladybug/issues/75
- 현실이, SSH login fail로 인한 비슷한 오류 보고가 자꾸올라와서, 이를 반영해주고자 하는 취지였습니다. 
- 저 상태 체크는 어디선가(user-TB-SP) 해야 할일인데, TB에서 처리해준다면 
- Spider에서는 관련 작업을 추가하지 않겠습니다.

**Comment by seokho-son** [comment]
@powerkimhub 
```
Agent 설치 없이 제공되는 VM에 대해서도 SSH 접속이 가능한 상태를 제공 예정인가요?
```
Agent 설치와 무관하게, VM에 SSH가 가능한지 확인은 가능합니다. (원격 제어 기능 활용)

그러나 그것을 SSH 접속 가능 여부를 관리하여 보장하는 기능으로 본다면 의미가 달라질 것 같습니다. (flag나 status로 ssh 가능여부를 표시 하는 등...의 형태)

일단 단편적인 생각으로는

각 FW 또는 사용자가 SSH가 가능한지 여부는 직접확인하는 것이 어떨까 싶습니다. 


```
사례 참고: Error occurs while running ./cluster-create.sh cb-ladybug#75
```
요 사례로 예를 들자면
CB-Ladybug이 
CB-TB를 통해 MCIS(VM)을 생성 후, 
CB-TB의 SSH 가능 여부 확인 커맨드 (원격 제어 기능)를 반복적으로 사용해서 
SSH가 가능한 것을 확인하면
그 이후에
SSH로 설치 작업을 하시는 것이 좋지 않을까 생각합니다.


당연히 장단점이 있기 때문에, 선택을 하면 될 것 같습니다.

**Comment by powerkimhub** [comment]
- closed by https://github.com/cloud-barista/cb-ladybug/issues/75
