### ISSUE TITLE
Environment setting function for adding new cloud OS

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#440]
**What would you like to be added**
: 신규 연동 driver를 개발 후 CB-Spider에 신규 cloud OS를 추가하는 단계를 가능한한 하나의 config 파일로 세팅하는 방식으로 보완하면 좋을것 같습니다.(급한 사항은 아니니 장기적으로 보완되면 좋을것 같네요.)
  
CB-Spider config 파일에 다음과 같은 기능을 반경하면 좋을것 같습니다. 
  - CB-Spider에 연동된 cloud OS list 설정
  - Driver build 수행시의 build 대상 cloud OS list (=driver list) 설정
  - HisCall log 수집 대상 cloud OS list 설정 등

**Why is this needed**
: 현재 기준으로 CB-Spider에 신규 cloud OS를 반영하는 작업, driver build, HisCall log 수집 등의 작업을 위해서는 신규 연동 driver를 개발한 후 수작업으로 CB-Spider의 여러 파일들을 수정해야합니다.
따라서, 신규 driver를 추가하거나 이미 추가된 driver에서 특정 driver를 제외 시키기 위해서는 좀 번잡한 작업들이 진행되어야하며 여러 파일 수정시 실수로 어떤 부분은 수정이 않되어서 오동작을 할 수도 있습니다.

**Comment by powerkimhub** [comment]
@innodreamer 

### CloudOS 설정 관련
설정 관련 파일은 다음과 같이 2가지가 존재합니다. 

1. ./build_all_driver_lib.sh
2. conf/cloudos.yaml

- 1번은 Spider가 plugin mode로 운영될 경우 driver별로 공유 라이브러리(~.so)를 빌드하는 스크립트입니다. 
  - plugin mode가 아닌 static mode인 경우 실행하실 필요는 없습니다. 
    - static mode는 make 시에 서버 코드와 함께 제공되는 모든 CSP Driver가 함께 build되어서 하나의 단일 binary로 제공합니다.
  - 현재는 static mode가 기본이며, plugin mode 가이드는 별도 제공하지는 않고 있습니다. 
  - 현재 plugin mode는 private repos로 운영되는 driver(cloud-twin 등) 활용에서만 내부 시험용으로 활용되고 있습니다.
  - 궁극적으로는 plugin mode가 기본 환경으로 갈 계획입니다만, 현재는 일반 사용자는 static mode로 운영됩니다.
  - 1번 파일은 개발자가 주로 설정합니다. 

- 2번은 Spider 운영할때 운영 사이트마다 Spider가 제공하는 CSP를 선택적으로 설정하는 Config 파일입니다. 
  - 이는 build 시와는 다른 CSP 운영 목록이 될 수 있습니다.  
  - 2번 설정 파일은 Spider 운영자가 설정 가능합니다. 

- 이와 같이 활용 시점 및 사용자가 달라, 1번과 2번 설정은 통합 운영하기는 어려운 설정입니다. 

### HisCall Log 설정 관련
- HisCall Log의 경우는 Driver에 HisCall Log 출력 코드가 존재하면, 아래 설정 위치에 log를 출력합니다. 
- Driver에 HisCall Log 출력 코드가 반영되어 있지 않으면, log를 출력하지 않습니다. 
  - ./config/calllog_conf.yaml
- 이와 같이 현재 HisCall log 수집 대상은 Driver의 코드와 HisCall Agent(filebeat) 설치 여부를 따르고 있습니다.


 ### ClousOS 추가 코드 관련 
- Driver 코드 외에 추가 코드 부분 내용은 다음과 같습니다. 

$grep -r TWIN * |grep -v log | grep -v Binary | grep -v ".sh"
```
  1 api-runtime/rest-runtime/admin-web/AdminWeb-CCM.go:     case "CLOUDTWIN":
  2 api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go:               case "CLOUDTWIN":
  3 api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go:          case "CLOUDTWIN":
  4 api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go:          case "CLOUDTWIN":
  5 api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go:         driverNameList = document.getElementsByName('driverName-CLOUDTWIN');
  6 api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go:         credentialNameList = document.getElementsByName('credentialName-CLOUDTWIN');
  7 api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go:         regionNameList = document.getElementsByName('regionName-CLOUDTWIN');
  8 cloud-control-manager/CloudDriverHandler_static.go:     case "CLOUDTWIN":
  9 cloud-control-manager/CloudDriverHandler_dynamic.go:    case "CLOUDTWIN":
 10 conf/cloudos.yaml:  - CLOUDTWIN
 11 utils/import-drv-region-info/import-regions.go:                 case "CLOUDTWIN":
```

- 관련 코드들의 역할은 다음과 같습니다. 

#### 1-7 Line: AdminWeb 도구 관련 코드
- credential 정보 등 CSP별로 다른 입력 값들이 존재합니다. 
- AdminWeb은 편의성 제공을 위해서 CSP별로 서로 다른 default 입력 값을 미리 셋팅 해줍니다.
- 현재 AdminWeb은 credential 정보 등 CSP별로 다른 셋팅 값을 위해서 새로운 CSP 추가시마다 static 코드로 추가 처리하고 있습니다.
- 향후, 사용자마다 원하는 default 값을 변경 할 수 있는 기능을 제공고자 한다면, AdminWeb 초기 값 설정 용 config file을 추가할수도 있겠습니다만, 현재는 미정입니다. 

#### 8-9 Line: Driver Handler 구현 코드
- 현재 CSP별로 Region 정보에 대한 Key가 다를 수 있습니다. (예시: location vs Region)
- GetRegionNameByRegionInfo() 함수에서 이를 구분하기 위하여 CSP에 대한 switch case가 부득이 존재합니다.
- 조만간 개선 예정입니다.
  - 관련 이슈 참고: https://github.com/cloud-barista/cb-spider/issues/414

#### 10 Line: 위 처음 설명 드린 설정 파일 중 2번 config 파일에 해당됩니다. 

#### 11 Line: Spider 서버 부분은 아니고, Region을 편하게 등록하기 위한 사용자 Utility 코드입니다. 
- 사용한 지가 좀 오래 되어서 동작 여부는 확인 사항입니다. 
- 현재는 필수 구현 사항은 아닙니다. 
- 이 부분도, 다음 이슈 반영 작업 시에 체크해볼 예정입니다. 
  -  관련 이슈 참고: https://github.com/cloud-barista/cb-spider/issues/414
