### ISSUE TITLE
AdminWeb lost Spider Server in K8S

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#441]
#### [Spider in K8S 운영 환경을 위한 개선 필요]

- AdminWeb: K8S 운영 환경에서 제공을 위한 개선 필요 (Server IP, Port 검토 필요)
- 증상: Browser에서 Spider API 호출 불가
- 예시: 밑줄 부분 등
<br> 

![image](https://user-images.githubusercontent.com/46367962/125594915-27973c6e-45a5-44f8-9085-40cf8868bdf1.png)

**Comment by powerkimhub** [comment]
https://github.com/cloud-barista/cb-spider/commit/6353a4b6967742b86c14135d5093d08084fbc3a0

#### LOCALHOST 설정 옵션 추가
- 다음과 같은 설정들이 가능함.
// unset                                  # default: like 'curl ifconfig.co':1024
// LOCALHOST="OFF"            # default: like 'curl ifconfig.co':1024
// LOCALHOST="ON"             # => localhost:1024
// LOCALHOST="1.2.3.4"        # => 1.2.3.4:1024
// LOCALHOST="1.2.3.4:31024"  # => 1.2.3.4:31024

#### TEST
- 다음 2가지 설정으로 AdminWeb에서 VM 생성/종료 시험 완료
  - export LOCALHOST=OFF  (기존 설정)
  - export LOCALHOST=3.36.93.11:**31024**  (신규 설정, for K8S)

#### VERSION
- https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.2 부터 적용


@jihoon-seo 
- 시험 부탁 드립니다.

**Comment by powerkimhub** [comment]
https://github.com/cloud-barista/cb-spider/commit/6353a4b6967742b86c14135d5093d08084fbc3a0

### 포트 설정만 설정 기능 추가

#### LOCALHOST 설정 옵션 추가
- 다음과 같은 설정들이 가능함.
// unset                                  # default: like 'curl ifconfig.co':1024
// LOCALHOST="OFF"            # default: like 'curl ifconfig.co':1024
// LOCALHOST="ON"             # => localhost:1024
// LOCALHOST="1.2.3.4"        # => 1.2.3.4:1024
// LOCALHOST="1.2.3.4:31024"  # => 1.2.3.4:31024
**// LOCALHOST=":31024"         # => like 'curl ifconfig.co':31024**

#### TEST
- 다음 2가지 설정으로 AdminWeb에서 VM 생성/종료 시험 완료
  - export LOCALHOST=OFF  (기존 설정)
  - export LOCALHOST=**:31024**  (신규 설정, for K8S)

#### VERSION
- https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.3 부터 적용


@jihoon-seo 
- 시험 부탁 드립니다.

**Comment by jihoon-seo** [comment]
@powerkimhub 발견한 사항이 있어서 알려 드립니다. 😊
(이미 알고 계신 사항입니다.)

- CB Helm chart 로 CB-Spider를 실행한 상황입니다.
- 하드웨어 공유기 아래에
  - 브라우저로 CB-Spider API를 호출하는 PC와
  - K8s 워커 노드 PC가 있는 상황입니다.

https://github.com/cloud-barista/cb-operator/issues/42#issuecomment-882432729

![image](https://user-images.githubusercontent.com/46767780/126145556-362c4b1f-ceda-401f-8baf-750f0a6c28d8.png)

스크린샷에는 `http://129.254.75.178:1024/spider` 로 나와 있는데
1. `129.254.75.178`은 하드웨어 공유기의 Public IP 입니다.
2. NodePort :31024 -> `cb-spider` Service :1024 -> `cb-spider-abc123` Pod :1024 의 구조입니다.

따라서 하드웨어 공유기에 포트포워딩을 설정하지 않는 이상, 
`http://129.254.75.178:1024/spider` 로는 접속을 할 수 없습니다.

---

![image](https://user-images.githubusercontent.com/46767780/126145736-d7a1d371-9efb-45ca-86a1-e331bafb4ba2.png)

마찬가지 이슈 입니다. 😊

**Comment by powerkimhub** [comment]
- 개선 중에 있습니다. 
- 개선에 참고토록 하겠습니다. 
- 아마도, 내일 쯤이면...^^

**Comment by powerkimhub** [comment]
####  Service Address Configuration 기능 추가
- 참고: https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-Service-Address-Configuration
- K8S 환경 설정 방법: 위 링크의 (5) 설정 참고
  - 기존 `LOCALHOST` 사용하지 않음.
  - `SERVICE_ADDRESS` 설정 필요

#### VERSION
- https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.4 부터 적용


@jihoon-seo 
- 시험 부탁 드립니다.

**Comment by powerkimhub** [comment]
resolved.
cf) https://github.com/cloud-barista/cb-operator/discussions/144
