### ISSUE TITLE
Update `Dockerfile`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#445]
**What would you like to be enhanced**
: 
https://github.com/cloud-barista/cb-spider/blob/master/setup.env 에 있는 ENV 들을
`Dockerfile` 에도 반영해야 함

**Why is this needed**
: 
- `LOCALHOST` ENV 는 더 이상 사용되지 않음
- ...

**Proposed solution**
:

**Comment by jihoon-seo** [comment]
CB-Spider를 컨테이너로 실행하는 경우에 가장 적합한 `SERVER_ADDRESS`, `SERVICE_ADDRESS` 값을 
`Dockerfile`에 적어 놓는 방안도 있겠습니다.

(cb-operator에서는 필요 시 `docker-compose.yaml` 과 Helm chart 에서
해당 환경변수를 override 할 수 있기 때문에
`Dockerfile`에 무엇으로 적혀 있어도 (혹은 적혀 있지 않아도) 괜찮습니다.)

**Comment by powerkimhub** [comment]
- Dockerfile에서 deprecated된 `LOCALHOST`만 삭제하였습니다. 
- 기본 Container 환경은 `-p 1024:1024` 설정도 고려해야 하고 해서 service address 관련 설정은 추가 하지 않고, 
- 가이드에 관련 정보를 추가했습니다. 
  - https://github.com/cloud-barista/cb-spider/wiki/Docker-based-Start-Guide
