### ISSUE TITLE
enhance the guide of 'REST API Examples'

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#448]
- #### Wiki에 REST API 사용자를 위한 Guide를 제공하고 있음
  - https://github.com/cloud-barista/cb-spider/wiki/REST-API-Examples

- #### 현재 가이드 전체 틀과 Cloud Driver 등록 가이드만 제공하고 있음. 

- #### 이후 가이드 추가/개선이 필요함.

- #### REST API 규격 및 활용 방법 등 관련 참고 자료 목록
  - 기능: https://github.com/cloud-barista/cb-spider/wiki/features-and-usages
  - 규격: https://github.com/cloud-barista/cb-spider/wiki/REST-API-Specs 
  - 시험: https://github.com/cloud-barista/cb-spider/tree/master/api-runtime/rest-runtime/test/full-test/1.aws-test.sh 등 추적

**Comment by NovusEdge** [comment]
I'd like to take this issue up if it's open

**Comment by powerkimhub** [comment]
@NovusEdge 
Of course! but would you be okay with language difference?
If that's not a problem for you, I'll be happy to assign you.
Thank you for your interest.

**Comment by NovusEdge** [comment]
> would you be okay with language difference?

I believe I'll manage somehow 😅 Although I'd appreciate any help with the language diff.
Lemme know about it all and I'll get working :)

**Comment by powerkimhub** [comment]
Sounds great! I'm happy to hear that. 
I believe that we'll be the best team.

**Comment by NovusEdge** [comment]
I'm sorry to say, I cant currently work on the issue due to some reasons. Please do forgive me for the hassle 😞

**Comment by powerkimhub** [comment]
@NovusEdge 

I see, thank you for letting me know.
Have a good day😊

**Comment by powerkimhub** [comment]
- Added a complete step-by-step guide from preparation to VM control in the [REST-API Examples](https://github.com/cloud-barista/cb-spider/wiki/REST-API-Examples)
