### ISSUE TITLE
enhance the guide of 'CLI spctl Examples' 

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#452]
- #### CLI(spctl: spider control) 사용자를 위한 Examples Guide를 제공하고 있음
  - https://github.com/cloud-barista/cb-spider/wiki/CLI-Examples

- #### 현재 가이드 전체 틀과 Cloud Driver 등록 가이드만 제공하고 있음. 

- #### 이후 가이드 추가/개선이 필요함.

- #### CLI 규격 및 활용 방법 등 관련 참고 자료 목록
  - 기능: https://github.com/cloud-barista/cb-spider/wiki/features-and-usages
  - 규격: https://github.com/cloud-barista/cb-spider/wiki/CLI-Command-Specs
  - 시험: https://github.com/cloud-barista/cb-spider/blob/master/interface/cli-examples/1.prepare-resources.sh 등 추적

**Comment by atg0831** [comment]
제가 CLI spctl 가이드 추가 및 개선해 보겠습니다!

**Comment by atg0831** [comment]
@powerkimhub 
제가 cloud-barista/cb-spider를 fork했는데 wiki 내용은 같이 fork가 안되는 거 같아요. 
원본 wiki에서 바로 edit해서 wiki를 수정해야 되는 건지 아니면 다른 방법이 있는지 궁금합니다.

**Comment by powerkimhub** [comment]
@atg0831 

- 말씀 주신 것처럼, GitHub의 source와 wiki의 repos는 분리되어 운영되고 있습니다.
  ```
  git clone https://github.com/cloud-barista/cb-spider.git
  ```
  ```
  git clone https://github.com/cloud-barista/cb-spider.wiki.git
  ```

- Source repos에 함께 운영하는 방법도 있겠지만, 
  - 소스를 받을 때마다 가이드 문서들이 함께 받아져서 관리되어야 한다는 단점이 있습니다. 

- WIKI 문서에 대한 공동 기여 방안에 대해서는
  -  좀만 더 고민 후 다시 공유드리도록하겠습니다.

**Comment by atg0831** [comment]
@powerkimhub 
[wiki edit테스트](https://github.com/cloud-barista/cb-spider/wiki/CLI-Examples/_compare/a7ee1690d4b22b667642420da6d161a177d1b3bb)

wiki에서 edit 버튼 누르고 수정을 해보았습니다. wiki 편집 권한은 일반 barista 멤버도 부여가 되는 걸로 보입니다.

**Comment by powerkimhub** [comment]
@atg0831 

- 앗, 그러군요. 잘되는 군요. 캄사합니다. 
- 혹시, 진행하시다 잘 안되시는 부분 있으면 알려주세요. 
- 그럼, ...🕷

**Comment by powerkimhub** [comment]
- Thanks, @atg0831
  - 그 사이 많이 작성을 하셨네요 👍
  - 캄사합니다. 
- 관련하여, 문의 드립니다. 혹시, WIP로 표시된 부분은,
  - 질문이나 추가 설명 등이 필요하신지요?
  - 아니면, 좀 여유를 두고 작성하실 계획이신지요?
  - 관련하여, 의견 및 계획 등 생각하시는 바를 공유 부탁드립니다.

**Comment by atg0831** [comment]
@powerkimhub 
- 제가 최근에 좀 일정이 바빠서 작성을 많이 못 하였는데 이번 주나 다음 주 내로 spctl 가이드는 작성을 다 해보도록 하겠습니다.
- WIP 부분은 아직 테스트해보지 못한 부분도 있고 몇 가지 질문할 사항이 있는 부분이 있습니다.
- 궁금한 부분은 `delete` 와 `deletecsp`의 차이점이 정확이 무엇인지 알고 싶습니다. `delete` 만 해도 CSP console에서 삭제되는 것을 확인했는데 `deletecsp` 와 어떻게 다른지 궁금합니다.
- `list` 와 `listall` 의 차이점도 정확히 알고 싶습니다. 저는 `list`는 각 `connection name`의 목록을 보여주고 `listall`은 각 `region`내의 목록 전체를 보여주는 것으로 이해했습니다. 맞을까요?

**Comment by powerkimhub** [comment]
Thanks, @atg0831 

**[현황/계획]**
- 넵, 잘 이해되었습니다.

**[질문/답변]**
- 질문: list vs. listall & delete vs. deletecsp ?
- 답변: 별도 답변 보다는 다음 링크를 쓱~ 한번 보시면 이해하시는 데 도움이 될 것 같습니다.
  - https://github.com/cloud-barista/cb-spider/issues/228#issuecomment-633874844
  - https://github.com/cloud-barista/cb-spider/issues/228#issuecomment-644536669

**[TMI]**
- listall과 deletecsp 등을 활용하여 만든 기능이 다음 링크에서 보실 수 있는 Dangling 자원 관리 기능입니다. 
  - https://github.com/cloud-barista/cb-spider/wiki/Dangling-Resource-Management-Guide

**[기타]**
- 추가 문의 및 지원해드릴 부분이 있으시면 또 남겨 주시기 바랍니다🕷

**Comment by atg0831** [comment]
[현재까지 spctl guide wiki 작성 현황]
- Guide 작성을 거의 완료하였습니다.
- 제가 작성한 guide 토대로 spctl을 실행해보니 정상적으로 잘 동작하는 것을 확인하였습니다.

[보완해야 할 부분]
- 위의 dangling 관련 코멘트 내용을 대략적으로 이해하였지만 dangling 상황을 연출하여 테스트하기가 약간은 무리인 것 같다는 생각도 들었고 dangling 되는 상황과 그것을 해결하기 위한 명령어에 대한 이해가 완벽하게 되지 않아서 제가 그 부분 guide 작성을 하는 것은 다른 컨트리뷰터에게 혼동을 줄 수 있다고 생각되어 작성하지 않았습니다.
- spctl의 subnet 생성 및 추가를 하는 부분은 subnet에 대한 배경지식이 제가 부족해 테스트 해보지 못하여 작성을 못하였습니다.
- spctl의 `create` , `delete` 등의 명령어가 필요한 것인지 이해가 되지 않아 작성하지 않았고 image `list` 명령어는 image 갯수가 많다는 오류 메시지가 뜨고 목록이 보여지지는 않았습니다.

**Comment by powerkimhub** [comment]
- Thanks, @atg0831 

**[질문]**
- 시험 시 활용하신 Spider 버전은 어떤 버전이신지요?

**[부연설명]**
- Dangling 자원은 정상적인 동작에서는 발생하지 않는 것이어서, 
  - 관련된 인터페이스(`deletecsp`, `listall` 등)는 말씀해주신 것처럼, 
  - 현재 작성 가이드에서는 제외하시는 것이 좋을 거 같습니다.
  - 이 부분은 추후 관리자 기능 세션으로 추가 정리하거나 별도 가이드 작성으로 추진하도록 하겠습니다. 
  - 관련 인터페이스는 현재 가이드에서는 삭제부탁드립니다. 
- Subnet 추가/삭제 관련해서는 먼저 다음 AWS KR 영상을 참고 한번 해보시기 바랍니다. 
  - Subnet 뿐만 아니라, VPC ~ SecurityGroup 등 설명을 아주 잘해주시네요. 
  - Subnet 추가/삭제 기능 이해보다는 전반적인 이해를 먼저 해보시는 것이 좋겠습니다. 
  - https://youtu.be/R1UWYQYTPKo
  - 위 영상 내용을 이해하시는 것에 시간를 먼저 투자하시고, 
  - Subnet 추가/삭제 가이드 작성은 선택적으로 마무리 해주시면 되겠습니다. 
    - 다만, 작성 여부 의사 및 계획만 현 이슈에 표현해주시면 되겠습니다. 
- VM Image Create/Delete 관련, 
  - 대부분의 CSP가 사용자가 필요한 Image를 추가 및 관리하는 기능을 제공하지만, 
  - 제공하는 Image 타입 및 Image 생성 방법 등이 CSP별로 상이하여 통합 제공하기가 난해합니다. 
  - 그래서, 현재 버전에서는 제공하지 않고 있으며, 향후 제공할 수 있도록 계획만하고 있습니다. 
  - 현재 가이드에서는 TBD(To Be Defined)로 표시하시면 되겠습니다. 

- 기여에 감사드립니다.

**Comment by atg0831** [comment]
> Dangling 자원은 정상적인 동작에서는 발생하지 않는 것이어서,
관련된 인터페이스(deletecsp, listall 등)는 말씀해주신 것처럼,
현재 작성 가이드에서는 제외하시는 것이 좋을 거 같습니다.
이 부분은 추후 관리자 기능 세션으로 추가 정리하거나 별도 가이드 작성으로 추진하도록 하겠습니다.
관련 인터페이스는 현재 가이드에서는 삭제부탁드립니다.

- Dangling 자원 관련 인터페이스 관련 가이드는 삭제해두었습니다.

> VM Image Create/Delete 관련,
대부분의 CSP가 사용자가 필요한 Image를 추가 및 관리하는 기능을 제공하지만,
제공하는 Image 타입 및 Image 생성 방법 등이 CSP별로 상이하여 통합 제공하기가 난해합니다.
그래서, 현재 버전에서는 제공하지 않고 있으며, 향후 제공할 수 있도록 계획만하고 있습니다.
현재 가이드에서는 TBD(To Be Defined)로 표시하시면 되겠습니다.

- Image Create/Delete 부분을 말씀해주신 대로 To Be Defined라고 표시해 두었고요

> Subnet 추가/삭제 관련해서는 먼저 다음 AWS KR 영상을 참고 한번 해보시기 바랍니다.
Subnet 뿐만 아니라, VPC ~ SecurityGroup 등 설명을 아주 잘해주시네요.
Subnet 추가/삭제 기능 이해보다는 전반적인 이해를 먼저 해보시는 것이 좋겠습니다.
https://youtu.be/R1UWYQYTPKo
위 영상 내용을 이해하시는 것에 시간를 먼저 투자하시고,
Subnet 추가/삭제 가이드 작성은 선택적으로 마무리 해주시면 되겠습니다.
다만, 작성 여부 의사 및 계획만 현 이슈에 표현해주시면 되겠습니다.

- Subnet 관련 자료 링크 감사드립니다. Subnet에 대한 공부를 좀 더 해보겠습니다.
  Subnet 추가/삭제 가이드 작성은 하지 않는 쪽으로 생각하고 있습니다.

- 감사합니다.

**Comment by powerkimhub** [comment]
- Thanks, @atg0831 

<br>

- 잘 정리해주신 내용 잘 이해되었습니다👍
- 시험시 사용하신 CB-Spider 버전이 궁금합니다. 
  - (답변 예시)
    - 실행방법: 아래 링크에서 `소스 기반 실행 방법`으로 실행
      - https://github.com/cloud-barista/cb-spider#2-%EC%8B%A4%ED%96%89-%EB%B0%A9%EB%B2%95
    - 실행버전
      ```
      $ git describe --tags
      v0.4.9-23-gb546164
      ```

**Comment by atg0831** [comment]
@powerkimhub
- CB-Spider는 소스 기반으로 실행했었고요
- 실행 버전은 `v0.4.9-26-g4c0d901`입니다.

**Comment by powerkimhub** [comment]
- Thanks, @atg0831 

- 현 이슈는 다음 사항을 반영해주시면 close 하도록 하겠습니다. 
  - Header에 'WIP' 삭제
  - 중간에 '[이하] WIP' 삭제
- 그 외 subnet 관련 WIP나 Image관련 TBD는 향후 update 항목으로 보고 가고자 합니다.  
- 우측 목차의 'CLI Examples-WIP'에서 WIP 삭제는 @powerkimhub가 하도록 하겠습니다. 
- 수고많으셨습니다. 
- 감사합니다.

**Comment by atg0831** [comment]
@powerkimhub 
- subnet 관련 WIP 부분도 전부 삭제를 하면 될까요?

**Comment by powerkimhub** [comment]
@atg0831 

- 신경 쓰이시면 삭제하셔도 됩니다^^

**Comment by atg0831** [comment]
@powerkimhub 
- 요청하신 WIP 부분을 모두 삭제 완료했습니다.(subnet WIP 부분도 같이 삭제를 했습니다)

**Comment by powerkimhub** [comment]
- Thank you for your contribution, @atg0831
- Updated: [1d83689](https://github.com/cloud-barista/cb-spider/wiki/CLI-Examples/1d83689830d78afabe2a4ea4f62929ecc393947e)
