### ISSUE TITLE
Update CB-Spider Go API example codes

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#456]
**What would you like to be enhanced**
: 
Update CB-Spider Go API example codes.

**Why is this needed**
: 
CB-Spider Go API example code가 CB-Spider `v0.3.13`을 테스트하도록 되어 있음

[[`cb-spider/interface/api-examples/go.mod`](https://github.com/cloud-barista/cb-spider/blob/master/interface/api-examples/go.mod)]

```
require github.com/cloud-barista/cb-spider v0.3.13
```

**Proposed solution**
:
- [`cb-spider/interface/api-examples/go.mod`](https://github.com/cloud-barista/cb-spider/blob/master/interface/api-examples/go.mod) 업데이트
- 필요 시, [`cb-spider/interface/api-examples/create_examples.go`](https://github.com/cloud-barista/cb-spider/blob/master/interface/api-examples/create_examples.go) 업데이트

**Comment by powerkimhub** [comment]
- completed (https://github.com/cloud-barista/cb-spider/commit/4c0d901cb06fe0fe616f09a47b975738073087df)
