### ISSUE TITLE
Change 'CBSPIDER_ROOT' value dynamically

### ISSUE THREAD

**Issue by computerphilosopher** [cloud-barista/cb-spider#458]
**What would you like to be enhanced**
: 

현재 start.sh 등의 스크립트는 CBSPIDER_ROOT라는 환경 변수를 사용하고 있는데, 다음과 같이 고정된 값입니다.

https://github.com/cloud-barista/cb-spider/blob/edcbcc30a96b54ece8ae6882122df4235b0590e7/setup.env#L4

이는 아마 go 패키지를 반드시 GOPATH에 두어야 했던 시절의 흔적이라고 생각합니다.

현재는 자유롭게 디렉토리를 설정할 수 있으므로 사용자가 clone한 디렉토리를 root로  지정하는게 어떨까요?

**Why is this needed**
: 
패키지 설치 경로에 대한 제약 때문에 불편한 점이 있을 수 있습니다.

예를 들어 [cloud-barista 메인 저장소](https://github.com/cloud-barista/cloud-barista)를 통째로 클론받아 사용하려는 유저의 경우 현재는 정상 사용이 불가능 합니다.

**Proposed solution**
:
setup.env를 다음과 같이 수정

```
export CBSPIDER_ROOT=$(dirname $(readlink -f "$0"))
```

**Comment by powerkimhub** [comment]
@computerphilosopher 

- 좀더 시원해진 아침이네요~
- 제안 감사드립니다. 
- setup.env는 초기 시절 급하게 만들어진 이후 
- 우선 순위에 밀려 그대로 유지되고 있는 개선이 필요한 부분입니다. 
- 사실, configuration관련된 부분이 전반적으로 개선이 필요한 상태이긴 합니다. 
- 시작 포인트로 CBSPIDER_ROOT 개선 좋은 것 같습니다.
- 혹시, 적용 및 시험 가능하신지요?

**Comment by powerkimhub** [comment]
This issue affected https://github.com/cloud-barista/cb-spider/commit/02af423a6d259a2a86cd5bc560e9c2819a8aea6b
