### ISSUE TITLE
Add a common function for input arguments validation 

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#464]
### reflect 이용한 사용자 입력 값에 대한 simple validation 공통 함수 개발

***
1. 사용자의 입력 값에 대한 simple validation 기능을 추가하고자 함.
2. 사용자의 입력 값은 대부분 다음 위치의 *ReqInfo struct으로 변환되어 처리됨.
    - cb-spider/cloud-control-manager/cloud-driver/interfaces/resources/*
3. *ReqInfo struct 객체들의 입력값을 validation하는 공통 함수 개발이 필요함.

4. 함수 규격 (안)
    - 제시하는 규격은 가이드가 목적임.
    - 실제 개발 시에는 부족할 수 있으며, 규격은 필요에 따라 변경 가능함.
    - flow 또한 변경이 가능함.

    ```
    func ValidateStruct(iT reflect.Type, excepts [] string) error {

      (1) iT struct을 scan하여 struct에 포함된 인자 이름 목록 추출
           - excepts 배열에 포함된 인자 이름은 제외
             - description 정보와 같이 반드시 요구되는 값이 아닌 인자의 경우임
      (2) 추출한 인자 이름 순회하면서 값 설정 여부를 체크함
           - 입력 값 설정이 없는 경우  오류 인자 이름 배열에 adding하고 모든 인자를 확인함.
      (3) 에러가 없을 경우 nil을 반환 하고, 에러가 존재하는 경우 다음과 유사한 에러 문자열을 포함한 error 객체를 반환함.
           - excepts 인자를 포함한 사용자가 설정한 값을 포함하는 struct 문자열 생성
           - 생성한 문자열에 (2)에서 구한 오류 인자 이름 배열을 이용하여 대상 인자의 값에 오류 메시지 추가
           - 오류 메시지는 영어로 작성
      (4) 인자가 struct일 경우 recursive로 처리 권고

    }
    ```

- 공통 함수 추가 위치
  - cb-spider/api-runtime/common-runtime/common.go

- 다음 예제 등 참고
  - https://gist.githubusercontent.com/jonbodner/1727d0825d73541db8d6fcb859515735/raw/8666904958d5519cdcc2570dd1fc9f04c2088cef/reflection1_4.go
  - 원문: https://medium.com/capital-one-tech/learning-to-use-go-reflection-822a0aed74b7

**Comment by jihoon-seo** [comment]
Ref: https://github.com/cloud-barista/cb-tumblebug/issues/706

**Comment by powerkimhub** [comment]
- 이 이슈는 1차적으로 common function의 자체 개발로 추진해보면 좋을 듯합니다.
  - 사유: reflect, recursive 등을 다뤄 보는 `good first issue'임
  - 사유: reflect 익숙해진 후 타 pkg 활용 여부 판단 가능

**Comment by powerkimhub** [comment]
-rel) https://github.com/cloud-barista/cb-spider/issues/182

**Comment by jihoon-seo** [comment]
Ref: TB case

`cb-tumblebug/src/api/rest/server/common/utility.go` 에 다음과 같은 함수가 정의되어 있습니다.

```Go
import (
	"github.com/beego/beego/v2/core/validation"
)

func Validate(c echo.Context, params []string) error {
	valid := validation.Validation{}

	for _, name := range params {
		valid.Required(c.Param(name), name)
	}

	if valid.HasErrors() {
		for _, err := range valid.Errors {
			return errors.New(fmt.Sprintf("[%s]%s", err.Key, err.Error()))
		}
	}
	return nil
}
```

그리고, 다른 함수에서 다음과 같이 활용합니다.

`cb-tumblebug/src/api/rest/server/common/namespace.go`

```Go
func RestCheckNs(c echo.Context) error {

	if err := Validate(c, []string{"nsId"}); err != nil {
		common.CBLog.Error(err)
		return SendMessage(c, http.StatusNotFound, err.Error())
	}
...
```

=> `"nsId"` 필드에 값이 채워져 있는지 검사

---

이 방법은, 이 이슈 본문의 "함수 규격 (안)" 은 만족시키지 못하므로
"함수 규격 (안)" 을 만족시키려면

> common function의 자체 개발

등이 필요하겠네요 😊

**Comment by powerkimhub** [comment]
- 관련, 예시 캄사합니다. 

- 넵, 현재는 말씀해주신 대로 reflect와 recursive 조합을 이용해서 개발해보는 것을 고려하고 있습니다. 
- `good first issue` 이유는 spider와 무관하게 아무 struct 및 nested struct에 대한  
- 간단한 validation을 제공하는 함수만 만들면 되기 때문입니다. 
- nested Struct 예시:
  - https://github.com/cloud-barista/cb-spider/blob/4c0d901cb06fe0fe616f09a47b975738073087df/cloud-control-manager/cloud-driver/interfaces/resources/SecurityHandler.go#L14

**Comment by powerkimhub** [comment]
- Common Validator 개발 및 적용
- 관련 내용 참고
  - https://github.com/cloud-barista/cb-spider/issues/394#issuecomment-963167074
