### ISSUE TITLE
Some minor update on Quick Start Guide

### ISSUE THREAD

**Issue by ChobobDev** [cloud-barista/cb-spider#465]
**What would you like to be enhanced**
:  As the Gopath being deprecated there is no need to clone the repository under the Gopath directory.  So I was wondering whether we should update the documentation or not. I have cloned the cb-spider into another directory and saw it working as usual.

**Why is this needed**
: 

**Proposed solution**
:

**Comment by powerkimhub** [comment]
- Thanks, @ChobobDev 
- 근래에는 Gopath를 염두하고 가이드한 적은 없었습니다만, 놓친 부분이 있었나 봅니다. 
- 또는, 현재 Spider는 활용보다는 개발에 집중하는 시기여서 개발자를 위한 배려 부분일 수도 있겠습니다만,
- 일단, 생각하시는 바를 적용하여 올려주시면 얘기를 나눠 볼수 있겠습니다.

**Comment by powerkimhub** [comment]
- 설치 위치가 무관한데도, 가이드에 제시된 설치 위치가 Gopath 잔재가 남아 있어 이를 수정함
  - [Before] $HOME/go/src/github.com/cloud-barista/cb-spider
  - [After] $HOME/cb-spider

- Thanks, @ChobobDev
