### ISSUE TITLE
Need to change error message when registering cloud connection configuration with sptcl

### ISSUE THREAD

**Issue by atg0831** [cloud-barista/cb-spider#478]
**What would you like to be enhanced**
: 
`spctl` 로 connection configuration을 등록할 때 data  값으로 `"ConfigName:" : value` 의 key-value 형태 입력을 하는데 실수로 key 값인 `ConfigName` 을 빼먹었거나 오타가 났을 경우에 `ConnectionName is empty!` 라는 오류 메시지가 출력이 됩니다. 
실제 입력해야 될 key 값은 `ConfigName` 인데 오류 메시지로는 `ConnectionName is empty!` 라고 보여주기 때문에 사용자로 하여금 key 값을 `ConnectionName` 이라고 혼동할 여지가 있다고 판단되어 오류 메시지 수정이 필요해 보입니다.

---
ex) 아래처럼 `ConfigName` 을 입력해아 하는데 오타로 `Configame` 이라고 잘못 입력했을 경우 `ConnectionName is empty!` 라는 오류 메시지를 출력하고 있습니다.
```
./spctl connection create -i json -d '{
  "Configame": "aws-us-east-2-connection-01",
  "ProviderName": "AWS",
  "DriverName": "aws-driver01",
  "CredentialName": "aws-credential-01",
  "RegionName": "aws-us-east-2"
}'
[CB-GRPC].[INFO]: 2021-10-03 14:35:43 client_interceptors.go:38, github.com/cloud-barista/cb-spider/api-runtime/grpc-runtime/interceptors/accesslog.UnaryClientInterceptor.func1() - grpc client unary call : /cbspider.CIM/CreateConnectionConfig service [1 ms]
message: rpc error: code = Internal desc =  error while calling CIMService.CreateConnectionConfig() method: ConnectionName is empty!
```

**Why is this needed**
: 
`spctl`을 사용하는 초기 사용자들에게 오류 메시지로 인한 혼동의 여지를 줄일 수 있다고 생각합니다.

**Proposed solution**
:
제가 생각하는 방법으로는 두 가지가 있습니다.
- 첫번째 방법은, 현재는 Cloud Connection Configuration 등록할 때 `ConfigName`이 없거나 오타가 났을 경우 error 메시지로 `ConnectionName is empty!` 라고 출력하는데 이것을 `ConfigName is empty!` 라고 출력하도록 오류 메시지를 수정하는 방법이 있습니다.
- 두번째 방법으로는 오류 메시지 수정이 아니라 Cloud Connection Configuration 등록하는 데이터의 key 값 자체를 `ConfigName` 에서 `ConnectionName` 으로 바꾸는 방법도 있을 것 같습니다.

**Comment by powerkimhub** [comment]
- @atg0831 , Thank you for your Interest 👍

**[Labels 변경 및 Spider 인터페이스 구조 개요]**
- 현재 이슈는 cli 뿐만 아니라, REST API, Go API에 공통으로 해당되는 이슈이어서, `cli` tag는 삭제하였습니다. 
  - REST API 관련 부분 참고: https://documenter.getpostman.com/view/9027676/TzefC4Uv#d55fffa8-102f-437f-8db1-bba0e16fa8ca 
  - TMI: 인터페이스 구성 참고
    - REST API
    - Go API(gRPC-based) 
    - AdminWeb -> REST API
    - CLI(spctl) -> Go API
  - TMI: Spider 기능 분류 및 인터페이스 런타임 구조
    - Spider 기능 분류
      - (1) CLOUD CONNECTION INFO MGMT(CCIM): driver 정보, credential 정보, region 정보 등 정보 관리
      - (2) CLOUD CONTROL MGMT(CCTM): VPC/Subnet, SG(SecurityGroup), KeyPair, VM 등 자원 제어 관리
      - source structure (Server Layer)
         ```shell
          $ tree -d -L 1 cb-spider
          cb-spider
          |-- api-runtime
          |-- bin
          |-- cloud-control-manager ----------- (2)
          |-- cloud-driver-libs
          |-- cloud-info-manager -------------- (1)
          |-- conf
          |-- interface
          |-- log
          |-- meta_db
          `-- utils
         ```
    - 인터페이스 런타임 구조: 인터페이스 런타임은 (1)REST 런타임과 (2)gRPC 런타임으로 구성
      - source structure(Interface Layer)
        ```shell
        $ tree -d -L 1 cb-spider/api-runtime
          cb-spider/api-runtime/
          |-- common-runtime -------------(*) 
          |-- grpc-runtime  ----------------(2)
          |-- meerkat-runtime : 삭제 예정
          `-- rest-runtime. ----------------(1)
        ```
      - common 구조: 위 소스 구조에서 REST 런타임과 gRPC 런타임에서 공통 부분(core function)을 포함하고 있는 (*)Common 런타임 구조
        - CCTM 기능은 common 구조를 따르고 있으며, 
        - CCIM 기능은 개별 런타임에서 Server Layer의 기능을 직접 호출함.
          - 즉, `./spctl connection create`의 경우: gRPC 런타임에서 CCIM 서버 기능 함수 직접 호출
          - Call flow
            ```
            api-runtime/grpc-runtime/service/connection.go::CreateConnectionConfig()
            --> cloud-info-manager/connection-config-info-manager/ConnectionConfigInfoManager.go::CreateConnectionConfigInfo()
            ```

**[의견 및 부연설명]**
- 첫번째 제안 방법으로 수정하는 것이 좋겠습니다. 
  - 사유: 인자를 바꾸는 방법은 현재 작업 범위가 너무 넓어집니다. (tumblebug 및 시험 프로그램 등 전파 필요)
    - 현재 tumblebug은 spctl을 직접 사용하지 않지만, REST API와 Go API를 사용하고 있으며, 
    - 위에서 설명드린 구조에서 처럼 현재의 이슈 반영 작업은 Server Layer의 CCIM-Connection Config 관리 기능에 대한 수정 작업이 필요하며
    - 이 변화는 Go API 및 REST API를 포함하여 WebAdmin, spctl까지 동시에 영향을 미치는 작업입니다. 

- 부연설명: 현재 관련 오류 메시지를 제공하는 부분에 대한 부연 설명 드립니다. 
  - 아래 `오류 메시지 출력 위치`에서  `IIDManager`는 메타 정보 저장을 위한 모듈로 현재 이슈와는 약간 다른 측면이 있으므로, 
  - 현재 이슈에서는 `ConnectionConfigInfoManager` 내용만 제안 내용으로 수정하면 되겠습니다. 
  - 오류 메시지 출력 위치
      ```shell
      grep -r "ConnectionName is empty"
      cloud-info-manager/connection-config-info-manager/ConnectionConfigInfoManager.go:		return nil, fmt.Errorf("ConnectionName is empty!")
      cloud-info-manager/connection-config-info-manager/ConnectionConfigInfoManager.go:		return false, fmt.Errorf("ConnectionName is empty!")
      cloud-info-manager/connection-config-info-manager/ConnectionConfigInfoManager.go:		return fmt.Errorf("ConnectionName is empty!")
      cloud-control-manager/iid-manager/IIDManager.go:                return fmt.Errorf("ConnectionName is empty!")
      cloud-control-manager/iid-manager/IIDManager.go:                return fmt.Errorf("ConnectionName is empty!")
      cloud-control-manager/iid-manager/IIDManager.go:                return fmt.Errorf("ConnectionName is empty!")
      ```

**Comment by powerkimhub** [comment]
@atg0831 

- 혹시, 관련하여 기여도 가능하시면, 
- self-assign 또는 댓글 남겨 주시기 바랍니다.

**Comment by atg0831** [comment]
@powerkimhub 
- 네 self-assign 해서 작업해보도록 할게요
- 기여 도중 궁금한 부분이 있으면 질문 드리도록 하겠습니다^^

**Comment by powerkimhub** [comment]
@atg0831 

**[참고자료]**
- 함께 보시면 도움이 될만한 도식화된 자료 공유 드립니다.
  - 이미 공유 드렸을 것 같은 자료이지만, 이제는 좀더 잘 보이실 것 같아 재공유 드립니다.

- Spider 구조 및 인터페이스 구성; 다음 링크 7page, 8page 참고 (장표 내 페이지 번호 기준)
  - https://www.slideshare.net/cloud-barista/cloudbarista-4-cbspider-cbtumblebug-multicloud-infrastructure-services

- Spider Process&Thread 구조: 다음 링크 9page 참고
  - https://www.slideshare.net/cloud-barista/cloudbarista-3-cbspider-multicloud-infrastructure-federation

**[TMI]**
- 그 외에도 보시다 궁금하신 사항 생기면 남겨주세요 🕷
