### ISSUE TITLE
Can't delete unused KeyPair in AWS

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#480]
@dev4unet 

**What happened**

**[재현절차]**

1. Spider를 통해서 AWS VM KeyPair 생성하면, 
- `cb-spider/cloud-driver-libs/.ssh-aws` 위치에 다음과 같이 키 파일이 생성되고,
  ```
  255e2c4cd5e4f1ba87cbed3b6911519d4a8f9ce5.pem  255e2c4cd5e4f1ba87cbed3b6911519d4a8f9ce5.pub
  ```
- AWS에 키페어가 생성됩니다.
![image](https://user-images.githubusercontent.com/46367962/136510410-6e5e9725-80ae-486c-9abc-e72a9548f415.png)

2. 꼬인 상태 재현을 위해서, Spider를 종료하고 메타정보를 삭제 후 Spider를 가동시킵니다.
- 꼬인 정보를 해결하고자 관리모드로 KeyPair를 확인해보면, 
- 아래 그림에서와 같이 `cb-spider/cloud-driver-libs/.ssh-aws` 에 관련 파일이 존재하는 목록만 보입니다. 
![image](https://user-images.githubusercontent.com/46367962/136516754-670ef6e1-3197-414c-86af-46a78efc534c.png)

- `cb-spider/cloud-driver-libs/.ssh-aws` 에 관련 파일도 삭제하면, 
  - Spider에서 보이지 않기 때문에 삭제할 수 없고, AWS Console에서만 삭제할 수 있습니다. 

![image](https://user-images.githubusercontent.com/46367962/136511152-30a6e29e-9acd-4b3e-ad26-a07d36c7c0cc.png)

**[질문]**
- 예전처럼 Spider를 통해서 꼬인 정보를 관리할 수 있도록 
- 다음 위치에 관련 파일 여부에 상관 없이 목록을 올려주실 수 있나요? 
  - `cb-spider/cloud-driver-libs/.ssh-aws` 
- 삭제 요청시 파일만 존재하면 파일만 삭제해서 clean하고, 
  - AWS에만 존재하면 AWS 실제 KeyPair를 삭제해서 clean할 수 있을지 확인 부탁드립니다.

**Comment by dev4unet** [comment]
@powerkimhub 네, 로컬에 키 페어를 유지하는 이유는 **cb-user 생성을 위한 PublicKey때문에 그렇습니다.**
AWS API에서는 PublicKey를 조회하는 방법은 없으며 PrivateKey가 있으면 지금처럼 go 라이브러리를 이용해서 PublicKey생성이 가능하지만 AWS API로는 PrivateKey 조회는 불 가능하고 **PrivateKey  정보는 키페어를 생성할 때에만 전달 받을 수 있습니다.**

cb-user를 생성할 때 PublicKey가 필요하기 때문에 외부에서 전달 받아서 사용하거나 VM에 존재하는 키 파일을 리눅스 쉘 커맨드를 이용해서 복사하는 방법이 있습니다.

VM  생성 시 PublicKey를 외부에서 전달 받을 수 있으면 별도로 관리할 필요는 없지만..
지난번 cb-user 생성 정책에서 바리스타의 경우 PrivateKey와 PublicKey를 Local에 저장하고 바리스타에서 생성된 키만 사용하는 형태로 통일하는 방향으로 결정나서 local에서 관리하고 있습니다.

Local에서 관리하지 않으려면 VM 생성시에 파라메터로 PublicKey를 전달 받거나...
생성하려는 VM 이미지의 로그인 계정(예:ec2-user)을 알 수 있다면 useradd로 cb-user를 생성 후 OS 이미지에 존재하는 로그인 계정의 PublicKey파일을 생성된 cb-user에게 복사하는 형태로 cb-user 생성이 가능하기 때문에 VM 생성 요청 파라메터로 OS의 계정을 전달 받거나 PublicKey를 전달 받아야 합니다.

아니면 cb-user 이슈에서 설명 드렸던대로 "ec2-user / root / ubuntu / ..." 처럼 OS 이미지마다 사용하는 계정 정보를 바탕으로  해당 계정이 존재하면 해당 위치의 키 파일을 복사하는 형태의 스크립트를 만들어도 가능은 합니다만 cloud-init의 길이 제한이 있어서 작성 가능한 스크립트 파일의 크기가 제한되니 어느 정도 예외 처리에 제한은 있으리라 봅니다.

**Comment by dev4unet** [comment]
@powerkimhub 알리 클라우드는 웹 콘솔에서 테스트해 보면 정상적으로 동작하는데...

텐센트는 우분투 18.04에서 해당 스크립트를 이용하면 cb-user나 ubuntu 모두 로그인이 안되네요.
/home/ubuntu 계정은 .ssh폴더에 생성되는 인증키(authorized_keys)가 0바이트입니다.
/home/cb-user 계정은 .ssh폴더에 생성되는 인증키(authorized_keys)는 8바이트이며 "ssh-rsa"라는 내용 외에는 저장된 내용이 없네요.

**Comment by dev4unet** [comment]
@powerkimhub 보니까 텐센트는 /root/.ssh 폴더의 키가 0바이트네요.

**Comment by seokho-son** [comment]
@powerkimhub 지금은 지원 VM 이미지을 기본 Ubuntu로 테스트하고 계시긴 할텐데.. 
혹시 나중에 주요 지원해야 하는 VM 이미지가 추가되면.. 다시 주요 로직이 달라져야 하는 상황이 발생할 수도 있을까요..?

**Comment by powerkimhub** [comment]
@dev4unet 

- 캄사합니다.

**Comment by powerkimhub** [comment]
@dev4unet @hyokyungk @innodreamer 

- 혹시, 변경 사항 발생시 다음 링크도 확인 및 필요시 반영 부탁 드립니다. 
- https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-VM-User-Guide

**Comment by powerkimhub** [comment]
@dev4unet @hyokyungk @inno-cloudbarista @innodreamer 

### [Patch 대상 및 적용 현황]

1.  AWS:         patch 대상 => 적용 완료
2. *Azure:        patch 대상 => 진행중
3. *GCP:           patch 대상 확인 필요(현재 local에 키 파일 생성)
4. Alibaba:      patch 대상 => 적용 완료
5. Tencent:      patch 대상 => 적용 완료
6. IBM:            patch 대상 => 적용 완료
7. *OpenStack: patch 대상 => 진행중
8. Cloudit:       patch 대상 아님
9. *NCP:            patch 대상 확인 필요
10. *KT:             patch 대상 확인 필요

**Comment by innodreamer** [comment]
@powerkimhub 
KT Cloud의 cloud-init 방식을 보완했습니다.
VM 내 root 계정 위치의 public key를 복사해서 사용하는 방식으로 변경했고, cloud-init UserData script를 활용하여 적용했습니다.

https://github.com/cloud-barista/cb-spider/pull/538
https://github.com/cloud-barista/ktcloud/pull/50

NCP는 VM을 생성하면 root password를 제공하여 기본적으로 password 로그인만 가능해서 VM 내에서 root 계정 위치에 public key가 존재하지 않고, ubuntu 등의 기타 계정이 생성되어 있지않아 public key가 없어서 우선은 기존 방식(public key를 생성해서 VM에 적용하는 방식)을 cloud-init UserData script로 반영하는 방식으로 보완했습니다.

위의 내용은 아래의 표에 반영했습니다.
https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-VM-User-Guide

**Comment by powerkimhub** [comment]
[KT/NCP 적용]
- https://github.com/cloud-barista/cb-spider/pull/538
