### ISSUE TITLE
Retrieve price of Cloud VM Specs

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#505]
**What would you like to be added**
VM Spec 정보 조회 시, VM의 시간 당 사용 비용을 포함하여 정보 리턴 

[참고] CSP별 가격 조회 정보 및 API 참고
[AWS]
https://github.com/lyft/awspricing
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-ppslong.html

[GCP]
https://cloud.google.com/billing/v1/how-tos/catalog-api

[Azure]
https://docs.microsoft.com/ko-kr/rest/api/cost-management/retail-prices/azure-retail-prices

**Why is this needed**

가격 기반의 클라우드 서비스(VM) 배치를 위해서는 
VM의 가격 (러프하게는 시간당 가격) 정보가 주요합니다.

가능하다면~ 이를 클라우드 API를 통해 자동적으로 조회할 수 있으면 좋겠습니다.
(그렇지 못한 경우는 손수 작업하거나, 필요에 따라 지속적인 업데이트가 필요합니다.)

**Comment by powerkimhub** [comment]
@seokho-son 

- 다음을 활용하시면 되겠습니다. 
- [RestAPI Multi‐Cloud Price Information Guide](https://github.com/cloud-barista/cb-spider/wiki/RestAPI-Multi%E2%80%90Cloud-Price-Information-Guide)
