### ISSUE TITLE
[IBM] spec별 RAM 크기 오류

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#513]
**What happened**
: 
![image](https://user-images.githubusercontent.com/46767780/140461995-cd3c6240-904f-4536-a120-ea09125887fd.png)

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 
MB 단위로 표시가 되면 좋을 것 같습니다~~
(현재는 `8GB` 와 같이 뒤에 `GB` string도 같이 붙어서 옴)

**Any other context**
:

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 참고하시기 바랍니다.
  - https://github.com/cloud-barista/cb-spider/issues/488#issuecomment-949385927

**Comment by powerkimhub** [comment]
- fixed it with https://github.com/cloud-barista/cb-spider/pull/515
