### ISSUE TITLE
Azure LocationNotAvailableForResourceGroup Error on image info retrieving

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#527]
아래 리전에서 이미지 정보 조회시,  LocationNotAvailableForResourceGroup, NoRegisteredProviderFound 에러 등이 발생합니다.

azure australiacentral2
azure francesouth
azure germanynorth
azure southafricawest
azure switzerlandwest
azure uaecentral

----

[CLOUD-BARISTA].[ERROR]: 2021-11-11 17:29:10 CCMCommon.go:174, github.com/cloud-barista/cb-spider/api-runtime/common-**runtime.ListImage()** - resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" 

Message="The provided location 'germanynorth' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast,jioindiawest,westus3,australiacentral2,koreasouth'."

[CLOUD-BARISTA].[ERROR]: 2021-11-11 17:31:45 CCMCommon.go:186, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.ListImage() - compute.VirtualMachineImagesClient#ListPublishers: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" 

Message="No registered resource provider found for location 'australiacentral2' and API version '2021-03-01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, australiacentral, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, francecentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, jioindiawest, westus3, koreasouth'."

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo @innodreamer @hyokyungk @inno-cloudbarista 

- bug는 아니고, 이들 6개 Region들은 별도 요청이 필요한 Region들 이네요. 
- Azure는 이와 같은 Region이 현재 총 8개인데, Region이 부족하면 추가 신청하면 됩니다. 

**[Deep dive]**
  - ref) https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions#azure-regional-pairs
  - 링크에 따르면, 추가 요청이 필요한 Region은 현재 총 8개
    ```
    Australia Central 2*
    Brazil Southeast*
    France South*
    Germany North*
    Norway West*
    South Africa West*
    Switzerland West*
    UAE Central*
    #----------
    US DoD East*
    US DoD Central*
    US Gov Arizona*
    US Gov Texas*
    US Gov Iowa*
    US Gov Virginia*
    US Gov Virginia*
    US Gov Texas*
    ```
- 위 반환 메시지를 기준으로 보면, 35개 Region들만 사용 가능하고, 
- 오늘 날짜 azure CLI 기준으로 확인해보면, 47개 Region 중 39개 Region(8개 제외하면)이 기본적으로 사용 가능합니다.
  - [How to get Azure available Regions](https://github.com/cloud-barista/cb-spider/wiki/How-to-get-Azure-available-Regions)

- 참고로, CSP들의 **Region 정보를 API**로 제공하는 것을 다음 이슈에서 고민해볼 예정입니다. 
  - https://github.com/cloud-barista/cb-spider/issues/408
