### ISSUE TITLE
[AWS] `RootDiskType`, `RootDiskSize`, `RootDeviceName` comes empty

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#531]
**What would you like to be enhanced**
: 

TB -> SP 통해서 VM 만들 때
`RootDiskSize` 를 명시하면 적용이 되는 것은 확인했으나
![image](https://user-images.githubusercontent.com/46767780/141749554-2dc06b6a-443a-496c-95e9-50092e8648a5.png)

VM 생성 요청에 대한 SP의 응답에는
`RootDiskType`, `RootDiskSize`, `RootDeviceName` 필드가 비어 있는 것으로 보입니다.

(왜 그런고 하니..)
TB VM 객체 안에는
`cspViewVmDetail` 필드가 있고, SP에서 온 응답을 이 필드에 그대로 넣는데,
AWS에 VM을 만드니 `cspViewVmDetail` 필드의 내용이 다음과 같습니다.

```JSON
            "RootDiskType": "",
            "RootDiskSize": "",
            "RootDeviceName": "",
```

**Why is this needed**
: 

**Proposed solution**
:

**Comment by powerkimhub** [comment]
@jihoon-seo (@dev4unet )

- 이슈 공유 캄사드립니다. 
- 관련 사항은 다음 이슈에서 추진 중에 있습니다. 
  - https://github.com/cloud-barista/cb-spider/issues/348#issuecomment-967039279
- 현 이슈는 close하고, 위 이슈가 완료되면 노티해드리지요~
