### ISSUE TITLE
SecurityGroup 관련 에러 메세지가 좀 더 명확했으면 좋겠어요

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#542]
**What would you like to be enhanced**
: 

예를 들어, `mock-seoul-jhseo` 라는 SG에 대해 GET API를 호출하면

`"sg-mock-seoul-jhseo does not exist!\"` 라는 메세지가 리턴됩니다.

이로 인해 사용자가 '내가 `sg-mock-seoul-jhseo` 를 조회했었나?' 등의 오해를 할 여지도 있으므로

다음과 같이 리턴해 주면 어떨까요? 😊

`"The security group 'mock-seoul-jhseo' does not exist!\"`

**Why is this needed**
: 

**Proposed solution**
:

**Comment by powerkimhub** [comment]
- Thanks, @jihoon-seo 
- fix it with https://github.com/cloud-barista/cb-spider/commit/0380aea0d991dd51dd79b7d1958c010a38082add
