### ISSUE TITLE
Enhance handling of local SSH Key files

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#548]
@dev4unet @inno-cloudbarista (@innodreamer )

### [현황]
- Spider 내부에서 SSH Key 관리 방법은 현재 2가지 타입이 존재합니다. 
(1) CSP 기능 활용 타입
(2) DRV 기능 제공 타입(local file로 관리)
~~(3)~~ CSP+DRV  혼용: 현재는 사용되지 않는 타입

- 현재 (2)번 타입의 local file 관리 방식은 다음과 같은 잠재적 이슈가 존재합니다. 
  - 입력되는 Key Name 형식에 따른 오류 발생 가능성 존재
  - file 형태 노출로 손실(훼손) 및 보안 문제 가능성 등

### [제안]
- 위와 같은 사유로 다음과 같은 방법으로 개선하고자 합니다. 
  - 서로 다른 driver에서 공통으로 사용되는 기능을 공통 함수화하여 제공
  - local file 대신 cb-store를 이용한 private key 저장 관리(backend store: nutsdb 또는 etcd 활용 가능)
  - public key는 별도 저장 관리 하지 않습니다. 필요시 다음 함수로 생성하여 활용
    - https://github.com/cloud-barista/cb-spider/blob/5a5445d5c0fe6be52384932d92ce2a68b05a7d66/cloud-control-manager/cloud-driver/common/common.go#L154
  - 이러한 기능을 제공하는 driver 개발용 common API 제공
    - https://github.com/cloud-barista/cb-spider/blob/master/cloud-control-manager/cloud-driver/common/common.go
  - common API 활용 방법은 다음을 참고해 주시기 바랍니다. 
    - https://github.com/cloud-barista/cb-spider/blob/master/cloud-control-manager/cloud-driver/common/test/keypair_manage_test.go
    - 필요 환경 변수 및 예시
      ```
      export CBSPIDER_ROOT=$HOME/cb-spider
      export CBSTORE_ROOT=$HOME/cb-spider
      ```
  - 향후, 저장되는 private Key 값은 common API 수준에서 encryption 처리 예정입니다.  

- 적용 대상 Driver
  - CloudIT Driver
  - GCP Driver
  - NCP Driver (Added, 2021.12.24)

- 추진 가이드
  - 현재는 기본 기능만 시험해본 상태입니다. 
    - VM 생성에 적용 및 VM 로그인 시험 등이 필요합니다. 
  - 효율적인 적용을 위해서 GCP 먼저 적용 완료 후 검증이 완료 되면, 
    - CloudIt을 추진하시는 것이 좋을 듯합니다. 
  - 적용에 문제가 있으시면 현재 이슈에 답글로 공유해주시기 바랍니다.

**Comment by powerkimhub** [comment]
#### [부연 설명]
- Spider Server가 내려 보내는 KeyPair NameId는 Unique 하다고 생각하시고 처리하시면 되겠습니다.
- List Key의 경우 다음 API가 제공하는 모든 목록을 KeyPairInfo로 변환해서 그대로 올려 주시면 되겠습니다. 
  - https://github.com/cloud-barista/cb-spider/blob/28965112d13105d7d224915f6beaac1fe3427fec/cloud-control-manager/cloud-driver/common/common.go#L92

**Comment by dev4unet** [comment]
@powerkimhub  GCP의 경우 기존에는 **VM 생성 시 Public Key를 사용**하기에 KeyPair 생성 및 조회 시에도 KeyPairInfo에있는 PublicKey 필드의 정보를 함께 리턴하고 있었습니다.

공통함수의 경우 PublicKey를 취급하지 않기에 KeyPair 생성시 함께 생성된 PublicKey를 사용하지 않는 형태로 수정할 경우...
키페어 조회나 목록에서는 KeyPairInfo의 PublicKey 정보를 공백("")으로 리턴하고 VM 생성 시에만 MakePublicKeyFromPrivateKey()를 이용해서 처리하도록 할까요?

아니면 KeyPair조회나 목록 요청시에도 매번 모든 KeyPair에 대해 MakePublicKeyFromPrivateKey()를 호출해서 PublicKey를 생성 해서 KeyPairInfo의 PublicKey 필드 값을 내려 보내야 할까요?

만약, KeyPair 정보 조회나 KeyPair 목록의 결과 값에  PublicKey가 포함될 필요가 없으면 기존의 PublicKey를 처리하는 부분을 삭제하고 VM 생성 시에는 MakePublicKeyFromPrivateKey()를 이용하도록 수정할 생각입니다.

그렇지 않고 조회나 목록에서도 PublicKey가 필요하다면 성능상 공통함수에 PublicKey가 포함되는게 좋을 듯싶습니다.

**Comment by powerkimhub** [comment]
@dev4unet 

- 의견 주신 것처럼, 
- KeyPair 생성시에만 제공해 주시면 되겠습니다. 
- Get/List KeyPairInfo 제공 시에는 안올려 주셔도 되겠습니다.

**Comment by powerkimhub** [comment]
- [GCP] 적용 완료 ( @dev4unet , Thanks)
  - https://github.com/cloud-barista/cb-spider/pull/550

- [CloudIt] 적용 및 시험 부탁 드립니다. ( @inno-cloudbarista )

**Comment by powerkimhub** [comment]
@innodreamer 

- NCP 적용 필요

**Comment by powerkimhub** [comment]
- CloudIt 적용 완료 (@inno-cloudbarista , thanks )
  - closed in https://github.com/cloud-barista/cb-spider/pull/569
