### ISSUE TITLE
Can't delete resources by name including parentheses when using spctl 

### ISSUE THREAD

**Issue by atg0831** [cloud-barista/cb-spider#549]
**What happened**
: cb-spider의 CLI인 spctl로 소괄호가 포함된 name으로 리소스 생성하면 spctl로 삭제시 syntax error가 발생
```bash
./spctl region create -i json -d '{
  "RegionName": "aws-us(ohio)-east-2",
  "ProviderName": "AWS",
  "KeyValueInfoList": [
    {
      "Key": "Region",
      "Value": "us-east-2"
    },
    {
      "Key": "Zone",
      "Value": "us-east-2a"
    }
  ]
}'
```
위와 같이 aws-us(ohio)-east-2로 소괄호가 포함된 region name으로 region 리소스 생성
```bash
./spctl region delete aws-us(ohio)-east-2
-bash: syntax error near unexpected token `('
```
`aws-us(ohio)-east-2` region name으로 삭제를 하였을 경우 위와 같이 syntax error가 발생

**Proposed solution**
: 사용자가 소괄호를 포함한 이름으로 리소스를 생성했을 때 그 이름으로 삭제를 해도 정상적으로 동작된다면 좋을 거 같습니다.

**Any other context**
: region 말고도 다른 리소스(driver, credential 등) 삭제할 때도 같은 문제가 발생합니다.

**Comment by atg0831** [comment]
소괄호 앞에 '' 따옴표를 붙여서 삭제를 하니 정상적으로 삭제가 잘 되네요;
```bash
./spctl region delete -n aws-us'(ohio)'-east-2
[CB-GRPC].[INFO]: 2021-12-07 23:59:16 client_interceptors.go:38, github.com/cloud-barista/cb-spider/api-runtime/grpc-runtime/interceptors/accesslog.UnaryClientInterceptor.func1() - grpc client unary call : /cbspider.CIM/DeleteRegion service [36 ms]
Result: true
```

**Comment by powerkimhub** [comment]
@atg0831, thanks for this report

- @jmleefree,
-  `'(' | ')'` 입력시 quotation 등의 처리를 http url escape처럼 통상 사용하는 방법으로 봐야 할까요?
- 아니면, 다음처럼 quotation 없이 사용도 가능하게 할수 있을까요?
  `./spctl region delete -n aws-us(ohio)-east-2` 
- 현재 성공 예시는 다음과 같습니다. 
  `./spctl region delete -n 'aws-us(ohio)-east-2'`
  `./spctl region delete -n "aws-us(ohio)-east-2"`
  `./spctl region delete -n aws-us'(ohio)'-east-2`
  `./spctl region delete -n aws-us"(ohio)"-east-2`
  `./spctl region delete -n aws-us\(ohio\)-east-2`

**Comment by jmleefree** [comment]
@powerkimhub 

에러가 난 내용이 다음과 같은것으로 보아 shell 단에서 에러가 나온것 같습니다. 
이것은 shell 규칙을 따라야 할 것 같습니다.
**-bash: syntax error near unexpected token `('**

참고로 cobra 에서는  Pflag library 를 사용해서 flag 값을 가져오고 있습니다.
  => https://stackoverflow.com/questions/67295788/how-to-pass-space-to-cobra-cli-string-slice-flag
  => 실제로 찾아보니 https://github.com/spf13/pflag/blob/master/string_to_string.go의  85라인에서
        r := csv.NewReader(strings.NewReader(val)) 가 있는 것으로 보아
       golang strings 과  encoding/csv 를 사용해서 flag 를 처리하고 있는 것으로 보입니다.

**Comment by powerkimhub** [comment]
- @jmleefree, Thanks for this analysis.
