### ISSUE TITLE
SP-XID is too short to manage resources with the CSP Console

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#561]
- 현황: 공통 관리를 위해서 CSP 자원 생성시 자원 ID 길이를 지원하는 모든 CSP의 최소 길이에 맞춤
  - ID 공통 길이: NCP=30자 (예외:Tencent 25자)
    - 세부내용참고: [IID2 Design](https://github.com/cloud-barista/cb-spider/wiki/Why-and-how-to-upgrade-Spider-Integrated-ID-Manager(IID2-Design))
  - 이 공통 CSP ID를 SP-XID라고 함.
    - SP-XID 예시: aws-seoul-c59d3bqba5o1pd5rn65g (30자)

- 이슈: 자원을 CSP 컨솔 및 API를 통해서 직접 관리하고자 할 경우, SP-XID 길에 제약으로 다음 예시처럼 관리에 어려움이 있음

  ![image](https://user-images.githubusercontent.com/46367962/151110101-53f91edb-c7a1-4220-9f19-115dc533927d.png)

-------

- 계획: 가급적 CSP별로 제공하는 ID 길이로 SP-XID 길이를 가변적으로 제공하고자 함
- 계획: CSP별 자원 ID 최대 길이 현황 분석 후 선별적 반영

    | VPC | Subnet | SecurityGroup | KeyPair | VM | 추천 ID Length
  -- | -- | -- | -- | -- | -- | --
  AWS | 255 | 256 | 255 | 255 | 255 | 255
  Azure | 64  | 80  | 64  | 80  | 64  | 64 
  GCP |  63 | 63  | 63  | -  | 63  |  63
  Alibaba | 128  | 128  | 128  | 128  | 128  |  128
  Tencent | 60  | 60  | 60  | 25  | 88  |  25(고민)
  IBM(VPC) | 63  | 63  | 63  | 63  | 63  | 63 
  OpenStack | 255  | 255  | 255  | 255  | 255  | 255 
  CloudIt | -  | 45  | 45  | -  | 45  | 45 
  NCP | -  | -  | only Console  | 30  | 30  |  30
  KT | -  | -  | 255  | -  | 확인중  |  
  NHN | only Console  | only Console  | 255  | 255  | 255  |  255

----

**Comment by powerkimhub** [comment]
@hyokyungk @inno-cloudbarista @dev4unet @innodreamer 

- 관련하여, AWS 제외한 CSP의 자원별 Max ID 테스트 부탁 드립니다. 
- 문서로 확인해도 되겠지만, 자원별로 차이가 있는 것도 같고 신뢰가 안가는 부분이 있습니다. 
- 해서 시험 결과로 공유 부탁드립니다. 
  - 공유 예시
    - AWS: Subnet 256자, 그 외 자원 255자
 
- ID Sample: 312자 (테스트 시 복사해서 쓰세요)
  ```
  abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
  ```

- 참고: AWS Console에서 시험 결과
```
<AWS-VPC> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu

<AWS-Subnet> 256
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv

<AWS-SecurityGroup> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu

<AWS-KeyPair> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu

<AWS-VM> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu
```

**Comment by powerkimhub** [comment]
@jihoon-seo @seokho-son 

- 먼저 AWS 반영 및 시험 결과입니다. 
  - https://github.com/cloud-barista/cb-spider/commit/3b3fa2b7eed661d2dd92b65418ae7662366b998c
  - 참고로, IID2의 경우 Spider 사용자가 입력하는 NameID는 3,200자 이상까지도 등록이 가능하며,
  - AWS경우 AWS로 저장되는 자원의 Name의 길이가 AWS 최대 길이인 255자 미만으로 맞추어 저장됩니다. 
  - 예시) 
    - input ID: earth-korea-daejeon-etri-cloudsw-multicloud-cloud-barista-aws-ohio-vpc-01
    - AWS에 저장된 Name:

![image](https://user-images.githubusercontent.com/46367962/151118769-f3f87e04-fe3d-4de0-a6ec-260d09920ec1.png)

**Comment by dev4unet** [comment]
각 CSP의 콘솔에서 테스트 했습니다.

**GCP**
`
<GCP - VPC> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<GCP -Subnet> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<GCP -SecurityGroup> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<GCP -KeyPair> - 미지원

<GCP -VM> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk`
`

**Tencent**
<Tencent- VPC> 60
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh

<Tencent-Subnet> 60
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh

<Tencent-SecurityGroup> 60
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh

<Tencent-KeyPair> 25
abcdefghijklmnopqrstuvwxy

<Tencent-VM> 88
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij


**Alibaba**
<Alibaba - VPC> 128
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx

<Alibaba - Subnet> 128
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx

<Alibaba -SecurityGroup> 128
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx

<Alibaba -KeyPair> 128
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx

<Alibaba -VM> 128
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx

**Comment by powerkimhub** [comment]
@dev4unet 

- 감사합니다.
- Tencent 25, ㅠㅠ

**Comment by inno-cloudbarista** [comment]
늦게 답변드려 죄송합니다.
각 CSP별 콘솔 테스트 결과입니다

Azure
========
```
<Azure-VPC> 64
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl

<Azure-Subnet> 80
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab

<Azure-SecurityGroup> 64
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl

<Azure-KeyPair> 80
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab

<Azure-VM> 64
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl
```
Openstack
========
```
<Openstack-VPC> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu

<Openstack-Subnet> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu

<Openstack-SecurityGroup> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu

<Openstack-KeyPair> 255
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv

<Openstack-VM> 25
abcdefghijklmnopqrstuvwxy
```
IbmVPC
========
```
<IBMVPC-VPC> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<IBMVPC-Subnet> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<IBMVPC-SecurityGroup> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<IBMVPC-KeyPair> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk

<IBMVPC-VM> 63
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk
```

Cloudit
======
```
<Cloudit-VPC> X
VPC 없음(Subnet대체)
<Cloudit-Subnet> 45
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs
<Cloudit-SecurityGroup> 45
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs
<Cloudit-KeyPair> X
키페어 없음
<Cloudit-VM> 45
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs
```

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 테스트 및 공유 감사합니다.

**Comment by innodreamer** [comment]
@powerkimhub 현재까지 파악된 내용 공유해드립니다.
아래 내용에서 KT Cloud는 더 확인 후 보완하겠습니다.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/오병택/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/오병택/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | VPC | Subnet | SecurityGroup | KeyPair | VM | 추천 ID Length
-- | -- | -- | -- | -- | -- | --
NCP |   |   | 30     (콘솔에서만 생성 가능. API는 생성/삭제 미지원) | 30 | 30 | 30
KT Cloud |   |   | Driver   내에서 생성해서 적용하므로 제한없음. | 콘솔   : 8      API : 255 | 콘솔/API   : 제한 가이드라인 없음.     (255는 안되고, 정확한 제한 수 문의중임) |  
NHN Cloud | 32     (콘솔에서만 생성 가능. API는  생성/삭제 미지원) | 32     (콘솔에서만 생성 가능. API는  생성/삭제 미지원) | 255 | 콘솔   : 20     API : 255 | 콘솔   : 50     API : 255 | 255



</body>

</html>

**Comment by powerkimhub** [comment]
- Thanks, @innodreamer 
- 혹시, 밑줄친 2개 바뀐거 아닌지요?
![image](https://user-images.githubusercontent.com/46367962/153181526-0f498de2-0fdf-4dec-bd9a-941f313c2828.png)

**Comment by powerkimhub** [comment]
[참고]
- 현재 IID2 저장을 위해서는 저장할 수 있는 **CSP의 자원 ID Max 길이는 21보다는 커야 함**.
- SP-XID format이 다음과 같고, 여기서 XID 길이가 20char, 거이에 구분자 '-'를 포함시키면 21char
  - "{UID}-{XID}"
- 현재 연동 대상 CSP들의 자원 중 가장 짧은 ID Max 길이는 `25'

**Comment by powerkimhub** [comment]
- completed via https://github.com/cloud-barista/cb-spider/commit/4ca5aca66bb5f02ea2eaae1b5f58f65992854a5a

---

### [@hyokyungk @inno-cloudbarista @dev4unet @innodreamer]

#### [공유: 적용 방법]
- Tencent, Azure 등과 같이 특정 CSP의 자원별로도 ID 최대 가능 길이가 다름
  - 당초 계획과 달리, CSP의 자원별로 CSP에 요청하는 ID 길이를 가변적으로 생성되도록 수정함
- 향후, 다른 CSP 연동 추가를 고려하여 코드 수정 없이, 자원별 ID 최대 길이를 제공할 수 있도록 구현함
- driver단에서는 root disk type 설정과 유사한 방법으로 다음과 같이,
  - CSP 메타 정보 파일에 자원별 ID Max Length를 설정하면 자동 적용됨
  - CSP 메타 정보 파일 TENCENT 예시 참고: cloud-driver-libs/cloudos_meta.yaml 
  ```
  TENCENT:
    region: Region / Zone
    credential: ClientId / ClientSecret
    rootdisktype: CLOUD_PREMIUM / LOCAL_BASIC / LOCAL_SSD / CLOUD_BASIC / CLOUD_SSD
    # idmaxlength: VPC / Subnet / SecurityGroup / KeyPair / VM
    idmaxlength: 60 / 60 / 60 / 25 / 88
  ```

#### [공유: 시험결과]
- 변화가 심한 Tencent와  'idmaxlength' 값을 사용하지 않는 Mock에 대해서 시험함.
- 시험 방법: AdminWeb으로 생성 후 Tencent Console에서 확인
```
User NameID(135자)> vpc-01-abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx	
Tencent Name(60자)> vpc_01_abcdefghijklmnopqrstuvwxyzabcdef_c81qmriba5obsj0t0nkg

User NameID(134자)> sg-01-abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx
Tencent Name(60자)> sg_01_abcdefghijklmnopqrstuvwxyzabcdefg_c81qnlqba5obsj0t0nlg

User NameID(135자)> keypair-01-abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx
Tencent Name(25자)> keyp_c81r46qba5o42d8uja5g

User NameID(135자)> vm-01-abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx
Tencent Name(88자)> vm_01_abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi_c81ra7qba5o42d8uja80
```

#### [공유: 향후 관리 방법 및 보완 필요 드라이버]
- 현 이슈에 취합된 driver에 대해서는 모두 반영한 상태입니다.  
  - 혹시라도 향후에 자원별 ID 최대 길이 수정이 필요하시면 각 driver 리더 분들께서
  - cloudos_meta.yaml 파일 수정 후 PR 부탁드립니다. 
  - 신규 driver 추가 하실때에도 cloudos_meta.yaml 파일에 추가해주셔야 합니다. 

- 값을 설정하지 않으면, 현재 default 30자 길이로 처리되고 있습니다. 
  - 30자는 가장 제약이 심했던, NCP VM 길이에서 왔지만, 현재는 큰 의미는 없습니다. 
  - 더 높여도 되지만, default 값은 Mock, Cloud-Twin 등에서만 사용될 것이어서 현재는 그냥 두었습니다. 

- 추가 확인 및 보완이 필요한 driver (@innodreamer )
  - NCPVPC: 다른 CSP와 마찬가지로 현재 이슈에 reply 달아 주시고, 
    - cloudos_meta.yaml 파일에 추가 후 PR 부탁드립니다. 
    - 기존처럼 실제 시험 후 Max length 값을 설정해 주셔야 합니다.
    - 간혹, document와 달른 경우 잠재적인 오류로 숨어 있을 수 있습니다. 
  - KT: 미확인 부분 확인이 되시면, 현재 이슈에 reply 달아 주시고,  
    - cloudos_meta.yaml 파일에 추가 후 PR 부탁드립니다.

**Comment by innodreamer** [comment]
@powerkimhub 네. KT Cloud 관련하여 확인하신것처럼 맞는 내용입니다.

참고로 말씀드리면, KT Cloud CSP는 Security Group이라는 개념이 없고, VM에 public ip를 port forwarding으로 매핑 시킨 후 그 ip 기준으로 security rule들을 생성하는 방식을 사용합니다.
따라서, KT Cloud 연동 드라이버는 S/G 생성시 S/G 생성 요청한 사항들을 yaml 파일 정의해서 저장했다가 VM 생성 요청이 오면 VM 생성 마지막 단계에서 public ip를 생성하고 VM 생성시 매핑한 S/G들에 대한 yaml 파일을 읽어와서 그 public ip에 security rule들을 생성하는 방식으로 개발했습니다.
