### ISSUE TITLE
Error : Get VM info/list through REST API using curl command on CLI

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#571]
**What happened**
: CB-Spider API 기준으로 최근 update된 NCP driver 테스트를 위해 curl 명령어로 테스트하는 NCP full test script를 활용해 VM 생성까지 마친 후, curl 명령어로 GetVM과 ListVM을 실행시키면 아래와 같은 메시지가 return됩니다.
참고로, AdminWeb을 통해서 테스트할때는 VM list가 제대로 나타납니다.

< Curl 실행시 return message >
- VM: List
{
   "message" : "ResourceType is empty!"
}

- VM: Get
{
   "message" : "ResourceType is empty!"
}

< Error Log >
[CLOUD-BARISTA].[ERROR]: 2022-02-24 20:26:52 CCMCommon.go:2678, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.getSetNameId() - ResourceType is empty!
[CLOUD-BARISTA].[ERROR]: 2022-02-24 20:26:52 CCMCommon.go:2629, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.ListVM() - ResourceType is empty!

**What you expected to happen**
: VM list와 VM 세부 정보가 제대로 return되어야함.

**How to reproduce it (as minimally and precisely as possible)**
: NCP driver build 후 Spider server 구동
: NCP connection config script를 실행해서 connection 관련 기본 정보들을 반영
: NCP full test script를 실행

**Comment by powerkimhub** [comment]
@innodreamer 

[분석 결과]
- VMHandler.ListVM() 결과로 올라오는 
- VMInfo에서 VPC SystmeId가 다음과 같이 기존의 default 값으로 올라고 있습니다. 
 
  ```
  {NameId:"ncp-vpc-01", SystemId:"000001"}
  ```

- 이 부분을 확인 해보시면 좋을 듯합니다. 
https://github.com/cloud-barista/ncp/blob/3572463fcd7c01073e5909e2696d430b9fa16cd6/ncp/resources/VMHandler.go#L496

```
		VpcIID: irs.IID{
			NameId:   defaultVPCName,
			SystemId: defaultVPCID,
		},
```

- `defaultSubnetID` 등 유사 값도 확인 부탁 드립니다.

**Comment by powerkimhub** [comment]
@innodreamer, Thanks. 

- fixed in https://github.com/cloud-barista/cb-spider/commit/b0a30ab1a9db7a7e680d34f3802ebeacda7aca6d

**Comment by innodreamer** [comment]
@powerkimhub 위의 보완해주신 commit은 S/G 관련 commit이니 제가 올린 다른 issue에 해당되는 거 같습니다.^^
이 issue는 다시 open해주시고요!!

**Comment by powerkimhub** [comment]
@innodreamer 

- 앗, 그러네요^^
- 다시 오픈하겠습니다.

**Comment by innodreamer** [comment]
@powerkimhub NCP Classic driver를 보완해서 위의 문제를 해결해서 본 issue를 close합니다.

기존 NCP Classic driver에서는 VPC, Subnet 정보와 VM 간의 mapping 관계가 없어서 VM instance의 tag를 활용해서 mapping 했습니다.
https://github.com/cloud-barista/ncp/issues/65
