### ISSUE TITLE
Error : Delete S/Gs through REST API using curl command on CLI

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#572]
**What happened**
: CB-Spider API 기준으로 NCP driver 테스트를 위해 curl 명령어로 테스트하는 NCP full test script를 활용한 테스트 진행시, curl 명령으로 NCP driver S/G들을 정상적으로 삭제 후 다시 삭제를 요청하면 아래와 같은 오류가 발생합니다.
(다시 요청시 driver 단까지 내려가지 않고 오류 발생)

< Curl 실행시 return message >
(최초 삭제시)
- SecurityGroup: Delete
####################################################################
{
   "Result" : "true"
}
{
   "Result" : "true"
}
{
   "Result" : "true"
}

(다시 삭제 요청시)
- SecurityGroup: Delete
####################################################################
{
   "message" : "Internal Server Error"
}
{
   "message" : "Internal Server Error"
}
{
   "message" : "Internal Server Error"
}

< Error Log >
[CLOUD-BARISTA].[INFO]: 2022-02-24 20:36:41 IIDManager.go:163, github.com/cloud-barista/cb-spider/cloud-control-manager/iid-manager.(*IIDRWLOCK).ListResourceType() - call ListResourceType()
[CLOUD-BARISTA].[INFO]: 2022-02-24 20:36:41 nutsdb-driver.go:160, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.(*NUTSDBDriver).GetList() - Key:/resource-info-spaces/iids:sg/ncp-korea1-config
{"time":"2022-02-24T20:36:41.211608722+09:00","level":"-","prefix":"echo","file":"recover.go","line":"92","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 238 

**What you expected to happen**
: 삭제된 S/G을 다시 삭제 요청하면 존재하지 않는 S/G이라고 return되어야함.

**How to reproduce it (as minimally and precisely as possible)**
: NCP driver build 후 Spider server 구동
: NCP connection config script를 실행해서 connection 관련 기본 정보들을 반영
: NCP full test script를 실행

**Comment by powerkimhub** [comment]
@innodreamer, Thanks. 

- fixed in https://github.com/cloud-barista/cb-spider/commit/b0a30ab1a9db7a7e680d34f3802ebeacda7aca6d
