### ISSUE TITLE
[AWS driver] ListVMhas nil pointer dereference, when ListVM

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#573]
- Spider를 통하지 않은 VM의 경우 KeyPair 없이 생성된 VM이 존재할 수 있음
- ListVM 시에는 이러한 VM들도 포함되어 제공되고 있음
- 이 경우 아래 위치에서 `nil pointer` 오류가 발생하고 있음

https://github.com/cloud-barista/cb-spider/blob/63bc71fbee1d668f6467c3aa0e2a9235e308daaa/cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go#L708

**Comment by dev4unet** [comment]
AWS에서 키페어 없는 VM생성 기능을 지원하므로 기존의 VM 필수 정보에서 키페어를 제거하고 옵션으로 처리하도록 수정했습니다.

**Comment by powerkimhub** [comment]
@dev4unet, Thanks.
