### ISSUE TITLE
When guest OS is CentOS, Cloud-Init code of each driver should be modified.

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#575]
**What would you like to be enhanced**
: VM의 Guest OS가 CentOS 일 경우에도 cloud-init 코드가 정상적으로 적용되도록 보완되어야함.

**Why is this needed**
: Guest OS가 CentOS 일 경우에 기존의 Ubuntu 기준의 cloud-init 코드로는 정상적으로 적용이 않되는 경우가 발생함.

**Proposed solution**
: CentOS 일 경우에도 적용되게 하기 위해 다음의 방법중 하나로 적용을 제안함.
 - 두 개 Guest OS에서 모두 실행되는 linux command를 활용한 코드를 생성하거나
 - 하나의 cloud-init 코드내에서 OS를 자동으로 구분해서 적용되도록 하거나
 - Guest OS별 별도의 cloud-init 코드를 생성해 놓고, 사용자가 VM 생성시 OS를 선택해서 적용하도록 하거나 드라이버 내에서 VM Image 정보를 활용해 자동으로 선택되게 적용함.

**Comment by powerkimhub** [comment]
@innodreamer 

- 분석 및 내용 공유 감사드립니다. 
- GuestOS 추가 지원은 연관 Framework 및 전반적인 지원 가능 여부 등 현황 파악이 선행되어야 할 것 같습니다.  
- 추후 전반적인 현황 파악 후 진행 결정 된다면, 
- 제안 주신 이슈 고려토록 하겠습니다.

**Comment by powerkimhub** [comment]
- 현재 단계 공식 지원 GuestOS에 따른 반영 및 시험이 완료됨
  - Ubuntu 18.04+
  - Debian 10
  - Windows 2012 R2

- 추후 필요 시점에
