### ISSUE TITLE
[CloudIt] Creating VPCs should be improved

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#576]
[CloudIt VPC/Subnet]
- CloudIt은 VPC 기능을 제공하지 않으며, 단일 고정된 'Default Network'을 제공
- Subnet은 고정된 서브넷 대역 중 선택하여 생성 가능

[Spider Mapping 및 제약 사항]
  - VPC: 이름이 고정된 Default-VPC 1개만 생성 가능
  - Subnet: 10.0.8.0/22, 10.0.12.0/22, 10.0.16.0/22 등 제한된 서브넷 추가 가능

[현황 및 Issue]
- Spider 서버 수준에서 1번째 VPC 'vpc-01' 생성을 요청하면, 
  - 정상 생성 및 동작됨
- Spider 서버 수준에서 2번째 VPC 'vpc-02' 생성을 요청하면, 
  - 생성된 것처럼 결과를 반환하지만, 
  - list에 2번째 생성한 'vpc-02' 이름으로 2개가 보이는 등 동작이 바르지 않음.

[expected]
  - 1개 이상 VPC가 생성되지 않도록 에러 처리 등 개선 필요

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 관련하여 driver layer에서 1개를 초과하는 VPC 생성 요청시에
- driver 단에서 이를 인지하고 에러 처리 방법이 있는지 점검 부탁드립니다. 
- 가급적 서버 단에서는 Spider 기본 개념에 맞도록 
  - driver common api를 통해서 CSP 무관하게 공통 처리를 하고자 합니다. 
- Driver 단에서 방안이 없거나 복잡하면, 서버 단에서 처리 예정입니다. 
- 관련 의견 부탁드립니다.

**Comment by inno-cloudbarista** [comment]
해당 이슈는 Cloudit의 VPC가 1개로 고정되어 있으므로, 
VPC가 생성되었다면 추가적인 CreateVPC를 요청을 막는 처리하는 로직이 필요하다고 이해했습니다.

해당기능 제공을 위해 아래와 같이 진행할 예정입니다.
서브넷의 유무를 통해 VPC 생성을 인지

A: 첫 VPC 생성 성공 
A-1. VPC 생성시 서브넷을 생성하여 성공 
- subnet이 추가됨 (VPC 존재한다 판단)

A-2.  두번째 VPC 생성 요청 
- 이미 subnet이 존재하므로 생성 불가

B: 첫 VPC 생성 실패
B-1. VPC 생성시 서브넷을 생성하여 실패 
- 미리 생성된 서브넷 클린

B-2.  두번째 VPC 생성 요청 
-  처음 요청이 실패 => 서브넷이 없으므로(VPC 존재하지 않는다 판단) 생성 요청 가능

해당 기능을 위해 Default Network 서브넷의 10.0.0.0/22영역 또한 서브넷 생성가능 대역에서 제외하거나 Default Network을 없이 제공할 예정입니다.
 => 미리 생성된 Default Network의 기능 조사 후 공유하겠습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 제안 방법 공유 감사드립니다. 
- 우려되는 부분이 있어서
- 관련하여, 문의 및 다른 방법 제안 드립니다. 

#### (Q1)
- CloudIt의 경우 Connection 설정시 등록되는 credential 정보가 다음과 같습니다. 
  ```
   credential: IdentityEndpoint / AuthToken / Username / Password / TenantId
  ```
- credential 정보가 다르면, Default Network/subnet 자원은 독립적으로 운영이 가능한지요?
- 독립운영이 가능하지 않다면, 제안해주신 방법은 간섭에 의해서 오동작할 수 있을 것 같습니다.
- 독립 운영이 가능하다 해도 해당 TenantId 자원은 Spider 전용으로만 사용해야 한다는 제약이 필요할 것 같습니다.    
  - 누군가 subnet을 생성한 후에 spider에 연동했다고 하면, Spider를 통해서는 VPC를 만들수 없는 상황이 될수도 있고요. 
  - Spider 또한 단일 Spider 연동으로 제약 필요

#### (Q2)
- 현재 Spider 및 driver API에는 생성된 VPC에 별도로 subnet을 추가 또는 삭제할 수 있습니다. 
- 최초 VPC 생성 후에 subnet 삭제를 실행하게 되면, subnet이 존재하지 않는 VPC도 존재가 가능합니다. 
- 제안 방법 사용 시에는 이런 부분도 추가로 고려가 되어야 할 것 같습니다.

#### (제안방법)
- VPC 생성 여부를 확인 하기 위해 Spider 메타 정보(cb-store)에 저장 및 활용(Local SSH Key 관리 방법 활용)
  - 참고: https://github.com/cloud-barista/cb-spider/issues/548
  - 함수(AddKey 등)의 이름 등의 의미는 맞지 않지만, 현재는 SSH Key 관리 공통 함수를 그대로 활용
  - 활용예시
    ```go
	err = cdcom.AddKey("CLOUDIT", strHash, "VPC-REGISTER", vpcNameId)
	if err != nil {
		log.Fatal("xxxxxxxxxxxxx")
	}
    ```

#### (추가고려)
- 제안방법의 경우 동일한 tenant에 여러 Spider 연동 및 VPC 생성과 Subnet 생성이 가능합니다. 
- 다만, CloudIt의 경우 사용 가능한 Subnet list 중에 선택 사용 방식이므로, 다음과 같은 오류 메시지를 만날 확률이 높습니다. 
  ```
  [CLOUD-BARISTA].[ERROR]: 2022-03-04 00:40:25 CCMCommon.go:985, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateVPC() - Failed to Create VPC err = Subnet IPv4_CIDR 10.0.8.0/22 already exist
  ```
- 가능하시다면, 위의 오류 메시지 뒤에 
  - 현재 선택 가능한 subnet list를 함께 제시 해준다면 사용자 입장에서 많이 도움이 될 것 같습니다.
- 확인 후 추진하시기 전에 의견 부탁 드립니다.

**Comment by inno-cloudbarista** [comment]
답변 감사합니다.
우선 문의에 대해 답변드리겠습니다.
Q1) 
- credential 정보가 다르면  Default Network/subnet 자원은 독립적으로 운영이 가능합니다. 
  -  Spider 전용으로만 사용해야 한다는 제약이 필요한것도 맞습니다.

Q2) 
- subnet 삭제를 통해서 VPC를 인지 못하게 되는 상황이 발생합니다. 

고려해주신대로 이전에 제시한 방법은 subnet으로 VPC가 존재한다고 가정하는 방법이라 위 문제사항이 있습니다.

해당 문제사항에 따라 제안해주신 방법과 추가 고려사항도 포함하여 기능 제공하도록 하겠습니다.

추가적으로 Cloudit의 제약사항인 
```VPC: 이름이 고정된 Default-VPC 1개만 생성 가능```
부분도 개선가능할 것으로 보입니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 검토 및 답변 감사드립니다. 
- Multi-VPC 제공은 추후 꼭 필요하게 될 때, 추진하는 게 좋을 듯합니다. 
- 사유
  - CloudIt의 VPC 제공은 실제 VPC 자원의 활용 목적 보다는 다른 CSP와 동일한 절차 및 API로 VM 생성 및 제어가 목적입니다.
  - Multi-VPC를 제공 하게 된다면, CloudIt의 경우 VPC CIDR 제공 등 실제 VPC 기능이 안되는 제약 사항 등의 추가 안내가 필요하게 됩니다. 
  - 그리고, Multi-VPC 제공이 되면, VPC에 의존 관계로 관리되는 SG 및 VM의 정보 제공 시에 Owner VPC 정보를 제공해야 하는데, 
    - 여러 VPC가 관리되고 있다면, VPC SystemID-VM SystemID와 같은 맵핑 정보가 driver layer에서 추가로 관리되어야 합니다. 
- 후에 가상 Multi-VPC 제공이 필요하게 될지는 모르겠지만, 현재는 미뤄 두는 게 좋을 것 같습니다. 
- 또한, 후에 CloudIt이 VPC를 제공하게 된다면 자연스럽게 해결될 문제이기도 합니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
넵 Multi-VPC 제공은 제외하고 추진하도록 하겠습니다
