### ISSUE TITLE
[Bug] NHN Cloud subnet info is not listed due to IID2 validation check

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#582]
**What happened**
- NHN Cloud 연동 driver에 대해 CB-Spider API로 CreateVPC(), ListVPC(), GetVPC()를 실행할때,  subnet name 및 subnet list가 제대로 return 되지 않음.
-  NHN Cloud driver 자체 test script로 실행할 경우에는 제대로 return 됨. 
- CB-Spider의 IID2 validation check 때문에 발생하는 것으로 생각됨.
  (참고) NCP driver에서 S/G 제어의 경우와 유사하게 NHN Cloud의 VPC/Subnet은 CSP에서 생성/삭제 API를 제공하지 않아 driver 내부적으로 console에서 미리 생성해놓은 자원을 활용함. 

[ CreateVPC() 실행시 CB-Spider server log message ]

[CLOUD-BARISTA].[ERROR]: 2022-03-16 16:09:25 CCMCommon.go:1012, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateVPC() - subnet-1is not requested Subnet.
[CLOUD-BARISTA].[ERROR]: 2022-03-16 16:09:25 CCMCommon.go:1012, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateVPC() - subnet-2is not requested Subnet.

[ CB-Spider server returned results ]
#### VPC: Create
{
   "IId" : {
      "SystemId" : "5ef1f5c2-2467-4cc3-9dd8-0c52456ae015",
      "NameId" : "nhn-vpc-1"
   },
   "SubnetInfoList" : [
      {
         "IId" : {
            "SystemId" : "5ebe7cf8-7011-43af-b196-733d12b523e0",
            "NameId" : ""
         },
         "KeyValueList" : null,
         "IPv4_CIDR" : "172.16.0.0/24"
      },
      {
         "IPv4_CIDR" : "172.16.1.0/24",
         "KeyValueList" : null,
         "IId" : {
            "NameId" : "",
            "SystemId" : "42d51f23-0e94-4c28-89dc-d60ad1847ea8"
         }
      }
   ],
   "KeyValueList" : [
      {
         "Key" : "Status",
         "Value" : "ACTIVE"
      },
      {
         "Value" : "No",
         "Key" : "External_Network"
      }
   ],
   "IPv4_CIDR" : ""
}
#### VPC: List
{
   "vpc" : [
      {
         "SubnetInfoList" : [],
         "KeyValueList" : [
            {
               "Key" : "Status",
               "Value" : "ACTIVE"
            },
            {
               "Value" : "No",
               "Key" : "External_Network"
            }
         ],
         "IPv4_CIDR" : "",
         "IId" : {
            "SystemId" : "5ef1f5c2-2467-4cc3-9dd8-0c52456ae015",
            "NameId" : "nhn-vpc-1"
         }
      }
   ]
}
#### VPC: Get
{
   "SubnetInfoList" : [],
   "IPv4_CIDR" : "",
   "IId" : {
      "NameId" : "nhn-vpc-1",
      "SystemId" : "5ef1f5c2-2467-4cc3-9dd8-0c52456ae015"
   },
   "KeyValueList" : [
      {
         "Value" : "ACTIVE",
         "Key" : "Status"
      },
      {
         "Key" : "External_Network",
         "Value" : "No"
      }
   ]
}
#-----------------------------

**What you expected to happen**
: VPC 생성 및 정보 조회시 subnet name, subnet list가 제대로 return 되어야함.

**How to reproduce it (as minimally and precisely as possible)**
: NHN Cloud driver를 build하고 CB-Spider 서버가 구동된 상태에서 NHN Cloud full test script로 CB-Spider API를 통해 CreateVPC(), ListVPC(), GetVPC()를 실행함.

**Proposed solution**
: Subnet Name 관련해서 CB-Spider의 IID2 validation check 부분 확인해서 보완

**Comment by powerkimhub** [comment]
@innodreamer 

- 다음 분석 내용 참고해보시기 바랍니다. 
- 코드로만 분석한 내용이니 감안하시어 참고하시기 바랍니다. 

[분석]
- VPC 생성 시 Subnet ID 처리 과정에서
  - (1) User: `subnet-1` NameID로 Spider server에 생성할 VPC에 subnet을 생성 요청
  - (2) Server: `subnet-1-xxxx...xxx`(30자) NameID로 driver에 subnet을 생성 요청
  - (3) Driver: `subnet-1` 기준으로 subnet 생성(맵핑) 처리
  - (4) Driver: 생성 결과 정보를 포함하는 VPCInfo를 Spider server로 반환
    - 이때 포함된 subnet info의 NameID는 다음 위치에서 설정된 `subnet-1` 값으로 설정됨
      - https://github.com/cloud-barista/nhncloud/blob/3917519e0739dd26d323aeeb995f00741d5f8712/nhncloud/resources/VPCHandler.go#L448
  - (5) Spider Server에서는 driver가 생성해서 반환한 VPCInfo 정보에서 subnetInfo list를 순회하면서 
    - driver에 생성 요청했던 `subnet-1-xxxx...xxx`(30자) NameID와 동일한 subnet을 찾는데 존재하지 않음
    - 사유: 아마도 위 코드블록에서 설정된 name인 `subnet-1`으로 설정되어 올라오기 때문인 듯
    - 해결: driver로 넘겨 받은 NameID로 맵핑하여 정보 반환

**Comment by innodreamer** [comment]
@powerkimhub 
위에서 분석해주신 내용과 함께 NCP driver의 SecurityHandler 부분을 참고해서 다시 테스트해보고 정리한 내용과 driver 보완 내용입니다.

O 추가 분석 내용 :
- Spider API를 통해 CreateVPC()를 실행할 경우에 Spider server에서 Spider server가 생성해서 요청한 subnet NameID(IID2 체계)와 동일한 정보를 return하는지 validation check를 함.
- CreateVPC() 가 아닌 ListVPC(), GetVPC() 의 경우는 return 하는 정보에 대해 위와 같은 validation check를 하지 않고, CreateVPC() 때 return된 subnet 정보를 저장하여 사용하는 것 같음.(테스트로만 파악한 내용입니다.)

O 보완 내용 :
 - NHN Cloud driver에서는 CreateVPC() 실행시 내부적으로 CreateSubnet()을 실행하는 과정의 마지막에 Subnet NameID에 CSP의 실제 NameID 대신 Spider server에서 생성해서 driver에 요청한 IID2 체계의 NameID를 반영했음.
- 위와 같이 보완 후, Spider API를 통해 CreateVPC()를 한번 실행한 후 ListVPC(), GetVPC() 을 실행하는 경우에도 SubnetInfoList 값이 정상적으로 return 됨.

https://github.com/cloud-barista/nhncloud/pull/19
