### ISSUE TITLE
[CLOUDIT] When creating some resources, internal ID can be over 45 char.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#589]
- 사용자가 입력한 NameID는 Spider server에서 
- 대상 CSP가 제공하는 자원 ID의 최대 길이를 넘지 않도록 변환 및 맵핑 관리합니다.
  -  자원 ID별 최대 길이 정의: https://github.com/cloud-barista/cb-spider/blob/39794fb43bffcc53f62462678b027baed68dbb8f/cloud-driver-libs/cloudos_meta.yaml#L68
- 현재 설정에서 Server에서 내려 보내질 수 있는 ID 최대 길이는 45 char 입니다.

- [x] **[Issue-1]**
- 현재 driver의 SG 생성시 rule ID에 문자열을 추가하여 ID를 관리하고 있습니다. 
  - 이 경우 45자를 넘게 되어 다음과 같은 오류 보고가 되고 있습니다.  
  - 확인 부탁 드립니다.
    - https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1648110205352989?thread_ts=1648101174.142359&cid=CLFCLNFTJ

- [x] **[Issue-2]**
-  VM 생성의 경우에도 유사한 다음과 같은 오류 보고가 되고 있습니다. 
- 확인 부탁 드립니다.
  - https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1648183414078659?thread_ts=1648101174.142359&cid=CLFCLNFTJ

- [x] **[Issue-3]**
- 위 issue-2와 같은 중간 오류 발생 시 함수 초반에 생성한 VM 또는 생성한 다른 자원이 있을 경우
- 에러 반환 전에 생성했던 자원을 반환 해주셔야 할 것 같습니다.
- Server에서는 driver의 StartVM()이 오류를 반환하면 
  - 메타 정보에 생성된 VM 정보(ID)를 추가하지 않고 오류를 반환하고 있습니다. 
  - 이 경우 CSP에는 Spider는 알 수 없는 VM이 남아 있을 것 같습니다. 
- 확인 부탁 드립니다. 

- ⁕ issue-3의 작업이 길어질 듯하면 issue-1,2 선 PR 후 3번 이슈 확인 부탁 드립니다.

**Comment by inno-cloudbarista** [comment]
[Issue-1] , [Issue-2] 같은 경우는 지금 바로 PR을 요청하겠습니다.
[Issue-3]은 차주 내로 적용하도록하겠습니다

**Comment by powerkimhub** [comment]
- closed [issue-1] and [issue-2] in https://github.com/cloud-barista/cb-spider/pull/590

**Comment by powerkimhub** [comment]
- closed [issue-3] in https://github.com/cloud-barista/cb-spider/pull/591
