### ISSUE TITLE
[GCP] When creating a VM, Disk ID can be over 63 char.

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#592]
CB-TB 를 통해서 GCP VM을 생성할 때, 

 - Disk 관련 요청값
    - "rootDiskType": "",
    - "rootDiskSize": "77"

아래와 같은 오류가 Spider에서 발생합니다. (AWS VM은 오류가 발생하지 않았습니다.)

아마도 GCP 드라이버의 경우 DISK 생성 시에 VM 명칭과 동일한 명칭을 사용하여 DISK 자원을 생성하는 것 같은데, CB-TB가 요청하는 ID의 형태가 길어서 발생하는 것 같기도 합니다. (아마도 ID 길이 줄이는 매커니즘이 적용되지 않은?)

systemMessage: 

{\"message\":\"googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.diskName': 'ns01-test-clouds04-gcp-europe-west3-0-c922nd67p30na26k45sg-europe-west3-a'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid\"}

(cc @jihoon-seo)

_Originally posted by @seokho-son in https://github.com/cloud-barista/cb-spider/issues/536#issuecomment-1082898206_

**Comment by powerkimhub** [comment]
@dev4unet 

관련하여, 

- Server에서 vmName이 63자로 driver에 요청되었을 경우,
  - 아래 disk name이 경우 63자를 넘게 되어 오류가 발생할 수 있을 것 같습니다.  
  - 확인 부탁 드립니다.

https://github.com/cloud-barista/cb-spider/blob/a35009eaf085f04701d2a84d74f5bb32c8c9db4f/cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go#L171

**Comment by dev4unet** [comment]
설명하신 것처럼 디스크 이름 길이 초과로 오류가 발생하고 있어서 디스크 생성 시 명시적으로 이름을 지정하지 않고 API의 기본 값으로 생성되도록 소스를 변경하고 있습니다.

**Comment by dogfootman** [comment]
> 

disk Name을 할당하지 않는 경우 vm Name으로 설정되므로

**Comment by powerkimhub** [comment]
- fixed in https://github.com/cloud-barista/cb-spider/pull/600
