### ISSUE TITLE
Azure VM provisioning: shortening ID seems not applied for PublicIP resource

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#594]
CB-Tumblebug을 통해서 Azure VM 생성시

"{\"message\":\"Failed to Start VM. err = Failed to create PublicIP, error=network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\\\"InvalidResourceName\\\" Message=\\\"Resource name ns01-test-clouds1-azure-westus-0-c92make7p30na26k46dg-1648715089850908491-PublicIP is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'.\\\" Details=[]\"}\n",

와 같은 Error가 발생하는 경우가 있습니다.

VM에 적용되는 짧게 처리된 CSP관리ID와 
VM의 PublicIP 생성에 사용되는 CSP관리 ID가 다른 것 같습니다.

`Resource name ns01-test-clouds1-azure-westus-0-c92make7p30na26k46dg-1648715089850908491-PublicIP is invalid. The name can be up to 80 characters long.`

**Comment by powerkimhub** [comment]
@seokho-son @inno-cloudbarista 

[계획]
- **관련하여 전체 CSP에 대해 ASAP 시험 해보도록 하지요.** 

[분석] 
- Driver 내에서 input 인자로 넘겨 받은 NameID(max length일 수 있음)를 이용하여 
  - Driver 내부 관리 자원의 ID로 활용하는 경우가 존재함
  - 이때, 대상 자원의 ID에 문자열을 추가하는 경우 긴 ID 요청의 경우 오류가 발생하고 있음

- 보고된 비슷한 유형들
  - [GCP] https://github.com/cloud-barista/cb-spider/issues/592
  - [CloudIt] https://github.com/cloud-barista/cb-spider/issues/589

- 최근 갑자기 에러가 나타나는 사유
  - IID2 초기: CSP로 내려 보내는 ID 길이가 30자로 일괄 적용 (긴 문자열 ID 전체 시험 완료)
  - IID2 개선: CSP별 max id length를 고려하여 가변적으로 내려 보냄 (긴 문자열 ID 전체 시험 안됨)

- Azure 예상 위치 참고 (@inno-cloudbarista )

```go
1162 func generatePublicIPName(vmName string) string {
1163         nanos := time.Now().UnixNano()
1164         return fmt.Sprintf("%s-%s-PublicIP", vmName, strconv.FormatInt(nanos, 10))
1165 }
```

**Comment by powerkimhub** [comment]
- CSP/자원별 긴 NameID 1차 시험 결과
  - 전체 성공 CSP: AWS, Alibaba, Tencent
- 그외 CSP 세부 결과 참고: [CSP별/자원별 긴 NameID 시험 결과](https://docs.google.com/spreadsheets/d/1CVaDiJ2KGrwUxE-WAmU1Khc0VjgY6nX3/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

**Comment by powerkimhub** [comment]
@inno-cloudbarista @dev4unet @innodreamer  ( @seokho-son @jihoon-seo )

<br>

- CSP/자원별 긴 NameID 사용시 시험 결과입니다.
  - 전체 성공 CSP: AWS, Alibaba, Tencent

<br>

- 현재 오류 요약
  - Azure, GCP, IBM: VM 입력 NameID가 길 경우 오류 발생
  - NHNCloud: 입력 ID가 짧아도 VM 생성 오류 발생
  - NCP Classic: 입력 ID 짧아도 SecurityGroup 생성 오류
  - 세부 결과: [CSP별/자원별 긴 NameID 시험 결과](https://docs.google.com/spreadsheets/d/1CVaDiJ2KGrwUxE-WAmU1Khc0VjgY6nX3/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

![image](https://user-images.githubusercontent.com/46367962/161463960-cb31be73-ab2c-49d9-920a-8a3355c4ca2d.png)

**Comment by innodreamer** [comment]
@powerkimhub 위의 HNN Cloud VM 생성시의 오류 관련하여, 오늘 VPC/Subnet 생성 단계부터 SSH login까지 모든 테스트를 다시 진행해보면서 제가 파악하기에, VM 생성 테스트하실때 VMSpec type을 AdminWeb에 기본적으로 설정되어있는 VMSpec으로 지정하신것 같습니다.

테스트를 통해 제가 내린 결론은, NHN Cloud에서 지원하는 Ubuntu Server 18.04.6 LTS (2021.12.21) image와 그 VMSpec type과는 호환이 되지 않는거 같네요.(해당 region의 VMSpec list에 제시됨에도 불구하고 호환 않됨)

VM 생성 시험 결과를 간단히 정리하면 아래와 같습니다.
(NHN Cloud full-test scrip에 기본적으로 지정된 VMSpec과 AdminWeb에 지정된 VMSpec을 활용한 테스트입니다.)

- Full-test scrip : 
  - $CBSPIDER_ROOT/api-runtime/rest-runtime/test/full-test/13.nhncloud-test.sh
  - $CBSPIDER_ROOT/api-runtime/rest-runtime/test/full-test/nhncloud-full_test.sh

[ VMImage를 Ubuntu Server 18.04.6 LTS (2021.12.21) 로 동일하게 지정하여 테스트할때 ]

- 아래의 경우는 VM 생성시 정상적으로 생성 완료됨.
  - CONN_CONFIG=nhncloud-korea-pangyo-config
  - IMAGE_NAME=5396655e-166a-4875-80d2-ed8613aa054f
  - SPEC_NAME=**u2.c2m4** 
    - # VM Spec : vCPU: 2, Mem: 4GB

- 아래의 경우는 VM 생성시, 위에 테스트하신 경우와 같은 error 발생함.
  - CONN_CONFIG=nhncloud-korea-pangyo-config
  - IMAGE_NAME=5396655e-166a-4875-80d2-ed8613aa054f
  - SPEC_NAME=**m2.c4m8**
    - # VM Spec : vCPU: 4, Mem: 8GB

향후에 AdminWeb에 기본적으로 지정된 그 VMSpec을 다른 Spec으로 변경하여 PR 올리겠습니다.

**Comment by powerkimhub** [comment]
@innodreamer 

- 캄사합니다. 
- 적용하여 재시험 해보도록하겠습니다.

**Comment by innodreamer** [comment]
@powerkimhub 추가 분석한 결과 NHN Cloud 로부터 제시되는 VMSpec 목록에서 원인이 있는것 같습니다
https://github.com/cloud-barista/nhncloud/issues/30

**Comment by powerkimhub** [comment]
[현황]

- Azure, GCP, IBM: VM 입력 NameID가 길 경우 오류 발생
  - Azure, IBM, Cloudit patch: https://github.com/cloud-barista/cb-spider/pull/597
  - GCP: WIP

<br>

- NHNCloud: 입력 ID가 짧아도 VM 생성 오류 발생
  - VM Spec 변경 후 재시험 필요
  - ref) https://github.com/cloud-barista/cb-spider/issues/594#issuecomment-1087167794
  - ref) https://github.com/cloud-barista/cb-spider/issues/594#issuecomment-1087209746

<br>

- NCP Classic: 입력 ID 짧아도 SecurityGroup 생성 오류
  - WIP

**Comment by powerkimhub** [comment]
@innodreamer 

- NHNCloud VM Spec 변경 후 시험 완료 하였습니다. 
  - [CSP별/자원별 긴 NameID 시험 결과](https://docs.google.com/spreadsheets/d/1CVaDiJ2KGrwUxE-WAmU1Khc0VjgY6nX3/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

<br>

- 추가로, Root Disk Type 및 Size 변경 관련 확인이 필요합니다. 
  - 관련 이슈: https://github.com/cloud-barista/cb-spider/issues/598
  - 현재 NHNCloud 관련 정보 출력 결과
    ```
      RootDiskType: ""
      RootDiskSize: "50"
      RootDeviceName: ""
      VMBootDisk: ""
    ```

**Comment by powerkimhub** [comment]
- fixed in https://github.com/cloud-barista/cb-spider/pull/597

**Comment by powerkimhub** [comment]
@inno-cloudbarista @dev4unet @innodreamer  ( @seokho-son @jihoon-seo )

<br>

- CSP/자원별 긴 NameID 시험 현재 결과입니다.
  - 전체 성공 CSP: AWS, Azure, Alibaba, Tencent, IBM, Cloudit, NHNCloud

<br>

- 현재 오류 요약
  - GCP: VM 입력 NameID가 길 경우 오류 발생
  - NCP Classic: 입력 ID 짧아도 SecurityGroup 생성 오류
  - 세부 결과: [CSP별/자원별 긴 NameID 시험 결과](https://docs.google.com/spreadsheets/d/1CVaDiJ2KGrwUxE-WAmU1Khc0VjgY6nX3/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

![image](https://user-images.githubusercontent.com/46367962/161548622-31b22417-16de-45ba-8b02-6767aa58d33d.png)

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo ( @inno-cloudbarista @dev4unet @innodreamer )

<br>

- 시험 결과가 아래와 같습니다. 
- NCP Classic 등 다른 CSP는 다른 이슈로 현 이슈는 close하도록 하겠습니다.
- 수고들 하셨습니다. 

![image](https://user-images.githubusercontent.com/46367962/161664070-b81476af-60f9-4b42-8bbe-92a318fe4272.png)

**Comment by seokho-son** [comment]
@powerkimhub 고생하셨습니다. 정리 감사합니다. 해당 bug fix를 기준으로 프리릴리스 버전을 찍어두면 좋을 것 같습니다.

**Comment by powerkimhub** [comment]
@seokho-son ( @jihoon-seo )

- Thanks~.
- https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.3
