### ISSUE TITLE
[NHNCloud, NCPVPC] Root Disk Configurability Test

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#598]
@innodreamer ( @seokho-son @jihoon-seo )

- [x] NHNCloud 적용 가능 확인 및 시험 필요
- [x] NCPVPC 적용 가능 확인 및 시험 필요

- **[최신 결과 참고]**
  - [Root Disk Type 및 size 변경 시험 결과.xlsx](https://docs.google.com/spreadsheets/d/1kSqwMTkt9O4r3K1OVO-EW2uXmZeaNlhV/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

---

_Originally posted by @powerkimhub in https://github.com/cloud-barista/cb-spider/issues/536#issuecomment-1075632273_

**Comment by innodreamer** [comment]
@powerkimhub 우선 두 CSP에 대해 RootDiskType과 RootDiskSize 지정 가능 여부 확인 결과, NHN Cloud는 console 및 API를 통해 VM 생성시 RootDiskType과 RootDiskSize 지정이 가능하고, NCP VPC는 console을 RootDiskType만 지정 가능하고 API를 통해서는 RootDiskType과 RootDiskSize 지정이 불가능합니다. 

NHN Cloud의 경우, CB-Spider API 기준의 test case와 test result는 아래와 같습니다.
- Test scripts : https://github.com/cloud-barista/cb-spider/pull/605
- Test cases and results : https://docs.google.com/spreadsheets/d/1kSqwMTkt9O4r3K1OVO-EW2uXmZeaNlhV/edit#gid=858532461

**Comment by innodreamer** [comment]
@powerkimhub CB-Spider > Wiki에 있는 아래의 요약표에도 NHN Cloud와 NCP VPC의 경우에 대해 정리해놨습니다.

https://github.com/cloud-barista/cb-spider/wiki/API-and-features-of-VM-rootfs-volume-configuration
