### ISSUE TITLE
Align case of the SG rules' `IPProtocol` value

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#621]
**What would you like to be enhanced**
: 
SG rule의 `IPProtocol` 필드의 값이 대문자 또는 소문자로 통일되었으면 좋겠습니다.

[TB를 사용하여 AWS에 SG 생성 시]: 해당 값이 소문자임
```JSON
{
  "id": "aws-ap-southeast-1-jhseo",
  "name": "aws-ap-southeast-1-jhseo",
  "connectionName": "aws-ap-southeast-1",
  "vNetId": "sjh-aws-ap-southeast-1-jhseo",
  "description": "test description",
  "firewallRules": [
    {
      "FromPort": "1",
      "ToPort": "65535",
      "IPProtocol": "udp",
      "Direction": "inbound",
      "CIDR": "0.0.0.0/0"
    },
    {
      "FromPort": "1",
      "ToPort": "65535",
      "IPProtocol": "tcp",
      "Direction": "inbound",
      "CIDR": "0.0.0.0/0"
    },
    {
      "FromPort": "-1",
      "ToPort": "-1",
      "IPProtocol": "icmp",
      "Direction": "inbound",
      "CIDR": "0.0.0.0/0"
    },
    {
      "FromPort": "",
      "ToPort": "",
      "IPProtocol": "-1",
      "Direction": "outbound",
      "CIDR": "0.0.0.0/0"
    }
  ],
  "cspSecurityGroupId": "sg-078e1384e4a52f205",
  "cspSecurityGroupName": "sjh-aws-ap-southeast-1-jhseo",
  "keyValueList": [
    {
      "Key": "GroupName",
      "Value": "sjh-aws-ap-southeast-1-jhseo-c9nq9gd6qs8a1lq9qos0"
    },
    {
      "Key": "VpcID",
      "Value": "vpc-0d894ffc396cef65b"
    },
    {
      "Key": "OwnerID",
      "Value": "635484366616"
    },
    {
      "Key": "Description",
      "Value": "sjh-aws-ap-southeast-1-jhseo-c9nq9gd6qs8a1lq9qos0"
    }
  ],
  "associatedObjectList": [],
  "isAutoGenerated": false,
  "systemLabel": ""
}
```

[TB를 사용하여 Mock에 SG 생성 시]: 해당 값이 대문자임
```JSON
{
  "id": "mock-seoul-jhseo",
  "name": "mock-seoul-jhseo",
  "connectionName": "mock-seoul",
  "vNetId": "sjh-mock-seoul-jhseo",
  "description": "test description",
  "firewallRules": [
    {
      "FromPort": "1",
      "ToPort": "65535",
      "IPProtocol": "TCP",
      "Direction": "inbound",
      "CIDR": "0.0.0.0/0"
    },
    {
      "FromPort": "1",
      "ToPort": "65535",
      "IPProtocol": "UDP",
      "Direction": "inbound",
      "CIDR": "0.0.0.0/0"
    },
    {
      "FromPort": "-1",
      "ToPort": "-1",
      "IPProtocol": "ICMP",
      "Direction": "inbound",
      "CIDR": "0.0.0.0/0"
    }
  ],
  "cspSecurityGroupId": "sjh-mock--c9nqbg56qs8a1lq9qotg",
  "cspSecurityGroupName": "sjh-mock-seoul-jhseo",
  "keyValueList": null,
  "associatedObjectList": [],
  "isAutoGenerated": false,
  "systemLabel": ""
}
```

**Why is this needed**
: 
TB 사용자가 SG rule 추가 또는 삭제를 위해 TB API 호출 시
SG rule의 `IPProtocol` 값을 대문자 또는 소문자로 기재할 수 있기 때문에

CB-Spider Mock driver의 리턴값을 참고하여

- `IPProtocol`: 사용자가 입력한 값을 대문자로 변환하여 TB 객체와 비교
- `Direction`: 사용자가 입력한 값을 소문자로 변환하여 TB 객체와 비교

하도록 작성했는데,
CB-Spider AWS driver는 `IPProtocol` 필드의 값을 대문자로 반환하네요.. 😅

`IPProtocol` 필드와 `Direction` 필드의 값을 대문자 또는 소문자 중 한 쪽으로 통일시켜 주실 수 있을까요?
그렇게 변경된다면, TB도 그에 맞춰 동작하도록 작성하겠습니다. (https://github.com/cloud-barista/cb-tumblebug/pull/1083)

(Reminder: SP 사용자도 SP API 호출 시 `IPProtocol` 필드 및 `Direction` 필드의 값을 대문자 또는 소문자로 명시할 가능성이 있음)

**Proposed solution**
:

**Comment by powerkimhub** [comment]
@jihoon-seo 

현재, Spider 규격은 이렇게 정의되어 있습니다. 

- Direction : 소문자
- IPProtocol : 대문자
- [규격 참고](https://docs.google.com/spreadsheets/d/1m2xih9QedxiQ3pHY6_5F9YLoQYJRIkPe/edit#gid=1783693395)

사용자 입력에 대해서는 아래처럼 변환하여 driver로 내려 보내고 있는데,
driver가 올려 주는 정보는 확인하지 않고 올려주면서 대소문자가 틀린 경우가 있나보네요. 
<br>
위 기준대로 대소문자를 맞추어 반환하면 될까요?

**Comment by powerkimhub** [comment]
@jihoon-seo 

- fixed in [5b047299b60dbe9edc38f00e51ed9d9ec2a88f94](https://github.com/cloud-barista/cb-spider/commit/4d50c7bb1ebdb27dba3e6de855d268b2d699cd10)

**Comment by seokho-son** [comment]
@powerkimhub [5b047299b60dbe9edc38f00e51ed9d9ec2a88f94](https://github.com/cloud-barista/cb-spider/commit/4d50c7bb1ebdb27dba3e6de855d268b2d699cd10) 를 포함하는 마이너버전 프리릴리스 부탁 드립니다. (기존 기능 동작에 문제 없는)

**Comment by powerkimhub** [comment]
@seokho-son 

- 아직 진행 중입니다. 
- 현황 참조
  - https://github.com/cloud-barista/cb-spider/issues/482#issuecomment-1114800335
  - 진행 및 개선 중이어서 됐던 CSP도 안되는 것도 있는 상황이에요. 
- 안정화 되면 배포/노티 예정입니다.

**Comment by seokho-son** [comment]
넵 TB에 관련 PR이 머지 되었는데 해당 내용이 SP의 HEAD 커밋을 사용하고 있어서 요청 드렸습니다. TB에서도 그럼 잠시 동작하지 않는 기능으로 처리하고 있겠습니다.
