### ISSUE TITLE
[OpenStack] Can't see the 'GuestOS' Info in Image Info

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#641]
- Image List/Get 시에 GuestOS 정보 추가 부탁드립니다. 
- 현재 OpenStack의 경우 UUID만 보이고 있어서, 
- Image 선택에 어려움이 있습니다. 
- AdminWeb 결과 예시:
  - ![image](https://user-images.githubusercontent.com/46367962/168286396-2705c35b-efa9-4e85-afca-b6c1b4580063.png)

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
Openstack 내에서 해당 이미지의 OS 정보가 존재하지 않습니다. 
제공할 수 있는 방법은 Image의 이름을 GuestOS로 넣어주는 방법이 있습니다.
다만, Image의 이름이 OS명이 아닐 경우 전혀 다른 정보가 제공될수 있습니다.

현재 이미지에서 OS에 대한 정보를 제공할 수 있는 방법이 위방법 밖에 떠오르지 않아 위 방법 대로 적용하려고 합니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 넵, Image Name으로 설정해주시면 될듯합니다. 
- OpenStack 운영자가 대상 OpenStack 서비스 사용자들이 인지할 수 있는 이름으로 입력할 것으로 생각됩니다.
