### ISSUE TITLE
[OpenStack] Meet NeutronError when creating a SecurityGroup with spctl

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#643]
- ETRI OpenStack 환경에서 SG 검증 시험 중 spctl 통한 SG 생성시 오류 발생
  ```
  ubuntu@powerkim-PC:3.create-add-list-get-info-test# ./01.inbound-create-add.sh openstack-etri
  #############################################
  # TEST: ./01.inbound-create-add.sh
  #############################################
  ============== before create SecurityGroup: 'SG-Rules-Test-SG01'
  message: rpc error: code = Internal desc =  error while calling CCMService.CreateSecurity() method: Bad request with: [POST http://1.2.3.4:9696/v2.0/security-group-rules], error message: {"NeutronError": {"type": "SecurityGroupProtocolRequiredWithPorts", "message": "Must also specify protocol if port range is given.", "detail": ""}}
  ```

- AdminWeb 이용한 SG 생성은 성공
- Go(gRPC) API Runtime 오류로 추정됨
- OpenStack 버전 또는 SDK 버전 문제 등 추가 분석 필요

@inno-cloudbarista 
- 혹시, 사내 오픈스택에서는 오류 발생하지 않으셨는지요?

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
사내 Openstack으로 테스트 해본 결과 ./01.inbound-create-add.sh  openstack-inno 실행 시 오류 발생은 없었습니다.

AdminWeb 생성도 성공했습니다.

코드상의 문제라면, Protocol이 all 일 경우의 문제가 생기는 상황인거 같습니다. 
위 내용은 해당 팜에서 테스트 해봐야 알 수 있을거 같습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 넵, 의견 공유 감사합니다.

**Comment by powerkimhub** [comment]
- Go API is no longer supported.
- Additionally, this issue has been inactive.
