### ISSUE TITLE
[IBM-VPC] Panic when trying to fetch a resource doesn't exist

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#657]
- 증상: 존재하지 않는 VPC 자원 요청(GetVPC)에 대해 Panic이 발생하고 있습니다. 
- 분석 
  - 212 line에서 존재하지 않는 VPC 일 경우 vpc 객체는 nil
  - 217 line에서 vpc가 nil인 상태에서 vpc.Defa...를 호출하고 있음.

```go
209 func (vpcHandler *IbmVPCHandler) GetVPC(vpcIID irs.IID) (irs.VPCInfo, error) {
210         hiscallInfo := GetCallLogScheme(vpcHandler.Region, call.VPCSUBNET, "VPC", "GetVPC()")
211         start := call.Start()
212         vpc, err := getRawVPC(vpcIID, vpcHandler.VpcService, vpcHandler.Ctx)
213
214         // default SecurityGroup modify
215
216         options := &vpcv1.GetSecurityGroupOptions{}
217         options.SetID(*vpc.DefaultSecurityGroup.ID)
```
<br>

- 다른 자원들도 확인 부탁 드립니다. (Get, Delete 포함)
- 또한, 존재하지 않는 자원 호출시 반환하는 getRawVPC() 에러 메시지도 공유 부탁 드립니다. 
  - 사유: 서버에서 에러 메시지를 파싱해야 할일이 생겼습니다. 
- OpenStack / Cloudit 도 Get/Delete panic 가능성 확인 및 없는 자원 호출 에러 메시지 공유 부탁 드립니다. 
  - 에러 메시지는 하나의 자원에 대해서만 공유 해주시면 되겠습니다.
  - 유사 패턴일 것이기 때문입니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
위 패닉 사항은 타 CSP도 확인 후 빠른 시일 내에 PR 요청하도록 하겠습니다.

getRawVPC()의 에러 메세지 관련하여 답변 드립니다.

Openstack, Cloudit, Azure, Ibm-VPC 내의 getRawVPC(Resource)는 CB-Spider의 IID 기준으로 CSP의 데이터 원본을 가져오기 위한 내부 함수입니다. CSP의 에러메세지는 바로 리턴하는 경우도 있으나, List에서 값이 같은 것을 경우가 없을 경우 에러메세지를 만들어 리턴하는 경우도 있어, 에러 메세지가 상이합니다. 
List에서 값이 같은 경우를 리턴하는 경우는 List를 Get해올 때, 통신 문제로 전혀 다른 에러메세지가 나올 수도 있습니다.

Ibm-VPC : 
getRawVPC : VPC not found 이름
=> 핸들러 최종 리턴 에러  Failed to Get VPC err = VPC not found 이름

Azure : 
getRawVPC : network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/virtualNetworks/nlb-tester-vpc-no' under resource group 'CB-GROUP' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

=> 핸들러 최종 리턴 에러  getRawVPC : network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/virtualNetworks/nlb-tester-vpc-no' under resource group 'CB-GROUP' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

Cloudit: VPC
getRawVM : not found vm
getRawVPC가 존재하지 않고, KeyPair처럼 db에 등록된 값을 찾는 방식으로 지정된 메세지 전달 Failed to Get VPC err = Not Exist, Failed to Get VPC err = Not Exist VPC : %s 등
=> 핸들러 최종 리턴 에러  Failed to Get VM. err = not found vm 

Openstack 
getRawVPC: not found vpc
=> 핸들러 최종 리턴 에러 Failed to Get VPC with Id , err=not found vpc

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 확인 감사드립니다. 
- 에러 문자열은 크게 문제가 없어 보입니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 현재 이슈는 close해도 되는지요?
- 계획 중인 작업이 남아 있는지요?

> @powerkimhub
> 위 패닉 사항은 타 CSP도 확인 후 빠른 시일 내에 PR 요청하도록 하겠습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
넵 1차적으로 타 CSP에서도 확인하고 NLB 기능 업데이트 전에 적용하였습니다!
