### ISSUE TITLE
[NCPVPC/NCP/NHN] What happened when trying to fetch a resource that doesn't exist

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#658]
- 존재하지 않는 자원 호출시 반환하는 CSP의 에러 메시지를 공유 부탁 드립니다. 
  - 사유: 서버에서 에러 메시지를 파싱해야 할일이 생겼습니다. 
  - 에러 메시지는 하나의 자원에 대해서만 공유 해주시면 되겠습니다.
  - 유사 패턴일 것이기 때문입니다. 
- 예시
  - GetVM("no")
  - TerminateVM("no")

**Comment by innodreamer** [comment]
@powerkimhub CSP에서의 error message를 의미하시는건가요. 아니면 연동 드라이버에서의 error message를 의미하시는건가요?
참고로, 국내 CSP 연동 드라이버에서 error message를 return 할때는 주로 '드라이버에서 안내하는 에러 메시지 + CSP 에러 메시지' 형태의 message로 return 하도록 개발되고 있습니다.

**Comment by powerkimhub** [comment]
@innodreamer 

- 드라이버 반환 메시지를 공유해주시면 되겠습니다.

**Comment by innodreamer** [comment]
@powerkimhub
우선 NCP, NCPVPC driver의 Get~~() 관련 error message를 정리해서 공유해드립니다.
- Google sheet link : 
https://docs.google.com/spreadsheets/d/1mq8JgCKoyw6R4dCZGV2gyjXy5Mrk0LX4pm3P9QIo2NI/edit#gid=0

추가로 작성되는 대로 다시 댓글 남기겠습니다.

**Comment by powerkimhub** [comment]
@innodreamer 

- 캄사합니다.
