### ISSUE TITLE
Cannot create VM using general specs in Azure

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#661]
**What happened**
: CB-TB를 통해 MCIS 생성시, (azure 리전들로 구성된 vm) DISK TYPE에 의해 오류 발생

(생성 요청 예시)
- basic-a1, standard-a1, standard-b1s 등 기존에 동작하던 기본 스펙들
- Input DiskType	Input DiskSize(GB) 는 모두 default로 지정

```
  "vm": [
    {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiacentral-basic-a1"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiacentral-standard-a1"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiacentral-standard-b1s"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiaeast-basic-a1"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiaeast-standard-a1"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiaeast-standard-b1s"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiasoutheast-basic-a1"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiasoutheast-standard-a1"
  },
  {
    "commonImage": "ubuntu18.04",
    "commonSpec": "azure-australiasoutheast-standard-b1s"
  }
  ]
```

(결과 예시)
```
  "id": "mcis01-son",
  "name": "mcis01-son",
  "status": "Partial-Failed:6 (R:3/9)",
  "statusCount": {
    "countTotal": 9,
    "countCreating": 0,
    "countRunning": 3,
    "countFailed": 6,
    "countSuspended": 0,
    "countRebooting": 0,
    "countTerminated": 0,
    "countSuspending": 0,
    "countResuming": 0,
    "countTerminating": 0,
    "countUndefined": 0
  },
```

실패한 6개의 spec 오류 메시지 예시
```
"systemMessage": "{\"message\":\"Failed to Start VM. err = compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\\\"InvalidParameter\\\" Message=\\\"Requested operation cannot be performed because the VM size Basic_A1 does not support the storage account type Premium_LRS of disk ''. Consider updating the VM to a size that supports Premium storage.\\\" Target=\\\"osDisk.managedDisk.storageAccountType\\\", and Finished to rollback deleting\"}\n",
```

**How to reproduce it (as minimally and precisely as possible)**
CB-TB로 동적 프로비저닝 수행

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: CB-SP v0.5.6 / CB-TB HEAD
- OS: ubuntu 18.04
- Others: 

**Proposed solution**
: CSP가 제시하는 기본 옵션으로 처리가 가능하도록 처리?

**Any other context**
:
https://docs.google.com/spreadsheets/d/1kSqwMTkt9O4r3K1OVO-EW2uXmZeaNlhV/edit#gid=858532461

에 공유된 시험 결과가, 특정 spec들을 기준으로 하고 있어서, 
시험 예시와 다른 spec을 사용하면, 오류를 일으키는 경우가 많은 것 같습니다.

**Comment by seokho-son** [comment]
A1은 StandardSSD로 지정하면 동작하는 듯 합니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 급한 시연 준비로 Azure Driver 임시 반영 하여, 현황 공유 드립니다. 
  - VM 생성 요청시 RootDiskType 설정 관련 기본값(default) 처리 방법 변경
  - 기존 방법의 경우 VM Spec에 따라 VM 생성이 불가능한 경우가 존재하여 
  - 부득이, CSP에 RootDiskType을 맡기는 방법으로 수정하였습니다. 
  - RootDiskType 설정이 "" or "default"일 경우 
    - **Before: PremiumSSD로 CSP에 요청, 이 경우 A1-series(VM spec)은 VM 생성 오류**
      - 참고: 오류 메시지
        ```
        message: rpc error: code = Internal desc =  error while calling CCMService.StartVM() method: Failed to Start VM. err = compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="Requested operation cannot be performed because the VM size Basic_A1 does not support the storage account type Premium_LRS of disk ''. Consider updating the VM to a size that supports Premium storage." Target="osDisk.managedDisk.storageAccountType", and Finished to rollback deleting
        ```
    - **After: CSP에서 자동으로 RootDiskType을 선택하도록 요청**

- 생각과 다른 부분이 있으신 지 리뷰 부탁 드립니다.  
  - 변경 내용: https://github.com/cloud-barista/cb-spider/commit/a481628c0aa2d03f8bfa22d8d0a351ed6b69f81e , https://github.com/cloud-barista/cb-spider/commit/5e73da3685424b17418ac4c17689db42df6f05cd

- **RootDiskSize default 처리도 동일 방법으로 처리하는 지 확인 부탁드립니다.** 
- **IBM/OpenStack도 처리 방법 확인 부탁드립니다.** 

- 기타 참고 사항
  - [Av1 Series retirement](https://docs.microsoft.com/en-us/azure/virtual-machines/av1-series-retirement) 서비스 종료 예정(2024.8.31))이며, 
    - Console 통해 생성 불가, API는 생성 가능, Premium Storage는 지원 불가
  - 사용중인 VM은 [Av2 Series](https://docs.microsoft.com/en-us/azure/virtual-machines/av2-series)로 변경 권고하고 있음.
    - **Av2도 Premium Storage는 지원 불가**

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

[참고] 반영 후 시험 결과
- Disk 설정 없이 `Basic_A1` VM 생성 요청 결과 : `Standard HDD LRS` 정상 성공
- Disk `StandardSSD` 설정으로 `Basic_A1` VM 생성 요청 결과: `Standard SSD LRS` 정상 성공

**Comment by inno-cloudbarista** [comment]
@powerkimhub
Azure의 경우 DiskSize는 VM 생성후 ReSize를 하는 방식이라, "" 혹은 "default"일 경우 Resize를 진행하지 않도록 구현되어 있어, 
현재 적용된 DiskType과 비슷한 방식("" 혹은 "default" 일 경우 기본 설정 활용)으로 지원됩니다.

Ibm-VPC, CloudIT의 경우는 RootDiskType과 RootDiskSize는 지원하지 않지만 "" 혹은 "default" 가 아닐 경우 지원하지 않는다는 에러를 리턴하는 로직을 추가해야할 거 같습니다. 적용 후 PR 올리겠습니다!

Openstack은 RootDiskType은 제공하지 않고, RootDiskSize의 기능만 제공합니다. 
"" 혹은 "default" 가 아닐 경우만 Size를 변경하기에, 현재 Azure에 적용된 DiskType과 비슷한 방식("" 혹은 "default" 일 경우 기본 설정 활용)으로 지원됩니다.

추가적으로 Azure의 DiskType의 변경 사항에 대해서는 기존에 DiskType이 존재하지 않을 경우와 같은 방식이라 생각되어 이견 없습니다

기타 참고 사항은 Api로 가져오는 Spec내에 해당 정보가 있는지 확인해보겠습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 캄사합니다.
- Ibm-VPC, CloudIT 오류 메시지 반영(PR)을 위해서 현 이슈는 유지해두겠습니다.
