### ISSUE TITLE
[IBM-VPC] Want to meet faster VM Status Info

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#666]
@inno-cloudbarista ( reported by @seokho-son , Thanks )

- List VM 또는 List VM Status 또는 Get VM Status 성능 확인 부탁드립니다. 
- 혹시, 개선 가능성이 있는 지 Driver 단에서의 성능 분석 부탁드립니다. 
- VM Status 관련 비교 결과
  - 타 CSP
    ```
    5개 VM 존재시: List VM Status elapsed time
    real    0m5.678s
    user    0m0.012s
    sys     0m0.016s
    
    1개 VM 존재시: List VM Status elapsed time
    real    0m1.359s
    user    0m0.013s
    sys     0m0.015s
    
    1개 VM 존재시: Get VM Status elapsed time
    real    0m0.477s
    user    0m0.021s
    sys     0m0.006s
    ```

  - IBM-VPC
    ```
    5개 VM 존재시: List VM Status elapsed time
    real    0m18.541s
    user    0m0.013s
    sys     0m0.016s
    
    1개 VM 존재시: List VM Status elapsed time
    real    0m5.757s
    user    0m0.015s
    sys     0m0.014s
    
    1개 VM 존재시: Get VM Status elapsed time
    real    0m2.759s
    user    0m0.019s
    sys     0m0.009s
    ```

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
늦게 답변드려 죄송합니다.
List VM Status 또는 Get VM Status 관련해서는 Driver단에서 API 호출 후, 인스턴스 상태의 문자열에 의한 상태 값 반환 로직으로 이루어져 있습니다. 
  - 해당 부분에선 성능향상의 부분이 보이지 않습니다.
  - 리스트를 조회시 VM의 갯수가 50개 이상인 경우에는 Limit로 인해 50개씩 여러번 호출하지만, 50개 이하인 경우 1번만 호출(예시는 5개 이므로 1번만 호출됩니다.)
List VM 관련해서는, 각 VM의 정보를 가져오기 위한 API를 호출하지만, 이도 불필요하게 API를 여러번 호출하는 경우는 보이지 않습니다.
  - 속능 향상을 위해서, ListVM의 경우 각 VM의 정보를 가져오는 곳을 Go Function으로 비동기적으로 처리하면 성능 향상이 기대됩니다.

**Comment by powerkimhub** [comment]
- 관련하여, 다음 2가지 사항을 점검 부탁 드립니다. 
- 참고로, 현 이슈는 반영하시더라도 카페라떼 이후에 Merge 예정입니다. 
 
- (1) ListVM, ListVMStatus() 관련
  - 제안 주신 방안 대로, Go Routine 이용한 동시 처리 고려해주시기 바랍니다. 
  - 사유: setVmInfo() 한번 호출시 마다 CSP 4회 호출, (현재 1VM = 2Sec 정도,  50VM 이면 약 100sec 예상)
    ```
    setVmInfo() pseudo flow: 
            vmHandler.VpcService.GetInstanceInitializationWithContext()
            vmHandler.VpcService.GetInstanceNetworkInterfaceWithContext()
            vmHandler.VpcService.GetVPCWithContext()
                  vpcService.ListVolumesWithContext()
    ```
  
- (2) GetVM(), GetVMStatus() 관련
  - func (vpc *VpcV1) GetInstance() 활용 가능성 검토
    - ref) https://raw.githubusercontent.com/IBM/vpc-go-sdk/master/vpcv1/vpc_v1.go
  - 현재: getRawInstance() local 함수 활용 중이며,
    - 해당 함수는 vpcService.ListInstancesWithContext()를 이용하여 모든 VM List 획득 후 
    - 대상 VM에 대한 정보를 조건 filtering하고 있음

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
(1) ListVM, ListVMStatus() 관련해서  Go Routine 이용한 동시 처리로 바꾸도록 하겠습니다
(2) GetVM(), GetVMStatus() 관련해서 말씀해주신 GetInstance()는 GetInstanceWithContext로 사용되고 있습니다.
    - 다만, GetInstance(WithContext)의 경우 ID로만 조회가 가능하기에 로컬 함수인 getRawInstance()로 ID가 있는 경우는 GetInstance(WithContext)로, ID가 없는 경우엔 ListInstancesWithContext에서 VM 정보를 가져오도록 하고 있습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

> (1) ~
- 캄사합니다. 

> (2) GetVM(), GetVMStatus() ~

- 맞네요. else{}를 못 봤네요^^
  - 말씀해주신대로, 1 VM 정보를 얻는 시간은 어쩔 수 없는 시간이네요.
  - 사족: setVmInfo() 내부 CSP 향한 호출들을 Thread화 할 수는 있겠지만, 
    - 현재는 그냥 두고 가보는 게 좋을 듯하네요.

**Comment by powerkimhub** [comment]
• Fix in https://github.com/cloud-barista/cb-spider/pull/710
