### ISSUE TITLE
Issue in vm termination and status check (maybe related with new lock mechanism)

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#680]
**What happened**
CB-TB와 CB-SP (v0.5.9) 연동 테스트 중,

VM Terminate 제어 요청 시 (동기 형태의 오퍼레이션),  
해당 VM의 상태를 동시에 조회되지 않는 상황 발생. (아마도 신규 추가된 lock 이슈)

**What you expected to happen**

기존(v0.5.5 이전)에는 VM terminate 과정 중에도 상태 조회가 가능해서
terminating 과정을 확인할 수 있었음.

**How to reproduce it (as minimally and precisely as possible)**
CB-TB로 MCIS 생성 및 Terminate 제어 수행하고, 동시에 상태를 조회

**Anything else we need to know?**

 - create, suspend, resume 등에서는 문제 없는 것으로 보임. (확실한 테스트는 아님. Terminate 가 가장 오래걸려서 terminate 에서만 문제가 확인된 것일 수도 있음.)

- MapUI 를 통한 제어시 상황 참고 (30초 이상 지연되면, timeout 처리 중)
  - Error: timeout of 30000ms exceeded
    at createError (createError.js:16:15)
    at XMLHttpRequest.handleTimeout (xhr.js:130:14)

![image](https://user-images.githubusercontent.com/5966944/173222318-f370ceff-0220-4eae-bda7-a0b95052ca51.png)

**Environment**
- Source version or branch: CB-SP v0.5.9
- OS: ubuntu 18.04
- Others: 

**Proposed solution**
Terminate 중에도 status 확인 가능하도록 개선

**Any other context**
:

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo 

### [현황]
- 현재 동작은 오류 상황이라기 보다는 Locking 정책이 그렇게 되어 있는 상태입니다. 
  - 기존 상태: 성능 이슈로 임시로 VM 관련 Lock만 임시 해제한 상태
    - https://github.com/cloud-barista/cb-spider/issues/342#issuecomment-950526752
  -  Lock을 풀면,
      - StartVM/TerminateVM/GetVM/ListVM API: 범용으로 사용시 오류가 발생할 수 있음
      - GetVMStatus/ListVMStatus API만 풀면, 문제가 없을 것 같습니다만, 불확실(Driver 의존적일 듯)

- 좋은 대안으로는 리모델링시 계획했었던 Async Call 추가하여 상황에 맞게 선택적으로 사용하는 것 입니다. (아니면, CSP들처럼 Async로 전환)
  - Sync Call `API 호출 반환`은 `요구 상태 반영 완료`  => Lock 필요, 호출 완료 시간 느린 대신, 사용자가 완료 상태 확인 불필요
  - Async Call `API 호출 반환`은 `요구 상태 반영을 백그라운드로 진행 중` => Lock 불필요, 또는 짧은 Critical Section, 호출 완료 시간 빠른 대신, 사용자가 완료 상태 확인 필요(또는 notify)
  - Spider Call: Sync이면서(long Critical Section), Status check 패턴을 제공

- Create/Suspend/Resume/Reboot/Terminate 동일 상황일 것입니다. 
  - 신규 Lock에서는 VM ID가 다르면 서로 간섭이 없기 때문에, 
  - 기다림이 길어지는 현상은 동일 VM에 대한 호출들의 지연으로 보입니다.
  - 아마도, 실행 시간이 긴 Terminate(Sync Call) 진행 중에 
  - 동일 VM에 대한 Status Check 반복 호출로 인한 기다림일 듯합니다.

- [Timeout 관련 현황]
  - 1월~5월사이의 HisCall 정보에서 Driver별 Terminate VM 소요 시간을 추출한 차트가 다음과 같음
  - Azure의 경우 대게 30초를 넘기고 있습니다.
    - 참고: 짧은 elapsed time 중에는 Driver가 Async Call 일수도 있음(미확인 상태)

<br>

  - ![image](https://user-images.githubusercontent.com/46367962/173271588-1211d878-98dd-45be-a987-61ee3a57d9c4.png)

### [관련 이슈]
- #### issue(1): Driver별로 API 동작이 Sync와 Async가 섞여 있는 상태
- #### issue(2): Async API 추가 필요성 재검토
  - 추가로, Spider VM 상태 중 `Creating`, `Running` 등  ~ing 상태는 Sync Call 기반 API 상에서는 무의미
    - Sync vs Async  vs Status 종류, 정리가 필요
    - [Spider VM 상태 규격 참고](https://github.com/cloud-barista/cb-spider/wiki/features-and-usages#1-vm-%EC%83%9D%EC%84%B1-%EB%B0%8F-%EB%9D%BC%EC%9D%B4%ED%94%84%EC%82%AC%EC%9D%B4%ED%81%B4-%EC%A0%9C%EC%96%B4)

- #### [Plan]
  - (1) GetVMStatus/ListVMStatus: 일단, Unlock 후 배포/운영
  - (2) 6차 행사 후 Async Call 추가 고려

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo

- [Plan] (1) 반영
  - https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.10

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo

- [Plan] (1) 반영으로도 느림 현상이 계속되는 이슈 해결 버전
  - 사유: ListVMStatus에서 불필요하게 GetVM()을 사용 중이 었음.
  - https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.10-p1
