### ISSUE TITLE
Speed of response for list VM is too slow with SP v0.5.9

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#681]
**What happened**
CB-TB를 통해 MCIS 약 10개, VM 총 37개 상황에서

기존(v0.5.4 신규 lock 방식 적용 전)에 비해서, VM list 조회 속도가 현저하게 낮아서, Timeout 오류가 지속적으로 발생.

**What you expected to happen**
속도 개선 (적어도 v0.5.6 수준)

**How to reproduce it (as minimally and precisely as possible)**
CB-TB로 CSP 기존 자원 모두 등록하기 수행. (공용 클라우드 계정에 의해서 약 37개 정도의 VM 등록됨)

**Anything else we need to know?**
 - 라이프사이클 상태가 다양한 VM들로 구성되어 있음. (이중, CSP 상에서 terminated 되었지만, 완전 삭제되지 않고 기록만 남은 상태의 VM도 있음)
   - 등록 기능, 라이프사이클 상태와 관련된 문제일 수도 있음.
 - 문제가 v0.5.9 에서만 발생하는지 확신은 없음.

![image](https://user-images.githubusercontent.com/5966944/173371706-34570823-1d43-42f5-ac8c-e5012896cc2e.png)

**Environment**
- Source version or branch: v0.5.9
- OS: ubuntu
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by seokho-son** [comment]
#680 와 연관이 있을 수 있음.

**Comment by powerkimhub** [comment]
●  #680 과 원인이 같을 것으로 추정
