### ISSUE TITLE
[GCP] Need to check Reboot() flow and status

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#685]
- Reboot 오류 관련 확인 필요합니다. 
  - Reboot 호출하면 재시작이 되지 않고, Stopped 상태로 멈춰 있음
- 코드분석
  - Driver-Reboot 호출: SuspendVM() ==> ResumeVM()을 순서대로 호출
  - SuspendVM()은 CSP의 Stop()을 호출하고, 
  - ResumeVM()은 CSP의 Start()를 호출함.

- 확인필요
  - SuspendVM()에서 CSP의 Suspend()를 호출해야 하는 건 아닌지 확인 필요
    - GCP Console에서는 Suspend가 별도 존재, 
    - API는 Suspend() 존재 여부 미확인

- 확인필요
  - SuspendVM() 호출 후, Stopped 되기 전에
  - ResumeVM()이 호출되는 건 아닌지 확인 필요

**Comment by seokho-son** [comment]
참고.

https://cloud.google.com/compute/docs/instances/instance-life-cycle#resetting_an_instance

https://cloud.google.com/compute/docs/instances/stop-start-instance#resetting_an_instance

GCP에 Resetting a VM 기능이 있던데,

OS hard reboot 에 해당하지 않을까 싶네요.

**Comment by powerkimhub** [comment]
● Fixed in https://github.com/cloud-barista/cb-spider/pull/689
