### ISSUE TITLE
[Cloudit] Check the continuous Rebooting status

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#692]
- 아래 시험 결과와 같이 5회의 시험 중 3회의 시험이 Rebooting 상태로 남아 있습니다.
  - RebootingVM() 후 VM 상태를 한동안 체크해본 결과
- Test Flow를 참고하시면, Life Cycle 조정 후에 현 이슈가 발생하는 걸로 예상됩니다. 

#### * Test Flow: StartVM => SuspendVM => ResumeVM => RebootVM
[1] Status: Rebooting
[2] Status: Rebooting
[3] Status: Rebooting

#### * Test Flow: StartVM => RebootVM
[4] Status: Running
[5] Status: Running

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
확인해보겠습니다!

**Comment by inno-cloudbarista** [comment]
@powerkimhub
* Test Flow: StartVM => SuspendVM => ResumeVM => RebootVM 의 경우 Rebooting 상태로 오래 남아있는 현상에 대한 답변 드립니다.

StartVM => SuspendVM => ResumeVM의 상태에서 Running으로 표현되어 Return되지만, 
해당 Running은 VM Instance내 OS가 모두 준비됨을 의미하지 않아, 이때 Reboot 혹은 Suspend 등의 명령을 보내면, 해당 명령을 수행하지 못하고 주기적으로 명령 수행을 요청합니다.

이 과정에서 많은 시간이 소요되는것으로 판단됩니다. 

Stopped => Running로 상태가 변경되는 부분에서 상태를 판단하는 부분에 해당 VM이 요청을 받을수 있는 상태인지(ssh 혹은 ping 체크) 확인하는 로직을 추가하려고 합니다.

StartVM에서는 ssh로 붙기위해 대기하는 로직이 있기에 ResumeVM 부분에 추가적으로 작업하려고 합니다.

그럼 Test RebootVM => RebootVM 일 경우에도 동일한 문제가 발생할 수 있는데, RebootVM은 Rebooting이 아니라, Running 상태일 때 리턴하도록 변경해야 할 거 같습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 질문: 위와 같은 'Rebooting' 상태가 오래 기다리면, 'Running' 상태로 되나요?
- 그렇다면, 대략 어느 정도 시간을 기다리면 되는지요?

**Comment by inno-cloudbarista** [comment]
@powerkimhub
5분(300초)정도 지나면, 강제적으로 ShutDown을 하고(콘솔에선 VmShutdown Fail Timeout: {VM_UUID}이라는 에러로 확인이 됩니다.) 다시 Running가 됩니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub
위 내용에 부정확한 부분이 있어, 관련 부서에 협조요청중입니다.
(콘솔에선 VmShutdown Fail Timeout: {VM_UUID}이라는 에러로 확인이 됩니다. 에러 출력후 => 강제 종료=>재시작 )

에러 출력 후 강제 종료인지 => 재시작인지 아니면 Reboot 자체가 되지 않는것인지, 확인 후 다시 공유드리겠습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

**ResumeVM()을 기준으로 나누어 보면, 다음과 같은 상황인 것인지요?**

- Test Flow: StartVM => SuspendVM => ResumeVM
  - 비동기로 'Running' 반환 ('Resuming' 상태가 아닌)
  - 하지만, 사용자가 생각하는  'Running' 상태는 미도달

- Test Flow: StartVM => SuspendVM => ResumeVM => RebootVM(또는 SuspendVM)
  - 약 5분 후 정상 상태(중간 과정 확인 중)

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 추가로, ResumeVM() 반환 상태 'Running'이 실제 사용자가 원하는 'Running'이 되는 상태는Cloudit API로는 확인 불가
- 대안으로, 제시해주신 방법 등 제 3의 방법으로 가능한 상황(ssh, ping 등)

**Comment by inno-cloudbarista** [comment]
@powerkimhub
넵 맞습니다.

추가적으로  에러 출력 후 강제 종료인지 => 재시작이 아니라,  Reboot 자체가 되지 않습니다.

현재 대안으로 제시한 제 3의 방법으로 실제 사용자가 원하는 'Running'이 되는 상태를 확인후, 리턴하는 방향으로 생각하고 있습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

[참고사항]
- Async Call API: SuspendVM() / ResumeVM() / RebootVM()
- Sync Call API: StartVM() / TerminateVM(), 그 외 API
- 현재 기본은 이와 같이 맞춰 진행되고 있는 상황입니다. 
- 현재 Cloudit Driver 현황: 
  - ResumeVM() : CSP 호출 후 Running 상태를 기다렸다 반환
  - RebootVM(): CSP 호출 후 바로 반환
  - 일관성이 없지만, 현재는 이를 굳이 조정할 필요는 없으십니다. 
  - 하지만, ssh, ping 가능시 까지 함수 내부에 추가하는 것은 Async Call로서는 
    - 좀 부담스럽기는 합니다. 

---
- 그래서, 다시 이슈를 좀더 세분화 해보고 추가 시험을 해보았습니다. 

- **Spider API**: SuspendVM() => ResumeVM() => Loop(cb-user@vm)
  - 이 패턴을 여러번 반복 실행 해도 cb-user ssh 로그인 성공
  - cb-user login은 'Running' 상태 이후 시간이 좀 필요하긴 함.
    - 현재 이렇게 ssh에 시간이 좀 필요한 부분은 문제는 아닙니다.
    - 이 부분은 Spider에서도 Tumblebug에서도 인지하고 사용 중입니다. 

- **Cloudit Web**: `재시작` => `재시작` => 반복
  - (VM 생성만 Spider API로 생성 이후 Web Console에서 재시작만 반복)
  - 두번째 `재시작` 또는 몇차례 후 `재시작`에서 
  - `rebooting` 상태로 멈추는 최초 이슈가 발생합니다. 
  - 이렇다는 얘기는 CSP 상태 제공에 이슈가 있는 건 아닌지 확인해보는 것이 우선 일 것 같습니다. 
  - `재시작`을 실행하면, `rebooting` => `running`으로 상태가 바뀝니다.
  - `running` 상태로 바뀌기 전에는 `재시작` 실행이 안되고, 
  - `running` 상태로 바뀐 후에 `재시작`이 가능하여 실행하면, 
  - 간헐적으로 오류가 발생하는 것 같습니다.

- 시험 과정에서 제가 실수가 있었을 수도 있으니, 재확인 해보시기 바랍니다.
- 현재 시험 상황이 맞다면, 
- Driver 개선 작업은 CSP 검증 후 다시 고려해보시는 것이 좋을 것 같습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
넵 현재 관련부서와 해당 사항에 대해 문의 후, 논의중입니다.

확인후 공유드리겠습니다!

**Comment by inno-cloudbarista** [comment]
@powerkimhub
위 이슈에 관하여, 공유드립니다.

중복되는 표현이 많아 잠시 용어를 정리하고 말씀드리겠습니다.

실제 사용자가 원하는 'Running'를 **Spider-Running**이라고 표현하겠습니다.
실제 사용자가 원하는 'Running'이 아니지만, CSP(Cloudit)의 'Running'을 **OnlyCSP-Running**이라 표현하겠습니다.
OnlyCSP-Running은 VM은 Runnig이나, OS, Network등이 준비되지 않은 상태를 이야기합니다.(cb-user@vm 불가)

 VM이 Stop => Running 상태일 때,  **OnlyCSP-Running** => **Spider-Running**  상태로 되는데,  **OnlyCSP-Running** 일때, VM을 끄는 액션(Reboot or suspend)을 보내면 상황이 재현됩니다. 
 
 - **Spider-Running** 이라면 SuspendVM, RebootVM 등의 액션을 받을수 있습니다.
 -  **OnlyCSP-Running**이라면  SuspendVM, RebootVM 등의 액션을 받을수 없습니다.
	   - 이 경우, 300초가 지난 후 Running으로 돌아오나, 이것은 Reboot 과정을 지나지 않고, Reboot를 실패했음을 의미합니다.  
	   -  두번째  `재시작`  또는 몇차례 후  `재시작`에서  `rebooting`  상태로 멈추는 최초 이슈가 발생합니다. 이부분에서 재현되는 경우는 **OnlyCSP-Running**  일때 재시작을 요청하였을 때 발생합니다. (타이밍의 문제로 언제나 재현되지 않는거 같습니다. )
	   
문제는 CSP에서 **Spider-Running** 을 확인 할 수 없다는 부분입니다.

케이스 1
- StartVM()=> [1]SuspendVM() => [2]ResumeVM() => [3]Loop(cb-user@vm) => SuspendVM() => ResumeVM() => Loop(cb-user@vm) ....

	1. 최초 SuspendVM()을 하는 경우, Spider-Running상태입니다.
	   - VM 생성 후, SSH Key를 넣기위해 StartVM내에서 wait하며 기다립니다.
	   -  **Spider-Running**상태임을 기다리는 로직이 포함되어 있습니다.
	   - CSP의 SuspendVM() 요청을 받아 종료될 수 있습니다.

	2. Stop된 상태에서 다시 ResumeVM 상태이기에 문제는 없습니다.

	3. 이상태에서 OnlyCSP-Running 혹은 Spider-Running 상태입니다.
       - 위 테스트에서는 Loop(cb-user@vm)으로 Spider-Running임을 체크하는 것으로 OnlyCSP-Running => Spider-Running을 Loop(cb-user@vm)으로 기다립니다.

만약 Loop(cb-user@vm)이 없이  SuspendVM() => ResumeVM() =>  SuspendVM() => ResumeVM() 이 반복되는 경우 Reboot와 같은 현상을 겪게 됩니다.(Stopping)

현재 CSP에서 해당 VM의 상태가 Spider-Running인지 확인할 수 있는 방법은 없습니다.

케이스2.
Cloudit Web: 재시작 => 재시작 => 반복 
 - Cloudit에서 내부적으로 Reboot도 결국 SuspendVM -> ResumeVM 의 구성으로 되어 있습니다.
 - RebootVM  = SuspendVM() => ResumeVM() 으로 생각하면

케이스2사항도 만약  케이스 1처럼 
 - 재시작 => Loop(cb-user@vm) => 재시작 => Loop(cb-user@vm) => ... 처럼 Loop(cb-user@vm)으로 **Spider-Running**임을 체크하는 부분이 있다면 문제는 발생하지 않습니다. 
 - 웹 콘솔의 경우:  재시작 => 충분한 시간 => 재시작 => 충분한 시간  => ...으로 진행하면  위 문제는 발생하지 않습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 상세 현황 설명 감사드립니다~
- Cloudit VM 제어 관련 현황 잘 이해 되었습니다.

**[Driver 추진 관련]**

> 웹 콘솔의 경우: 재시작 => 충분한 시간 => 재시작 => 충분한 시간 => ...으로 진행하면 위 문제는 발생하지 않습니다.

&nbsp;&nbsp;  ⇛ 이와 같은 사용 패턴이 Cloudit의 정상 서비스 패턴(정책)이라고 한다면, 

- 처음에 제안 주신 방법대로 Driver 내부에서 확인하는 처리(ssh,... 등) 적용 부탁 드립니다. 
- 적용 후 Driver 단에서 수 차례 관련된 VM 제어 점검 시험 후 PR 부탁 드립니다.
- 참고로, Spider Server단에서 VM 제어 관련된 시험 도구 위치는 다음과 같습니다. 
  - 1.~ => 2.~ => ~ 순으로 시험을 진행합니다.
  - sh을 열어 보시면, 대략 Suspend 등의 VM 제어 요청 후 다음 항목을 실행하기 전에 
    - 확인하는(기다리는) 내용을 보실 수 있습니다. 참고해주시기 바랍니다.
  ```
  ./cb-spider/test/functional-test-cli/4.vm-test/*
  ```

**Comment by powerkimhub** [comment]
• Fix in https://github.com/cloud-barista/cb-spider/pull/711
