### ISSUE TITLE
[NLB] Integration and Test

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#695]
- 다음과 같이 분석 및 작성해주신 CSP별 제공 기능 및 이슈 현황을 토대로
  - [1. CSP별 NLB 이슈 현황 분석](https://docs.google.com/spreadsheets/d/1z4-H-rmbuPLS93JxQwY4prmT9CFLr2TT/edit#gid=1183721823)

- 다음과 같이 NLB 통합 방안 및 시험 계획을 공유 드립니다. 
  - 세부 내용은 아래 관련 문서 링크를 참고해주시기 바랍니다. 
  - [2. 시험 가이드 및 시험 항목 참고](https://docs.google.com/spreadsheets/d/1z4-H-rmbuPLS93JxQwY4prmT9CFLr2TT/edit#gid=1707315016)

  - [3.시험 결과 양식 참고](https://docs.google.com/spreadsheets/d/1z4-H-rmbuPLS93JxQwY4prmT9CFLr2TT/edit#gid=625044322)

---

- 관련 문의 및 이슈 공유는 현 이슈 답글로 부탁 드립니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
아래 에러에 대해서 공유드립니다.

에러 메세지에 vpc-01이라는 vpc를 조회하지만, 실제로 생성된 vpc의 이름은 vpc-01-cb78527emdcekdhuamgg로 생성되어, 찾지 못하는 문제 같습니다.

cb-spider/test/nlb-test-curl/common/create-nlb-test.sh 내에서 VPCName을 변경하여 테스트하려고 해보니,

{
   "message" : "[azure-azure-northeurope--connection-config-01:vpc:vpc-01-cb78527emdcekdhuamgg] does not exist!"
}
위의 에러가 뜹니다.
IBM도 테스트 해보니, vm을 찾지 못해 발생하는 문제 같습니다.

Azure VPCName에도 ConvertVMIID()와 같은 기능이 필요한거 같습니다. 
IBM도 동일한 기능이 필요한거 같습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub
Azure-VM 추가 삭제시, 에러 확인하였습니다. 
위 테스트 후, 수정하여 반영하도록 하겠습니다!

**Comment by powerkimhub** [comment]
• Fix in https://github.com/cloud-barista/cb-spider/pull/714
