### ISSUE TITLE
[NLB:GCP] Need to check the result infos about NLB API

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#699]
- 반환 되는 NLB 정보 점검 부탁드립니다. 
- 대상 API: Create/List/Get/AddVMs/Change
- VMGroup Protocol, Port 설정 값의 경우 항상 Listener 설정과 동일하므로
  - Listener 값으로 설정해서 올려주시면 될 것 같습니다. 
- 결과 및 대상 참고
  ```
  {
     "Scope" : "REGION",
     "VpcIID" : {
        "SystemId" : "vpc-01-cbcdnhqba5o0nga5f070",
        "NameId" : "vpc-01"
     },
     "CreatedTime" : "2022-07-20T21:58:01.396-07:00",
     "VMGroup" : {
        "CspID" : "spider-nl-cbcdpjqba5o0nga5f0a0",
        "Port" : "",               <======== (1) expected result: Port Number
        "VMs" : [
           {
              "SystemId" : "vm-01-cbcdnriba5o0nga5f090",
              "NameId" : "vm-01"
           },
           {
              "NameId" : "vm-02",
              "SystemId" : "vm-02-cbcdo6iba5o0nga5f09g"
           }
        ],
        "KeyValueList" : null,
        "Protocol" : ""               <======== (2) expected result: Protocol Value
     },
     "Type" : "PUBLIC",
     "KeyValueList" : null,
     "Listener" : {
        "IP" : "35.232.81.104",
        "Protocol" : "TCP",
        "DNSName" : "",
        "CspID" : "spider-nl-cbcdpjqba5o0nga5f0a0",
        "Port" : "22-22",                            <======== (3) expected result: single Port Number (22)
        "KeyValueList" : null
     },
     "HealthChecker" : {
        "Protocol" : "HTTP",
        "Timeout" : 9,
        "Interval" : 10,
        "CspID" : "https://www.googleapis.com/compute/v1/projects/powerkimhub/global/httpHealthChecks/spider-nl-cbcdpjqba5o0nga5f0a0",
        "KeyValueList" : null,
        "Port" : "22",
        "Threshold" : 3
     },
     "IId" : {
        "SystemId" : "spider-nl-cbcdpjqba5o0nga5f0a0",
        "NameId" : "spider-nlb-01"
     }
  }
  ```

**Comment by MZC-CSC** [comment]
[NLB:GCP] Check SystemId format of ListNLB Result #700 내용 보완 후 
NLBNAME : spider-nlb-904
VM Name : vm-901, vm-902
Add VM Name : vm-911, vm-912
로 Test 한 결과입니다.

1. Create NLB
#####---------- CreateNLB ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 10,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 3,
      "Timeout" : 9
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901-cbbkikat39hdgf4ri26g",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902-cbbkj1qt39hdgf4ri270",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}

2. ListNLB
#####---------- ListNLB ----------####
{
   "nlb" : [
      {
         "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
         "HealthChecker" : {
            "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
            "Interval" : 10,
            "KeyValueList" : null,
            "Port" : "22",
            "Protocol" : "HTTP",
            "Threshold" : 3,
            "Timeout" : 9
         },
         "IId" : {
            "NameId" : "spider-nlb-904",
            "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
         },
         "KeyValueList" : null,
         "Listener" : {
            "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
            "DNSName" : "",
            "IP" : "34.146.161.242",
            "KeyValueList" : null,
            "Port" : "22-22",
            "Protocol" : "TCP"
         },
         "Scope" : "REGION",
         "Type" : "PUBLIC",
         "VMGroup" : {
            "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
            "KeyValueList" : null,
            "Port" : "",
            "Protocol" : "",
            "VMs" : [
               {
                  "NameId" : "vm-901",
                  "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
               },
               {
                  "NameId" : "vm-902",
                  "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
               }
            ]
         },
         "VpcIID" : {
            "NameId" : "vpc-01",
            "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
         }
      }
   ]
}
#####---------- GetNLB ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 10,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 3,
      "Timeout" : 9
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}
#####---------- ListAllNLB ----------####
{
   "AllList" : {
      "MappedList" : [
         {
            "NameId" : "spider-nlb-904",
            "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
         }
      ],
      "OnlyCSPList" : [],
      "OnlySpiderList" : []
   }
}


#####---------- GetNLBOwnerVPC ----------####
{
   "message" : "nlb-spider-nl-cbcf8fqt39heil02ajs0 already exists with spider-nlb-904!"
}

3. Add/Remove Vm
#####---------- AddVMs ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 10,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 3,
      "Timeout" : 9
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         },
         {
            "NameId" : "vm-911",
            "SystemId" : "vm-911-cbcfc62t39heil02ajsg"
         },
         {
            "NameId" : "vm-912",
            "SystemId" : "vm-912-cbcfcfit39heil02ajt0"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}
#####---------- GetNLB ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 10,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 3,
      "Timeout" : 9
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         },
         {
            "NameId" : "vm-911",
            "SystemId" : "vm-911-cbcfc62t39heil02ajsg"
         },
         {
            "NameId" : "vm-912",
            "SystemId" : "vm-912-cbcfcfit39heil02ajt0"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}

#####---------- RemoveVMs ----------####

true

#####---------- GetNLB ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 10,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 3,
      "Timeout" : 9
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}

4. Change
#####---------- ChangeListener ----------####
{
   "message" : "GCP_CANNOT_CHANGE_LISTENER"
}
#####---------- ChangeVMGroup ----------####
{
   "message" : "GCP_CANNOT_CHANGE_VMGroupINFO"
}
#####---------- ChangeHealthChecker ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 11,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 4,
      "Timeout" : 11
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}
#####---------- GetNLB ----------####
{
   "CreatedTime" : "2022-07-20T23:38:29.515-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbcf8fqt39heil02ajs0",
      "Interval" : 11,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 4,
      "Timeout" : 11
   },
   "IId" : {
      "NameId" : "spider-nlb-904",
      "SystemId" : "spider-nl-cbcf8fqt39heil02ajs0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "DNSName" : "",
      "IP" : "34.146.161.242",
      "KeyValueList" : null,
      "Port" : "22-22",
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbcf8fqt39heil02ajs0",
      "KeyValueList" : null,
      "Port" : "",
      "Protocol" : "",
      "VMs" : [
         {
            "NameId" : "vm-901",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}

**Comment by powerkimhub** [comment]
@MZC-CSC @dogfootman 

•  #700 이슈에 대한 시험 결과인데
----  #699 이슈 답글로 잘못 올리신 거 같아요.
---- 현재 이슈도 확인 부탁드려요~
•  #700 반영 PR은 잘 동작하는 거 확인했습니다.
----  감사합니다.

**Comment by MZC-CSC** [comment]
test/nlb-test-curl 에서 
Create/List/Get/AddVMs/Change 에 대한 결과를 1,2,3,4번으로 첨부했는데
해당 API 수행 후 GET 결과를 첨부하면 될까요?

**Comment by powerkimhub** [comment]
@MZC-CSC 

- 아, 죄송합니다. 제가 이슈를 모호하게 올렸네요. 
- GetNLB로 얻는 정보 중에 잘못된 값이 있어서 점검을 부탁드린 거였습니다.^^
- 첫 이슈 글에서  `<========` 로 검색 해보시면, 3군데 있어요. 
- 이러한 부분이 Create/List/Get/AddVMs/Change 결과에서도 제공하는 값들이어서 함께 점검을 부탁드린 내용이었습니다.

**Comment by dogfootman** [comment]
내용 확인했습니다.
1.2번 VMGroup의 Protocol, Port는 GCP가 사용하지 않는 부분이고
AddVM에서 VmGroup을 return하는데 해당 값을 설정하기 위해서는 불필요한 listener를 조회해야해서 뺴 놓은 것이었습니다.
말씀하신대로 넣도록 하겠습니다.
3번 내용은 미처 확인 못했던 부분이네요. Range로 받아온 부분은 처리하도록 하겠습니다.

**Comment by MZC-CSC** [comment]
NLB 조회시 아래와 같이 결과를 보여줍니다.
말씀하신 1,2,3번 항목 보완했습니다.

{
   "CreatedTime" : "2022-07-21T21:40:41.167-07:00",
   "HealthChecker" : {
      "CspID" : "https://www.googleapis.com/compute/v1/projects/csta-349809/global/httpHealthChecks/spider-nl-cbd2k8at39hbbgsubnt0",
      "Interval" : 10,
      "KeyValueList" : null,
      "Port" : "22",
      "Protocol" : "HTTP",
      "Threshold" : 3,
      "Timeout" : 9
   },
   "IId" : {
      "NameId" : "spider-nlb-906",
      "SystemId" : "spider-nl-cbd2k8at39hbbgsubnt0"
   },
   "KeyValueList" : null,
   "Listener" : {
      "CspID" : "spider-nl-cbd2k8at39hbbgsubnt0",
      "DNSName" : "",
      "IP" : "34.85.8.36",
      "KeyValueList" : [
         {
            "Key" : "createdTime",
            "Value" : "2022-07-21T21:40:41.167-07:00"
         },
         {
            "Key" : "loadBalancerType",
            "Value" : "PUBLIC"
         }
      ],
      "Port" : "22",   /////// 3
      "Protocol" : "TCP"
   },
   "Scope" : "REGION",
   "Type" : "PUBLIC",
   "VMGroup" : {
      "CspID" : "spider-nl-cbd2k8at39hbbgsubnt0",
      "KeyValueList" : null,
      "Port" : "22",  ////// 2
      "Protocol" : "TCP", ////// 1
      "VMs" : [
         {
            "NameId" : "vm-901-cbbkikat39hdgf4ri26g",
            "SystemId" : "vm-901-cbbkikat39hdgf4ri26g"
         },
         {
            "NameId" : "vm-902-cbbkj1qt39hdgf4ri270",
            "SystemId" : "vm-902-cbbkj1qt39hdgf4ri270"
         }
      ]
   },
   "VpcIID" : {
      "NameId" : "vpc-01",
      "SystemId" : "vpc-01-cb8h3s16to9ucj6qrihg"
   }
}

**Comment by powerkimhub** [comment]
• fixed in https://github.com/cloud-barista/cb-spider/pull/703
