### ISSUE TITLE
[GCP] NLB has no return message to UDP Call

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#708]
- NLB 관련 다음 시험에서
  - https://docs.google.com/spreadsheets/d/1z4-H-rmbuPLS93JxQwY4prmT9CFLr2TT/edit#gid=1051610479

#### [4. UDP 사용자 서비스 대상 설정 및 시험] - CASE 2 시험 항목 시험에서 (현재 빨간색 폰트로 표시)
- 시험 조건: 2개의 VM을 포함하고, 다음 NLB 설정으로 NLB를 구성하였습니다. 

Listener | VMGroup | HealthChecker
-- | -- | --
UDP:100 | UDP:100 | HTTP:80

- VM에는 다음과 같이 설치 및 설정되어 있습니다. 
    - SG: UDP:100, TCP:80 오픈
    - UDP:100번 포트로 데몬 가동(콜 받으면, VM의 public ip를 반환함)
      - 설치 스크립트: 0.prepare-udp-nlb-test.sh
    - nginx:80번 포트로 데몬 가동(HealthCheck 용)
      - 설치 스크립트: 0.prepare-nginx-nlb-test.sh

--------

- VM 직접 호출하면, 
- 다음처럼 VM의 public ip를 잘 반환합니다. (15byte 수신)
  ```
  $ ncat -zvu 34.136.244.xxx 100
  Ncat: Version 7.60 ( https://nmap.org/ncat )
  Ncat: Connected to 34.136.244.145:100.
  34.136.244.xxx
  Ncat: UDP packet sent successfully
  Ncat: 1 bytes sent, 15 bytes received in 2.39 seconds.
  ```
- NLB를 통해서 호출하면, 
- 다음처럼 VM의 public ip 정보를 수신하지 못합니다. (0byte 수신)
  ```
  $ ncat -zvu 35.202.201.xxx 100
  Ncat: Version 7.60 ( https://nmap.org/ncat )
  Ncat: Connected to 35.202.201.xxx:100.
  Ncat: UDP packet sent successfully
  Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.
  ```

- 타 CSP AWS, Azure의 경우, NLB를 통하여도 잘 수신 되고 있습니다. 
  - AWS 예시
    ```
    $ ncat -zvu spider-nl-cbh8sc2ba5o48g4leql0-867c5b73f6815ffd.elb.us-east-2.amazonaws.com 100
    Ncat: Version 7.60 ( https://nmap.org/ncat )
    Ncat: Connected to 18.217.189.98:100.
    18.219.45.154
    Ncat: UDP packet sent successfully
    Ncat: 1 bytes sent, 14 bytes received in 2.38 seconds.
    ```

- SG 설정 문제인지, 아니면 GCP NLB 기본 설정 문제인지, 
- 원인을 잘 모르겠습니다. 
- 확인 부탁 드립니다.

**Comment by MZC-CSC** [comment]
GCP에 문의한 결과,
NLB를 통해서 호출했을 때 UDP 연결은 형성되었으나 응답은 주지 않는 것이 정상 케이스라고 합니다.

**Comment by powerkimhub** [comment]
@MZC-CSC 

- 확인 및 공유 감사합니다~
