### ISSUE TITLE
[IBM:NLB] API Response too late

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#709]
- Create NLB 등 전반적인 API 응답 속도가 매우 느립니다. 
- IBM CLI나 웹 콘솔과 유사한 소요 시간인지 확인이 필요해 보입니다. 
- 또한, 내부에서 사용되는 IBM API 호출들의 병렬 요청 등의 개선 포인트 점검 부탁드립니다.

**Comment by inno-cloudbarista** [comment]
@powerkim
CreateNLB시에, creating 상태에서 active상태가 되기까지 많은 시간이 소요됩니다.(콘솔에서도 동일)
NLB를 변경하는 핸들러의 경우도, 업데이트 후 active상태까지 기다리는데 여기서도 시간이 많이 소요됩니다(콘솔에서도 동일)...
조회의 경우, 시간이 오래 소요되는 것은 API 개선가능합니다(병렬 요청으로 개선 가능)

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 넵, 그렇군요. 현황 공유 감사드립니다. 
- 병렬 요청 개선은 추진 부탁드립니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 아, 그리고 전 @powerkimhub ^^

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
병렬 요청 개선 추진하도록 하겠습니다

**Comment by powerkimhub** [comment]
• Fixed in https://github.com/cloud-barista/cb-spider/pull/762
