### ISSUE TITLE
Suggestion: alignment about VM status types with CB-Tumblebug

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#71]
Suggestion: alignment about VM status types with CB-Tumblebug

CB-Tumblebug defined the following VM status types,
Final status category :
	Running
	Suspended
	Failed
	Terminated

Transitional status category :
	Creating
	Suspending
	Resuming
	Rebooting
	Terminating

CB-Spider provides the following status types which are not aligned with CB-Tumblebug.
```
type StatusInfo struct {
        Status string 
// PENDING | RUNNING | SUSPENDING | SUSPENDED | REBOOTING | TERMINATING | TERMINATED

```
There are missing status types for VM. (Failed)
And "PENDING" status can be changed to "Creating" status

**Comment by powerkimhub** [comment]
Thank you for your suggestion.
I'll check it ASAP ~

**Comment by powerkimhub** [comment]
![image](https://user-images.githubusercontent.com/46367962/68849383-4d407900-0715-11ea-91a5-fe6159d4fc19.png)
