### ISSUE TITLE
[+K8S] Cloud Driver API Definition for Managed K8S

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#716]
- [x] Provider Managed K8S(PMKS) features and Interfaces Analysis of CSPs
- [x] Cloud Driver PMKS API Definition
- [x] Cloud Driver PMKS API Review

**Comment by powerkimhub** [comment]
- ref) https://github.com/cloud-barista/cb-spider/wiki/Provider-Managed-Kubernetes-and-Driver-API

**Comment by MZC-CSC** [comment]
[AWS] K8S 관련 확인내용입니다.
1.Cluster 생성 후 NodeGroup, Addon을 붙이는 형태이며 Cluster 생성시간이 오래걸림.
따라서 CreateCluster에서 모든것(nodegroup, addon 등)을 한번에 만들 것인지 결정필요

2. 현재 Cluster, NodeGroup 만 interface에 정의되어 있으나, Addon 등도 정의 필요

3. Nodegroup은 ClusterName이 required이나 현재 spider의 NodeGroupInfo에는 해당 parameter(clusterName)가 없음.

4. NodeGroup에 Node추가/제거는 제공하지 않음
우회적으로 Scaling의 기본갯수(desiredSize)를 변경하는 것으로 처리 가능

5. Cluster 뿐 아니라 NodeGroup도 Subnet이 required

6. Cluster 뿐 아니라 NodeGroup도 Role 이 required 이므로 
cluster의 roleName : spider-eks-role 를 spider-eks-cluster-role 로
nodeGroup의 roleName : spider-eks-nodegroup-role 등으로 변경/추가 필요

7. NodeGroup에서 Node의 IID를 사용하지 않음
 -> 현재 확인한 API(describeNodegroup)에서는 node(instance)정보를 찾지 못했습니다. 좀 더 확인 필요

현재까지 파악한 내용입니다. 참고바랍니다.

**Comment by powerkimhub** [comment]
@MZC-CSC 

- 현황 분석 및 공유 감사드립니다.
- 다음 버전 업그레이드 시에 감사히 참고하도록 하겠습니다.

**Comment by MZC-CSC** [comment]
[AWS] 추가내용입니다.
AWS 관련 API 경로
https://docs.aws.amazon.com/eks/latest/APIReference/API_Operations.html

1. PMKS Interface 의 AddNodeGroup, RemoveNodeGroup 은 사용할 수 없습니다.
AWS는 NodeGroup을 따로 등록해놓고 사용하지 않기 때문에 NodeGroup IID를 추가하는 방식으로는 사용불가합니다.
CreateNodeGroup, DeleteNodeGroup 만 가능합니다.

2. NodeGroupHandler에서 
RemoveNodes는 특정 vm 을 제거 할 수 없습니다. scaling만 가능합니다.

3. NodeGroupHandler에서
모든 function은  ClusterName 이 필수입니다.

ps. NodeGroup Config변경 function이 정의되어 있지 않습니다. AddOn 관련 function이 정의되어 있지 않습니다.

참고 바랍니다.

**Comment by powerkimhub** [comment]
@MZC-CSC 

- 넵, 감사합니다.
- 버전 업그레이드 시 참고하겠습니다.

**Comment by MZC-CSC** [comment]
[AWS] Node 정보 관련해서 확인 된 내용입니다.
https://repost.aws/questions/QUmdIYaeG7QHWd-AdI8To4Qw/query-eks-node-information-with-python-boto-3-or-aws-cli

내용정리를 하면 
EKS에서는 cluster와 nodegroup 정보만 확인가능하다.
node 정보가 필요하다면 kubectl 또는 kubernetes open api를 이용해서 조회가능하다.

다른 provider도 비슷하다면 kubernetes-client를 공통으로 이용해야 하지 않을까요?

kubernetes-client golang 버전입니다.
https://github.com/kubernetes-client/go

--- 원문입니다.
With an EKS cluster, you can gather information in the EKS level or in the Kubernetes level. In the EKS level, you can use eksctl tool or the Boto EKS Client, but at this level, you can only look into cluster/nodegroup information. What you want is node information. So you have to query at Kubernetes level. You could use [kubectl tool](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources) to create your query. For example:

# list all nodes in the cluster with their labels
kubectl get nodes --show-labels
# list all nodes in a specific nodegroup
kubectl get node --selector='eks.amazonaws.com/nodegroup=x86-br-spot-xl'

If you want to do this in Python, you could use [Kubernetes Python Client](https://github.com/kubernetes-client/python).

from kubernetes import client, config

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

k8s_api = client.CoreV1Api()
logger.info("Getting k8s nodes...")
response = k8s_api.list_node()

You should look into Kubernetes documentation on how to get all the info you want with kubectl and then translate it later to Python.

**Comment by powerkimhub** [comment]
@MZC-CSC 

### [Node 정보 제공]
- 현황 분석 및 공유 감사드립니다. 
- 일단, Spider 수준에서는 아래 가이드 중 첫번째 방법(VM ID만 제공)으로 추진하는 게 좋겠습니다. 
  - ref) https://github.com/cloud-barista/cb-spider/wiki/Provider-Managed-Kubernetes-and-Driver-API

          ... 중략 
          
          • NodeGroup의 Node(VM) 제공 정보 범위: TBD
            - IID만 반환하고, 필요시 VMHandler 활용하는 방법 vs NodeGroup으로서의 Node(VM) 정보를 별도로 제공
            - NodeGroup 생성 요청 후 NodeGroup 정보 제공시 VM의 상태 제공 등
             
          중략 ...
          

### [개략적인 활용 시나리오]
- PMKS에서는 NodeGroup을 구성하는 VM ID 목록만 제공
- 사용자가 노드 상세 정보 필요시에는 다음처럼 획득
  - VMHanlder를 통한 Node 정보 획득 
    (Spider 상위 계층에서는 필요시 NLBHandler+VMHandler를 사용하여 NodeGroup의 Node 상세 정보 제공 가능)
  - 또는 추가 도구( kubectl, Lens 등) 활용한 상세 정보 획득

**Comment by powerkimhub** [comment]
Commented by @iworkist 

- 다음 2개의 Handler 통합 고려 필요
  - type ClusterHandler interface
  - type NodeGroupHandler interface

**Comment by powerkimhub** [comment]
Reported by @iworkist 

[NHN 특징]
- Cluster 생성시 default NodeGroup 반드시 생성, 이후 NodeGroup 추가/삭제 가능
  - default NodeGroup 최소 node: 1

**Comment by powerkimhub** [comment]
@MZC-CSC @iworkist (@inno-cloudbarista @innodreamer )

- PMKS Driver API가 개선되었습니다. - [v0.6.7](https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.7)
- 먼저, 다음 링크 및 링크 내 하단의 이력 사항 확인 부탁 드립니다. 
  - https://github.com/cloud-barista/cb-spider/wiki/Provider-Managed-Kubernetes-and-Driver-API

<br>

- 위쪽에서 이슈 되었었던 사항에 대해서 정리한 다음 내용도 확인/검토 부탁 드립니다. 
  - Addon 관련
    - 필수 Addon: Driver 단에서 default로 설정
    - 추가 Addon: 3rd party 도구 등을 활용하여 사용자에 의해 관리

  - AWS: Subnet 설정이 Cluster 뿐 아니라 NodeGroup도 필요
    - 일단, Cluster.NetworkInfo 설정과 동일 서브넷으로 설정
      - NodeGroup 추가시에는 대상 Cluster 정보 획득하여 설정
    - NodeGroup에 다른 Subnet 설정이 꼭 필요시 추후 재논의

  - AWS: Role 관련
    - cluster Role과 NodeGroup Role을 별도로 사전에 정의(위 가이드 링크 참고)

  - AWS-EKS: Node 목록 제공 방법 후보로 다음 flow를 검토 부탁 드립니다. (해보진 않았습니다^^)
    - DescribeNodegroup() => DescribeNodegroupOutput => Nodegroup => NodegroupResources => AutoScalingGroups => AutoScalingGroup Name을 얻은 후 
    - DescribeAutoScalingGroups() => DescribeAutoScalingGroupsOutput => Group => Instances 목록 획득
      - 관련 API 참고: https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.DescribeAutoScalingGroups

**Comment by iworkist** [comment]
먼저, 다음 링크 및 링크 내 하단의 이력 사항 확인 부탁 드립니다.
링크(https://github.com/cloud-barista/cb-spider/wiki/Provider-Managed-Kubernetes-and-Driver-API) 문서에서 변경이력을 보니
"NodeGroup Size 관리를 Autoscaling 방법으로만 제공"으로 변경되었고,

인터페이스(https://github.com/cloud-barista/cb-spider/blob/master/cloud-control-manager/cloud-driver/interfaces/resources/ClusterHandler.go)
에는 NodeGroupList.NodeGroupInfo.AutoScaling 필드가 삭제된것을 확인했습니다.


노드그룹의 Autoscaling 옵션은 디폴트로 활성화(true) 시켜서 처리하면 되는지요?

**Comment by powerkimhub** [comment]
@iworkist ( @MZC-CSC @inno-cloudbarista @innodreamer )

**[Auto-Scaling On/Off 관련]**

- 사용자가 AutoScaling을 멈추고 싶을 때가 있다는 것을 깜밖 했네요. 
- 아래와 같은 인자와 API를 추가했습니다. 
  
  ```
          OnAutoScaling   bool // default: true
          .... 중략 ......
          SetNodeGroupAutoScaling(clusterIID IID, nodeGroupIID IID, on bool) (bool, error)
  ```
- Auto-Scaling 기능 관련 지원 이슈가 있는 CSP의 경우 현 issue에 남겨 주시면, 
  - 추후 조정해보도록 하겠습니다.

**Comment by iworkist** [comment]
CreateCluster(clusterReqInfo ClusterInfo, nodeReqInfo NodeGroupInfo) (ClusterInfo, error)
함수에 NodeGroupInfo 파라미터가 추가된 이유가 있는가요?

ClusterReqInfo에 NodeGroupList []NodeGroupInfo 가 있어서 질문드립니다.

**Comment by powerkimhub** [comment]
@iworkist 

- 캄사합니다. 
- 실수입니다. 
- 원복했습니다.

**Comment by iworkist** [comment]
/interfaces/CloudDriver.go 에 필드 추가 필요합니다.

필드: ClusterHandler bool

type DriverCapabilityInfo struct {
	NLBHandler   bool // support: true, do not support: false
	ImageHandler bool // support: true, do not support: false
	VPCHandler   bool // support: true, do not support: false
	//VNetworkHandler bool // support: true, do not support: false
	SecurityHandler bool // support: true, do not support: false
	KeyPairHandler  bool // support: true, do not support: false
	VNicHandler     bool // support: true, do not support: false
	PublicIPHandler bool // support: true, do not support: false
	VMHandler       bool // support: true, do not support: false
	VMSpecHandler   bool // support: true, do not support: false
	DiskHandler	bool // support: true, do not support: false

	**👉ClusterHandler bool // support: true, do not support: false**
	
	FIXED_SUBNET_CIDR bool // support: true, do not support: false
	VPC_CIDR          bool // support: true, do not support: false
	SINGLE_VPC        bool // support: true, do not support: false
}

**Comment by powerkimhub** [comment]
@iworkist 

- 캄사합니다.
- ClusterHandler capability field 추가 하였습니다. (https://github.com/cloud-barista/cb-spider/commit/64ee2b95b64073edbede1265a399331bdc268af2)

**Comment by innodreamer** [comment]
@powerkimhub

**Comment by powerkimhub** [comment]
@innodreamer 

- 캄사합니다. 
- 반영되었습니다. (https://github.com/cloud-barista/cb-spider/commit/67573d4381dcbab517e5bcc3a3167935d48c0342)

**Comment by powerkimhub** [comment]
**[Driver 개발 현황]**

- Alibaba: https://github.com/cloud-barista/cb-spider/pull/760
- Tencent: https://github.com/cloud-barista/cb-spider/pull/760

**Comment by MZC-CSC** [comment]
Transaction 처리관련 문의입니다.

AWS의 경우 
Cluster 생성 -> NodeGroup 추가가 나뉘어 있습니다.
NodeGroup도 여러개를 한번에 추가하지는 못하고 한개씩 추가합니다.

PMKS는 1개의 클러스터에 복수개의 Nodegroup이 추가 가능한 형태인 것같은데
일부 실패가 되면 어떻게 처리하면 될까요?

case1. cluster 생성실패 : failed
case2. cluster 생성성공 -> NodeGroup 추가 실패 : 
case3. cluster 생성성공 -> 복수개의 NodeGroup 추가중 1개 실패 :

case 2,3의 경우 실패하더라도 생성된 것들(클러스터, 추가된 NodeGroup)은 정상적으로 조회도 가능하고 동작도 가능합니다.
생성된 것들을 모두 삭제처리 해야할까요?

**Comment by powerkimhub** [comment]
@MZC-CSC  ( @inno-cloudbarista @innodreamer )

- 내부 단계들이 시간이 많이 걸려서 생성된 자원들이어서 아깝긴한데,
- 중간 생성된 자원들을 clear 후 error 처리하는 것이 좋을 듯합니다. 
  - 좀 친절하게 하자면, 
  - 생성했던 자원을 clear하는 대도 시간이 많이 소요 되니, 
    - 에러 발생 등의 의미 있는 시점에 logger 출력으로 최종 반환 전에도 단계별 현황을 알리고, 
  - 최종 에러 메시지에 성공 단계와 어떤 단계에서 fail인지 등의 정보를 포함 시켜 주신다면 
  - 사용자가 대응하기에 좋을 듯 합니다.

- 사유/사족
  - 사용자의 경우 다음 단계로 활용 할 거 같습니다.
    ```
        1. Create Cluster(with NodeGroupList)
        2. Deploy Apps
    ```
  - 2단계 진입 전에 1단계 결과를 확인 후 진입해야 하는데
    - 1단계 내부에서 Cluster만 또는 일부 NodeGroup만 생성 되는  것을 허용 한다면,
      - 생성 성공한 자원들이 무엇인 지를 확인해야만 2단계 App 배포를 할지 말지 판단이 가능하리라 생각됩니다.
      - 예를 들면, CPU NodeGroup과 GPU NodeGroup을 포함하는 Cluster 생성을 요청 했다고 하면, 
      - 부분 성공한 결과에 따라서, GPU PoD를 배포할지 말지를 결정해야 하는 등의 분별력 있는 추가 코드가 필요할 거 같습니다. 
      - 이때, 이 사용자 코드에 결함이 있거나 잘못 꼬이기 시작하면 상황이 점점 악화 될 거 같습니다.
  - 또한, 많이 안정화된 CSP 상에서는 부분 fail case가 나오는 경우는 근본적인 코드 결함이거나 자원 부족 상황이 주일 것같습니다.
    - 이 경우 대부분의 해결 책은 부분 성공한 Cluster를 계속 사용하기 보다는
    - 코드 수정이나 자원이 가능한 Regon/Zone으로 옮겨 가는 등을 수행 후 
    - 다시 Cluster  생성을 시도 할 거 같습니다.

**Comment by inno-cloudbarista** [comment]
AKS Cluster 생성시 입력 정보 및 SSH 제공에 관해 질문이 있습니다.
1. NetworkInfo
ClusterInfo를 생성시 받게 되는데, 이중 Network에 대한 정보도 같이 입력이 되는건가요?
AKS는 클러스터 생성시, resourceGroup을 새로 생성해, 클러스터의 서브리소스들을 관리합니다.
ex: CB-Group 하위에 클러스터 생성시 => 클러스터 리소스는 CB-Group 하위에 존재, 클러스터 서브 리소스들은 클러스터에 의해 만들어진 리소스그룹(이름 지정가능) 내에 존재,
VPC, subnet등도 새로 생성되게 되는데, 이미 존재하는 vpc를 이용하지는 못합니다.

2. NodeGroupInfo
NodeGroup내 각 KeyPair의 IID가 존재하는데, AKS는 생성시 클러스터 단위에서만 SSH키를 지정해줄수 있습니다.
NodeGroup이 2개 이상이고 KeyPair의 IID값이 서로 다를 경우, 어떻게 처리해야할까요...

3. NodeGroup의 SSH
NodeGroup의 SSH는 지정해줄수 있으나, 클러스터에 의해 만들어진 서브넷의 SecurityGroup은 22번 포트가 열려있지 않은 상태로 생성됩니다.
클러스터 생성후, SSH를 열어주는 로직을 추가하려고 합니다. 혹시 이 로직을 추가해도 될지요?(보안쪽이라, cb-spider에서 변경해도 될지 질문드립니다.)

**Comment by powerkimhub** [comment]
**1. NetworkInfo**
  - 넵, 함께 입력됩니다. 
  - NodeGroupInfo도 최소 1개 입력됩니다.
  - Cluster 생성시 내부에서 생성되는 Sub Resource Group은 Cluster 삭제시 함께 삭제되므로 큰 이슈는 없을 것 같습니다.
  - VPC/Subnet 설정은 웹콘솔로는 아래 참고 예시와 같이 가능하였습니다. API로 가능한지는 확인이 필요합니다. 
    - 이렇게 생성하면, 내부에서 생성된 Resource Group에는 VP나 Subnet이 별도로 생성되지도 않았습니다. 

**2. NodeGroupInfo**
  - 처음 Cluster 생성시 입력된 첫번째 NodeGroupInfo.KeyPair를 이용하여 Azure의 Cluster.KeyPair로 설정
  - NodeGroup이 2개 이상일 경우 Cluster에 설정된 ID와 동일하지 않을 경우 에러(모든 노드그룹은 동일한 KeyPair...) 반환
    - 이후 추가되는 NodeGroup도 동일하게 체리
  - Cluster/NodeGroup 정보 제공시에는Azure의  Cluster.KeyPair 정보를 활용 하여 NodeGroupInfo에 동일 Keypair로 설정 및 제공

**3. Security Group 설정 및 22 Port 관련**
  -  내부 자동 생성된 Resource Group에 생성된 SG Rule의 설정을 
  - 사용자가 입력한 SG의 Rule과 동일하게 다음 그림과 같이 추가/삭제하여 맞춤

<br>

- ![image](https://user-images.githubusercontent.com/46367962/196341401-f2a88a42-1938-475d-ae36-eaddecd9dfc0.png)

<br>

  - 즉, 처음 Cluster 생성 시에만 Cluster의 SG 기본 규칙을 사용자가 입력한 SG의 규칙에 맞추고, 
  - 생성된 이후에는 SG Rule을 개별 운영
    - 다른 CSP와 달라서, 사용자가 혼란스러울 수 있는 부분이 있긴 하지만, 
    - 현재는 이 방법이  최선인 것 같습니다. (@todo 가이드에 반영)
    
---

**[참고: 웹콘솔 기반 Cluster 생성 예시]**
- 현재 Spider는 단일 Zone만 설정(Connection Config 등록시)이 가능하므로, 다음처럼 단일 Zone으로 설정

<br>

- ![image](https://user-images.githubusercontent.com/46367962/196325501-2ab52c44-28e1-4ebd-b2cb-c6affbea6cd4.png)

<br>

- 기존 VPC/Subnet 활용한 설정을 위해서 다음처럼 `Azure CNI` 설정 (이때 red box 부분 CIDR 관련 자동화 처리 필요)
- ![image](https://user-images.githubusercontent.com/46367962/196325698-3e52265e-3938-48a5-9319-e4f19b07b60d.png)

**Comment by inno-cloudbarista** [comment]
@powerkimhub
위 내용대로 진행하고, 추가적인 이슈 있을시 공유드리겠습니다!

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 캄사합니다.

**Comment by powerkimhub** [comment]
@iworkist  @inno-cloudbarista @MZC-CSC @innodreamer 

**[요약]**
- PMKS Driver API 변경 검토 요청 드립니다. 
  - (1) Sync vs ASync Call => ASync Call로 변경
  - (2) Cluster 생성시 NodeGroup 1개 이상 반드시 함께 생성 => Cluster 생성과 NodeGroup 추가를 분리

**[개요]**
- @MZC-CSC 께서, Cluster 생성과 NodeGroup 추가 분리에 대한 검토 의견을 주셨었습니다.
- 현재 Tencent, Alibaba PMKS Driver에 대한 서버 통합 및 시험 중에 있습니다. 
  - Cluster와 NodeGroup 분리가 더 효율적이고, 비용이 절감 되는 걸로 생각됩니다.
  - PMKS 경우, 기본적으로 더비싸고 더오래 걸리는 Call들로 구성되어 있어서, 
    - 오류 발생시 비용 손실이 Sync Call에 비해 ASync Call이 더 적합한걸로 생각됩니다. 
- 현재 해당 부분 완료된 Driver도 있어 안타깝지만, 감수하고 수정 하는 것이 좋을 것 같습니다. 
  - 이점 양해 부탁드립니다.

**[계획]**
- (1) Create/Add 등 CSP가 Async Call로 제공하는 API는 Spider에서도 Async Call로 제공
- (2) CreateCluster와 NodeGroup 추가를 분리
  - NHN: Cluster 생성시 반드시 default NodeGroup이 포함됨, 이는 예외 상황을 PMKS 가이드로 제공 예정
- Usage: 최종적으로 사용자는 PMKS Cluster 생성시 다음처럼 상태 확인 후 사용
  - User: CreateCluster() => User: Check `Active` Status => User: AddNodeGroup()

**[검토]**
- 변경안을 확인해주신 분들께서는 검토 의견을 바로 답글로 부탁 드리겠습니다. 
- 서버 통합 작업 중이어서 빠른 결정이 필요한 상태인 점 감안해주시기 바랍니다.

**Comment by iworkist** [comment]
네. 변경안으로 진행하겠습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub
- ASync Call로 변경 사항 이해하였습니다.
- Cluster 생성과 NodeGroup 추가를 분리에 관해서는 Azure는 CB-Spider에 속하는 NodeGroup이 1개는 존재해야합니다..

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

> * Cluster 생성과 NodeGroup 추가를 분리에 관해서는 Azure는 CB-Spider에 속하는 NodeGroup이 1개는 존재해야합니다..

- (1) Cluster 생성 요청 전에 NodeGroup이 생성이 되어 있어야 하는 것인지요?
- (2) 아니면, Cluster 생성 시에 반드시 1개 이상의 NodeGroup 생성도 필요한 것인지요?
- 음.. (1), (2)번이 같은 얘기 같기도 하고, 좀만 더 설명 부탁드립니다^^

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
(2)번이 맞습니다. Cluster에 1개 이상의 agentPool(NodeGroup을 구성하는 정보)를 넣어주어야 cluster를 생성할 수 있습니다.
[Azure의 측면]
Cluster 생성시, agentPool을 지정을 해주면 agentPool을 바탕으로 Virtual machine scale set이라는 리소스로 vm을 생성하게 됩니다.
agentPool - Virtual machine scale set - [vm1,vm2...]
이때, agentPool의 정보를 1개는 넘겨주어야 생성이 됩니다.
아래 콘솔에서 표시되는 부분이 agentPool입니다. (첫번째의 agentPool는 삭제 불가능 합니다. api에서도 빈값으로 불가합니다)
![image](https://user-images.githubusercontent.com/69338107/197497339-973bf5c1-7cc5-4760-b9c8-957278c11527.png)


[cb-spider의 측면]
이렇게 생성된 vm들을 cb-spider에서 인식하는 NodeGroup이라는것으로 정보를 넘겨주는 방식으로 구현중에 있습니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 넵, 상세 설명 캄사드립니다. 
- NHN 스타일이네요.  
- Azure도 설명해주신 바와 같이 
- 일단, 최소 1개의 NodeGroup을 받아 들이는 형태로 추진해주셔야 할 것  같습니다.

**Comment by powerkimhub** [comment]
- **Worker Node 선택 가능 이미지 목록**
  - Tencent: 다음 링크에서 OS Name
  - https://www.tencentcloud.com/document/product/457/46750

**Comment by inno-cloudbarista** [comment]
@powerkimhub
1. Async 관련해서, CreateCluster, DeleteCluster, AddNodeGroup, SetNodeGroupAutoScaling, ChangeNodeGroupScaling, UpgradeCluster이 대상이 되는 것인가요?
DeleteCluster => Deleting중이지만, true로 리턴 가능
SetNodeGroupAutoScaling => Scaling중이지만, true로 리턴가능
RemoveNodeGroup => Deleting중이지만, true로 리턴 가능
UpgradeCluster => Upgrade 중이지만, 리턴 가능(version이 적용되지 않은 Old 정보)

AddNodeGroup => 생성후, 어느정도의 정보를 리턴해야할지 궁금합니다. NodeGroup의 정보로 agentPool이라는 리소스를 생성합니다. 
해당 agentPool은 VMScaleSet을 생성합니다. VMScaleSet은 VM을 생성합니다. 작업이 완료되기전까진 NodeGroup의 Nodes 정보를 보여줄수 없을것같습니다.
CreateCluster => 생성후, 여러 리소스가 생성되는데 NodeGroup의 VM Running을 기다리지 않고, 리턴하면될까요? 클러스터에 의해 생성되는 SecurityGroup에 입력받은 SecurityGroup Rule을 적용하는 부분이 있기에, SecurityGroup 생성은 기다려야하는 상황입니다. 

Async 관련해서 여러부분에서 수정이 필요할것 같습니다. 
오늘 Cluster에 대한 Handler를 먼저 merge 후에, 차주 초에 Async관련 부분을 보강하려고 합니다.(급한것이 아니면 함께 merge하겠습니다.)

**Comment by powerkimhub** [comment]
@inno-cloudbarista @MZC-CSC @iworkist @innodreamer 

- @inno-cloudbarista 좋은 질문 감사드립니다.
- 공통 내용이라 공유 드립니다. 

**[Async Call 처리 참고]**

- (1) 기본은 CSP가 Return하는 시기에 Return
- (2) Driver내에서 부득이 추가 작업 필요한 경우(SG적용 등) 최소한 Waiting 시킴
- (3) 반환 직전에 CSP 호출 명령이 성공하면 true, 
- (4) SG와 같은 추가 작업이 포함된 경우, 
  - 실패시 기존 Sync Call 처럼 모든 자원 clear, 
  - 이때도 가능한 오래 걸리는 Cluster 삭제는 비동기로 호출하고 반환(상태는 Deleting으로 자동 변경)
- (4) Update 등과 같은 경우에도 다음 상태 정보만 맞춰서 반환해주시면 되겠습니다. 
  - User는 updating 중에 받은 버전 정보는 무효 함을 인지할 수 있습니다.

    ```
    const (
            ClusterCreating ClusterStatus = "Creating"
            ClusterActive   ClusterStatus = "Active"
            ClusterInactive ClusterStatus = "Inactive"
            ClusterUpdating ClusterStatus = "Updating"
            ClusterDeleting ClusterStatus = "Deleting"
    )
    
    type NodeGroupStatus string
    
    const (
            NodeGroupCreating NodeGroupStatus = "Creating"
            NodeGroupActive   NodeGroupStatus = "Active"
            NodeGroupInactive NodeGroupStatus = "Inactive"
            NodeGroupUpdating NodeGroupStatus = "Updating"
            NodeGroupDeleting NodeGroupStatus = "Deleting"
    )
    ```

**Comment by powerkimhub** [comment]
@iworkist @inno-cloudbarista @MZC-CSC @iworkist @innodreamer

**[개발 현황 및 이슈 공유]**

- 다음 링크에 공유 부탁 드립니다. 
- https://docs.google.com/spreadsheets/d/1mPmfnfmyszYimVzplZMzsqO3WsBmOdes/edit#gid=1299745060

**Comment by powerkimhub** [comment]
@iworkist @inno-cloudbarista @MZC-CSC @innodreamer

**[API 변경 관련: ClusterInfo.AccessInfo 추가]**
- 변경된 API는 다음과 같습니다. 
- **Driver 개발 및 WebTool 통합 개발**에 참고해주세요

<p align="center">
<img width=550 src="https://user-images.githubusercontent.com/46367962/199372380-27fb3995-810a-4c61-860f-8d9fa505853f.png">
<br>
<br>
<b>[CB-Spider PMKS API 변경]</b>
</p>


- 반영된 규격(v0.5)은 다음과 같습니다. 
  - https://github.com/cloud-barista/cb-spider/wiki/Provider-Managed-Kubernetes-and-Driver-API
