### ISSUE TITLE
[+Disk] Cloud Driver API Definition for Disk(Volume)

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#717]
- [x] Disk(Volume) features and Interfaces Analysis of CSPs
- [x] Cloud Driver Disk API Definition
- [x] Cloud Driver Disk API Review

**Comment by powerkimhub** [comment]
- ref) https://github.com/cloud-barista/cb-spider/wiki/Disk-and-Driver-API

**Comment by dongjae** [comment]
짧은시간에 체계적인 분석, 정리...Great Job!^^

**Comment by MZC-CSC** [comment]
[AWS의 경우]
Disk 상태 : **creating**, available, in-use, **deleting**, deleted, error
Attached 상태 : attaching, **attached**, detaching, detached, busy

Disk 의 상태값에서 두가지 상태가 존재하는데 현재 인터페이스에는 두가지가 4단계로만 정의되어 있어 
다른 상태값 표현을 어떻게 매핑 해야할 지 궁금합니다.

현재 Interface : DiskCreating, DiskAvailable, DiskAttached, DiskDeleting


또한 attached 상태는 배열형태로 instance별로 attache 상태를 가지고 있습니다.
그래서 attached 상태를 적절히 표현할 수 있을지
아니면 1개의 Disk = 1개의 Instance로 하면 될까요?

ex)
 {
      Attachments: [{
          AttachTime: 2020-12-10 02:21:36 +0000 UTC,
          DeleteOnTermination: true,
          Device: "/dev/sda1",
          InstanceId: "i-022cd91d75e9752f3",
          **State: "attached",  -->instance 별 attache 상태**
          VolumeId: "vol-088d6f97c083fb426"
        }],
      AvailabilityZone: "ap-northeast-2a",
      CreateTime: 2020-12-10 02:21:36.404 +0000 UTC,
      Encrypted: false,
      Iops: 100,
      MultiAttachEnabled: false,
      Size: 8,
      SnapshotId: "snap-0957d19a4d727ee25",
      **State: "in-use", -- Disk의 상태**
      VolumeId: "vol-088d6f97c083fb426",
      VolumeType: "gp2"
    }

**Comment by powerkimhub** [comment]
@MZC-CSC 

- 검토 및 의견 공유 감사드립니다.
- #### Disk Status 관련
  - `DiskError` 상태를 추가하였습니다.
  - AWS의 다른 상태는 다음처럼 맵핑하면 이슈가 없을지 검토 부탁 드립니다.

  |   -    | Disk 생성 중          | Disk 부착 가능 | Disk 부착 중(VM 소유) | Disk 삭제 중 | Disk 오류 | 기타 |
  |:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
  | Spider Disk Status | DiskCreating | DiskAvailable | DiskAttached | DiskDeleting | DiskError |
  | AWS Disk Status| creating| available| in-use | deleting |  error | * deleted: Spider 목록에는 Disk가 존재하지 않는 상태로 걸러 주시면 되겠습니다. |
  | AWS Disk Attached Status| N/A | detached | attaching / attached / detaching / busy | N/A |  |

<br>

- #### Multi Attach 관련
  - AWS의 경우 1개의 Disk를 여러 VM에서 공유 할 수 있는 옵션이 있지만,
  - 공유가 불가능한 CSP들이 존재합니다. 
  -  현재의 Spider는 공통 기능 제공을 위해서,
    - 1 Disk는 1VM에서만 소유 가능하도록 설계되었습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub

DiskHandler의 DiskStatus에 대해 질문사항이 있습니다.

현재, DiskStatus에는 DiskCreating, DiskAvailable, DiskAttached, DiskDeleting, DiskError 위와 같은 값이 있는데,

생성이 완료되고, Attach가 가능한 상태는 DiskAvailable이고, Attach가 된 상태는 DiskAttached으로 값을 리턴하려고 합니다.

DiskAvailable => DiskAttached로 넘어가는 중간 상황(Updating 과정)은 아직 Attach DiskAvailable로 리턴해야할까요?

Attach가 진행중인 과정이라, Attach가 되진 않기에, 새로운 상태값(Updating, 변경 등의 작업이 불가능한 상태)이 필요합니다.

아니면, 혹시 위 상황에서는 어떤 값을 리턴하는것이 좋을까요?

**Comment by MZC-CSC** [comment]
[AWS]
AttachDisk 에서 
AWS 는 
- DiskId, InstanceId, Device 값이 필수입니다.

device는 운영체제에 따라 사용되는 이름이 다르며 권장되는 이름은 다음과 같습니다.
- Linux용 권장 디바이스 이름: 루트 볼륨의 경우 /dev/sda1, 데이터 볼륨의 경우 /dev/sd[f-p].
- Windows용 권장 디바이스 이름: 루트 볼륨의 경우 /dev/sda1, 데이터 볼륨의 경우 xvd[f-p].

또한 device는 attach하는 인스턴스 내에서 중복이 되지 않습니다.
xvdf 라는 디바이스 이름이 존재하고 attachDisk에서 xvdf라는 이름을 주게되면
"Invalid value 'xvdf' for unixDevice. Attachment point xvdf is already in use"

- 현재 AttachDisk 정의 된 내용에는 Device가 정의되어 있지 않은데
추가가 될 것인지, 아니면 특정값을 지정하면 될지 결정이 필요합니다.
검토바랍니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 현재 disk의 status는 모든 CSP들이 제공할 수 있도록 단순함과, 
  - disk를 사용하려는 사용자 입장에서  `내가 사용 가능한가?`에 중심을 두었습니다. 
    - DiskAvailable: 아무도 안쓰고 있음, 내가 사용할 수 있음.
    - DiskAttached: Attaching(Updating), Attached 등을 포함하여 누군가(사용자 or CSP OS) 점유(사용)하고 있음, 
- 현재는 사용하기 위해서 Attaching(Updating) 중인 사용자의 경우에는 
  - Attach가 완료되었는지 Attaching 중인 지를 알 수는 없습니다. 
  - 이 경우에 Attaching 중일 경우에 Disk에 접근하면 error 메시지를 반환 할 것이며, 
    -  이를 통해서 대응이 될 걸로 생각했습니다. 
- 국내 CSP 등 연동 대상의 모든 CSP가 Disk Status가 세분화 되어 있다면, 
  - 추후에 반영 작업을 진행하도록 하겠습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub
넵 알겠습니다! 사용가능 중심으로 상태 출력하겠습니다.

**Comment by powerkimhub** [comment]
@MZC-CSC ( @choryang @dev4unet  @inno-cloudbarista @innodreamer  )

### [Attach와 DeviceName 관련]

- 관련된 추가 시험을 진행하였습니다. 
  - 먼저 다음 링크의 시험 항목 및 결과를 확인 부탁 드립니다. 
  - [AWS: VM에 2개의 Disk(Volume) Attach 시험 및 중복 Device Name 시험](https://docs.google.com/document/d/1KIXv71LDkzsHbWHLXizw22EzWREUFcRp/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

- AWS의 Device Name의 경우 Driver 내부에서 설정해주실 것을 검토 부탁 드립니다. 
  - (사유1) device name 설정이 없는 CSP들이 존재합니다. (Azure 등)
  - (사유2) 위의 시험 결과처럼 사용자가 설정한 Device Name과 
    - 실제 OS 내부의 Device Name의 차이가 있고,
    - Device Name 중복 확인 및 처리에 어려움이 있어 보입니다.

### [참고 사항]
- 현재 Cloud-barista가 제공하는 GuestOS Target은 Ubuntu 18.04로 한정되어 있습니다.
  - 초기에 빠른 개발을 위해서 협의된 제약 조건 중 하나입니다. 
  - 일단, 현재는 Linux만을 가정하시고 AWS가 Device Name 중복 오류를 반환하면, 
  - 다음처럼 Driver 내부 규칙 및 중복 오류 반환시 순차 요청 처리 등이 필요할 거 같습니다. 
    - Attach 요청전 VM의 data-disk 수 확인
      - 0: /dev/sdf
      - 1: /dev/sdg
      - ...
    - 혹시, 중복 오류 반환시 다음 순으로 시도
      - /dev/sdf => /dev/sdg => /dev/sdh ~ /dev/sdp

- 추후 Windows 지원을 위해서는 
  - DeviceName 뿐만아니라 여러 가지 확장 작업이 동시에 필요합니다. 
  - 현재는 당초 계획처럼 Ubuntu 기반으로 빠르게 추진하고, 
  - 추후 필요 시점에 전체적인 반영 작업으로 추진하는 게 좋을 것 같습니다.

**Comment by powerkimhub** [comment]
@MZC-CSC @choryang @dev4unet @inno-cloudbarista @innodreamer 

**[Build Error 예방 관련]**
- AWS Disk 기능이 추가되었습니다. 
- 이로 인하여, Disk 관리 기능 구현 전인 드라이버의 경우  build 오류가 발생합니다. (아래 오류 예시 참고)
- 아직 구현 전인 Driver의  Connection 관련하여 아래와 같이 임시 코드를 일괄 추가하였습니다. 
- Disk Driver 개발 시에 정상 코드로 수정해주시기 바랍니다. 

**[오류 예시]**

  ```
  # github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/mock
  cloud-control-manager/cloud-driver/drivers/mock/MockDriver.go:70:9: cannot use &iConn (value of type *"github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/mock/connect".MockConnection) as type "github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/interfaces/connect".CloudConnection in return statement:
          *"github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/mock/connect".MockConnection does not implement "github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/interfaces/connect".CloudConnection (missing CreateDiskHandler method)
  ```

**[임시 코드 예시]**

- $vi ./connect/MockCloudConnection.go

  ```
  func (cloudConn *MockConnection) CreateDiskHandler() (irs.DiskHandler, error) {
          return nil, errors.New("Mock Driver: not implemented")
  }  
  ```

**Comment by innodreamer** [comment]
@powerkimhub 
국내 Cloud driver에서 build error 방지를 위해 DiskHandler Connection 코드를 추가했습니다.

**Comment by MZC-CSC** [comment]
@powerkimhub 
질문있습니다.
vm 생성시 VMReqInfo 에 DataDiskIIDs 만 있다는 것은
기존에 있는 disk를 바로 붙인다는 의미인가요?

AWS에서 instance 생성 시 volume추가를 보면
스냅샷 정보를 set할 수 있는데 이것으로 보면 될까요?
dataDiskIID == snapshotID

루트디스크 설정처럼 
사용자가 volume 유형, 크기로 추가하는 방식은 아닌거죠?

**Comment by powerkimhub** [comment]
@MZC-CSC 

> vm 생성시 VMReqInfo 에 DataDiskIIDs 만 있다는 것은
> 기존에 있는 disk를 바로 붙인다는 의미인가요?

- 넵, AWS의 Volume으로 만들어진 Volume을 Attach하는 것으로 디자인하였습니다. 
- Spider 규격으로 보자면, 
  - 사용자는 DiskHandler를 통해서 Data-Disk를 생성 하고,
  - VM 생성시 또는 생성 후에 Attach하여 사용할 수 있습니다. 
  - Disk 유형 및 Size는 DiskHandler에서 설정이 될 수 있겟습니다.
- 현재의 Spider에서는 Disk(volume) Snapshot은 제공하지 않으며,
  - VM Snaphot만 제공하고 있습니다. 
  - 참고로, VM Snapshot은 AWS로 보자면, 
    - Console: `VM Instance` => `Image and templates` => `Create Image` 로 생성되는 `AMIs`(MyImage) 이며, 
  - Spider의 이에 대한 규격은 다음 링크의 MyImage에 해당됩니다. 
    - https://github.com/cloud-barista/cb-spider/wiki/MyImage-and-Driver-API

**Comment by choryang** [comment]
GCP 특이사항입니다.
GCP의 경우 Disk에서는 Attach할 Instance를 선택할 수 없고, Instance에서 Attach할 Disk를 선택하도록 구성되어 있습니다. 

DiskHandler.Client.**Disks**.Insert(projectID, zone, disk).Do()
DiskHandler.Client.**Disks**.Get(projectID, zone, diskIID.SystemId).Do()

DiskHandler.Client.**Instances**.AttachDisk(projectID, zone, instance, attachedDisk).Do()

참고로, AWS의 경우 AttachDisk를 할 때 Disk(Volume)에서 Instance를 선택할 수 있도록 되어 있습니다.

**Comment by powerkimhub** [comment]
@choryang 

- 현재 Spide disk Attach API로 입력되는 인자를 활용하여
- driver API 내부에서 GCP instance API를 이용할 수 있는지 확인 부탁드립니다.

**Comment by choryang** [comment]
@powerkimhub 
네, 이용 가능합니다. AWS와 관점이 달라 알려드렸습니다.

**Comment by powerkimhub** [comment]
@choryang 

- 넵, 현황 공유 감사드립니다.

**Comment by powerkimhub** [comment]
**[Driver 개발 현황]**

- AWS: https://github.com/cloud-barista/cb-spider/pull/721
  - https://github.com/cloud-barista/cb-spider/pull/723
- Azure: https://github.com/cloud-barista/cb-spider/pull/722
- GCP: https://github.com/cloud-barista/cb-spider/pull/724

**Comment by MZC-CSC** [comment]
callogger.go 에 RES_TYPE 으로 DISK 추가 필요합니다.
MyImage는 기존에 있는 VMIMAGE로 쓰면 될까요?

**Comment by powerkimhub** [comment]
- `DISK`, `MYIMAGE` 추가했습니다.

**Comment by MZC-CSC** [comment]
참고 : Alibaba 의 경우 
Disk Type : cloud / cloud_efficiency / cloud_ssd / cloud_essd 네 가지가 있고
Type별 Size 는
cloud : 5 ~ 100 GB
cloud_efficiency : 20 ~ 32768 GB
cloud_ssd : 20 ~ 32768 GB
이고 특이점이 
cloud_essd 인 경우 PerformanceLevel(PL0, PL1, PL2, PL3) 에 따른 min/max 가 다시 구분됩니다.
cloud_essd PL0 : 40 ~ 32768 IOPS
cloud_essd PL1 : 20 ~ 32768 IOPS
cloud_essd PL2 : 461 ~ 32768 IOPS
cloud_essd PL3 : 1261 ~ 32768 IOPS

현재 spider에는 PerformanceLevel 관리하지 않기 때문에
default PL2 를 기준으로 설정하도록 하겠습니다.

https://api.aliyun.com/#/?product=Ecs&version=2014-05-26&api=CreateDisk&params={}&tab=DOC&lang=JAVA

**Comment by powerkimhub** [comment]
@MZC-CSC 

**[AWS Driver]**

- DiskType관련 오류를 반환하고 있습니다. 
- `gp2`으로 시험 해도 동일합니다. 
- 다음 요청이 맞는 지 확인 부탁드립니다. 
  ```
  curl -sX POST http://X.X.X.X:1024/spider/disk -H 'Content-Type: application/json' -d '{ "ConnectionName" : "aws-ohio-config", "ReqInfo" : { "Name" : "spider-disk-01", "DiskType" : "standard", "DiskSize" : "12"}}'
  ```
  ```
  [9:40:51 PM]    ==> {"message":"Disktype : standard' is not valid"}
  ```

- 참고: cloudos_meta.yaml
```
AWS:
  region: Region / Zone
  credential: ClientId / ClientSecret
  # rootdisktype: standard / io1 / io2 / gp2 / sc1 / st1 / gp3
  # issues: https://github.com/cloud-barista/cb-spider/pull/523#issuecomment-965363272
  rootdisktype: standard / gp2 / gp3
  disktype: standard|gp2|gp3|io1|io2|st1|sc1|
  disksize: standard|1|1024|GB / gp2|1|16384|GB / gp3|1|16384|GB / io1|4|16384|GB / io2|4|16384|GB / st1|125|16384|GB / sc1|125|16384|GB
  # idmaxlength: VPC / Subnet / SecurityGroup / KeyPair / VM
  idmaxlength: 255 / 256 / 255 / 255 / 255
```

**Comment by MZC-CSC** [comment]
cloudos_meta.yaml 에서
aws의 disktype 구분자를 "|" 에서 "/"로 변경하고 PR했습니다.

**Comment by MZC-CSC** [comment]
[AWS] 추가보완 사항입니다.
GetDisk 에서 KeyValueList Set부분 보완하여 PR했습니다.

Disk and Driver API 보완2 #727

**Comment by powerkimhub** [comment]
@MZC-CSC 

- (last PR 반영 버전) Attach 시 다음 오류 발생하고 있습니다. 
- 확인 부탁드립니다. 

```
[11:36:54 AM] PUT> http://3.36.93.11:1024/spider/disk/spider-disk-01/attach -H 'Content-Type: application/json' -d '{ "ConnectionName": "aws-ohio-config", "ReqInfo": { "VMName" : "vm-01" } }'
[11:36:54 AM]    ==> {"message":"There are no names available"}
```

<br>

- **참고: 동일 요청 웹콘솔 예시**
  - [설정]
  - ![image](https://user-images.githubusercontent.com/46367962/186804722-011c1a8e-d5a9-4593-9a99-0e7d48ca6492.png)

  - [결과]
  - ![image](https://user-images.githubusercontent.com/46367962/186804972-d2390814-bc2a-4d35-978b-32373676bf3f.png)

**Comment by MZC-CSC** [comment]
AttachDisk에서 가용 diskName 체크로직 보완했습니다.

PR : [AWS]Disk and Driver API 보완3 #728

**Comment by powerkimhub** [comment]
@MZC-CSC 

**[AWS]**
- gp2 / 12GB 설정으로 
- VM에 Attach/Detach까지 확인 되었습니다.
- 수고 많으셨습니다. 👍🕷

**Comment by powerkimhub** [comment]
@MZC-CSC 

**[AWS:Disk Upsize]**
- 15GB => 20GB 요청시 다음과 같습니다. 
- 확인 부탁드립니다. 
  ```
  [8:33:11 PM] PUT> http://x.x.x.x:1024/spider/disk/spider-disk-03/size -H 'Content-Type: application/json' -d '{ "ConnectionName": "aws-ohio-config", "ReqInfo": { "Size" : "20" } }'
  [8:33:11 PM]    ==> {"message":"Disktype : gp2' is not valid"}
  ```

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

**[Azure Driver]**
- Create/Delete(PremiumSSD/32GB): 성공
- Attach/Detach: 성공
- Upsize(32->40): 성공

 - Attach 후 VM 정보: DataDiskIIDs이 설정되어 있지 않습니다. 확인 부탁드립니다.

**Comment by powerkimhub** [comment]
@MZC-CSC @inno-cloudbarista @innodreamer 

- Disk 기능 시험 시, AdminWeb 활용 가능합니다. 
  - 또는 아래 Curl 참고
  - Mock Driver도 활용 가능합니다. 
- Disk 생성시 현재 Type/Size의 'default'는 잘 동작하지 않습니다. 
  - 직접 입력해주시기 바랍니다. 
  - 'default'는 "" 빈문자열로 Driver로 내려 보내집니다. 
  - 이 경우에는 RootDisk 처리 처럼 CSP의 기본 값으로 생성 부탁드립니다. 

---

- Disk REST API Examples

```
[Create]
curl -sX POST http://localhost:1024/spider/disk -H 'Content-Type: application/json' -d \
        '{
                "ConnectionName": "mock-config01",
                "ReqInfo": {
                        "Name": "spider-disk-01",
                        "DiskType": "gp2",
                        "DiskSize": "12"
                }
        }' | json_pp

[List]
curl -sX GET http://localhost:1024/spider/disk -H 'Content-Type: application/json' -d \
        '{ 
                "ConnectionName": "mock-config01"
        }' |json_pp

[Get]
curl -sX GET http://localhost:1024/spider/disk/spider-disk-01 -H 'Content-Type: application/json' -d \
        '{ 
                "ConnectionName": "mock-config01"
        }' |json_pp


[Upsize]
curl -sX PUT http://localhost:1024/spider/disk/spider-disk-01/size -H 'Content-Type: application/json' -d \
        '{
                "ConnectionName": "mock-config01",
                "ReqInfo": {
                        "Size" : "128"
                }
        }' | json_pp


[Attach]
curl -sX PUT http://localhost:1024/spider/disk/spider-disk-01/attach -H 'Content-Type: application/json' -d \
        '{
                "ConnectionName": "mock-config01",
                "ReqInfo": {
                        "VMName" : "vm-01"
                }
        }' | json_pp


[Detach]
curl -sX PUT http://localhost:1024/spider/disk/spider-disk-01/detach -H 'Content-Type: application/json' -d \
        '{
                "ConnectionName": "mock-config01",
                "ReqInfo": {
                        "VMName" : "vm-01"
                }
        }' | json_pp

[Delete]
curl -sX DELETE http://localhost:1024/spider/disk/spider-disk-01 -H 'Content-Type: application/json' -d \
        '{ 
                "ConnectionName": "mock-config01"
        }' |json_pp
```

**Comment by innodreamer** [comment]
@powerkimhub 
NHN Cloud의 경우, 'VM 생성시' VMSpec에 따라 크게 다음의 두가지 경우가 존재합니다.  
  Case 1) Local volume을 기준으로 booting되는 VM
  Case 2) Local volume이 없이 VMSpec에 지정된 type과 size의 volume으로 VM 생성 과정에서 attach되어 그 volume으로 booting되는 VM
 
위의 Case 2의 경우, VM 생성시 attache된 volume도 'ListDisk()' 실행시에 제시되는데, 현재 CB-Spider Disk info structure에는 'Bootable' volume을 표시하는 parameter가 없어서, NHN Cloud driver에서 현재는 부가정보로 Key/Value 정보 형태로 제시되도록 개발되어있습니다.

CB-Spider Disk info structure에 'IsBootable'을 표시하는 bool parameter가 추가되면 더 좋을거 같습니다.

<(참고) Case 2로 생성된 VM에 volume이 추가로 attach된 경우>
![image](https://user-images.githubusercontent.com/51111668/187872660-cfe55d01-a367-48a8-affb-1dc8455c4d1b.png)

**Comment by powerkimhub** [comment]
@innodreamer @MZC-CSC @inno-cloudbarista ( @seokho-son @jihoon-seo )

- bootable disk 옵션 관련 의견 공유 감사드립니다. 
- 고민하다가 제외 했던 속성입니다. 
- 제외 사유는 다음과 같습니다. 
  - VM과 Bootable disk 관련된 관계는 아래 그림과 같고, 세부 내용은 다음과 같습니다. 
  - ImageHandler: (1) Public Image 제공 ---------> bootable image
  - MyImageHandler: (2) My Image 관리 ---------> bootable image
    - Snapshot: bootable disk + sw + data => MyImage 생성
  - DiskHandler: (3) Data Disk 관리 ---------------> non bootable disk
  - VMHandler: VM 관리 및 VM을 위해 필요한 자원들(IP, cb-user, root disk 등) 자동 관리
    - VM 생성시 자동 생성되는 (4) Root Disk -----> bootable image
  - DiskHandler: List Disk 제공관련
    - Driver 단: Root Disk, Data Disk 구분 없이 제공
    - Server 단: Driver가 제공하는 List 중 User가 생성한 Data Disk만 NameId를 설정하여 User에게 제공
  - => 현재의 Spider는 User가 제공 받는 Disk는 항상 `non bootable disk`입니다.
  - => 몇몇 CSP들은 bootable disk 기반으로 VM을 생성할 수도 있지만, 
    - 모든 CSP들이 제공할 수 있는 flow 제공과 무엇보다 활용에 있어 쉽게 단순화 시키고자 하였습니다.
- bootable 속성은 추후 필요하게 되면, 그때 추가하도록 하겠습니다.  


<p align="center">
<img width=500 src="https://user-images.githubusercontent.com/46367962/188771870-34d05e66-97a4-4684-ad28-32254efc8d04.png">
<br>
<br>
<b>[CB-Spider Image와 Disk 종류 및 활용 개요]</b>
</p>

**Comment by innodreamer** [comment]
@powerkimhub

**Comment by powerkimhub** [comment]
- cf) https://github.com/cloud-barista/cb-spider/wiki/VM-Snapshot,-MyImage-and-Disk-Overview

**Comment by powerkimhub** [comment]
**[Driver 개발 현황]**

- AWS: https://github.com/cloud-barista/cb-spider/pull/721
  - https://github.com/cloud-barista/cb-spider/pull/723
- Azure: https://github.com/cloud-barista/cb-spider/pull/722
- GCP: https://github.com/cloud-barista/cb-spider/pull/724
  - https://github.com/cloud-barista/cb-spider/pull/735
- Alibaba: https://github.com/cloud-barista/cb-spider/pull/733
- OpenStack: https://github.com/cloud-barista/cb-spider/pull/734, https://github.com/cloud-barista/cb-spider/pull/739
  - Client 2가지 Version 포함 (Volume2Client, Volume3Client 등)
- Tencent: https://github.com/cloud-barista/cb-spider/pull/742

**Comment by powerkimhub** [comment]
@inno-cloudbarista @MZC-CSC @innodreamer 

- Disk default type 및 size에 대한 처리 문제 등 
- Disk 일부 기능에 문제가 있는 경우가 존재합니다. 
- 이에 아래와 같이 최종 검증 부탁 드립니다. 

**[Driver 통합 시험 및 현황]**
- Disk 통합 시험은 VM과 연계된 바 결과 확인 등의 편리함을 위하여 AdminWeb으로 진행하고 자합니다. 
- 시험 방법 및 시험 항목은 다음과 같습니다. 
  - 시험 방법: 다음 링크를 순서대로 참고해주시기 바랍니다. 
  - 시험 항목: 다음 링크의 [기능 활용] 단계를 참고해주시기 바랍니다.
  - [링크](https://github.com/cloud-barista/cb-spider/wiki/AdminWeb-Disk-Management-Guide)

[Disk default type & size 적용 관련]
- 다음 링크의 관련된 내용을 참고해주시기 바랍니다. 
- [링크](https://github.com/cloud-barista/cb-spider/wiki/Disk-and-Driver-API#3-%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B2%84-%EA%B0%9C%EB%B0%9C-%EB%85%B8%ED%8A%B8)

**[시험 결과 공유]** 
- 상기 `시험 항목`의 시험 결과를 다름 링크에 공유 부탁 드립니다. 
- [링크](https://docs.google.com/spreadsheets/d/1YPXnYpIP4w-BLj2w37Do485Y4k4qOBRe/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

**Comment by powerkimhub** [comment]
@jihoon-seo 

- 하... 한참 보고 차이점을 알았어요. 
- 캄사합니다. 
- Fix in https://github.com/cloud-barista/cb-spider/commit/ebd66fd216a10ef5ae07a829913f21d4e3a17857

**Comment by MZC-CSC** [comment]
@powerkimhub 

AWS, GCP, Alibaba, Tencent Disk 통합 시험 결과 기록하였습니다.
AWS, Alibaba, Tencent 에서 default Disk 생성이 되지 않는 부분은 수정하여 PR하도록 하겠습니다.

**Comment by powerkimhub** [comment]
- [통합 시험 완료](https://docs.google.com/spreadsheets/d/1YPXnYpIP4w-BLj2w37Do485Y4k4qOBRe/edit?usp=sharing&ouid=112452395505563061289&rtpof=true&sd=true)
- [대상 버전](https://github.com/cloud-barista/cb-spider/tree/3e47e57e09331de9e845dc5413e55fe699c1970f)
