### ISSUE TITLE
Ladybug needs the VM Driver NameId to create a CMKS cluster

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#718]
**[이슈 현황]**
- CB-Ladybug의 CMKS(Cloud-Barista Managed Kubernetes) 서비스는 
  - Cluster 생성을 위해서 [CCM(Cloud-Controller Manager)](https://kubernetes.io/docs/concepts/architecture/cloud-controller/)을 활용하고 있음
- 현재 OpenStack CCM Plug-in은 OpenStack이 제공하는 VM의 (ID가 아닌) Name 정보를 활용하고 있음
- 현재 Spider는 CCM이 원하는 OpenStack(CSP)의 자원 Name을 제공하고 있지 않음
  - Spider 내부에서 변형된 Name으로 활용 중, 세부 내용 아래 참고

<br> 

**[Spider IID 제공/운영 현황]**
- CB-Spider는 생성된 자원의 ID 정보를 다음과 같은 IID 형식으로 사용자에게 제공합니다. 
```
  IID={NameId, SystemId}
  ex) {vm-01, i-0bc7123b7e5cbf79d}
``` 
- NameId: 사용자가 자원 생성시 입력한 Human Readable한 ID (ex: `vm-01`)
- SystemId: CSP가 관리하는 대상 자원의 ID (ex: `i-0bc7123b7e5cbf79d`)
  - (1) 사용자가 입력한 NameId를 그대로 SystemId로 사용하는 CSP도 있고, (ex-GCP: `vm-01`)
  - (2) 별도의 자체 SystemId로 관리하는 CSP도 있음. (ex-AWS: `i-0bc7123b7e5cbf79d`)
  - (1)의 경우 NameId로 사용 가능한 문자 또는 길이 등의 제약 사항이 존재(ex: 어떤 CSP는 ID 길이 9자 등)
  - (2)의 경우에도 사용자들이 관리하는 Name과 같은 Text ID를 제공하는 데 Name도 길이의 제약 등이 CSP별로 다름
- Spider는 이와 같은 ID 길이 제약 및 이질성을 해결하기 위해서 
  - 사용자의 입력 NameId(`vm-01`)를 기반으로 내부에서 다음과 같은 공통 형식의 Spider XID 형식을 CSP의 Name으로 운영합니다.
    - ex) `vm-01-9m4e2mr0ui3e8a215n4g`
  - 이를, DriverNameId라 칭함.
- Spider 서버에서는 Driver에 IID.NameId를 내려 보낼때 이 DriverNameId를 생성하여 내려 보내고, 
- 사용자에게 제공할 때는 사용자가 생성시 입력한 NameId로 변환하여 올려 보낸다.
  - 결국, 사용자와 Spider 사이에 사용되는 IID 정보는 다음과 같고
    ```
      [IID]
        - NameId: vm-01
        - SystemId: i-0bc7123b7e5cbf79d
    ```

  - Spider 서버 <--> Driver/CSP 사이에 사용되는 IID 정보는 다음과 같음
    ```
      [IID]
        - NameId: vm-01-9m4e2mr0ui3e8a215n4g
        - SystemId: i-0bc7123b7e5cbf79d
    ```

**Comment by seokho-son** [comment]
@powerkimhub 
일단 현황 공유를 위한 이슈라고 이해하고 있습니다.

사용자 측면에서는 가급적 기존 IID 활용 형태의 변경이 아니라, 
필요시 (이슈 상황과 같은 예외 상황) 추가 정보를 제공하는 형태로 개선이 되는 것이 좋을 것 같습니다. :)

**Comment by powerkimhub** [comment]
@seokho-son @jihoon-seo ( @sykim-etri )

- Fixed in https://github.com/cloud-barista/cb-spider/commit/ba0dfb5078ec7a6b513e97efa8c0e7773edaea66
- 다음과 같은 REST API를 Spider [v0.6.6](https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.6)부터 제공 (Go API: 추후 필요시 지원)
- 관련 REST API 규격 및 Examples
  - [CB Spider User Interface](https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-User-Interface)에서
  - v0.6.6 [CCTM Spec]의 맨 끝 [Get CSP Resource Name](https://documenter.getpostman.com/view/9027676/VUqmuK1E#d474dd49-d54f-41ac-b3e9-a957ae4d2e63) 참고

- 다음과 같은 2가지 형식의 호출 방법 제공
- (1) Get-Body 형식 호출
  ```
    curl -sX GET http://localhost:1024/spider/cspresourcename/vm-01 -H 'Content-Type: application/json' -d '{
     "ConnectionName": "aws-ohio-config", "ResourceType":"vm"}' |json_pp
  ```

  ```
  {
     "Name" : "vm-01-cbu5mdaba5obh27t1qb0"
  }
  ```

- (2) Get-Query Param 형식 호출
  ```
  curl -sX GET http://localhost:1024/spider/cspresourcename/vm-01?'ConnectionName=aws-ohio-config&ResourceType=vm' |json_pp
  ```

  ```
  {
     "Name" : "vm-01-cbu5mdaba5obh27t1qb0"
  }
  ```

- API 호출시 ResourceType 참고
  ```
  "image"
  "vpc"
  "subnet"
  "sg"
  "keypair"
  "vm"
  "nlb"
  ```
