### ISSUE TITLE
Azure VM 생성 요청에 DataDisk도 명시하는 경우, VM은 생성되나 DataDisk는 attach되지 않음

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#771]
**What happened**
: Azure VM 생성 요청에 DataDisk도 명시하는 경우, VM은 생성되나 DataDisk는 attach되지 않음
(AWS, GCP에 대해서는 정상적으로 작동함)

**What you expected to happen**
: VM 생성 요청에 DataDisk도 명시하면 해당 DataDisk가 VM에 attach됨

**How to reproduce it (as minimally and precisely as possible)**
: CB-Spider latest master (4dc65d1) 실행 후
AdminWeb에서 (REST API로 해도 동일)
- VM 생성에 필요한 모든 자원 생성
- DataDisk 생성
- VM 생성 시, DataDisk 선택

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: CB-Spider latest master (4dc65d1)
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by powerkimhub** [comment]
@jihoon-seo 

- 다음 링크의 통합 시험이 진행 중에 있습니다. 
  - [makeMyImageSelect_html](https://github.com/cloud-barista/cb-spider/issues/717#issuecomment-1256009132)
- 링크 마지막 시험 결과 현황을 참고하시어 
  - 성공한 CSP 및 기능을 활용하시기 바랍니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub @jihoon-seo
해당 현상 확인 했습니다. 기능 누락 부분입니다. 타 CSP에도 확인 후 적용하도록 하겠습니다!

**Comment by powerkimhub** [comment]
@jihoon-seo 

- Fixed in https://github.com/cloud-barista/cb-spider/pull/780
