### ISSUE TITLE
[Cloudit] ClusterID boundary and RegionInfo

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#773]
@inno-cloudbarista 

```
  * Code 개발 연관되어 slack 내용을 issue로 옮겨 왔습니다.
```

**[ClusterID Issue 현황]**
- Cloudit Farm은 구축 규모에 따라 Cluster가 여러개 존재 가능
- 자원별 ClusterID 의존 관계가 존재
  - Cluster 무관: Image(Template), VMSpec, Subnet, IP, SecurityGroup, KeyPair(driver 관리), NLB
  - Cluster 의존: VM, Disk, MyImage (동일 Cluster 상에 존재해야 연동 가능)

**[개선 방안]**
- 제안 주신 방법처럼, RegionInfo를 활용
- 세부 내용은 다음과 같습니다. 

[AS-IS]
- 단일 Region `default`로 고정하여 활용 중
- ex) `{"Key":"Region", "Value":"default"}`

[TO-BE]
- Region 정보 개선
  - Region = ClusterID로 맵핑 
  - Default Cluster 지원

- (1) default cluster 지원:
  - ex) `{"Key":"Region", "Value":"default"}`
  - default cluster 지원 방법: Driver내에서 첫번째 cluster 등으로 일관된 해석

- (2) 명시적 cluster 설정: 
  - ex) `{"Key":"Region", "Value":"cluster-01"}`
  - ex) `{"Key":"Region", "Value":"cluster-02"}`

**Comment by powerkimhub** [comment]
> (1) default cluster 지원:

- Cloudit Farm이 운영 중에 Cluster가 추가 삭제 될 수 있으므로
- Driver 내부에서 default 적용에 이슈 존재
- ref) https://github.com/cloud-barista/cb-spider/pull/777

**Comment by powerkimhub** [comment]
- 관련하여, 
- 다음과 같이 Credential 정보에 `ClusterId` 정보를 추가하는 방법을 제안 드립니다. 
- 의미상 Region/Zone 보다는 사용 가능한 Cluster를 지정(할당) 측면에서 Credential이 좀더 가깝지 싶습니다.
- 확인 부탁 드립니다. 

[AS-IS]
- ./cloud-driver-libs/cloudos_meta.yaml
```
CLOUDIT:
  region: Region
  credential: IdentityEndpoint / AuthToken / Username / Password / TenantId
```
- 등록 정보
```
                {"Key":"IdentityEndpoint", "Value":""},
                {"Key":"AuthToken", "Value":""},
                {"Key":"Username", "Value":""},
                {"Key":"Password", "Value":""},
                {"Key":"TenantId", "Value":""}
```

[TO-BE]
- ./cloud-driver-libs/cloudos_meta.yaml
```
CLOUDIT:
  region: Region
  credential: IdentityEndpoint / AuthToken / Username / Password / TenantId / ClusterId
```
- 등록 정보
```
                {"Key":"IdentityEndpoint", "Value":""},
                {"Key":"AuthToken", "Value":""},
                {"Key":"Username", "Value":""},
                {"Key":"Password", "Value":""},
                {"Key":"TenantId", "Value":""},
                {"Key":"ClusterId", "Value":""}
```

**Comment by inno-cloudbarista** [comment]
네 알겠습니다. 기존 Region에서 ClusterId를 전달받는 로직을 롤백하고, Credential에서 전달받도록 수정하겠습니다.

**Comment by powerkimhub** [comment]
- 캄사합니다~

**Comment by inno-cloudbarista** [comment]
ClusterId를 Credential에서 전달받도록 수정한 커밋을 Push 하였습니다.

**Comment by powerkimhub** [comment]
• Fixed in https://github.com/cloud-barista/cb-spider/pull/777
