### ISSUE TITLE
[+Debian GuestOS]

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#801]
@inno-cloudbarista @MZC-CSC @innodreamer

- 대상 버전: Debian 10
- 대상 CSP: ALL
- 다음 링크를 참고하시어 시험 현황 공유 부탁드립니다: 
  - [GusetOS 확장 지원 검증 시험 현황](https://docs.google.com/spreadsheets/d/1pssVh3iK7t612roxwJ9YLMFRz9u_PW35/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)
  - `O` 표시 Driver는 정상 동작함을 확인하였습니다.
  - Tencent: 이슈 점검 필요합니다. (ASAP)
  - OpenStack/Cloudit/~: 시험 필요합니다. 
- Windows Platform 지원은 별도 안내 드리겠습니다. 
- 
---

### 참고: 프레임워크별 시험 순서 및 체크 항목

**[SP]**
- `cb-user` ssh 접속 여부 확인

**[TB]**
- MCIS 생성 및 Agent 설치 상태 확인

**[DF]**
- 모니터링 정보 확인

**[LB]**
- Multi-Cloud Type: Cluster 배포 후 Pod 동작 확인
- Single-Cloud Type: Cluster 배포 후 Pod 동작 확인

**[WT]**
- 필요시 여러 GuestOS 지원 내용 UI 반영
- 최종 시험

**Comment by MZC-CSC** [comment]
@powerkimhub 

Tencent cb-user permission denied 이슈에 대하여 원인을 파악하였고 현재 테스트 중에 있습니다.
내일 중으로 수정 완료하여 PR하겠습니다.

**Comment by powerkimhub** [comment]
@MZC-CSC 

- 넵, 캄사합니다.

**Comment by MZC-CSC** [comment]
@powerkimhub 

Tencent cb-user permission denied 이슈 보완해서 PR하였습니다.(https://github.com/cloud-barista/cb-spider/pull/804)

**Comment by powerkimhub** [comment]
- @inno-cloudbarista :  Cloudit  관련하여 템플릿 추가 일정 확인 가능할지요?
- @seokho-son @jihoon-seo : TB 시험한 CSP 결과를 다음 링크에 공유 부탁드립니다. 
- [GusetOS 확장 지원 검증 시험 현황](https://docs.google.com/spreadsheets/d/1pssVh3iK7t612roxwJ9YLMFRz9u_PW35/edit?usp=sharing&ouid=108635813398159139552&rtpof=true&sd=true)

**Comment by inno-cloudbarista** [comment]
@powerkimhub 
- 현재 이미지 테스트 후, CB-Spider로 VM 생성 테스트 진행중입니다.
- 마무리 되면 시험 현황 update후 코멘트 드리겠습니다.

**Comment by inno-cloudbarista** [comment]
@powerkimhub
- Debian 10 템플릿 추가 및 CB-Spider Admin Web Tool을 통한 테스트가 완료되어 업데이트 드립니다.

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

- 캄사합니다. 
- 이로써 Spider 시험은 모두 완료되었네요^^
