### ISSUE TITLE
Error occurs when the NHN-generated MyImages are two or more when viewing the MyImage list with AdminWeb.

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-spider#855]
**What happened**
: AdminWeb으로 NHN Cloud의 MyImage 관련 작업을 할때, 생성된 MyImage 2개 이상일때는 다음의 error가 발생합니다.
 위와 같은 상황에서 '3. MyImage' 우측의 'mgmt'를 클릭하면 MyImage list가 2개 이상 정상적으로 나타나는데, '3. MyImage'를 클릭하면 아래와 같은 error가 발생합니다. (생성된 MyImage가 1개 일때는 정상적으로 표시됨.)

제 추측에 spider server에서 list 실행시, 실질적으로는 get으로 처리해서 각각의 정보를 불러오는 처리할때 발생하는 error인거 같습니다.

```
[CLOUD-BARISTA].[ERROR]: 2022-11-22 18:18:08 MyImageManager.go:294, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.ListMyImage() - IID.SystemId is empty!
```

**What you expected to happen**
:  생성된 MyImage 2개 이상일때도 MyImage list 및 정보들이 정상적으로 제시되어야함.

**How to reproduce it (as minimally and precisely as possible)**
: AdminWeb으로 NHN Cloud의 MyImage를 두개 이상 생성
 (한개는 u2 type VMSpec의 VM, 또 한개는 u2 type이 아닌 VMSpec의 VM으로 MyImage를 생성한 상태임.)

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 현 시간 기준 최신 버전
- OS: Ubuntu 18.04
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by innodreamer** [comment]
위와 같은 상황에서, AdminWeb으로 VM 생성시 VM 생성 조건중 'MyImage'를 선택할때 생성되어 있는 MyImage list가 이 정상적으로 나타나지 않네요.

**Comment by powerkimhub** [comment]
@innodreamer 

- 일단, Create/List/Get MyImage 시에 
- SourceVM 정보가 없더라도(SystemId=""), 에러를 반환하지 않고,
- 정상적으로 MyImageInfo를 반환하여 목록을 볼수 있도록 수정하였습니다. 
- 가급적, SourceVM 정보를 채워 주시고 너무 복잡해진다고 하면 그냥 두셔도 되겠습니다. 
![image](https://user-images.githubusercontent.com/46367962/203296320-d56f6e8f-a12e-4b5b-b052-822fec312f19.png)

**Comment by powerkimhub** [comment]
@innodreamer 

- SourceVM SystemId가 없을 경우 NameId를 "N/A"에서 ""로 변경하였습니다.
  - AdminWeb으로 보면 이제 비어 있습니다.
- 사유: TB와 같이 program으로 handling할 경우 "N/A"로 다시 검색을 요청할수도 있다는 의견이 있었습니다.

---

- 위 AdminWeb 캡춰에서 보면, 
- Created Time이 제대로 설정이 되어 있지 않습니다. 
- 이 부분도 확인 부탁드립니다.

**Comment by innodreamer** [comment]
@powerkimhub 
MyImage 정보에 CreatedTime을 적용했습니다.
- Related PR) https://github.com/cloud-barista/nhncloud/pull/127

덧붙여, 참고로, NHN Cloud의 경우 snapshot 대상의 source VM의 VMSpec type이 u2 type 일 경우에는 생성된 image 정보에 instance id 정보가 포함되어 있지만, u2 type 외의 VMSpec으로 생성된 VM을 기준으로 image를 생성할 경우 생성된 image 정보에 instance id 정보가 포함되어 있지 않습니다.
