### ISSUE TITLE
API to look up all available Region lists and the usability

### ISSUE THREAD

**Issue by raccoon-mh** [cloud-barista/cb-spider#885]
**What would you like to be added**
: 지원하는 CSP에 대하여 모든 가용한 Region 목록과 특정 Region의 사용성을 조회하는 API

**Why is this needed**
: 지금까지 spider는 region을 수동으로 등록해서 사용하고 있습니다.
사용자가 사용하는 해당 region이 변경 또는 추가되거나 삭제가 되는 상황 또는 특정 리전을 조회하고 추가하는 상황에서 이를 인지하고 대응 할 수 있도록 해당 기능이 필요해 보입니다.

*CSP Region 조회기능

 aws : [](url)https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeRegions
 gcp : [](url)https://cloud.google.com/compute/docs/reference/rest/v1/regions/list
 ten : xxx
 ...

위와 같이 CSP에서 리전 리스트를 조회할 수 있는 API를 제공하고 있습니다.
이를 사용하여 모든 가용한 Region 목록 조회와 특정 Region의 사용성을 조회하는 API가 추가되었으면 합니다.

**Comment by powerkimhub** [comment]
@raccoon-pi 

- 제안 감사드립니다. 
- 관련된 내용 공유드리 오니 참고해봐 주시기 바랍니다.
- https://github.com/cloud-barista/cb-spider/issues/408

**Comment by raccoon-pi** [comment]
- 코멘트 감사합니다.

- Meta 정적 관리가 아닌 daily 관리 기능입니다.
- - 1회성 등록이 아닌 주기적인 API 사용이 예상됩니다.
- - DB 등에 Daily 업데이트 등으로 최신 상태 유지 목적입니다.
- - 해당 API를 통해 향후 발생할 수 있는 Region 변경에 즉각 대응하기 위함입니다.

**Comment by powerkimhub** [comment]
@raccoon-pi 

아, 좀더 부연 설명 드리겠습니다. 

- MC-Meta가 제공할 대상 정보들로는  
  - 자주 바뀌지는 않지만, 예측할 수 없이 간헐적으로 변경될 수 있는 메타 정보들 입니다. 
  - 1차적으로 그 개수가 많은 public image 정보, spec 정보 등이 후보입니다. 
  - 현재 Region/Zone 정보는 MC-Meta에서 제공할지는 미확정 상태이긴 합니다. 

- 선정된 메타 정보들은 MC-Meta(가칭)가 주기적으로 수집(동기화) 예정입니다. 
  - 이때, 제안 해주신 각 CSP의 API 등을 내부에서 활용 예정이며,
  - 사용자가 반복적으로 해야 하는 최신 상태 유지 등을 MC-Meta 내부에서 대신 해드릴 예정입니다.
  - 수집 주기에 따라 간혹 올드 데이터를 제공할 수도 있겠습니다. (Cache Miss)
    - 이에 대한 대안으로 Cache Miss 오류 발생시 오류 핸들링으로 최신 데이터를 즉시 유지시키거나, 
    - 제안 해주신 방법처럼 사용자가 직접 호출할 수 있는 API를 직접 꺼내주고, 사용자가 대응할 수 있게 할수도 있겠습니다.
    - 아직은 미결정 상태이고, 진행하면서 살펴바야 할 것 같습니다. 

- 만약, 추진해보다가 Region/Zone 정보가 MC-Meta로 제공하는 것이 적합하지 않다면, 
  - Region/Zone 정보는 MC-Meta로 제공하지 않을 것이며,
  - **제안 주신 방법처럼 공통 API 형태로 제공하는 것을 고려하도록 하겠습니다.**

**Comment by raccoon-pi** [comment]
설명 감사드립니다.

Meta 데이터에  Region/Zone 정보에 대한 정확한 정의와 후보에 관련 계획이 없는 만큼, 확정 전까지
다음 두가지
- cspRegionList(csp string) // CSP별 리전 리스트 조회
- availableRegion(csp string, region string) bool // 해당 CSP 리전의 가용성 조회
가 인터페이스에 추가 된다면 관련 기능 spider에 구현하여 사용하고 싶습니다.

**Comment by powerkimhub** [comment]
@raccoon-pi 

- 넵, 개발 로드맵에 참고하도록하겠습니다. 
- 감사합니다.

**Comment by powerkimhub** [comment]
@raccoon-mh 

- Added in v07.6
- 참고: https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-User-Interface

**Comment by raccoon-mh** [comment]
@powerkimhub 

- 감사합니다. ( _ _ )
