### ISSUE TITLE
[Alibaba:PMKS] Cannot deploy application from outer client

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#902]
- CB-Spider PMKS(Managed-K8S)는 기본 형상이 내외부 client에서 App(Pod) 배포가 가능함
- 현재 Alibaba 경우 CSP Web Console을 통한 Application 배포는 가능하지만,
- 외부에서의 배포(Helm, kubectl 등)는 Pending 상태로 멈춰지는 현상이 발생하고 있음.

**Comment by powerkimhub** [comment]
**[Test for Analysis]**

- Cluster Definition
  - Spider Cluster: CB-Spider 기반으로 생성한 Cluster
  - Console Cluster: Alibaba Console에서 생성한 Cluster


[현상]
- Spider Cluster 생성 후 nginx 배포 => pending 상태
- Console Cluster 생성 후 nginx 배포 => OK, 
  => Console Cluster 생성 후 Spider Cluster nginx가 자동으로 배포 완료됨.
  => Console Cluster 생성으로 생긴 변화 분석이 필요함

[분석]
- Spider와 Console로 생성된 Cluster 구성 및 환경 분석 필요
- 일단, 생성된 네트워크 자원이 다름: NAT Gateway, SNAT 관련
  - by Spider
<img width="509" alt="image" src="https://github.com/cloud-barista/cb-spider/assets/46367962/615018cd-5880-4ee9-ac9f-93159804fe48">
  
  - by Console
<img width="539" alt="image" src="https://github.com/cloud-barista/cb-spider/assets/46367962/8a066f7e-d9a6-4ce5-863a-d5216274e1d7">

- Console Cluster 삭제 후에도 
  - Spider Cluster App 배포는 성공함
  - Console Cluster를 삭제하면, 생성되었던 NAT Gateway도 삭제된 상태임
  => 다른 환경/설정 차이 등의 추가 분석이 필요함.

**Comment by powerkimhub** [comment]
**[Solution] 대상 VPC에 NAT Gateway 추가/유지**
- Driver 내부에서,
- Cluster 생성시: 대상 VPC에 Spider가 생성한 NAT Gateway가 없을 경우 추가
- Cluster 삭제시: 대상 VPC에 Spider가 생성한 마지막 Cluster일 경우 Spider NAT Gateway 함께 삭제
- 단, 향후 Spider가 NAT Gateway 제공 시 사용자가 선택하게 할지 고려 필요

**[Test for Analysis]**
1)	Spider로 pmks 생성
2)	원격 Pod 배포 안됨(pending 상태)
3)	관련 VPC에 NAT Gateway 추가(시험에서는 CSP Console 이용)
  a.	과정에서 EIP 선택 또는 구매 필요
  b.	다음 그림처럼 SNAT Entry 동반 생성됨
  
<img width="527" alt="image" src="https://github.com/cloud-barista/cb-spider/assets/46367962/f32e1aa7-5147-430b-afde-089e8a454081">

4)	Pod 정상 배포됨

**Comment by sykim-etri** [comment]
Alibaba의 클러스터 생성 API 파라미터들 중 이와 관련한 문제를 해결해주는 파라미터(`snat_entry`)를 제공하는 것으로 보입니다. 간단히 테스트를 진행하니 신규 클러스터 생성시 해당 VPC에 NAT Gateway가 생성되는 등 해당 클러스터에서 인터넷 접근이 가능하고, 클러스터 삭제시 NAT Gateway가 자동 삭제되는 것을 확인하였습니다. 추가 클러스터 생성 후 신규 클러스터 삭제시 이슈가 없는지 등은 추후 확인 후 해당 내용을 반영할 예정입니다.
* [참고 링크](https://www.alibabacloud.com/help/en/ack/ack-managed-and-ack-dedicated/developer-reference/create-an-ack-managed-cluster)

**Comment by sykim-etri** [comment]
추가 클러스터 생성 후 초기 클러스터 삭제를 시도하였으나 초기 클러스터 생성시 함께 생성된 NAT Gateway를 사용하는 자원(추가 클러스터)으로 인해 초기 클러스터 삭제가 실패합니다.

따라서 아래 방안으로 개발 검토를 진행할 예정입니다.

> **[Solution] 대상 VPC에 NAT Gateway/EIP 추가/유지**
> 
> * Driver 내부에서,
> * Cluster 생성시: 대상 VPC에 Spider가 생성한 NAT Gateway/EIP가 없을 경우 추가
> * Cluster 삭제시: 대상 VPC에 Spider가 생성한 마지막 Cluster일 경우 Spider NAT Gateway/EIP 함께 삭제
> * 단, 향후 Spider가 NAT Gateway, EIP 제공 시 사용자가 선택하게 할지 고려 필요

**Comment by powerkimhub** [comment]
> @powerkimhub
> 
> * 클러스터 생성시 NAT Gateway 생성을 지원하는 기능 개발과 관련하여, CSP API 호출 방식 적용과 관련한 의견을 부탁드립니다. 개발 공수가 다소 차이 날 것으로 예상됩니다.
>   
>   * (1안) 클러스터 관리 기능(REST API 방식) 유지 및 NAT Gateway 관리 기능(SDK 방식) 개발
>   * (2안) 클러스터 관리 기능과 NAT Gateway 관리 기능 모두 SDK 방식으로 개발
>   * 관련 이슈: [[Alibaba:PMKS] Need to update Alibaba API calls as SDK instead of REST API #1078](https://github.com/cloud-barista/cb-spider/issues/1078)

<br>

@sykim-etri 

<br>

- Driver 직접 핸들링 들어가기 전에 아래 [선행 시험]처럼 create/delete option으로 해결 가능한지 재확인해보면 좋을 것 같습니다. 
  - DeleteCluster 오류에서 사용중인 자원 목록을 반환하지 않는다면, descritbexxx() 이용해서 대상 자원 ID 획득 등 추가 고려 필요
- 만일, 결과적으로 직접 핸들링해야 한다면, 가능하다면 driver 전체가 사용하는 호출 방식으로 개발하여 일관성 유지

<br>

**[선행 시험]**
- cluster 삭제시, 일단 모든 자원 함께 삭제 옵션(default)으로 삭제 시도
- 이때, 사용중 에러를 반환하면 Cluster 생성시 자동 생성된 자원들을 남겨두고 Cluster 삭제 
- flow 예시
  ```
  (1) CreateCluster(cluster1, snat_entry)
  (2) CreateCluster(cluster2, snat_entry)
  (3) DeleteCluster(cluster1)
       if error(nat-gw-1234 is used by other cluster).  
              DeleteCluster(cluster1, retain_resources[nat-gw-1234], ...)
  ```

**Comment by sykim-etri** [comment]
API를 활용하여 진행한 재시험 결과를 공유합니다.

```
(1) CreateCluster(cluster1, snat_entry)
   - Internet NAT Gateway가 없기에 신규로 자동 생성됨(ngw01)
   - ngw01에 태그(ack.aliyun.com:cluster1_id) 자동 처리됨
   - cluster1 생성 성공
(2) CreateCluster(cluster2, snat_entry)
   - cluster2 생성 성공
   - Internet NAT Gateway의 추가 생성 없음
(3) DeleteCluster(cluster1) - no retain resources
   - ngw01에 대한 DependencyViolation 에러 발생
(4) DeleteCluster(cluster1) - retain ngw01
   - 삭제 성공
(5) DeleteCluster(cluster2) - no retain resources
   - 삭제 성공
   - ngw01 자동 삭제되지 않음
```

이에 따라 다음과 같은 로직으로 해당 이슈를 해결하고자 합니다.

* 클러스터 생성시
   - 클러스터에 CLUSTER 태그(#CB-SPIDER:PMKS:CLUSTER:) 처리하고, 클러스터와 함께 생성된 NAT Gateway에도 NATGATEWAY 태그(#CB-SPIDER:PMKS:NATGATEWAY:) 처리
   - 클러스터와 함께 생성된 NAT Gateway에는 태그(ack.aliyun.com:cluster_id)가 자동 생성

* 클러스터 삭제시
  - 삭제 요청된 클러스터 ID(cluster1_id)와 동일한 값의 태그(ack.aliyun.com:cluster1_id)를 가진 NAT Gateway는 유지시키면서 클러스터 삭제 처리 (해당 NAT Gateway를 사용하는 클러스터가 있는 경우 유지시키지 않고 삭제시 에러 발생)
  - 해당 VPC에 CLUSTER 태그(#CB-SPIDER:PMKS:CLUSTER:)를 가진 클러스터가 더 이상 없는 경우 NATGATEWAY 태그(#CB-SPIDER:PMKS:NATGATEWAY:)를 가진 NAT Gateway 삭제 처리

의견 부탁드립니다.
@powerkimhub

**Comment by powerkimhub** [comment]
flowchart TD
```mermaid
flowchart TD
    start(시작) --> createCluster1["CreateCluster(cluster1, snat_entry)"]
    createCluster1 -->|Internet NAT Gateway 없음| autoCreateNgw01["ngw01 자동 생성"]
    autoCreateNgw01 --> tagNgw01["ngw01에 태그(ack.aliyun.com:cluster1_id) 처리"]
    createCluster1 --> tagCluster1["클러스터1에 CLUSTER 태그 처리"]
    createCluster1 --> tagNgwCluster1["생성된 NAT Gateway에 NATGATEWAY 태그 처리"]
    tagNgw01 --> cluster1Success["cluster1 생성 성공"]

    start --> createCluster2["CreateCluster(cluster2, snat_entry)"]
    createCluster2 -->|Internet NAT Gateway 추가 생성 없음| cluster2Success["cluster2 생성 성공"]
    createCluster2 --> tagCluster2["클러스터2에 CLUSTER 태그 처리"]

    cluster1Success --> deleteCluster1First["DeleteCluster(cluster1) - no retain resources"]
    deleteCluster1First -->|DependencyViolation 에러| deleteCluster1Second["DeleteCluster(cluster1) - retain ngw01"]
    deleteCluster1Second --> deleteSuccess1["삭제 성공"]
    deleteSuccess1 --> checkCluster1["해당 VPC에 CLUSTER 태그를 가진 클러스터 확인"]
    checkCluster1 -->|클러스터 없음| deleteNgw1["NATGATEWAY 태그를 가진 NAT Gateway 삭제 처리"]

    cluster2Success --> deleteCluster2["DeleteCluster(cluster2) - no retain resources"]
    deleteCluster2 --> deleteSuccess2["삭제 성공"]
    deleteSuccess2 --> checkCluster2["해당 VPC에 CLUSTER 태그를 가진 클러스터 확인"]
    checkCluster2 -->|클러스터 없음| deleteNgw2["NATGATEWAY 태그를 가진 NAT Gateway 삭제 처리"]

    deleteNgw1 --> end(종료)
    deleteNgw2 --> end
```

**Comment by powerkimhub** [comment]
@sykim-etri 

<br>

- 넵, 제안 주신 방법으로 추진하시는 것이 좋을 것 같습니다.  

<br>

[사족]

```
  Spider와 Spider를 사용하지 않는 다른 방법으로 자원 관리를 공유 한다고 하면, 
  아래와 같이 NG가 잔류 또는 간섭하는 케이스가 있을 수는 있겠습니다만...

  Spider를 사용하는 시점부터는 
  Spider를 통한 단독 관리를 기본으로 진행하는 것이 맞다고 생각합니다. 
  Spider 외에 다른 방법과 관리 체계가 공유되어 상호작용한다면 
  이 보다 더한 관리 문제가 생길거라 생각합니다.
```

<br>

[Create]
- (1) create sp1  # => ack.aliyun.com:sp1 tagging된 NG 생성
- (2) create sp2  # => ack.aliyun.com:sp1 tagging된 NG 활용
- (3) create other1 # spider를 통하지 않은 cluster 생성 => ack.aliyun.com:sp1 tagging된 NG 활용

<br>

[Delete]
- (4) delete sp1  # => ack.aliyun.com:sp1 tagging된 NG 유지
- (5) delete sp2  # => ack.aliyun.com:sp1 tagging된 NG 삭제 불가(또는, 사용자가 other1 클러스터 삭제 선행 등)
- (6) delete other1  # => ack.aliyun.com:sp1 tagging된 NG 잔류(또는, 사용자가 생성하지 않았지만 별도 삭제 필요 등)

**Comment by sykim-etri** [comment]
말씀해주신 사항을 검토한 결과 예상하신 바와는 다르게 다음과 같은 결과를 얻었기에 현황을 공유드립니다.

[Create]

(1) create sp1 # => ack.aliyun.com:sp1 tagging된 NG 생성
(2) create sp2 # => ack.aliyun.com:sp1 tagging된 NG 활용
(3) create other1 # spider를 통하지 않은 cluster 생성 => ack.aliyun.com:sp1 tagging된 NG 활용

[Delete]

(4) delete sp1 # => ack.aliyun.com:sp1 tagging된 NG 유지
(5) delete sp2 # => ack.aliyun.com:sp1 tagging된 NG **_삭제 처리됨_**
(6) delete other1 # => **_외부 인터넷 접근 불가_**

**Comment by powerkimhub** [comment]
@sykim-etri 

- 현황 공유 캄사합니다. 
- 현황 및 잠재적 이슈 등을 정리해두도록 하겠습니다. 

<br>

[요약]
- 기본적으로 상기 flow로 관리
- CSP 동작: Cluster 삭제시 NG 자동 삭제 요청은 NG를 생성한 Cluster 삭제시에만 가능
  - 현재는 Driver Tagging 기반으로 최종 Cluster 삭제 시 NG를 정리하므로, OK
- Tagging 에 `#` 포함시 이상 동작 => Tagging에서 `#` 제외

<br>

[잠재적 이슈]
- Spider API가 비동시 생성 요청이므로, 
- 최초 Cluster 생성 시점에 동시에 2개 이상의 Cluster 생성이 요청되면, 
  - Spider가 생성한 NG가 2개 이상 유지 되는 상황이 가능
- 확률은 적지만, 2개의 Cluster 삭제 호출이 동시에 발생하면 
  - 2 삭제 호출 모두 NG가 `in use`로 판단하고 NG를 유지할 수도 있음

**Comment by sykim-etri** [comment]
상기 시험 진행 중 확인된 사항과 추가적인 이슈가 있었기에 현황을 공유드립니다.

[확인사항]
* 클러스터 생성 요청시 NAT Gateway의 생성 시점이 클러스터가 어느정도 생성된 뒤에 생성되기 때문에 NAT Gateway에 태그 처리가 불가하였고, NAT Gateway에는 클러스터 생성시 요청한 태그(#CB-SPIDER:PMKS:CLUSTER)가 자동 처리됩니다.

[이슈]
1. Alibaba API의 버그로 보이는데, 태그 키값(#CB-SPIDER:PMKS:CLUSTER) 조건으로 조회시 불특정한 상황에서 에러가 발생합니다. 태그 조건 없이 조회하면 에러가 발생하지는 않고, 샵(#)을 제거한 태그 키값(CB-SPIDER:PMKS:CLUSTER) 조건으로 조회시에도 에러가 발생하지 않습니다. 또한 상기 에러는 항상 발생하는 것이 아니라 sp1 삭제시 문제가 없다가 sp2 클러스터 삭제시에만 발생합니다. 
    * [에러 발생 로그](https://github.com/cloud-barista/cb-spider/files/14566072/sharp-tag-unknwonerror.txt)
2. sp1 클러스터 생성 요청시 NAT Gateway가 자동 생성되는데, NAT Gateway가 생성되기 전 sp2 클러스터 생성을 요청하면 NAT Gateway가 추가로 생성됩니다.

상기 이슈 1은 로직이 꼬이는 경우가 발생할 수 있기에 해결을 위해 태그 값은 CB-SPIDER:PMKS:CLUSTER:owned (샵 제거 및 값 추가)으로 변경하고, NAT Gateway에 태그값은 CB-SPIDER:PMKS:NATGATEWAY 가 아닌 클러스터 생성시 전달한 태그를 기준으로 처리하도록 하겠습니다.

상기 이슈 2는 마지막 클러스터 삭제시 관련 태그를 가진 NAT Gateway가 모두 삭제하는 것으로 처리하도록 하겠습니다.

의견 주셨던 클러스터 동시 삭제시 NAT Gateway가 삭제되지 않을 수 있는 상황은 추후 문제가 될때 가비지 콜렉터를 추가하는 등의 개선하는 방안을 마련하여 대응하도록 하겠습니다.

**Comment by powerkimhub** [comment]
@sykim-etri 

- 넵, 캄사합니다~
