### ISSUE TITLE
[+Region/Zone] Cloud Driver API Definition

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#905]
- [x] Region and zone features and Interfaces Analysis of CSPs
  - [Analysis space](https://docs.google.com/spreadsheets/d/1X0IV4p4FdF3PDD1VpBlZXTi4VHhADHJC/edit#gid=1180727129)
- [x] Cloud Driver Region/Zone API Definition
  - [Definition space](https://docs.google.com/spreadsheets/d/1DeEOcJZLBe3wJbb_e9A7DY3O3sITwoXp/edit#gid=748266323) 
- [x] Cloud Driver Region/Zone API Review
  - [latest Interface](https://github.com/cloud-barista/cb-spider/blob/master/cloud-control-manager/cloud-driver/interfaces/resources/RegionZoneHandler.go)

**Comment by innodreamer** [comment]
@powerkimhub 국내 5종 클라우드에 대한 Region/Zone 분석 및 정리를 완료했습니다.

**Comment by powerkimhub** [comment]
@innodreamer 

- 캄사합니다.

**Comment by powerkimhub** [comment]
**[특이사항]**
- **GCP** 
  - Region Zone 정보 조회 위한 IAM Role 설정 필요
  - Required Compute Engine IAM ROLE : ### **compute.regions.list**
  - cf) https://github.com/cloud-barista/cb-spider/pull/921

**Comment by innodreamer** [comment]
@powerkimhub NCP에서도 status 정보를 제공하지 않아 드라이버에서 Status parameter에 "Available" 이라고 추가했습니다.

그리고, 제안 사항으로, 본 RegionZoneHandler에는 Status parameter가 "Available", "Unvailable"로 첫자가 대문자로 안내되는데, ImageHandler의 경우는 첫자가 소문자로 안내되고 있습니다.
통일이 필요할거 같습니다.

**Comment by powerkimhub** [comment]
@innodreamer 

- Status 관련해서는 다음 slack msg를 참고해주시기 바랍니다. 
  - 참고 후 적용 부탁드립니다. 
  - cf) https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1695110415342289?thread_ts=1695108335.793949&cid=CLFCLNFTJ
  - slack msg 요약

    ```
    Zone Status를 제공하지 않는 경우를 표현하기 위해서
    아래처럼 NotSupported 옵션을 추가해드렸습니다.
    활용하시어 설정 부탁 드립니다.
    const (
            ZoneAvailable   ZoneStatus = "Available"
            ZoneUnavailable ZoneStatus = "Unavailable"
            NotSupported ZoneStatus = "NotSupported"  <============
    )
    ```

<br>

- 대소문자 관련
  - 다음 Image 이슈와 함께 추후 한번에 정리하도록 하겠습니다. 
    - cf) https://github.com/cloud-barista/cb-spider/issues/399
  - 이런 문제를 없애고자, RegionZoneHandler에서는 const string을 추가해보았습니다.

**Comment by innodreamer** [comment]
@powerkimhub NCP Classic, NCP VPC driver에 "NotSupported"로 적용했습니다.

**Comment by innodreamer** [comment]
@powerkimhub Region 정보를 API로 제공하지 않는 CSP는 NHN Cloud, KT Cloud Classic 입니다.
저 위의 내용 보완해야할 거 같습니다.
NCP Classic, NCP VPC는 status 정보를 제공하지 않고요.

**Comment by powerkimhub** [comment]
@innodreamer 

- 검토 캄사합니다. 
- 반영하였습니다.

**Comment by powerkimhub** [comment]
- cf) https://github.com/cloud-barista/cb-spider/wiki/Region-Zone-Driver-API
