### ISSUE TITLE
GCP CreateVM이 안되는 이슈

### ISSUE THREAD

**Issue by taking** [cloud-barista/cb-spider#958]
### 설명
- adminweb 에서는 GCP VM 생성 시 에러가 발생하고, restapi post로 시도시에는 에러가 발생하지 않습니다.
- document 에 gcp VM 생성에 대한 내용이 없어  조금 애먹었지만 해결했습니다.

#### 구현 방법
- 기본 환경 설정(Driver, Credential, Region, Connection 생성)
- 추가 설정(VPC/Subnet, SecurityGroup, KeyPair 생성)
- VM 생성 요청

#### 스크린샷
(1) adminweb
-

-> 로그
```
[오후 2:54:08] curl -sX POST http://*.*.*.*:1024/spider/vm -H 'Content-Type: application/json' -d '
{
    "ConnectionName": "taking-gcp-config",
    "ReqInfo": {
        "Name": "vm-01",
        "ImageType": "PublicImage",
        "ImageName": "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024",
        "VMSpecName": "f1-micro",
        "VPCName": "taking-gcp-config-vpc",
        "SubnetName": "taking-gcp-config-subnet",
        "SecurityGroupNames": taking-gcp-config-sg,
        "DataDiskNames": [],
        "KeyPairName": "taking-gcp-config-key",
        "VMUserId": "Administrator",
        "VMUserPasswd": "cloudbarista123^"
    }
}
[오후 2:54:08]    ==> {"message":"code=400, message=Syntax error: offset=422, error=invalid character 'e' looking for beginning of value, internal=invalid character 'e' looking for beginning of value"}
```

(2) insomnia RestAPI Testing
![image](https://github.com/cloud-barista/cb-spider/assets/9063986/3b23280e-ccd3-4c3e-9833-93c3d026d340)

**Comment by taking** [comment]
RestAPI 호출의 경우, Document AWS 예제와 같이 보내는게 아닌 adminweb 의 json 값으로 보내니 정상적으로 동작하였습니다!
```
"ImageType": "PublicImage",
"ImageName": "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024",
```

**Comment by powerkimhub** [comment]
```
  * 이슈 공유 감사드립니다.
  * 이슈 분석 내용이 다음과 같습니다. 
```

<br>

**[Case-I] (1) AdminWeb을 통한 GCP VM 생성 이슈**
- 올려 주신 로그 중 다음 부분으로 추정해보면, 
  ```
      "SecurityGroupNames": taking-gcp-config-sg,
  ```
- 다음 AdminWeb 예시 중 SG 입력 시 `["`, `"]`이 빠진 것 같습니다.

<br>

  ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/30dc9251-5e91-44a3-89e2-8b3909c8e35c)

<br>

**[Case-II] (2) insomnia RestAPI Testing**
- 에러 메시지로 추정해보면, 
- 연결 설정(Connection Config)에 포함된 Credential  정보에 포함된 
- GCP Project ID가 없거나, 잘못 설정된 것으로 보입니다. 

<br>

**[Case-III] Image Name 설정 관련**
- 예시의 AWS와 달리, GCP Image 이름 입력 포멧 차이로 혼란스러우셨을 것 같습니다. 
- 일단 [가이드](https://github.com/cloud-barista/cb-spider/wiki/features-and-usages#1-vm-%EC%83%9D%EC%84%B1-%EB%B0%8F-%EB%9D%BC%EC%9D%B4%ED%94%84%EC%82%AC%EC%9D%B4%ED%81%B4-%EC%A0%9C%EC%96%B4)를 최소 보완해두었습니다. 
  - 혹시, 다른 가이드를 참고하셨다면, 공유해주시면 고맙겠습니다.
- 간단히, 포멧만 참고하시고자 하면 다음처럼 하셔도 되겠습니다. 
  - AdminWeb에서 선택된 CSP에 따라 초기 값으로 제공되는 포멧 참고

<br>

  ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/63f9b5fa-521a-42b5-9676-f48b14317256)

<br>

- #### 혹시, 이슈 중 제가 놓친 부분이 있다면 답글 부탁 드립니다. 
- #### 해결 되셨다면, close 해주시면 감사하겠습니다.

**Comment by taking** [comment]
려주신 내용으로 AWS, OpenStack, GCP 모두 정상적으로 생성했습니다.

상세한 답변 감사드립니다!

감사합니다. Taking 드림.

**Comment by powerkimhub** [comment]
- 캄사합니다.
