### ISSUE TITLE
[PMKS] Request's 'ConnectionName' field name is different from Response

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-spider#981]
**What would you like to be enhanced**
: PMKS 관련 API(CREATE, GET)를 살펴보면 Request Body에 'ConnectionName'으로 입력하도록 되어 있는데,
이에 대한 Response Body에는 이와 다른 'Connection'으로 출력되는 것으로 설명되어 있습니다.

* Request Body
  ```json
  {
    "ConnectionName" : "tencent-seoul1-config"
  }
  ```

* Response Body
  ```json
  {
    "Connection": "tencent-seoul1-config",
    "ClusterInfo": 
  }
  ```
참조: https://documenter.getpostman.com/view/24786935/2s9YJjSzUj#8d0c843b-dc41-4273-a0c0-a093cc0cfe79

**Why is this needed**
: 혼란 방지

**Proposed solution**
: 동일한 명칭(ConnectionName 등)으로 통일

**Comment by powerkimhub** [comment]
@MZC-CSC @dogfootman 

- 위 이슈에서, 
- Response Body에서, `Connection` => `ConnectionName`으로 수정해도 큰 이슈가 없을 지 확인 부탁 드립니다. 
- 다른 자원들에 대한 결과에는 Connection 이름이 포함되어 있지 않은데, Cluster에만 포함되어 있네요. 
- 아마도, WebTool PMKS 통합 시에 활용하실 수 있을 것 같아서 문의 드립니다.

**Comment by powerkimhub** [comment]
- v0.9.4 부터 Response-Body에서 Connection(Name)이 삭제되었습니다. 
- https://github.com/cloud-barista/cb-spider/issues/1319
