### ISSUE TITLE
[PMKS] Different Response Format between DeleteCluster and RemoveNodeGroup in REST API

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-spider#992]
**What would you like to be enhanced**
: REST API 중 DeleteCluster와 RemoveNodeGroup의 HTTP 응답 양식이 통일되면 좋을 것 같습니다.

* DeleteCluster
  * 현재 응답
    ```
    {
      "Result": "true"
    }
    ```
  * https://documenter.getpostman.com/view/24786935/2s9YJjSzUj#57d566d9-5f62-484b-9e8a-c5d2d36d01ed
* RemoveNodeGroup
  * 현재 응답
    ````
    true
    ````
  * https://documenter.getpostman.com/view/24786935/2s9YJjSzUj#00dbb541-0e7d-41fa-88b4-da5df2ba2ed0
 
**Why is this needed**
: 일관성 제공

**Proposed solution**
: DeleteCluster 응답 방식으로 통일

**Comment by powerkimhub** [comment]
- 감사합니다. 
- 다음처럼 수정 하겠습니다.
  ```
  {
    "Result": "true"
  }
  ```

**Comment by powerkimhub** [comment]
@sykim-etri 

- Changed via https://github.com/cloud-barista/cb-spider/commit/b770956f913ccc5853dd71f4778d527946666eac
- API reference: [v0.8.1](https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-User-Interface)

**Comment by sykim-etri** [comment]
ClusterRest.go::SetNodeGroupAutoScaling() 도 동일한 포맷으로 수정이 필요해 보입니다. (v0.8.1 이후)

https://github.com/cloud-barista/cb-spider/blob/7ce279fc355eb46a7996152aaa400f50452e21e4/api-runtime/rest-runtime/ClusterRest.go#L545-L578

**Comment by powerkimhub** [comment]
> ClusterRest.go::SetNodeGroupAutoScaling() 도 동일한 포맷으로 수정이 필요해 보입니다. (v0.8.1 이후)

- 관련된 내용은, 
- [v0.8.4](https://github.com/cloud-barista/cb-spider/releases/tag/v0.8.4)에 반영 되었습니다.
