### ISSUE TITLE
[Price:AWS] ListProductFamily()

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#998]
- 현재, Spider가 제공하는 가격 정보는 CSP가 제공하는 모든 서비스 제품 패밀리가 아닌,
- `Computing Infra Service`에 한정하고 있습니다. 
  - 참고: [다음 링크](https://github.com/cloud-barista/cb-spider/wiki/Price-Info-and-Cloud-Driver-API#2-cb-spider-%EA%B0%80%EA%B2%A9-%EC%A0%95%EB%B3%B4-%EC%A0%9C%EA%B3%B5-%EB%8C%80%EC%83%81-%EC%84%9C%EB%B9%84%EC%8A%A4-%EB%B6%84%EB%A5%98%EC%A0%9C%ED%92%88-family-or-%EC%A0%9C%ED%92%88-category)에서 다음 Red Under Line 부분 참고 
    - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/694960f0-41e1-4bdf-b715-a720e4dd32b7)
    - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/bd8551da-bd11-43b0-801f-7eefdef526bd)

- 가이드가 빠르게 읽혀지면, 잘 눈에 안 띌수 있겠네요.
  - 일단, bold 체로 수정해두었습니다.

<br>

**[As-Is]**
```
  [
   "A4B",
   "AWSAmplify",
   "AWSAppFabric",
   "AWSAppRunner",
   "AWSAppSync",
   "AWSApplicationMigrationSvc",
   "AWSB2Bi",
   "AWSBackup",
   "AWSBillingConductor",
   ... 중략 ...
   "translate"
  ]
```

**[To-Be]**
```
  [
    "CPU Credits",
    "Compute Instance (bare metal)",
    "Compute Instance",
    "Data Transfer",
    "Dedicated Host",
    "EBS direct API Requests",
    "Elastic Graphics",
    "Fast Snapshot Restore",
    "Fee",
    "IP Address",
    "Load Balancer",
    "Load Balancer-Application",
    "Load Balancer-Network",
    "NAT Gateway",
    "Provisioned Throughput",
    "Storage Snapshot",
    "Storage",
    "System Operation"
  ]
```

**Comment by raccoon-mh** [comment]
> * 현재, Spider가 제공하는 가격 정보는 CSP가 제공하는 모든 서비스 제품 패밀리가 아닌,
> * `Computing Infra Service`에 한정하고 있습니다.
>   
>   * 참고: [다음 링크](https://github.com/cloud-barista/cb-spider/wiki/Price-Info-and-Cloud-Driver-API#2-cb-spider-%EA%B0%80%EA%B2%A9-%EC%A0%95%EB%B3%B4-%EC%A0%9C%EA%B3%B5-%EB%8C%80%EC%83%81-%EC%84%9C%EB%B9%84%EC%8A%A4-%EB%B6%84%EB%A5%98%EC%A0%9C%ED%92%88-family-or-%EC%A0%9C%ED%92%88-category)에서 다음 Red Under Line 부분 참고
>     
>     * ![image](https://private-user-images.githubusercontent.com/46367962/293633914-694960f0-41e1-4bdf-b715-a720e4dd32b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Njk3OTYsIm5iZiI6MTcwNDg2OTQ5NiwicGF0aCI6Ii80NjM2Nzk2Mi8yOTM2MzM5MTQtNjk0OTYwZjAtNDFlMS00YmRmLWI3MTUtYTcyMGU0ZGQzMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2NTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTQwZGMzYTkxZTQzZmI0NDVhZmE4ZmQzODk2N2MwMTBkM2Q0MmY1ZGJiY2RjYWNhNjJiYTM4NDRiNjZiOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LmmIK-Ed0jyl4yCzy3R4DGOzRdE5lwMOLtxMa97b8ns)
>     * ![image](https://private-user-images.githubusercontent.com/46367962/293634812-bd8551da-bd11-43b0-801f-7eefdef526bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Njk3OTYsIm5iZiI6MTcwNDg2OTQ5NiwicGF0aCI6Ii80NjM2Nzk2Mi8yOTM2MzQ4MTItYmQ4NTUxZGEtYmQxMS00M2IwLTgwMWYtN2VlZmRlZjUyNmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2NTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjQ5ZTc5MTcyN2Y3OGNjYzAzNTI0Y2NmZGJjYTUzMmQ0OTc2OWU3ZWZlOTg2ZTI1NTUxMWNiM2Q1ZTgyOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVLyvVuvvYmkYU-LOHrEb_wRTno0YkUOTOq6L5m9rOo)
> * 가이드가 빠르게 읽혀지면, 잘 눈에 안 띌수 있겠네요.
>   
>   * 일단, bold 체로 수정해두었습니다.
> 
> 
> **[As-Is]**
> 
> ```
>   [
>    "A4B",
>    "AWSAmplify",
>    "AWSAppFabric",
>    "AWSAppRunner",
>    "AWSAppSync",
>    "AWSApplicationMigrationSvc",
>    "AWSB2Bi",
>    "AWSBackup",
>    "AWSBillingConductor",
>    ... 중략 ...
>    "translate"
>   ]
> ```
> 
> **[To-Be]**
> 
> ```
>   [
>     "CPU Credits",
>     "Compute Instance (bare metal)",
>     "Compute Instance",
>     "Data Transfer",
>     "Dedicated Host",
>     "EBS direct API Requests",
>     "Elastic Graphics",
>     "Fast Snapshot Restore",
>     "Fee",
>     "IP Address",
>     "Load Balancer",
>     "Load Balancer-Application",
>     "Load Balancer-Network",
>     "NAT Gateway",
>     "Provisioned Throughput",
>     "Storage Snapshot",
>     "Storage",
>     "System Operation"
>   ]
> ```

수정했습니다!
