### ISSUE TITLE
[Price:AWS] GetPriceInfo()

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#999]
다음 2가지 항목 확인 부탁 드립니다.

- ~~(1) escape 처리(`\`) 제거~~
  - 모든 CSP에 대한 Price 정보가 동일한 format으로 제공될 수 있도록 수정 부탁드립니다. 
  - [As-Is]
    ```
    "{\"meta\":{\"version\":\"v0.1\",\"description\":\"Multi-Cloud Price Info\"},\"cloudPriceList\":[{\"cloudName\":\"AWS\",\"priceList\":[{\"productInfo\":{\"productId\":\"222UTRCZXNBDKCNH\",\"regionName\":\"eu-south-1\",\"zoneName\":\"\",\"instanceType\"
    ```

  - [To-Be]
    "{"meta":{"version":"v0.1","description":"Multi-Cloud Price Info"},"cloudPriceList":[{"cloudName":"AWS","priceList":[{"productInfo":{"productId":"222UTRCZXNBDKCNH","regionName":"eu-south-1","zoneName":"","instanceType"
    ```

- (2) zoneName: NA로 설정
  - 현재 제공 정보 예시
    - ![image](https://github.com/cloud-barista/cb-spider/assets/46367962/aae50229-6329-40aa-83a5-4f14cbc0612d)
  - ""와 "NA"가 차이가 있습니다. "NA"로 설정 부탁드립니다. 
    - "": CSP가 제공하는 값이 ""인 경우
    - "NA": CSP가 제공하지 않는 정보이므로 제공할 수 없음을 의미(Not Applicable)

**Comment by powerkimhub** [comment]
- 일단, (1) 번 항목은 제외해주시기 바랍니다. 
- 서버 수준에서 대응 후 필요시 재요청 드리겠습니다.

**Comment by raccoon-mh** [comment]
- 1번 항목 제외한 2번 항목에 대한 보완하였습니다.
  - CommonAwsFunc.go 에 ReplaceEmptyWithNA 로 정의되어 있습니다.

**Comment by powerkimhub** [comment]
- 올려주셨던 PR에서, 
- "", nil에 대해서 "NA" 일괄적용 하는 부분은 조정이 필요해 보입니다, .
- AWS가 value를 ""로 제공하는 경우가 있을 수도 있을 것 같습니다. 
  - 이런 경우를 확인한 바는 아니지만, 추후에라도 가능할 여지가 있을 것 같습니다. 
  - "NA"의 경우는 변환시 대상 CSP가 제공하지 않는 Field(Key)일 경우 명시적으로 "NA"로 설정하는 것이 좋겠습니다. 
  - 현재는, Tencent에서만 의미 있는 "zoneName"이 해당되고 있습니다.

- 참고
>   - ""와 "NA"가 차이가 있습니다. "NA"로 설정 부탁드립니다. 
>     - "": CSP가 제공하는 값이 ""인 경우
>     - "NA": CSP가 제공하지 않는 정보이므로 제공할 수 없음을 의미(Not Applicable)

**Comment by raccoon-mh** [comment]
- CSP가 "" 로 제공하는 경우는 ""로 유지하고 제공하지 않는 경우만 "NA" 값을 리턴하는 것인가요?
- AWS는 현재 제공하지 않는 값에 대하여 기본적으로 "NA"를 값에 넣어 리턴하고 있습니다.

**Comment by powerkimhub** [comment]
- 넵, 맞습니다. 
- 다음 함수를 보고 comment 드렸는데, 최종적으로 위와 같이 반영 되어 있다면 되겠습니다.
  - https://github.com/cloud-barista/cb-spider/blob/c27608000ca06849c0e5aec818ee3469e4eaf6d7/cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go#L445C43-L445C43

**Comment by raccoon-mh** [comment]
- 넵 반영하겠습니다.

**Comment by raccoon-mh** [comment]
> * 넵 반영하겠습니다.

반영하여 다시 PR 했습니다.
